BBBB BBBB

BBB BBBBB BB BBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXBB BBBBBBBBBBBB XXXXXXXXXBBBBBXX
    XXXXXXXXXXXXXXX
    XXXXX
      
      BBB BBBBB BB BBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBBB
      BB BBBBBBBBBB BB BBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXX
          BBB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
          XX XXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXX gettext(u'Forgot your password?') XXXX
        XXXX
      BBBBB
    XXXXXX
  XXXXXX
BBBBBB
