BBBB BBBB

BB BBBBBBBBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXXXX
          XXXXXXXXXX XXXXXXXXXXX XXXXXXXX gettext(u'Back') XXXXXXXXX
BBBBB
BB BBBBBBBBBBBBBBBBBBBB BB BBBBBB
  BB BBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                       XXXXXX XXXXXXXXXXXXXXXXXX
                       XXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
      XX XXXXXXXXX XXXXXXXXXX XXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
       gettext(u'Sign In') 
    XXXXXXXXX
  BBBB
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX gettext(u'Sign In') XXXXXXXXX
  BBBBB
BBBB
  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX gettext(u'Next') XXXXXXXXX
BBBBB
