
TYPE_INTEGER = 'integer'
TYPE_SMALL_INTEGER = 'small_integer'
TYPE_DECIMAL = 'decimal'
TYPE_STRING = 'string'
TYPE_DATE = 'date'
TYPE_DATETIME = 'datetime'
TYPE_ARRAY = 'array'
ALL_TYPES = [TYPE_INTEGER, TYPE_DECIMAL, TYPE_STRING, TYPE_DATE, TYPE_DATETIME, TYPE_ARRAY]
