BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBB BBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX
           gettext(u'\n            Automatically update or close cases from CommCare HQ\n          ') 
            SSSSSSSSSSSSS SSSSSS SS SSSSS SSSSS SSSS SSSSSSSS SS
          
        XXXX
        XXX
           gettext(u'\n            Create rules for updating or closing cases from CommCare HQ.\n            All rules run every day at %(time)s GMT.\n            For more information, see the <a href="https://confluence.dimagi.com/display/commcarepublic/Automatically+Close+Cases">Help Site</a>.\n          ') 
            SSSSSS SSSSS SSS SSSSSSSS SS SSSSSSS SSSSS SSSS SSSSSSSS SSS
            SSS SSSSS SSS SSSSS SSS SS SSSSSSSS SSSS
            SSS SSSS SSSSSSSSSSSS SSS SSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSS
          
        XXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXX XXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Automatic Update Rules') XXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Rule Run History') XXXXXXXXX
    XXXXX

    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXX XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
    XXXXXX
  XXXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBBB
