BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBB BBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBB
      XX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'\n          This deduplication rule is currently backfilling. You will be able to edit it once it has completed. <strong>%(progress)s%%</strong> (%(complete)s / %(total)s) cases processed.\n          Reload the page to see the updated progress.\n        ') 
          SSSS SSSSSSSSSSSSS SSSS SS SSSSSSSSS SSSSSSSSSSSS SSS SSSS SS SSSS SS SSSS SS SSSS SS SSS SSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSS S SSSSSSSSSS SSSSS SSSSSSSSSS
          SSSSSS SSS SSSS SS SSS SSS SSSSSSS SSSSSSSSS
        
      XXXX
    BBBBB
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBBBBBB
      XXXXXXXXX BB BBBBBBBB XXXXXXXXXXXXXXXXXXX BBBBBX
        XXXXXXXX gettext(u'Basic Information') XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
             gettext(u'Name') 
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX
          XXXXXX
        XXXXXX
      XXXXXXXXXXX
      XXXXXXXXX BB BBBBBBBB XXXXXXXXXXXXXXXXXXX BBBBBX
        XXXXXXXX gettext(u'Rule Criteria') XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
             gettext(u'Case Type') 
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX BB BBBBBBBB XXXXXXXXXXXXXXXXXXX BBBBBX
            XXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
             gettext(u'Match Type') 
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXXX XXXXXXXXXX
              XXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              X X
            XXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
             gettext(u'Add Case Property') 
          XXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXX
             gettext(u'Add Case Property') 
          XXXXXXXXX
          XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
             gettext(u'Include Closed Cases') 
          XXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX
        XXXXXX
      XXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX BB BBBBBBBB XXXXXXXXXXXXXXXXXXX BBBBBX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBB
          BBBBBB BBBBBBBBBBBBB
        XXXXXX
      XXXXXX
      XXXXXXXXX BB BBBBBBBB XXXXXXXXXXXXXXXXXXX BBBBBX
        XXXXXXXX gettext(u'Actions') XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
             gettext(u'Add Action') 
          XXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXX
             gettext(u'Add Update Case Property') 
          XXXXXXXXX
          XXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
        XXXXXX
      XXXXXXXXXXX
      BB BBB BBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Save') XXXXXXXXX
          XXXXXX
        XXXXXX
      BBBBB
    XXXXXXX
  XXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
              XX XXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Case property') XXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXX
         XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXX
      XXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Set case property') XXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXX
         XXXXXXXXXXXXXXXX XXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXX gettext(u'to the exact value') XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'to the value from other case property') XXXXXXXXX
        XXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XX XXX XXXXXXXXXXX XXX XXXXXXX XXX
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XX
        XXXX XXX XXX
        XXXX XX XXX XXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXX
          XXXXXXXXXXXXXXXXXXXX XXXXXXXX
           XXXXXXXXXXXXXXXX XXXXXX
           XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXX XXX
      XXXXXX
    XXXXXX
  XXXXXXXXX

BBBBBBBB
