BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXX XXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBB
  XXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
        XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
BBBBBBBB

BBBBB BBBBB gettext(u'Case Search') BBBBBBBB

BBBBB BBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBB BBBBBBB
BBBBBBBB

BBBBB BB
  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                       XXXXXXXX X
                         XXXXXXXXXXXX XXXXXXXXXXXXXX
                         XXXXXXXXX XXXXX
                         XXXXXXXXXXX XXXXX
                         XXXX XXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                       XX
                       XXXXX X XXX XXXXXXXXX X XXXXXX XXXXXXXXXXXX
  XXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXX
                       XXXXXXXX X
                         XXXXXXXXXXXX XXXXXXXXXXXXXX
                         XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                         XXXXXXXX XXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXX XXXXXX
                       XX
                       XXXXX X XXX XXXXXXXXX X XXXXXX XXXXXXXXXXXX
  XXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBB BBBBB

  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  BBBBBBBBBBBBBBBBB BBBBBBBB BBBBBB


  XX XXXXXXXXXXXXX
     gettext(u'Explore Case Data (Preview)') 
  XXXX
  XX XXXXXXXXXXXXXXXXXXX
     gettext(u'\n      This feature allows you to quickly explore your case data for ad-hoc data\n      queries or to identify unclean data.<br />\n      This is a Feature Preview.\n    ') 
      SSSS SSSSSSS SSSSSS SSS SS SSSSSSS SSSSSSS SSSS SSSS SSSS SSS SSSSSS SSSS
      SSSSSSS SS SS SSSSSSSS SSSSSSS SSSSSSSS SS
      SSSS SS S SSSSSSS SSSSSSSS
    
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXX
       gettext(u'Learn more.') 
    XXXX
  XXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX
          XX XXXXXXXXXXXXX
             gettext(u'\n              Preparing your case data for exploration...\n            ') 
              SSSSSSSSS SSSS SSSS SSSS SSS SSSSSSSSSSSSSS
            
          XXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XBBBBBBBBBBBBBBB BBBBBBBB BBBB BBBBBXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXXX
         gettext(u'Export Data') 
      XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXX
         gettext(u'Save Filters') 
      XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Report Filters') 
          XXXX
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX
           XXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXX XXXXXX XXXXX X XXXX XXXXXXXXX X XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                XXXX XXXXXXXXXXXXXXXXXXXX X
                                  XXXXX XXXXXXXXXXXXXXX
                                  XXXXX XXXXXX
                                XXXXXXXXX

              XXXXXX
            XXXXXX

          XXXXXX
        XXXXXX
      XXXXXX

    XXXXXX

    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXXX
        XXXX
          XXXX XX XXXXXXXX XXXXXXX XXX
          XXX XXXXXXXXXXXXXXXXX X XXXXXX XXXXXXX X XXXX XX
                         XXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
            XXXX
          XXXXX
          XXXX XXX XXX
          XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXX
               XXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
               gettext(u'Add Column') 
            XXXX
          XXXXX
        XXXXX
      XXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXX XXX XXXXX XXX
        XXXX
          XXXX XX XXXXXXXX X XXXXX XXXXXXXXXXXXXX XXX XXXXXXXX X XXX
          XXXX
            XXXX XX XXX XXXXXXXX XXX X XX XXXXXXXXX XXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXX X XXXXX XXXXXXXXX XXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXX
            XXXX XXX XXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXXX XXX XXX
          XXXXXXXXX
        XXXXX
      XXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'\n          Loading...\n        ') 
          SSSSSSSSSS
        
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
         gettext(u'\n          Our system is experiencing an unusually large load on resources at the moment,\n          so data is not being received in a timely fashion. We are working on the problem, but\n          if you continue to experience this issue, please contact support.\n        ') 
          SSS SSSSSS SS SSSSSSSSSSSS SS SSSSSSSSS SSSSS SSSS SS SSSSSSSSS SS SSS SSSSSSS
          SS SSSS SS SSS SSSSS SSSSSSSS SS S SSSSSS SSSSSSSS SS SSS SSSSSSS SS SSS SSSSSSSS SSS
          SS SSS SSSSSSSS SS SSSSSSSSSS SSSS SSSSSS SSSSSS SSSSSSS SSSSSSSS
        
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXX
         gettext(u'\n          No cases found.\n        ') 
          SS SSSSS SSSSSS
        
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
         gettext(u'\n          There was an issue fetching cases with these filters.\n          Please check your filters and try again.\n        ') 
          SSSSS SSS SS SSSSS SSSSSSSS SSSSS SSSS SSSSS SSSSSSSS
          SSSSSS SSSSS SSSS SSSSSSS SSS SSS SSSSSS
        
      XXXXXX
    XXXXXX

    XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX XBBBBBBBBBBBBBBB BBBBBBBB BBB BBBBBBBBB BB BB BBB BBBBBBBB BB BB BBB BBBBBBBB BB BBBBBBXX
                        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXX XXXXX
         XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXX
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Add Column') 
            XXXXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Edit Column') 
            XXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                   gettext(u'Case Property') X
                XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXX
                          XXXXXXXXXXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXX XXXXX
                                     XXXXXXXX X
                                       XXXXXXXXXXXX XBBBBBBBBBBBBBBB BBBBBB BBBB BBBBBBBBBXX
                                       XXXXXX XXXX
                                       XXXXXXXXXXX XXXXX
                                       XXXXX XXXXX
                                       XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                       XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                       XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                       XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                     XX XXXXXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                   gettext(u'Title') X
                XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXX
                         XXXXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBX
                         XXXXXXXXXXXXXXXXXXXXX XXXXXX
                                    XXXXX X
                                      XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                    XX XX
                XXXXXX
              XXXXXX

              XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                             XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
              XXXXXXX XXXXXXXXXXXXX
                      XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
                      XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Filter Data in Column') 
              XXXXXXXXX

              XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                XXXX XX XXXXXXXX XXXXXXXXXXXXXX XXX

                  XXXX XX XXX XXXXXXXX XXX X XXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'\n                      Treat this property as\n                      <select class="form-control filter-type"\n                              data-bind="options: $root.editColumnController.availableFilterNames,\n                                         optionsText: function (val) {\n                                           return $root.editColumnController.filterTitleByName[val];\n                                         },\n                                         value: filterName,\n                                         event: { change: $root.editColumnController.updateFilterName }"></select>\n                      and match\n                      <select data-bind="value: $parent.clause,\n                                         event: { change: $root.editColumnController.updateFilter }"\n                              class="form-control filter-clause">\n                        <option value="all">\n                          all of the\n                        </option>\n                        <option value="any">\n                          any of the\n                        </option>\n                      </select>\n                      following conditions:\n                    ') 
                      SSSSS SSSS SSSSSSSS SS
                      SSSSSSS SSSSSSSSSSSSSSSSSSS SSSSSSSSSSSS
                              SSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
                                         SSSSSSSSSSSS SSSSSSSS SSSSS S
                                           SSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
                                         SS
                                         SSSSSS SSSSSSSSSSS
                                         SSSSSS S SSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSS
                      SSS SSSSS
                      SSSSSSS SSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSS
                                         SSSSSS S SSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS
                              SSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSS
                        SSSSSSS SSSSSSSSSSSS
                          SSS SS SSS
                        SSSSSSSSS
                        SSSSSSS SSSSSSSSSSSS
                          SSS SS SSS
                        SSSSSSSSS
                      SSSSSSSSS
                      SSSSSSSSS SSSSSSSSSSS
                    
                  XXXXXX
                  XXXX XXX XXX

                  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                     XXXXXXXXXXXX XXXXXXXX XXXXX X
                                       XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                     XX
                                     XXXXXX XXXXXXXXXXX
                                     XXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX

                  XXXXXX XXXXXXXXXXX
                         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXXXXXXXXXXX XXXXXX
                                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX

                  XXXXXX XXXXXXXXXXXXX
                         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXXXXXXXXXXX XXXXXX
                                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX

                  XXXXXX XXXXXXXXXXX
                         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXXXXXXX XXXXXX
                                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
                  XX XXXXXXXX
                     XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXX
                  XXXX
                XXXXXX
                XXXX XXX XXX

                XXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXX XXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                   XXXXXXXX XXXXXXXXXXXXXX X
                   gettext(u'Filter Data in Column') 
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                   XXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                   gettext(u'Add Expression') 
                XXXXXXXXX
              XXXX XXX XXX

            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                               XXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXX
               gettext(u'Delete') 
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                               XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Add') 
            XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Update') 
            XXXXXXX
            XXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXX XXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXX
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'\n              This task is currently not supported, but we are happy to\n              learn about your interest.\n            ') 
              SSSS SSSS SS SSSSSSSSS SSS SSSSSSSSSS SSS SS SSS SSSSS SS
              SSSSS SSSSS SSSS SSSSSSSSS
            
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX gettext(u'Ok') XXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXX
BBBBBBBB
