BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
  
BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBB

   gettext(u"\n    <p>\n      This page allows you to directly access a specific form data or case data page.\n      Read more on our <a href='https://confluence.dimagi.com/display/commcarepublic/Find+Data+by+ID'>help site</a>.\n    </p>\n  ") 
    SSS
      SSSS SSSS SSSSSS SSS SS SSSSSSSS SSSSSS S SSSSSSSS SSSS SSSS SS SSSS SSSS SSSSS
      SSSS SSSS SS SSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSS
    SSSS
  

  BB BBBBBBBBBBBBBB
    XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXXXXX
    XXXXXXXXXXXX
  BBBBB

  BB BBBBBBBBBBBBBB
    XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXXXXX
  BBBBB
BBBBBBBB BBBBBBBBBBBB
