BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
  
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXX
         gettext(u'\n          Create rules for finding and updating duplicate cases.\n          Rules are run on each form submission.\n          When rules are created or edited the rule will be locked for further changes and a backfill process will be run.\n        ') 
          SSSSSS SSSSS SSS SSSSSSS SSS SSSSSSSS SSSSSSSSS SSSSSS
          SSSSS SSS SSS SS SSSS SSSS SSSSSSSSSSS
          SSSS SSSSS SSS SSSSSSS SS SSSSSS SSS SSSS SSSS SS SSSSSS SSS SSSSSSS SSSSSSS SSS S SSSSSSSS SSSSSSS SSSS SS SSSS
        
      XXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXX XXXXXX XXXXX XXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add Deduplication Rule') 
      XXXXXXXXX
    XXXX
  XXXXXX
BBBBBBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXX
    XXXXX
    XXXX
      XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'deprecated') XXXXXXX
    XXXXX
    XXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Active') XXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Inactive') XXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
         gettext(u'Explore Duplicates') 
      XXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
         gettext(u'Activate') 
      XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
         gettext(u'Deactivate') 
      XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
              XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XX XXX
        XX XXXXXXXXX XXXXXXXXXXXXXXX
         gettext(u'Delete') 
      XXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXX X XX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX gettext(u'Delete this rule?') XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXX
                 gettext(u'\n                  Are you sure you want to <strong>delete</strong> this rule?\n                ') 
                  SSS SSS SSSS SSS SSSS SS SSSSSSSSSSSSSSSSSSSSSSS SSSS SSSSS
                
              XXXX
              XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Cancel') 
              XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXX
                 gettext(u'Delete Rule') 
              XXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX
    XXXXX
  XXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Removed') XXXXXXX
    XXXXX
  XXXXXXXXX
BBBBBBBB BBBBBBBBBBBBBBBBBBBB
