BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX X XXXXX XXXXXXX XX XXXXX XXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXX XXXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Delete') 
      XXXXXXXXX

      XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX X XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXX
                 gettext(u'\n                  Delete case group <strong data-bind="text: name"></strong>?\n                ') 
                  SSSSSS SSSS SSSSS SSSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSS
                
              XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXX
                 gettext(u'\n                  Yes, delete the case group <strong data-bind="text: name"></strong>.\n                ') 
                  SSSS SSSSSS SSS SSSS SSSSS SSSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSS
                
              XXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                 gettext(u'Cancel') 
              XXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXX gettext(u'Deleting Group...') XX
                XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Delete Group') 
              XXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Group Deleted') XXXXXXXXXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'New') XXXXXXX
      XX XXXXXXXXXXXXXXXX X XXXXX XXXXXXX XX XXXXX XXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX
      XX XXXXXXXXXX XXXXXXXXXXXX
         XXXXXXXXXXXXXXXX X
                    XXXXX XXXXXXX
               XXX
         gettext(u'Manage Cases') 
      XXXX
    XXXXX
  XXXXXXXXX

BBBBBBBB


