BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBB
  XXXX
     gettext(u'\n      Cases in Group\n      <a href="#" id="toggle-group-name">%(group_name)s <small><i class="fa fa-edit"></i> Edit</small></a>\n    ') 
      SSSSS SS SSSSS
      SS SSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSS SSSSSSSSS SSSSSSSSSSSSS SSSSSSSSSSSSSSSS
    
  XXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    BBBBBB BBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
  BB BBBBBBBBBBBBBB

    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX
        XXXXXXXXXXXX X XXXXXXXXXX  gettext(u'cases processed. Please do not refresh or close this page.') 
      XXXX
    XXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XX XXXXXXXXXXXXXXX X XX X XX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX gettext(u'Cases were successfully added:') XXXXX
        XXXX
          XX XXXXXXXXXXXXXXX XXXXXXXX XXX X XX
          XXXXXXXXXXXXXXX
          XX XXX XX
        XXXXX
      XXXXXX
      XX X XX

      XX XX XXXXXXXXXXXXXX X XX X XX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX gettext(u'Issues encountered during bulk upload:') XXXXX
        XXXX
          XX XXXXXXXXXXXXXX XXXXXXXX XXXXXXX X XX
          XXXXXXXXXXXXXXXXXXX
          XX XXX XX
        XXXXX
      XXXXXX
      XX X XX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXX
        XXXX
          XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Processing file...') 
        XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  BBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXX XX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX gettext(u'Removing...') XX
        XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Remove') 
      XXXXXXXXX
    XXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XX XXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXX XX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXFFFFFFFFX
        XXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XX XXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXX XX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Case Removed') XXXXXXX
    XXXXX
  XXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBB
  XXX XX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Bulk upload cases to group') 
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
