EXCHANGE_RATE_DECIMAL_PLACES = 9

SMALL_INVOICE_THRESHOLD = 1
OVERDUE_INVOICE_LIMIT_DAYS = 15
DAYS_PAST_DUE_TO_TRIGGER_DOWNGRADE = OVERDUE_INVOICE_LIMIT_DAYS + 1
DAYS_PAST_DUE_TO_TRIGGER_DOWNGRADE_WARNING = OVERDUE_INVOICE_LIMIT_DAYS - 2
DAYS_PAST_DUE_TO_TRIGGER_OVERDUE_NOTICE = OVERDUE_INVOICE_LIMIT_DAYS - 7
DAYS_BEFORE_DUE_TO_TRIGGER_REMINDER = 7
