from django.urls import re_path as url

from corehq.apps.accounting.dispatcher import (
    AccountingAdminInterfaceDispatcher,
)
from corehq.apps.accounting.views import (
    AccountingSingleOptionResponseView,
    CustomerInvoicePdfView,
    CustomerInvoiceSummaryView,
    EditSoftwarePlanView,
    EditSubscriptionView,
    InvoiceSummaryView,
    ManageAccountingAdminsView,
    ManageBillingAccountView,
    NewBillingAccountView,
    NewSoftwarePlanView,
    NewSubscriptionView,
    NewSubscriptionViewNoDefaultDomain,
    TestRenewalEmailView,
    TriggerBookkeeperEmailView,
    TriggerCustomerInvoiceView,
    TriggerInvoiceView,
    SoftwarePlanVersionView,
    WireInvoiceSummaryView,
    accounting_default,
    TriggerDowngradeView,
    TriggerAutopaymentsView,
)
from corehq.apps.sso.views.accounting_admin import (
    NewIdentityProviderAdminView,
    EditIdentityProviderAdminView,
)

urlpatterns = [
    url(r'^$', accounting_default, name='accounting_default'),
    url(r'^trigger_invoice/$', TriggerInvoiceView.as_view(),
        name=TriggerInvoiceView.urlname),
    url(r'^trigger_downgrade/$', TriggerDowngradeView.as_view(),
        name=TriggerDowngradeView.urlname),
    url(r'^trigger_autopayments/$', TriggerAutopaymentsView.as_view(),
        name=TriggerAutopaymentsView.urlname),
    url(r'^trigger_customer_invoice/$', TriggerCustomerInvoiceView.as_view(),
        name=TriggerCustomerInvoiceView.urlname),
    url(r'^single_option_filter/$', AccountingSingleOptionResponseView.as_view(),
        name=AccountingSingleOptionResponseView.urlname),
    url(r'^trigger_email/$', TriggerBookkeeperEmailView.as_view(),
        name=TriggerBookkeeperEmailView.urlname),
    url(r'^test_reminders/$', TestRenewalEmailView.as_view(),
        name=TestRenewalEmailView.urlname),
    url(r'^manage_admins/$', ManageAccountingAdminsView.as_view(),
        name=ManageAccountingAdminsView.urlname),
    url(r'^accounts/(\d+)/$', ManageBillingAccountView.as_view(), name=ManageBillingAccountView.urlname),
    url(r'^accounts/new/$', NewBillingAccountView.as_view(), name=NewBillingAccountView.urlname),
    url(r'^subscriptions/(\d+)/$', EditSubscriptionView.as_view(), name=EditSubscriptionView.urlname),
    url(r'^accounts/new_subscription/$', NewSubscriptionViewNoDefaultDomain.as_view(),
        name=NewSubscriptionViewNoDefaultDomain.urlname),
    url(r'^accounts/new_subscription/(\d+)/$', NewSubscriptionView.as_view(), name=NewSubscriptionView.urlname),
    url(r'^software_plans/new/$', NewSoftwarePlanView.as_view(), name=NewSoftwarePlanView.urlname),
    url(r'^software_plans/(\d+)/$', EditSoftwarePlanView.as_view(), name=EditSoftwarePlanView.urlname),
    url(r'^software_plan_versions/(\d+)/(\d+)/$', SoftwarePlanVersionView.as_view(),
        name=SoftwarePlanVersionView.urlname),
    url(r'^invoices/(\d+)/$', InvoiceSummaryView.as_view(), name=InvoiceSummaryView.urlname),
    url(r'^wire_invoices/(\d+)/$', WireInvoiceSummaryView.as_view(), name=WireInvoiceSummaryView.urlname),
    url(r'^customer_invoices/(\d+)/$', CustomerInvoiceSummaryView.as_view(),
        name=CustomerInvoiceSummaryView.urlname),
    url(r'^customer_invoices/(?P<statement_id>[\w-]+).pdf$', CustomerInvoicePdfView.as_view(),
        name=CustomerInvoicePdfView.urlname),
    url(r'^identity_provider/(\d+)/$', EditIdentityProviderAdminView.as_view(),
        name=EditIdentityProviderAdminView.urlname),
    url(r'^identity_provider/new/$', NewIdentityProviderAdminView.as_view(),
        name=NewIdentityProviderAdminView.urlname),
    url(AccountingAdminInterfaceDispatcher.pattern(), AccountingAdminInterfaceDispatcher.as_view(),
        name=AccountingAdminInterfaceDispatcher.name()),
]
