BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXXX
  XXXXXX
    XXXXXXXBBBBB BBBBBXXXXXXXX XX XXXXXXBBBBBBBBXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    BBBBB BBBBBBBBBBB
    BBBBBBBB

    BBBBBBBBBBBBBBBBBBBB
    BBBBBBBB BB
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBBBBBBBB

    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    BBBBB BBBBBBBBBBBB
  XXXXXXX
  XXXXXX

    BBBBB BBBBBB
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
                   XXXXXXXXXXXXX XX XXXXXXX XX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              BBBBB BBBBBBBBBB
              BBBBBBBB
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    BBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      BBBBB BBBBBBBBBBBBBBBBBBB
      BBBBB BBBBBBBBBBBBBBB
    XXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBB
          XXX
             gettext(u'CommCare HQ Mobile is Copyright')  XXXXXX BBB BBB
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
          XXXX
          BBBBB BBBBBBBBBBBBB
            XXX
              XX XXXXXXBBB BBBBBBBBXX gettext(u'Logout') XXXX
            XXXX
          BBBBBBBB
        BBBBBBBB
      XXXXXX
    XXXXXXXXX

    BBBBB BBBBBBBBBB

  XXXXXXX
XXXXXXX
