BBBBBBB BBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB

  XXXX
     gettext(u'You do not have domain permissions.') 
  XXXXX

  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXXX XX XX X XXXXXXXXX XXXXXXXXX
  BBBB
    XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXX XXXXXX
  BBBBB

  BBBBB BBBBBBBBBBBBBBBBBBB

BBBBBBBB
