from django.conf.urls import patterns, url

from .views import (
    LocationsListView,
    NewLocationView,
    EditLocationView,
    FacilitySyncView,
    LocationImportView,
    LocationImportStatusView,
    LocationTypesView,
    LocationFieldsView,
    DowngradeLocationsView,
)

settings_urls = patterns('corehq.apps.locations.views',
    url(r'^$', 'default', name='default_locations_view'),
    url(r'^child_locations/$', 'child_locations_for_select2'),
    url(r'^list/$', LocationsListView.as_view(), name=LocationsListView.urlname),
    url(r'^location_types/$', LocationTypesView.as_view(), name=LocationTypesView.urlname),
    url(r'^sync_facilities/$', FacilitySyncView.as_view(), name=FacilitySyncView.urlname),
    url(r'^import/$', LocationImportView.as_view(), name=LocationImportView.urlname),
    url(r'^import_status/(?P<download_id>[0-9a-fA-Z]{25,32})/$', LocationImportStatusView.as_view(), name=LocationImportStatusView.urlname),
    url(r'^location_importer_job_poll/(?P<download_id>[0-9a-fA-Z]{25,32})/$',
        'location_importer_job_poll', name='location_importer_job_poll'),
    url(r'^export_locations/$', 'location_export', name='location_export'),
    url(r'^sync_openlmis/$', 'sync_openlmis', name='sync_openlmis'),
    url(r'^new/$', NewLocationView.as_view(), name=NewLocationView.urlname),
    url(r'^fields/$', LocationFieldsView.as_view(), name=LocationFieldsView.urlname),
    url(r'^downgrade/$', DowngradeLocationsView.as_view(),
        name=DowngradeLocationsView.urlname),
    url(r'^unassign_users/$', 'unassign_users', name='unassign_users'),
    url(r'^(?P<loc_id>[\w-]+)/archive/$', 'archive_location', name='archive_location'),
    url(r'^(?P<loc_id>[\w-]+)/unarchive/$', 'unarchive_location', name='unarchive_location'),
    url(r'^(?P<loc_id>[\w-]+)/$', EditLocationView.as_view(), name=EditLocationView.urlname),
)
