# Generated by Django 2.2.20 on 2021-05-07 04:40

import dimagi.utils.couch.migration
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLReportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=32)),
                ('report_type', models.CharField(max_length=32)),
                ('report_slug', models.CharField(max_length=32)),
                ('subreport_slug', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('owner_id', models.CharField(max_length=64)),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('date_range', models.CharField(max_length=12, null=True)),
                ('days', models.IntegerField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('datespan_slug', models.CharField(max_length=64, null=True)),
                ('update_seq', models.CharField(max_length=1000)),
                ('purge_seq', models.IntegerField()),
                ('db_name', models.CharField(max_length=12)),
                ('doc_del_count', models.IntegerField()),
                ('instance_start_time', models.CharField(max_length=1)),
                ('disk_size', models.IntegerField()),
                ('doc_count', models.IntegerField()),
                ('disk_format_version', models.IntegerField()),
                ('data_size', models.IntegerField()),
                ('couch_id', models.CharField(db_index=True, max_length=126, null=True)),
            ],
            options={
                'db_table': 'saved_reports_reportconfig',
            },
            bases=(dimagi.utils.couch.migration.SyncSQLToCouchMixin, models.Model),
        ),
    ]
