from corehq.apps.es.client import Tombstone
from corehq.pillows.core import DATE_FORMATS_ARR, DATE_FORMATS_STRING


SMS_MAPPING = {
    "_all": {
        "enabled": False
    },
    "_meta": {
        "comment": "Autogenerated [corehq.apps.sms.models.SMSLog] mapping from ptop_generate_mapping 09/23/2013",
        "created": None
    },
    "date_detection": False,
    "date_formats": DATE_FORMATS_ARR,
    "dynamic": False,
    "properties": {
        "backend_api": {
            "type": "text"
        },
        "backend_id": {
            "type": "keyword"
        },
        "base_doc": {
            "type": "text"
        },
        "billed": {
            "type": "boolean"
        },
        "couch_recipient": {
            "type": "keyword"
        },
        "couch_recipient_doc_type": {
            "type": "text"
        },
        "date": {
            "format": DATE_FORMATS_STRING,
            "type": "date"
        },
        "direction": {
            "type": "text"
        },
        "doc_id": {
            "type": "keyword"
        },
        "doc_type": {
            "type": "keyword"
        },
        "domain": {
            "fields": {
                "exact": {
                    "type": "keyword"
                }
            },
            "type": "text"
        },
        "phone_number": {
            "type": "text"
        },
        "processed": {
            "type": "boolean"
        },
        "reminder_id": {
            "type": "keyword"
        },
        "text": {
            "type": "text"
        },
        "workflow": {
            "type": "text"
        },
        "xforms_session_couch_id": {
            "type": "keyword"
        },
        Tombstone.PROPERTY_NAME: {
            "type": "boolean"
        }
    }
}
