BBBB BBBB
BBBB BBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXX
     gettext(u'Add Property') 
  XXXXXXXXX
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Property') XXXXXXXXX

      XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Graph') XXXXXXXXX
      XXXX XXX XXX
      XXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Graph <small>(upgrade to 2.17 or greater)</small>') XXXXXXXXX
      XXXX XXX XXX

      XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Calculated Property') XXXXXXXXX
      XXXX XXX XXX
    XXXXX
  BBBB
    XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Property') XXXXXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Calculated Property') XXXXXXXXX
    XXXXX
    XXXX XXX XXX
  BBBBB
XXXXXX
