BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBBBXX
  BBBBBBBBBB
  XXXXXXXXXX
       XXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Menu(s)')  XXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
                BBB BBBBBBBBB BB BBBBBBBBBBBBBBBBB
                  XXXXXXX XXXXXXXXXFFFFFFFFFFFFFFFFXXXXXXXXX
                BBBBBB
              XXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
            XXXXXX
          XXXXXX
            BB BBBBBBBBBBB BB BBBBBBB
            XXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                   gettext(u'Display properties') 
                XXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                   gettext(u'Case list filter') 
                XXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                   gettext(u'Sort configuration') 
                XXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Custom variables') 
                  XXXXXXXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                     gettext(u'Custom case list XML') 
                  XXXXXXXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Case tile configuration') 
                  XXXXXXXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Print template') 
                  XXXXXXXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Search properties') 
                  XXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Default search filters') 
                  XXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Search and claim options') 
                  XXXXXXXXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                     gettext(u'Multi-Select Case List Options') 
                  XXXXXXXXXXXX
                BBBBB
            XXXXXX
          XXXXXX
          BBBBB
          XXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXX
                BB BBBBBBBBBBB BB BBBBBBB
                   gettext(u'Overwrite Case List') 
                BBBB
                   gettext(u'Overwrite Case Detail') 
                BBBBB
              XXXXXXXXX
              XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Overwrite Case Lists/Case Details') XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                       gettext(u'Are you sure you want to overwrite this configuration? This action is irreversible.') 
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Cancel') 
                      XXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXXX
                         gettext(u'Overwrite') 
                      XXXXXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
       XXXXXX
  XXXXXXXXXXX
XXXXXXX
