BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
           gettext(u'Form Accessible from Case List') 
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX gettext(u'Forms Accessible from Case List') X
                XXXXXXXXXXXXXX gettext(u"Use Registration Forms to minimize duplicate registrations by requiring mobile workers to search the case list before registering a new case. Read more on the <a href='https://help.commcarehq.org/pages/viewpage.action?pageId=30605985'>Help Site</a>.\n                You can use followup forms for Parent Case button if this module uses Select Parent First workflow") SSS SSSSSSSSSSSS SSSSS SS SSSSSSSS SSSSSSSSS SSSSSSSSSSSSS SS SSSSSSSSS SSSSSS SSSSSSS SS SSSSSS SSS SSSS SSSS SSSSSS SSSSSSSSSSS S SSS SSSSS SSSS SSSS SS SSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSS
                SSS SSS SSS SSSSSSSS SSSSS SSS SSSSSS SSSS SSSSSS SS SSSS SSSSSS SSSS SSSSSS SSSSSS SSSSS SSSSSSSSX
          XXXXXXXX
        BBBB
           gettext(u'Registration Form Accessible from Case List') 
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX gettext(u'Registration Form Accessible from Case List') X
              XXXXXXXXXXXXXX gettext(u"Minimize duplicate registrations by requiring mobile workers to search the case list before registering a new case. Read more on the <a href='https://help.commcarehq.org/pages/viewpage.action?pageId=30605985'>Help Site</a>.") SSSSSSSS SSSSSSSSS SSSSSSSSSSSSS SS SSSSSSSSS SSSSSS SSSSSSS SS SSSSSS SSS SSSS SSSS SSSSSS SSSSSSSSSSS S SSS SSSSS SSSS SSSS SS SSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSX
          XXXXXXXX
        BBBBB
      XXXXXXXX
      BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Unknown Form (missing)') XXXXXXXXX
            BBBBB
            XXXXXXX XXXXXXXXX gettext(u"Don't Show") XXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXXXXXXX XXXXXXX gettext(u'Registration Forms') XX
                BBB BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  BB BBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXXX XXXXXXXXXXXXXXXXXX
                  BBBBB
                BBBBBB
              XXXXXXXXXXX
              XXXXXXXXX XXXXXXX gettext(u'Followup Forms for parent case ') SSSSSSSS SSSSS SSS SSSSSS SSSS XX
                BBB BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  BB BBB BBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXXX XXXXXXXXXXXXXXXXXX
                  BBBBB
                BBBBBB
              XXXXXXXXXXX
            BBBB
              BBB BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXXXXX XXXXXXXXXXXXXXXXXX
                BBBBB
              BBBBBB
            BBBBB
          XXXXXXXXX
          XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Error! The selected form does not exist.') 
          XXXXXX
        XXXXXX
      BBBB
        XXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXX
           gettext(u'Registration from the case list is not available because') 
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B
            BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              
            BBBBBB
          BBBB
            XXXX
              BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXXXXX
              BBBBBB
            XXXXX
          BBBBB
        XXXXXX
      BBBBB
    XXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
           gettext(u'Display Condition') 
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBX
                XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBB BBBB BBBB BBBB BB BBBBBBBBB BBBB BBBB BBBBB BBBBBBBBBB BBBBBBBBB BB BBBBB BBBB BBBB BBBBBB B BBBBBBB BBBBBBX
          XXXXXXXX
        XXXXXXXX
        XXXX XXXXXXXBBBBBBBBBBBBBBBXX
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFFFFFFFX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    BBBBB
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
           gettext(u'Label for Case List Form') 
        BBBB
           gettext(u'Label for Case List Registration') 
        BBBBB
      XXXXXXXX
      XXXX XXXXXXXBBBBBBBBBBBBBBBXX
        BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
           gettext(u'End of Form Action') 
        BBBB
           gettext(u'End of Registration Action') 
        BBBBB
      XXXXXXXX
      XXXX XXXXXXXBBBBBBBBBBBBBBBXX
        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                     XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                     XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
           gettext(u'\n            The case list form action will be the same as the selected form\'s end of form navigation.\n            To avoid this, set the form\'s end of form navigation to the default option (\'Home Screen\') in\n            <a target=\'_blank\' data-bind="attr: {href: caseListFormSettingsUrl() + \'#form-settings\'}">form settings</a>.\n          ') 
            SSS SSSS SSSS SSSS SSSSSS SSSS SS SSS SSSS SS SSS SSSSSSSS SSSSSS SSS SS SSSS SSSSSSSSSSS
            SS SSSSS SSSSS SSS SSS SSSSSS SSS SS SSSS SSSSSSSSSS SS SSS SSSSSSS SSSSSS SSSSSS SSSSSSSS SS
            SS SSSSSSSSSSSSSSS SSSSSSSSSSSSSSSS SSSSSS SSSSSSSSSSSSSSSSSSSSSSSSS S SSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSS
          
        XXXXXX
      XXXXXX

    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBB BBBBBB
    BBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBB
    BBBBB
  XXXXXX

BBBBB
