BBBB BBBB
BBBB BBBBBBBBBBBBBB

XXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXX
    XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXXX XXX XXX
      XXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Property') XXXXX
      XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Display Text') XXXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Format') XXXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Case Tile Mapping') XXXXX
      XXXXXXXXXX
      XXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Display Text') XXXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Format') XXXXX
      XXXX XXX XXX
      XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Row/Column') XXXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Width/Height') XXXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Align/Text Size') XXXXX
      XXXX XXX XXX
      XXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXX
            XXXXXXXXX XXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXX XX
            XXXXXXXXXXXXX XXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXX X
        XX
      
      
    XXXX XXXXXXXXXXX
                XXXX XXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXX X XXXXXXXXXX
                XXXXX XXXXXXXX XX X XXXXXX XXXXXXXXXXXXXXX XX
                XXXXXX XXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXX X
            XX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXXXXX XXXXXXXXXXX
                        XXX XXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX
                    XXXXXX
      XXXXX
      XXXXXX XXX XXXXXX XXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XX XXX XXXXXXXXXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Calculated Property') XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXXXXXXXX
        XXXX XXX XXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX
          XXXXXXX
        XXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX X
                            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX X
                            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX
      XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
      XXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXXXXXXXX
      XXXXXXXXXX
      XXXXXX XXX XXXXX XXX
      XXXXXX XXX XXXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX XXXXX XX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXXXXXXXX
      XXXXXX XXXXXX XXXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXX
      XXXXXXXXXX
      XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXX XXX XXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX
           XXXXXXX gettext(u'Delete') X
           XXXXXXXXX XXXXXXXXXX
           XXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
      XXXXX
      
      
    XXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXX
    XXXX
      XXXXXXXXX
      XXX XXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
    XXXXX
    XXXXXXXX
  XXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
XXXXXX
