BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Custom Case List XML') 
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBBBBB BB BBBBBBBB BBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB


XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
       gettext(u'Display Properties') 
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX
               gettext(u'Case Tile Template') 
            XXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      BBBBB
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
               gettext(u'Show some information about the case at the top of the screen when filling out forms') 
            XXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXX
               gettext(u'Case property to show') 
            XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XX
          XXXXXX
        XXXXXX
      BBBBB
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'Show case tiles grouped by parent case') 
          XXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
                 gettext(u'Parent case index name') 
              XXXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XX
              XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
                 gettext(u'Case tile header rows') 
              XXXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XX
              XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      BBBBB
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Use this case list tile persistently in forms') 
          XXXXXXXX
        XXXXXX
      XXXXXX

      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
          BB BBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX
                   gettext(u'Use persistent case tile from menu') 
                XXXXXXXX
                XXXXX
                  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXX
                       gettext(u'Select Menu') 
                    XXXXXXXXX
                    BBB BBBBBBBBB BB BBBBBBBBBBBBBBBBB
                      XXXXXXX XXXXXXXFFFFFFFFFFFFFFFFXXXXXXXXX
                    BBBBBB
                  XXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          BBBBB
        BBBBBBB
      BBBBB

      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Embed case details in case tile pull-down') 
                    XXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Embed case details in case tile pull-down from the menu') 
                    XXXXXXX
          XXXXXXXX
        XXXXXX
      XXXXXX

      XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX
              XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXX
           gettext(u'Reset Grid') 
      XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX X
                XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXX
            XXXX XXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXX XXXXX XXXX XXXXXXXXX XXXX XXXX XXXXXX XX XX XXXXXXXXXXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX XX XXX XX XXXXXXX XXXXXXXXXXXXXXXXX X XXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX XX XXX XX XXXXXXX XXXXXXXXXXXXXX X XXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXX
                  XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XX XXX XX XXXXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XX XXX XX XXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX X XXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXX XXXXX XXXXXXX XXXXXXXXXXX X XXX
                    XX XXXXXXXXX XXXXXXXXXXXXXX
                  XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXX
                  XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XX XXX XX XXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX X XXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XX XXXX XX XXXXXXX XXXXXXXXXXXX X XXX
                    XX XXXXXXXXX XXXXXXXXXXXXXX
                  XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXX
                  XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXX XXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XX XXX XX XXXXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXX
                XXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX

      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX
XXXXXX


BB BBBBBBBBBBB BB BBBBBB
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Filtering and Sorting') 
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
              XXXXXXX
              XXXX
                XXXXXXXXX
                XXXX
                   gettext(u'Sort Property') 
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX gettext(u'Sort Properties') X
                        XXXXXXXXXXXXX
                          X gettext(u'\n                                              Properties in this list determine how\n                                              cases are ordered in your case list. This\n                                              is useful if for example you want higher\n                                              priority cases to appear closer to the\n                                              top of the list. The case list will sort\n                                              by the first property, then the second,\n                                              etc.\n                                          ') 
                                              SSSSSSSSSS SS SSSS SSSS SSSSSSSSS SSS
                                              SSSSS SSS SSSSSSS SS SSSS SSSS SSSSS SSSS
                                              SS SSSSSS SS SSS SSSSSSS SSS SSSS SSSSSS
                                              SSSSSSSS SSSSS SS SSSSSS SSSSSS SS SSS
                                              SSS SS SSS SSSSS SSS SSSS SSSS SSSS SSSS
                                              SS SSS SSSSS SSSSSSSSS SSSS SSS SSSSSSS
                                              SSSS
                                          X X
                                XXXXXXX
                XXXXX
                XXXX gettext(u'Direction') XXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXX
                     gettext(u'Display Blanks') 
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                          XXXXXXXXXXXX gettext(u'Display Blanks') X
                          XXXXXXXXXXXXX
                            X gettext(u"\n                                                  Should cases that don't have a value for the sort property\n                                                  appear at the top or the bottom of the case list?\n                                              ") 
                                                  SSSSSS SSSSS SSSS SSSSS SSSS S SSSSS SSS SSS SSSS SSSSSSSS
                                                  SSSSSS SS SSS SSS SS SSS SSSSSS SS SSS SSSS SSSSS
                                              X X
                                    XXXXXXX
                  XXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXX gettext(u'Sort Calculation') XXXXX
                BBBBB
                XXXX gettext(u'Format') XXXXX
                XXXX
                   gettext(u'Display Text') 
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX gettext(u'Display Text') X
                        XXXXXXXXXXXXX
                          X gettext(u"\n                                              The 'Display Text' is used for properties that are only listed as\n                                              Sort Properties and not as Display Properties above. The text appears\n                                              in the 'Sort By' menu on the mobile to allow the user to change the\n                                              sort ordering. If the display text is left blank then the option\n                                              for that sort property will not appear in the 'Sort By' menu.\n                                          ") 
                                              SSS SSSSSSSS SSSSS SS SSSS SSS SSSSSSSSSS SSSS SSS SSSS SSSSSS SS
                                              SSSS SSSSSSSSSS SSS SSS SS SSSSSSS SSSSSSSSSS SSSSSS SSS SSSS SSSSSSS
                                              SS SSS SSSSS SSS SSSS SS SSS SSSSSS SS SSSSS SSS SSSS SS SSSSSS SSS
                                              SSSS SSSSSSSSS SS SSS SSSSSSS SSSS SS SSSS SSSSS SSSS SSS SSSSSS
                                              SSS SSSS SSSS SSSSSSSS SSSS SSS SSSSSS SS SSS SSSSS SSS SSSSS
                                          X X
                                XXXXXXX
                XXXXX
                XXXXXXXXX
              XXXXX
              XXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXX
                XXXX
                  XX XXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXX
                  XXXXXX
                XXXXX
                XXXX
                  XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXX
                  XXXXXXXXX
                XXXXX

                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX
                         gettext(u'Bottom of list') 
                      XXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Top of list') 
                      XXXXXXXXX
                    XXXXXXXXX
                  XXXXX
                BBBBB

                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                  XXXXX
                BBBBB


                XXXX
                  XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXXX XXXXXXXXXXXXXX
                       gettext(u'Plain') 
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX
                       gettext(u'Date') 
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXX
                       gettext(u'Integer') 
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXX
                       gettext(u'Decimal') 
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXX
                       gettext(u'Distance from current location') 
                    XXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Cache and Index') 
                      XXXXXXXXX
                    BBBBB
                  XXXXXXXXX
                XXXXX
                XXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXX
                XXXX
                  XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
                  XXXX
                XXXXX
              XXXXX
              XXXXXXXX
            XXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX XXX XXX XXXXX XXXXXX
            X
              XX XXXXXXXXX XXXXXXXXXXXXX
               gettext(u'Add sort property') 
            XXXXXXXXX
          XXXXXX
        BBBBB
      XXXXXX
    XXXXXX
  XXXXXX
BBBBB

BB BBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
           gettext(u'Parent Child Selection') 
        XXXXX
      XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBXX
               gettext(u'Select Parent First') 
            XXXXXXXX
            XXXXX
              XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                             XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
                             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXX
              XXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBXX
               gettext(u'Use Case List from') 
            XXXXXXXX
            XXXX XXXXXXXBBBBBBBBBBBBBBBXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                 gettext(u'\n                  This menu could not be found. It may have been deleted. Please select a different menu.\n                ') 
                  SSSS SSSS SSSSS SSS SS SSSSSS SS SSS SSSS SSSS SSSSSSSS SSSSSS SSSSSS S SSSSSSSSS SSSSS
                
              XXXXXX
            XXXXXX
          XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB

BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB

BB BBBBBBBBBBB BB BBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB
