BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
      BBBBB BBBBB
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXBBBBB BBBBBX
            XXXXXXXXXXXXXXBBBBB BBBBX
      XXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXBBBBBBBBBBBBBBBXX
      XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX BB BBB BBBBBBBBBBBBBBXXXXXXXXBBBBBXXXXXX XXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXXXXXXXXX
      XXXXXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
       gettext(u'Label for Case List Menu Item') 
    XXXXXXXX
    XXXX XXXXXXXBBBBBBBBBBBBBBBXX
      BBBBBBBBBBB BBBBBBBBBBBBBBB BBBBB
      XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Case list menu item requires a label') 
            XXXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBB BBB BBBB BBBB BBBB BBBBB BBBBBBBBBBBBBBBBBB BBB BBBB BBBB BBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX

BBBBB
