BBBB BBBBBBBBBBBBBB
BBBB BBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Multi-Select Case List Options') 
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
               gettext(u'Enable multi-select case list') 
            XXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Enable auto select') 
            XXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBXX
                 gettext(u'Maximum selected value') 
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Maximum Selected Value') X
                      XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBB B BBBBBBB BBBBBBBB BBBBB BBB BBBBB BBBBBB BBBB BBBBBB BB BB BBBBB BB BBBBBBBBB BBB BBBBBBB BBBBB BB BBBBBBXX
            XXXXXXXX
            XXXX XXXXXXXBBBBBBBBBBBBBBBXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

BBBBB
