BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX


BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
       gettext(u'Display Properties') 
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX gettext(u'Case Detail') X
            XXXXXXXXXXXXXX gettext(u'These properties will be displayed on a confirmation screen after a case has been selected. If no properties are listed here the confirmation screen will not be displayed at all.') X
      XXXXXXXX
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXX

  XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XX XXXXXXXXX XXXXXXXXXXXXX
     gettext(u'Add Tab') 
  XXXXXXXXX

  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Add Tab') XXXXXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Add Data Tab') XXXXXXXXX
    XXXXX
  BBBBB

XXXXXX

XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX gettext(u'Case Detail Tabs') X
      XXXXXXXXXXXXXX gettext(u"Do you have a lot of case properties? Try splitting them into tabs, which will appear as separate screens that mobile users can swipe through. Read more on the <a href='https://help.commcarehq.org/display/commcarepublic/Tabs+on+Case+Detail+Screen' target='_blank'>Help Site</a>.") SS SSS SSSS S SSS SS SSSS SSSSSSSSSSS SSS SSSSSSSSS SSSS SSSS SSSSS SSSSS SSSS SSSSSS SS SSSSSSSS SSSSSSS SSSS SSSSSS SSSSS SSS SSSSS SSSSSSSS SSSS SSSS SS SSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSS SSSSSSSSSXX
XXXXXXX

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Printing') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
             gettext(u'Document Template') 
          XXXXXXXX
          XXXX XXXXXXXBBBBBBBBBBBBBBBXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXX XXXXXXX
               XXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXX gettext(u'Opens file in new tab.') XX gettext(u'Open HTML') XXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXX
                                XXXXX X XXXXXXXXXXXXXXXXXXX XXXX XX
                                XXXXXX X XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX
                            XX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Upload HTML') XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Replace HTML') XXXXXXX
            XXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXX
               XXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXXX XXXXXX
                    XX
              XX XXXXXXXXX XXXXXXXXXXXXXXX
            XXXX
          XXXXXX
        XXXXXX
      BBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Printing the case detail is not supported on this version of CommCare') XXXXXX
      BBBBB
    XXXXXX
  XXXXXX
BBBBB
