BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBB

XXXXXXXX
   gettext(u'Case Search and Claim') 
XXXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
     gettext(u'Add at least one search property to activate case search for this case list') 
  XXXXXX
  XXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Search Properties') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXX gettext(u'Search against the following case properties.') XXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
          XXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX gettext(u'Case Property') XXXXX
            XXX XXXXXXXXXXXXXXXXX gettext(u'Display Text') XXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXX XXXXXXXXXXXXXXXXX gettext(u'Other Options') XXXXX
            BBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXXXX
        XXXXXXXX
        XXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXX XXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add search property') 
          XXXXXXXXX
        XXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Default Search Filters') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXX gettext(u'Filter based on a specific value of any case property. These are applied to every search and are hidden from the user.') XXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
          XXXX
            XXX XXXXXXXXXXXXXXXXX gettext(u'Case Property') XXXXX
            XXX XXXXXXXXXXXXXXXXX gettext(u'Value (XPath expression)') XXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                 gettext(u'A property is not allowed both here and Search Properties. Please remove from one of the lists') 
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
              XXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX
                 XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
          XXXXX
          XXXXXXXX
        XXXXXXXX
        XXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXX XXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add default search property') 
          XXXXXXXXX
        XXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Search and Claim Options') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Web Apps Search Workflow') 
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Web Apps Search Workflow') X
                        XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBB BB BBB BBBBBBBBBBBBBBBBBBB BBBB BBBBBB BBBBBBBBB  BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBB BBB BBBBBB BBBB BBBB BBBB BBB BBBBB BBB BBBB BB BBB BBBBBB BBBBBBB BBBB BB BBBBBBBBB BBBB BBB B BBBBBBBBBBBB BBBBBBBBBBB BBBBBBB  BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BB BBB BBBB BBBBBBBBBBBBB BB BBBBBB BBBB BBBBB BBBBBB BBBBBBBB BBB BBBBBB BBBBBB BBBB BBB BBBBBBB BBBBBBBB BBB BBBBBBB BBB BBBBBBBB BBB BBBB BBBBBBB BBB BB BBBBBB BBB BBBBBB BBBBBBBBB BBBB BBBBBBB B BBBBBBBB BBBBB BBB BBBB BBBB BBBBBB BB BBB BBBBB BBBBBB BBBB BBBBBB BBBBBBBBB BBBBBBBBBB BB BBBB BBB BBBBB BBBB BBB BBB BBBBBBBBB  BBBBBBBBBBBBBBBBBBBB BB BBBBBBB BBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBB BBBBBBBB BBB BBBBBBB BBBB BBB BBBBBBB BBBB BBBBBBB BBB BBBB BBBBB BBBB BBB BBBBBBB BB BBB BBBBBBBBXX
                  XXXXXXX
                XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Web Apps Search Workflow') 
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Web Apps Search Workflow (Data Registry)') X
                        XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBB BBB BBBBBB BBBB BBBB BBBB BBB BBBBB BBB BBBB BB BBB BBBBBB BBBBBBB BBBB BB BBB BBBBBBB BBB BBBB BBBBBBBB BBBBBBB  BBBBBBBBBBBBBBBBBBBB BB BBBBBBB BBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBB BBBBBBBB BBB BBBBBBB BBBB BBB BBBBBBB BBBB BBBBBBBBXX
                  XXXXXXX
                XXXXXXXX
                XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                  XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Normal Case List') XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Search First') XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'See More') XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX gettext(u'Skip to Default Case Search Results') XXXXXXXXX
                  XXXXXXXXX
                XXXXXX
              XXXXXX
            BBBBB
          XXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBXX
               gettext(u'Make search input available after search') 
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Make search input available after search') X
                    XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBB BBBBBB BBBBB BBBBBB BBB BBBBB BBB BBBBBBBBB BBB BBB BBBBBBBBBBBBBB BBBBBBBBB BBBB BBBB BBBBBBBB BBB BBBBBBB BBBBBB BBBBBBBBBBXX
              XXXXXXX
            XXXXXXXX
            XXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXX
              XXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXX
            XXXXXX
          XXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
               gettext(u'Label for Searching') 
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Label for Searching') X
                    XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBB BBBB BB BBB BBB BBBBBB BB BBBBB BBBB BBBBBBB BB BB BBBB BBB BBBBBB BB BBB BBBBBB BBBBBBB BBBBBBBBXX
            XXXXXXXX
            XXXX XXXXXXXBBBBBBBBBBBBBBBXX
              BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XX XXXXX XXXXXXXXX XXXX XXX XXXXXXX XX XXXXXXXXX XXXXXXXX XX X XXXXXXXXX XXXXXX XXXXXXXXXXX
          XXXX XXXXXXX XXX XXXX XXXXXXX XX XXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XX XXXXXXXXXXXX XXXX XXX
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBB BBBBBB
            XXXX XXX XXX
          XXXXXX
            BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                 gettext(u'Label for Searching Again') 
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Label for Searching Again') X
                      XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBB BBBB BB BBB BBB BBBBBB BBBBBB BBBBBBBBB BB BBB BBBBBB BB BBBBBB BBBBBBBB BB BBBBB BBB BBBBBB BBBBBBBXX
              XXXXXXXX
              XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XX XXXXX XXXXXXXXX XXXX XXX XXXXXXX XX XXXXXXXXX XXXXXXXX XX X XXXXXXXXX XXXXXX XXXXXXXXXXX
            XXXX XXXXXXX XXX XXXX XXXXXXX XX XXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XX XXXXXXXXXXXX XXXX XXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBB BBBBB BBBBBBBBBBBBBBBBBBB BBBBB BBBBBB
              XXXX XXX XXX
            XXXXXX
            BBBBB
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
               gettext(u'Search Screen Title') 
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Search Screen Title Translation') X
                    XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBB BBBBB BBBBB BBBBBBBBB BB BBB BBBBBB BBBBBBBBXX
            XXXXXXXX
            XXXX XXXXXXXBBBBBBBBBBBBBBBXX
              BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBB
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
               gettext(u'Search Screen Subtitle') 
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Search Screen Subtitle') X
                    XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBB BBBB BBBBBBBBB BB BBB BBBBBB BBBBBBB BBB BBBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBB BBBBBB BBB BBBBBBBB BBBBBB BBB BB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
            XXXXXXXX
            XXXX XXXXXXXBBBBBBBBBBBBBBBXX
              BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX
          XXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBXX
               gettext(u'Display Condition') 
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Display Condition') X
                    XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBB BBBB BBBBB BBBBBBBBBB BBBBBBBBB BB BBBBBB BBB BBBB BBBBBB BBBBBB BBBB BBB BB BBBBBBBBB BB BBB BBBB BBBBB BB BB BBBBBBBBBB BB BBBBBB BBB BBBBBB BBBB BBBBBB BB BBBBBBBBB BB BBB BBBB BBBBBBXX
              XXXXXXX
            XXXXXXXX
            XXXX XXXXXXXBBBBBBBBBBBBBBBXX
              XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXX
                         XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                       X
              XXXXXXXXXXXX
            XXXXXX
          XXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBXX
               gettext(u'Search Filter') 
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Search Filter') X
                    XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBB BBBBB BBBBBBBBBB BB BBBBBB BBB BBBBBB BBBBBBBBBXX
            XXXXXXXX
            XXXX XXXXXXXBBBBBBBBBBBBBBBXX
              XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   gettext(u'Copy case list filter') 
                XXXXXXXXX
                 gettext(u'Example: age > 5') 
              XXXX
            XXXXXX
          XXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBXX
               gettext(u'Claim Condition') 
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Claim Condition') X
                    XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBB BBBB BBBBBBBBBB BBBBBBBBB BB BBBBBB BB BBBB BBBB BB BBBBBBBBBXX
              XXXXXXX
            XXXXXXXX
            XXXX XXXXXXXBBBBBBBBBBBBBBBXX
              XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBXX
               gettext(u"Don't search cases owned by the following ids") 
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Ignore Owners') X
                    XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBB BBBBB BBBBBBBBBB BBBB BBBB BBBBBBBB BB B BBBBB BBBBBBBBB BBBB BB BBBBBXX
              XXXXXXX
            XXXXXXXX
            XXXX XXXXXXXBBBBBBBBBBBBBBBXX
              XXXXXXXXX XXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              X
                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXX
                 gettext(u"\n                  Example: instance('commcaresession')/session/context/userid or 'a1c0148dc2120c6b1762f5ac5aba2a15'\n                ") 
                  SSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
                
              XXXX
            XXXXXX
          XXXXXX
          BB BBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                   gettext(u'Data Registry') 
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Data Registry') X
                        XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBB B BBBB BBBBBBBB BB BBB BBB BBBBBBBBBB  BBBBB BBBB BBBBBB BBBB BBB BBBBBBB BBBB BBB BBBBBBBB BBBB BBBBBBBBBB BBBB BBBBBBBBXX
              XXXXXXXX
              XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                  XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXX
                      BBB BBBBBBBB BB BBBBBBBBBBBBBBB
                          XXXXXXX XXXXXXXXXXXXXXXXXX
                      BBBBBB
                  XXXXXXXXX
              XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                   gettext(u'Data Registry Workflow') 
              XXXXXXXX
              XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                  XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBB
                  XXXXXXXXX
              XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                   gettext(u'Load Additional Data Registry Cases') 
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Data Registry') X
                        XXXXXXXXXXXXXX gettext(u"\n                        Load additional cases from the Data Registry into the 'registry' instance for forms in this module.\n                        The case type of the case must be configured in the registry and in the module via the module's\n                        case type or the module's 'Additional Case List and Case Search Types' configuration.\n                        ") 
                        SSSS SSSSSSSSSS SSSSS SSSS SSS SSSS SSSSSSSS SSSS SSS SSSSSSSSSS SSSSSSSS SSS SSSSS SS SSSS SSSSSSS
                        SSS SSSS SSSS SS SSS SSSS SSSS SS SSSSSSSSSS SS SSS SSSSSSSS SSS SS SSS SSSSSS SSS SSS SSSSSSSS
                        SSSS SSSS SS SSS SSSSSSSS SSSSSSSSSSS SSSS SSSS SSS SSSS SSSSSS SSSSSS SSSSSSSSSSSSSS
                        XX
                  XXXXXXX
              XXXXXXXX
              XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXX
                    XXXX
                      XXX XXXXXXXXXXXXXXXXXX gettext(u'Case ID XPath') XXXXX
                      XXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXX
                        XXXX
                          XXXXXXXXX XXXXXXXXXXX
                              XXXXXX XXXXXXXXXXXX
                              XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                              X
                                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXXXXXXXX
                          XXXXXXXXXXXX
                        XXXXX
                        XXXX
                          XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX
                             XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX
                      XXXXX
                    XXXXXXXX
                  XXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add Case ID to Data Registry Query') 
                  XXXXXXXXX
              XXXXXX
          XXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                   gettext(u'Case property with additional case id to add to results') 
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Custom Related Case Property') X
                        XXXXXXXXXXXXXX gettext(u"\n                               Enter in the name of a case property that contains the ID of another\n                               case you'd like included in the results instance.  This is to allow\n                               you to configure your case list display to show properties of that\n                               related case. Read more on the\n                                <a href='https://confluence.dimagi.com/display/USH/Case+Search+Configuration'>Help Site</a>.\n                        ") 
                               SSSSS SS SSS SSSS SS S SSSS SSSSSSSS SSSS SSSSSSSS SSS SS SS SSSSSSS
                               SSSS SSSSS SSSS SSSSSSSS SS SSS SSSSSSS SSSSSSSSS  SSSS SS SS SSSSS
                               SSS SS SSSSSSSSS SSSS SSSS SSSS SSSSSSS SS SSSS SSSSSSSSSS SS SSSS
                               SSSSSSS SSSSS SSSS SSSS SS SSS
                                SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSS
                        XX
                  XXXXXXX
              XXXXXXXX
              XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXX
                         XXXXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBXX
               gettext(u'Include all related cases in search results') 
            XXXXXXXX
            XXXXX
              XXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXX
                XXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
          BBBBB
          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'\n              This is not a valid xpath expression. Check to make sure your parentheses match and you are referencing case properties correctly.\n            ') 
              SSSS SS SSS S SSSSS SSSSS SSSSSSSSSSS SSSSS SS SSSS SSSS SSSS SSSSSSSSSSS SSSSS SSS SSS SSS SSSSSSSSSSS SSSS SSSSSSSSSS SSSSSSSSSS
            
            XXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXX
XXXXXX
