BBBB BBBB
BBBB BBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
       gettext(u'Case List Search Callout') 
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'Enable case list search callout') 
          XXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Autolaunch Lookup') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
             gettext(u'Action') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
                   XXXXXXXXXXXXX gettext(u'ex: callout.commcarehq.org.dummycallout.LAUNCH') X XX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                           gettext(u'Case list callout requires an action') 
                      XXXXXXX
          XXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Action Name') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
                   XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'ex: Scan fingerprint') X XX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                           gettext(u'Case list callout requires a name') 
                      XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
             gettext(u'Extras') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XX XXXXXXXX XXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XX
              XXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X X XX XXXXXXX XXX XX XX XXXXXXX XXX XXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXX
                XXXX
              XXXXXX
            XXXXXX
            XXXX XXX XXX
            XX XXXXXXXX
               XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
              XX XXXXXXXXX XXXXXXXXXXXXX XXX XXX XXXXXX XXXXX XXXX
            XXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
                           gettext(u'At least one extra required') 
                      XXXXXXX
          XXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
             gettext(u'Responses') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XX XXXXXXXX XXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X X XX XXXXX XX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXX
                XXXX
              XXXXXX
            XXXXXX
            XXXX XXX XXX
            XX XXXXXXXX
               XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX
              XX XXXXXXXXX XXXXXXXXXXXXX XXX XXX
            XXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX gettext(u'At least one response required') XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXX XX XXXXXXXXXXXX XXXX XXX
          BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
          BBBBBBB
          XXXX XXX XXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
             gettext(u'Display results in case list') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
               gettext(u'Results display text') 
            XXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
               gettext(u'Results mapping property') 
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXX gettext(u'Case property or attribute used to map each result row to the correct case.') XXXXXXXXX
            XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                     XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
