BBBB BBBB
BBBB BBBBBBBBBBBBBB

XXXX
  XXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
  XXXXX
  XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
       gettext(u'A property is not allowed both here and Default Search Filters. Please remove from one of the lists') 
    XXXXXX
  XXXXX
  XXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXX
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX
    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X   XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX
       gettext(u'Configure') 
    XXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
               gettext(u'Options for:') 
              XXXX XX XXXXX XXXXX XXXXXXX XXX XXX
            XXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXX
                XXXXXXXX gettext(u'Basic') XXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                     gettext(u'Help Text') 
                  XXXXXXXX
                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXXXXXXX
                  XXXXXX
                XXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                     gettext(u'Default Value Expression') 
                  XXXXXXXX
                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXXXXX
                       gettext(u'In "YYYY-MM-DD to YYYY-MM-DD" format') 
                    XXXX
                    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXX XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX
                       gettext(u'e.g. Use #,# as separator to select multiple values') 
                    XXXX
                  XXXXXX
                XXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                       gettext(u'Format') 
                    XXXXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                        XXXXXXX XXXXXXXXX gettext(u'Text') XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                          
                          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                          XXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Checkbox') XXXXXXXXX
                          BBBBB
                          XXXXXXX XXXXXXXXXXXXX gettext(u'Date') XXXXXXXXX
                        BBBBB
                        XXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Date Range') XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Barcode') XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Lookup Table Selection') XXXXXXXXX
                        BBBBB
                        BB BBBBBBBBBBBBBBBBBBBBBBBBB
                          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Mobile UCR Selection') XXXXXXXXX
                        BBBBB
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                          XXXXXXX XXXXXXXXXXXXXXXX gettext(u'Geocoder Broadcast') XXXXXXXXX
                        BBBBB
                      XXXXXXXXX
                    XXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXX XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                           gettext(u'Allow multiple selections') 
                      XXXXXXXX
                      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
                          XXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
                      XXXXXX
                  XXXXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                       gettext(u'Allow searching for blank values') 
                    XXXXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                  XXXXXX
                BBBBB
              XXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXX XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                         XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXX
                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXX XXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXX XXXXXXX
                      XXXXXXXXXXXXX XXXXXXXX
                      XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX gettext(u'Label Field') XXXXXXXX
                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX gettext(u'Value Field') XXXXXXXX
                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX gettext(u'Sort Field') XXXXXXXX
                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                     gettext(u'Instance Nodeset') 
                  XXXXXXXX
                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                       gettext(u'This refers to data other than selected report/lookup-table.') 
                    XXXX
                  XXXXXX
                XXXXXX
                XXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXXXXXXXX
                      XXXXXXXX gettext(u'Advanced Options') XXXXXXXXX
                      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX XX
                          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                               gettext(u'Geocoder Receiver Expression') 
                            XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                               gettext(u'Hide in Search Screen') 
                            XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      BBBBB
                      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXX
                          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                             gettext(u'Exclude From Search Filters') 
                          XXXXXXXX
                          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                          XXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
                          XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                               gettext(u'Required') 
                            XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                              XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                                   gettext(u'Required Message') 
                              XXXXXXXX
                              XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                                  XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                              XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                               gettext(u'Validation Condition') 
                            XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                              XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
                               gettext(u'Validation Message') 
                            XXXXXXXX
                            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                              XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                          XXXXXX
                        XXXXXX
                      BBBBB
                    XXXXXXXXXXX
                BBBBB
              BBBBB
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
               gettext(u'Done') 
            XXXXXXXXX
          XXXXXX
            XXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXX
  BBBBB
  XXXX
    XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX
       XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
XXXXX
