BBBB BBBB

XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Custom Detail Variables') 
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXX gettext(u'Add custom variables to the variables node.') XXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX XXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                    XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
