BBBB BBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXX
       gettext(u'Visit Scheduler') 
    XXXXXXXXX

    XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX
             gettext(u'Enable visit scheduler') 
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXX gettext(u'Visit Schedule') X
                  XXXXXXXXXXXXXX gettext(u'Be able to configure a visit schedule') XXXXXXXXX
          XXXXXXXX
          BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXXXX
                 gettext(u'\n                  Visit schedule will be ignored as not all\n                  forms in the case list update or close a case.\n                ') 
                  SSSSS SSSSSSSS SSSS SS SSSSSSS SS SSS SSS
                  SSSSS SS SSS SSSS SSSS SSSSSS SS SSSSS S SSSSS
                
              XXXXXXXXX
            XXXXXX
          BBBBB
        XXXXXX
      XXXXXX
    XXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXXX gettext(u'Schedule Phases') XXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXXXXXXX
        XXXX gettext(u'Schedule Phase Number') XXXXX
        XXXX gettext(u'Schedule Anchor Property') XXXXX
        XXXX gettext(u'Forms in this phase') XXXXX
        XXXXXXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
                                  XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXX
         gettext(u'Add Phase') 
      XXXXXXXXX
    XXXXXXXXXXX
  XXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
      XXXX
        XX XXXXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXXXXX
           XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX
                              XXXXXXXX XXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
                                  XXXXXX X XXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX X XXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXX
      XXXX
        XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX
           XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                              XXXXXXXX XXXXXXXXXXXXXX XX X
                              XXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX
           XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
           XXXXXXX gettext(u'You can only delete phases that have no forms') X
           XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXX
      XXXXX
    XXXXX
  XXXXXXXXX
BBBB
   gettext(u'\n    Visit schedules can only be used when all the forms in the case list<br/>\n    update or close a case, which means registration forms must go in a separate case list.\n  ') 
    SSSSS SSSSSSSSS SSS SSSS SS SSSS SSSS SSS SSS SSSSS SS SSS SSSS SSSSSSSSS
    SSSSSS SS SSSSS S SSSSS SSSSS SSSSS SSSSSSSSSSSS SSSSS SSSS SS SS S SSSSSSSS SSSS SSSSS
  
BBBBB
