BBBB BBBB

XXXXXX XXXXXXXXXXXXXX
  XXXXXXX
  XXXX
    XXXX gettext(u'Filter') XXXXX
    XXXX gettext(u'Type') XXXXX
    XXXXXXXXX
  XXXXX
  XXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX XXX
  XXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXXXXXXXXX XXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX
        XXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXXXXXXXXX XXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX
                                            XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXX
                                XXX
            XXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX XX XXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXX
                  XXXXXXXXXXX
                                    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXXX XXXXXXXXXXXXXXX
                            XXXXXXXXXXXX XXXXXXXXXX
                            XXXXXXXXXXXXX XXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXX
                 XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXXX
              XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXX
                                        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    X
            XXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXX XXX
      XXXXXX
    XXXXX
  XXXXX
  XXXXXXXX
XXXXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
