BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBB
  XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XX XXXXXXXX X
      XXXXXXXXXXXX XXXXX
    X
  XXXXXXXX
BBBBBBBB

XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Settings') XXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Reports') XXXXXXXXX
XXXXX

XXXX XXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX
        XXXXXX
      XXXXXXXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXX
        XXX XXXXXXXXXXXX
          XXXXXXXXX
          XXXX gettext(u'Report') XXXXX
          XXXX gettext(u'Display Text') XXXXX
          XXXX gettext(u'Description') XXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Sync Delay (in hours)') 
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXX XXXXXX
                  XXXXXXXXXXXXXXXXXXX XX XXXXX XXXXXX XXXXXXX XXX XXXXXX XXXX XX XXXXXX XXXXXXXX XXXXX XXXXX XX XXXXXXXXXX XXXXXX XXXXXX XXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
          XXXXX

          XXXX
             gettext(u'Data Table') 
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXX XXXXXX
                  XXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXX XXXX XXXX X XXX XXXX X XXXXXXX XXXXX XXXXXXXXXX XXX XXXX XXX XXXX XXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX
          XXXXX
          XXXXXXXXX
        XXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXX XXX XXXXXXXX XXX
        XXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXX
            XX XXXXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
          XXXXX
          XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
            XXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Display codes') XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Hide codes') XXXXXXX
            XXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXXXX gettext(u'UUID:') XXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                                                XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Custom alias:') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXX
          XXX XXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXXXXXX XXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
               gettext(u'Use xpath expression') 
            XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXX
                 gettext(u'Must be a valid xpath expression.') 
              XXXX
              XXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXX
                 gettext(u'Not localizable.') 
              XXXX
            XXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXX
               gettext(u'Domain sync delay set to: ') XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u' hours.') 
            XXXX
          XXXXX
          XXXX
            XXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXX
          XXXXX
          XXXX
            XX XXXXXXX gettext(u'Delete') X XXXXXXXXXXXXXX XXXXXXXXX
               XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
        XXXXX
        XXXXXXXX
      XXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXX
         gettext(u'Add Report') 
      XXXXXXXXX
    XXXXXXXXXXX
  XXXXXX

XXXXXX
