BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBX
      XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXX
  BBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Show') XXXXX
      BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB BB BBBBBBBB BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB BB BBB BBBBBBBBBBBBBBBBB
        XXXX
          XX XXXXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXX gettext(u'Menu') 
          XXXX
        XXXXX
      BBBBB
      XXXX
        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXX gettext(u'Multimedia') 
        XXXX
      XXXXX
      BB BBBBBBBBBBBBBBBBBBBBBB
        XXXX
          XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXX gettext(u'Advanced') 
          XXXX
        XXXXX
      BBBBB
    XXXXX
  XXXXXX
  XXXXXXXXXX
    BBBBB BBBBBBBBBBBBBBB

      BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB BB BBBBBBBB BB BBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB BB BBB BBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Menu') XXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            BB BBB BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBB BB BBBBBBBB
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

              BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                   gettext(u'Additional Case List and Case Search Types') 
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX gettext(u'Additional Case List and Case Search Types') X
                        XXXXXXXXXXXXXX gettext(u"\n                             Cases of these types will be displayed in Case List and Case Search screens, in addition to the Case Type inputted above.\n                             <a target='_blank'\n                             href='https://confluence.dimagi.com/display/ccinternal/Case+Search+and+Claim'>(More   Information)</a>\n                              ") 
                             SSSSS SS SSSSS SSSSS SSSS SS SSSSSSSSS SS SSSS SSSS SSS SSSS SSSSSS SSSSSSSS SS SSSSSSSS SS SSS SSSS SSSS SSSSSSSS SSSSSS
                             SS SSSSSSSSSSSSSSS
                             SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS   SSSSSSSSSSSSSSSS
                              XX
                  XXXXXXX
                XXXXXXXX
                XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
                    BBB BBBBBBBBB BB BBBBBBBBBB
                    XXXXXXX XXXXXXXX BB BBBBBBBBB BB  BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
                    BBBBBB
                  XXXXXXXXX
                XXXXXX
              XXXXXX
              BBBBB
            BBBBB

            BB BBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                   gettext(u'Parent Menu') 
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX gettext(u'Parent Menu') X
                        XXXXXXXXXXXXXX gettext(u"\n                               Nest this menu under another for easier application navigation.\n                               <a href='https://confluence.dimagi.com/display/commcarepublic/Sub+Menus'>(More Information)</span>\n                               ") 
                               SSSS SSSS SSSS SSSSS SSSSSSS SSS SSSSSS SSSSSSSSSSS SSSSSSSSSSS
                               SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSS
                               XX
                  XXXXXXX
                XXXXXXXX
                XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                  BB BBBBBBBBBBBBB
                    XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                      XXXXXXX XXXXXXXX XXXXXXXX X
                        FFFFFFFFFFF
                      XXXXXXXXX
                    XXXXXXXXX
                  BBBB
                    XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBB BB BBBBBBBB XXXXXXXX BBBBBX
                      XXXXXXX XXXXXXXXX gettext(u'No Parent') XXXXXXXXX
                      BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXXXXX XXXXXXXXBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB XXXXXXXXBBBBBX
                          FFFFFFFFFFF
                        XXXXXXXXX
                      BBBBBB
                    XXXXXXXXX
                  BBBBB
                XXXXXX
              XXXXXX
            BBBBB

            BB BBBBBBBBBBBBBBBBBB BB BBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                     gettext(u'Source Menu') 
                  XXXXXXXX
                  XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                    
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB XXXXXXXX BBBBB
                            XXXXXXXXXXXXXXXXXXX XXXXXXXX
                                             XXXXXXXXXXXX XXXXXXX
                                             XXXXXXXXXXXXX XXXXXXXXXXX
                                             XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                     gettext(u'Include Forms') 
                  XXXXXXXX
                  XXXXXX XXXXXXXBBBBBBBBBBBBBBBX
                       XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                                 XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                             XXXXXXXXXXXX XXXXXXX
                                             XXXXXXXXXXXXX XXXXXXXXXXX
                                             XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBB
                      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                      XXXXXX
                    BBBBB
                  XXXXXX
                XXXXXX
              XXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BB B
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                     gettext(u'Shadow Module Version') 
                  XXXXXXXX
                  XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                    XX 
                      XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBBBXX
                         gettext(u'Upgrade to version 2') 
                      XXXX
                  XXXXXX
                XXXXXX
              BBBBB
            BBBBB

            BB BBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                   gettext(u'Menu Mode') 
                XXXXXXXX
                XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                  XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                                                 XXX XXXXXXXXXXXXXX
                                                 XXXXXXXX XX
                                                    XXX XXXXXXXX
                                                    XXXXX XBBBBBBBBBBBBBBB BBBBBBBB BBBB BBB BBBB BBBBBBXX
                                                 XX X
                                                    XXX XXXXXXX
                                                    XXXXX XBBBBBBBBBBBBBBB BBBBBBBB BBBB BBBBBBXX
                                                 XXX
                                                 XXXXXX XBB BBBBBBBBBBBBBBBBBBXXXXBBBBXXXXXBBBBBXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            BBBB
              
              XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBXXXXBBBBXXXXXBBBBBX XX
            BBBBB

            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                   gettext(u'Display Style') 
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX gettext(u'Display Style') X
                        XXXXXXXXXXXXXX gettext(u"Display this module's forms as a list or a grid. Read more on the <a target='_blank' href='https://confluence.dimagi.com/display/commcarepublic/Grid+View+for+Form+and+Module+Screens'>Help Site</a>.") SSSSSSS SSSS SSSSSSSS SSSSS SS S SSSS SS S SSSSS SSSS SSSS SS SSS SS SSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSXXXXXXXXX
                XXXXXXXX
                XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                  XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX gettext(u'List') XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXBBBBBX
                       gettext(u'Grid') 
                    XXXXXXXXX
                  XXXXXXXXX
                XXXXXX
              XXXXXX
            BBBBB

            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

          XXXXXX
        XXXXXX
      BBBBB

      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Multimedia') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      XXXXXX

      BB BBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Advanced') XXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBB
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBB

            BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBB BB BBBBBBBB BBB BBB BBBBBBBBBBBBBBBBB
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBB BBBB BBBB BBBBB BBBBBBBB BBBB BB BBB BBBBBBBB BBBB BBBB BBBB BBB BBBBBB BBB BBBB BBBB BBBBBBB BBBBBB BB BB BBBB BBB B BBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB

              BB BBBBBBBBBBBBBBBBBB BB BBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBB BBBBB BBBBBBBBBBBBB BB BBBB BB BBBB BB BBB BBBBBBBB BBBB BBBB BBBB BBB BBB BBB BB BBBB BBBBBBBBB BBBBBB BBBB BBBBB BBBBB BB BBBBBB BBBBB B BBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
              BBBBB
            BBBBB

            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

            BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBXX
                   gettext(u'Auto Select Case') 
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXX gettext(u'Auto Select Case') X
                        XXXXXXXXXXXXXX gettext(u'When the case list contains only one case, skip over it, jumping directly to case details.') SSSS SSS SSSS SSSS SSSSSSSS SSSS SSS SSSSS SSSS SSSS SSS SSSSSSS SSSSSSSS SS SSSS SSSSSSSSX
                  XXXXXXXX
                XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
                  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            BBBBB

            BB BBBBBBBBBBBBBBBBBBBBBBBBB
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBB
              BB BBB BBBBBBBBBBBBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBB
              BBBBB
            BBBBB

            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
                 gettext(u'Empty Case List Text') 
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Empty Case List Text') X
                      XXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBB BBBBBBBBB BBBB BBBB BBBB BBB BB BBBBBBBBBX
                XXXXXXXX
              XXXXXXXX
              XXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
              XXXXXX
            XXXXXX
            BBBBB

            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBB

          XXXXXXXXXX XXX XXXXXXXXXXX XXX
        XXXXXXXXXX XXX XXXXXX XXX
      BBBBB

    BBBBBBBB
  XXXXXXXXXXX
XXXXXXX
