BBBB BBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BBBB BBBBBBBBBBBBBBBBBBBBBBBB B BBB BBBBBBBBBB B BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBB
      BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBB
      BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
      BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBB BBBBBBBBBBBBBBBBB
      BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBB
      BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB
  BBBBBBB
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXX
    XXXXXXXXXXXXXXXX
    XXXXXX XFFFFFFFFXX
    XXXXXXXXXXXX XXXXXX BB BBB BBBBBBBBBBBBBBBBBXXXX XXXXBBBBB XXXXXXXXXXX XXXXXX
    XXXX XBBB BBBBBBBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBXX
    XXXXXXXXXXXXXX XXXXXXXXXX
    XXXXX XXX
    XXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFX
XXXXXXXXXXXXXXXX
  XXX XX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
