BBBB BBBBBBBBBBBBBB
BBBB BBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX
       gettext(u'Display Condition') 
    XXXXXXXX
    XXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
              XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXX gettext(u'XPath expression') X
              XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXX X
                    XXXXX BB BBBBBBBBBBBBXXXXXBBBBBX
                    XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXX XX XXXXXXXXX XXXXX XXXX XXX XXXXX XX XXX XXXXXXX
        XXXXX XX XXXX XXXX XXXX XXXXXXXXXXX XXXXXX
        XXXX XXXX XXXXX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
    XXXXXX
  XXXXXX
BBBBB
