BBBB BBBB
BBBB BBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXX
      XXXXXXXXXXXFFFFFFFFFFFFFFX
      XXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XX XXXXXXXXXXXXX gettext(u'New feature to overwrite case lists/case details in bulk.') XXXX
    XXX
         gettext(u'\n          Please select the case lists/detail menu(s) that needs to be overwritten.\n        ') 
          SSSSSS SSSSSS SSS SSSS SSSSSSSSSSSS SSSSSSS SSSS SSSSS SS SS SSSSSSSSSSSS
        
    XXXX
  XXXXXX
BBBBB
XXXXX
  XXX gettext(u"To save time when building large applications, it can be useful to copy one menu's entire case list or case details configuration to another menu.") 
    XX XXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Learn More') 
    XXXX
  XXXX
XXXXXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
       gettext(u'Copy Case List to another menu') 
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXX
       gettext(u"This will <strong>overwrite</strong> the case list of the selected menu with the current menu's case list configuration.") 
    XXXX
    BBBB BBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB
  XXXXXX
XXXXXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
       gettext(u'Copy Case Detail to another menu') 
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXX
       gettext(u"This will <strong>overwrite</strong> the case detail of the selected menu with the current menu's case detail configuration.") 
    XXXX
    XXXXXXXX
    BBBB BBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB
  XXXXXX
XXXXXX
