BBBB BBBBBBBBBBBBBB
BBBB BBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX BBBBBBBBBBBBBBBXX
       gettext(u'Last UCR Update') 
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXX
      XXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X XX
        XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXX
         gettext(u'\n          Throughout this menu, include a persistent report tile displaying the last time UCR data\n          was synced.\n        ') 
          SSSSSSSSSS SSSS SSSSS SSSSSSS S SSSSSSSSSS SSSSSS SSSS SSSSSSSSSS SSS SSSS SSSS SSS SSSS
          SSS SSSSSSS
        
      XXXXXXXX
    XXXXXX
  XXXXXX
BBBBB
