BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      BBBBBBB BBBB
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
