BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB

BBBBB BBBBB gettext(u'Thank you for logging in!') BBBBBBBB

BBBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'Thank you for logging in!') XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXX
         gettext(u'You may close this window and return to your work.') 
      XXXX
    XXXXXX
  XXXXXX
BBBBBBBB BBBBBBB
