BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB

BBBBB BBBBB gettext(u'Thank you for logging in with Single Sign-On!') BBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'Thank you for logging in with Single Sign-On!') XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXX
         gettext(u'\n          You may close this window and return to your work. Thank you.\n        ') 
          SSS SSS SSSSS SSSS SSSSSS SSS SSSSSS SS SSSS SSSSS SSSSS SSSS
        
      XXXX
    XXXXXX
  XXXXXX
BBBBBBBB BBBBBBB
