BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Register OAuth application') 
    XXXXX
    BBBBBBBBBB

    BBB BBBB BB BBBBB
      BBB BBBBB BB BBBB
        XXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBXXXXXBBBBBXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            
            BBB BBBBB BB BBBBBBBBBBBB
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBB
          XXXXXX
        XXXXXX
      BBBBBB

      XXXX XXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBXXXXXBBBBBXX
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBB
      XXXXXX
    BBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
             gettext(u'Go Back') 
          XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Save') XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXXXXX
  XXXXXX
BBBBBBBB
