BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBB

  XXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXX
    XXXXXXXX
      
    XXXXXXXXX
  XXXXXX

  BB BBBBBBBB BBB BBBBBBBBBBBBB
    XX XXXXXXXXXXXX
  BBBBB
BBBBBBBB
