BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBB

BBBBB BBBBBBB
  BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX BBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
      XXXX XXXXXXXXXXXXXXX
           XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXXXXXX XXXXXXXXBBBBBBBB XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
      XXXXXX
      XXXX XXXXXXXXXXXXXXX
           XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXX XXXXXXXX XXXXXXXXXBBBBBBBBXX
        BBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX
            XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX
        BBBB
          BBBBB BBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXX
          BBBBBBBB
        BBBBB
        BBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB BBBBBBB
