BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBB XXXXXXBBBBBXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBB BBBBBBX
       XXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBB XXXXXXBBBBBXX
      XX XXXXXXXXX XXXXXXXXXXXXX
    XXXX
  XXXXXX
  XXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBB BBBBBBX
       XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX
  XXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXX XXXXXXX
     gettext(u'Updates Available to Publish') 
  XXXXXX
  BB BBBBBBBBBBB BBB BBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXXXX
  X
     gettext(u'\n    Linked from %(name)s | V%(version)s\n    ') 
    SSSSSS SSSS SSSSSSSS S SSSSSSSSSSSS
    
  XXXXXX
  BBBBB
XXXXXX
