BBBB BBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
           gettext(u'\n            Are you sure you want to delete this application?\n          ') 
            SSS SSS SSSS SSS SSSS SS SSSSSS SSSS SSSSSSSSSSSS
          
        XXXXX
      XXXXXX

      XXXXX XXXXXXXXBBB BBBBBBBBBBBB BBBBBB BBBBBBX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXX
             gettext(u'You are about to delete this application') SSS SSS SSSSS SS SSSSSS SSSS SSSSSSSSSSS
            XXXXXXXXXXXXXXXXXX
          XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
             gettext(u'Cancel') 
          XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXX
             gettext(u'Delete') 
          XXXXXXXXX
        XXXXXX
      XXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXX XXX
  XXXXXXXXXX XXXXXXXXXXXXXX XXX
XXXXXXXXXX XXXXXXX XXX
