BBBB BBBBBBBBBBBBB
BBBB BBBB

XXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Custom Icon') XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXX
                XXXXXX
                     gettext(u'Form') 
                XXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
               XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBXX
      XXXXXXXX
      XXXXXXX
                XXXXXX
                     gettext(u'Text Body') 
                XXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXFFFFFFFFFFFXX
      XXXXXXXX
      XXXXXXX
                XXXXXX
                     gettext(u'XPath Function') 
                XXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBXX
      XXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
