 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #


BBBB BBBB
BBBB BBBBBBBBBBBBBB
XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Downloading Your File') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Processing data. Please wait...') 
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
