BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBB BBBBB
BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBB BBBBB
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX
    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBB BB BBBBBBBBBBBBBB
       gettext(u'Form Summary')  X  gettext(u'Version')  XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    BBBB BBBBBBBBB BB BBBBBBBBBBB
       gettext(u'Form Changes')   X
       gettext(u'Version')  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX
       gettext(u'Version')  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    BBBBB
    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Go') XXXX
  XXXXX

  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXX XXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                         XXXXX XXX XXXXXXXXXXXXXXX XXXXX X gettext(u'Calculations') X X XXXXXXXX XXX XXX
          XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX X XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                         XXXXX XXX XXXXXXXXXXXXXX XXXXX X gettext(u'Display') X X XXXXXXXX XXX XXX
          XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
                         XXXXX XXX XXXXXXXX XXXXX X gettext(u'Validation') X X XXXXXXXX XXX XXX
          XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX X XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                         XXXXX XXX XXXXXXXXXXXXXXX XXXXX X gettext(u'Comments') X X XXXXXXXX XXX XXX
          XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                         XXXXX XXX XXXXXXXXX XXXXX X gettext(u'Default Values') X X XXXXXXXX XXX XXX
          XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                         XXXXX XXX XXXXXXXXXXXXXX XXXXX X gettext(u'Cases') X X XXXXXXXX XXX XXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
