BBBB BBBB
BBBB BBBBBBBBBBBBBB
XXXX XXXXFFFFFFFFFFFFFFFFFFXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXBBBBB BBBBBXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXX
      BB BBBB BB BBBBBBB
        
        
        XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
          XXXXXX
      BBBB BBBB BB BBBBBBB
        XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX
           XXXXXXXXXX XXXXXXXXXXXX
           XXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXX
           gettext(u'Preview') 
        XXXX
      BBBBB
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
                               XXXXXXX XXXXXXXX
                               XXXXXX X
                                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                               XXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Replace') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Upload') XXXXXXX
      XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
              XXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXX
                        XXXXXXX XXXXXXXX
                        XXXXXX X
                            XXXXXX XXXXXXXXXXX
                        X
                    XX
        XX XXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
              XXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXX
                        XXXXXX XXXXXXXX XX X
                            XXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXX XXXX XXX X XXXX XX XXXXXXXX XXXX
                        XXX
        XX XXXXXXXXX XXXXXXXXXXXX
         gettext(u'Set Path') 
      XXXXXXXXX
      BB BBBB BB BBBBBBB
        XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
           gettext(u'\n            To hear audio on Java Phones, you must be in CommCare Sense\n            mode or Numeric Selection Mode. (On Android it will always work.)\n          ') 
            SS SSSS SSSSS SS SSSS SSSSSSS SSS SSSS SS SS SSSSSSSS SSSSS
            SSSS SS SSSSSSS SSSSSSSSS SSSSS SSS SSSSSSS SS SSSS SSSSSS SSSSSS
          
        XXXX
      BBBBB
      BB BBBBBBBBBBBBBBBB B B
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXXX
             gettext(u'\n              Use this %(label)s for all languages\n            ') 
              SSS SSSS SSSSSSSSS SSS SSS SSSSSSSSS
            X
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XX
          XXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX
           gettext(u'\n            This %(label)s is linked to the default language, and can only be modified there.\n          ') 
            SSSS SSSSSSSSS SS SSSSSS SS SSS SSSSSSS SSSSSSSSS SSS SSS SSSS SS SSSSSSSS SSSSSS
          
        XXXXXX
      BBBBB
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Path') XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                         XXXXXXX XXXXXXXX
                         XXXXXXXXXXXX XXXXXXXXXXXXX XX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXFFFFFFFFFFFFFFFFFFXXXXXXX
             XXXXXXXXXXXXXXXXX XXXXXXXXXX XX
      XXXXXX XXXXXXXXXXXXX
             XXXXXXFFFFFFFFFFFFFFFFFFXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
              XXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXX
                        XXXXXX X XXXXXX XXXXXXXXXXXXXX X
                    XX
        XX XXXXXXXXX XXXXXXXXXXXXXXX
         gettext(u'Use Default Path') 
      XXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
