BBBB BBBBBBBBBBBBBB
BBBB BBBB
XXXX XXXXXXXXXXXX XXXXX XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Upload Icon Image') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
             gettext(u'Select Icon Image') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Select') XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
             gettext(u'Current Icon') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXX
        XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Begin Upload') 
        XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXX XXXXX XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Upload Menu Audio') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
             gettext(u'Select Menu Audio') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Select') XXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX

            XXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
             gettext(u'Current Audio') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXX
        XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Begin Upload') 
        XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
