BBBB BBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXBBB BBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
