BBBB BBBB

XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Feature Discrepancy') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXX
           gettext(u"\n            The following features are not turned on in the domain to which you're copying.\n            Select any that you wish to copy along with this application.\n          ") 
            SSS SSSSSSSSS SSSSSSSS SSS SSS SSSSSS SS SS SSS SSSSSS SS SSSSS SSSSSS SSSSSSSS
            SSSSSS SSS SSSS SSS SSSS SS SSSS SSSSS SSSS SSSS SSSSSSSSSSSS
          
        XXXX
        XXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXX
             gettext(u'Select All') 
          XXXXXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Copy') XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXX XX
        XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXX
        XXX XXXXX XX
      XXXXXXXX
    XXXXX
  XXXXXXXXX
XXXXXX
