BBBB BBBB

XXXX XXXX XXXX XXXXXX XX XXXX XXXXX XX XXXXX XXX XXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX XX XXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Oops! This application was deleted.') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXX gettext(u'If you want your application back, click Restore.') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBB BBBBBBX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX
           gettext(u'Restore') 
        XXXX
        XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'No thanks, get me out of here') 
        XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
