BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBBBBBB BB
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXX
  XXXXXX
XXXXXXXXX
