# Generated by Django 2.2.16 on 2021-02-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_auto_20210119_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclogsql',
            name='auth_type',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
