"""Views serving the committed OpenAPI reference artifacts.

The Redoc page and the bundled specification under ``docs/api/openapi/dist/``
are generated by ``yarn openapi:docs`` and ``yarn openapi:bundle`` and committed
to the repository, because readthedocs builds this project with a Python-only
environment and cannot run the Node bundler. The ``lint-openapi`` CI job
verifies that the committed copies still match the specification source, so
serving them directly is safe.

These views are deliberately unauthenticated, matching the styleguide: the same
content is already published publicly through readthedocs, so gating it would
only make the reference harder for integrators to reach.
"""
from functools import lru_cache
from pathlib import Path

from django.conf import settings
from django.http import Http404, HttpResponse

DIST_DIR = Path(settings.FILEPATH) / 'docs' / 'api' / 'openapi' / 'dist'
REDOC_PAGE = DIST_DIR / 'openapi' / 'index.html'
BUNDLED_SPEC = DIST_DIR / 'openapi.bundled.yaml'

_REGENERATE_HINT = "Run 'yarn openapi:bundle && yarn openapi:docs' to generate it."


@lru_cache(maxsize=None)
def _read_artifact(path):
    """Read a generated artifact, caching the result for the process lifetime.

    The artifacts are immutable for the lifetime of a deploy, so reading each
    one once is enough. ``lru_cache`` does not cache exceptions, so a missing
    file is retried on the next request — which matters in development, where
    the artifacts may be generated after the server starts.
    """
    return path.read_bytes()


def _serve_artifact(path, content_type):
    try:
        content = _read_artifact(path)
    except OSError:
        raise Http404(f'{path.name} has not been generated. {_REGENERATE_HINT}')
    return HttpResponse(content, content_type=content_type)


def api_docs(request):
    """Serve the Redoc reference page for the public APIs."""
    return _serve_artifact(REDOC_PAGE, 'text/html; charset=utf-8')


def api_spec(request):
    """Serve the bundled OpenAPI document.

    Offered alongside the rendered page so that code generators and LLM tooling
    have a stable URL for the machine-readable specification.
    """
    return _serve_artifact(BUNDLED_SPEC, 'application/yaml; charset=utf-8')
