BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXX X
                      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX
        XXXX XX XXX XXXXXXX XX XXXXXX XXX
          XXXX XX XXX XXXXXXXXXX XXX
             gettext(u'Delete Selected Feeds') 
          XXXX XXX XXX
          XXXX XX XXX XXXXXXXXXXXXX XXX
             gettext(u'Delete Selected Feed') 
          XXXX XXX XXX
        XXXX XXX XXX
        XXXX XX XXX XXXXXXXX XX XXXXXXX XXX
          XXXX XX XXX XXXXXXXXXX XXX
             gettext(u'Delete Selected Exports') 
          XXXX XXX XXX
          XXXX XX XXX XXXXXXXXXXXXX XXX
             gettext(u'Delete Selected Export') 
          XXXX XXX XXX
        XXXX XXX XXX
      XXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX
  XXXXXX
XXXXXX
