BBBB BBBB

XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXX
        XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
           gettext(u'\n            Maximum number of OData feeds reached.\n          ') 
            SSSSSSS SSSSSS SS SSSSS SSSSS SSSSSSSS
          
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
         gettext(u"\n          At this time we allow a maximum of %(odata_feed_limit)s OData feeds per project space.\n          Please consider deleting the feeds that you don't need anymore.\n        ") 
          SS SSSS SSSS SS SSSSS S SSSSSSS SS SSSSSSSSSSSSSSSSSSSS SSSSS SSSSS SSS SSSSSSS SSSSSS
          SSSSSS SSSSSSSS SSSSSSSS SSS SSSSS SSSS SSS SSSSS SSSS SSSSSSSS
        
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Ok') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
