from __future__ import absolute_import

from custom.enikshay.const import (
    ALTERNATE_NUMBER_1,
    ALTERNATE_NUMBER_2,
    ALTERNATE_NUMBER_3,
    BACKUP_PHONE_NUMBER,
    CURRENT_ADDRESS,
    ENIKSHAY_ID,
    ENROLLED_IN_PRIVATE,
    OTHER_NUMBER,
    PERSON_FIRST_NAME,
    PERSON_LAST_NAME,
    PRIMARY_PHONE_NUMBER,
    PRIVATE_SECONDARY_PHONE_NUMBER,
    TREATMENT_OUTCOME,
    TREATMENT_OUTCOME_DATE,
    TREATMENT_START_DATE,
    TREATMENT_SUPPORTER_FIRST_NAME,
    TREATMENT_SUPPORTER_LAST_NAME,
    TREATMENT_SUPPORTER_PHONE,
    WEIGHT_BAND,
)

NINETYNINEDOTS_NUMBERS = [
    PRIMARY_PHONE_NUMBER,
    BACKUP_PHONE_NUMBER,
    PRIVATE_SECONDARY_PHONE_NUMBER,
    OTHER_NUMBER,
    ALTERNATE_NUMBER_1,
    ALTERNATE_NUMBER_2,
    ALTERNATE_NUMBER_3,
]

MERM_ID = 'merm_id'
MERM_DAILY_REMINDER_STATUS = 'merm_alarm_enabled'
MERM_DAILY_REMINDER_TIME = "merm_daily_reminder_time"
MERM_REFILL_REMINDER_STATUS = "merm_refill_reminder_status"
MERM_REFILL_REMINDER_DATE = "merm_refill_reminder_date"
MERM_REFILL_REMINDER_TIME = "merm_refill_reminder_time"
MERM_RT_HOURS = "merm_rt_hours"
MERM_PROPERTIES = [
    MERM_ID,
    MERM_DAILY_REMINDER_STATUS,
    MERM_DAILY_REMINDER_TIME,
    MERM_REFILL_REMINDER_STATUS,
    MERM_REFILL_REMINDER_DATE,
    MERM_REFILL_REMINDER_TIME,
    MERM_RT_HOURS,
]

NINETYNINEDOTS_PERSON_PROPERTIES = [
    ENIKSHAY_ID,
    PRIMARY_PHONE_NUMBER,
    BACKUP_PHONE_NUMBER,
    OTHER_NUMBER,
    PERSON_FIRST_NAME,
    PERSON_LAST_NAME,
    CURRENT_ADDRESS,
    ENROLLED_IN_PRIVATE,
    'owner_id',
]
NINETYNINEDOTS_EPISODE_PROPERTIES = [
    TREATMENT_SUPPORTER_FIRST_NAME,
    TREATMENT_SUPPORTER_LAST_NAME,
    TREATMENT_SUPPORTER_PHONE,
    TREATMENT_OUTCOME,
    TREATMENT_OUTCOME_DATE,
    TREATMENT_START_DATE,
    WEIGHT_BAND,
    OTHER_NUMBER,
] + MERM_PROPERTIES
