XXXXXX
XXXXXX
XXXXXXXXX
BB BBBBBBB
  XXXXXXXXXXXXXXXX
  XXXXXXX
    XXXXXXX
    BBB BBBB BBBBB BB BBBBBBBBBBBBB
      XXXX
        XXXXXXXXX
        XXXXXXXXX
      XXXXX
    BBBBBB
    XXXXXXXX
  XXXXXXXX
BBBBB

XXXXXXXXXX XXXX
XXXXXXX BB BBBXX XXXXXXXXXXXXBBBBXXXXXXXBBBBBXXXX
XXXXXXXX BB BBBBBBBBBBBBXXXXXXXBBBBBXXXX

BBB BBBB BB BBBBBBB
  BB BBBBBBBBBBBBBBBB BB B
    XXXXXXXXX
  BBBB BBBBBBBBBBBBBBB BB BBBB
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
  BBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  BBBBB
BBBBBB

XXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXX
BB BBB
  XXXXXXX
    XXXXXXX
    BBB BBBB BBBBB BB BBB
      XXXX
        XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
      XXXXX
    BBBBBB
    XXXXXXXX
  XXXXXXXX
BBBB
  XXXXXXX XXXXXX
BBBBB

XXXXXXXXXXXXX
BB BBBB
  XXXXXXX
    XXXXXXX
    BBB BBBB BBBBB BB BBBBBBBBBB
      XXXX
        XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
      XXXXX
    BBBBBB
    XXXXXXXX
  XXXXXXXX
BBBB
  XXXXXXX XXXXXX
BBBBB

XXXXXXXXXXXXXXXX
XXXXXXXXXXX

XXXXXXX
XXXXXXX
