XXXXXXXXXX XXXX XXX XXXXXXXXX XXXXXXX
  XX XXXXX XXXXXX XXXXXXXXX XXX XXXXX XXXXXXXX XX XXX  XXXXXXXXXXXXXXXX

XXXXXXX
  XXXXXXX
    XXXX
      XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX XXXXXXXXXXXXXX
      XXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX
    BBB BBBBBBBBBBB BB BBBBBBBBBBBB
      XXXX
        XXXXXXXXX
        BB BBBBBBBBBB BB BBBBBBBBBBB
          XXXXXXXFFFFFFFFFFFFFFFFFFXXXX X XXXXXXXXXXXX
        BBBB BBBBBBBBBBBB BB BBBBBBBBBBB
          XXXXXXXXX
        BBBBB
        BB BBBBBBBBBBBBBB BB BBBBBBBBBBB
          XXXXXXXFFFFFFFFFFFFFFFFFFXXXX X XXXXXXXXXXXX
        BBBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBB
          XXXXXXXXX
        BBBBB
        BB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
          XXXXXXXFFFFFFFFFFFFFFFFFFXXXX X
            XXXXXXXXXXXX
        BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
          XXXXXXXXX
        BBBBB
      XXXXX
    BBBBBB
    XXXXXXXX
XXXXXXXX

XXXXXX XXXXXXXXXXXXXXXX
    XX X
      XXXXXXXXXXXXXX XXXXX
    X
XXXXXXXX
