XXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXX XXXXXXX XX XXXXXXXX XX XXX XXXX XXXXXXXXXX

XXX
  BB BBBBB
    XXX XXXX XXXXX XXXXXXX XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
  BBBB
    XXX XXXX XXXX XX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXX XXX XXXXX XXXXX XXXXXXXX XX XXXXXX
  BBBBB
XXXX

XXXXX XXX XXX XXX XXXXXXX XXXX XXXXXX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFXXXXXXFFFFFFFFFXX
  XXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXX
XXXX
