# See https://github.com/dimagi/label-bot
disabled_actions:
  - triage
  - review
  - lgtm

# Label rules
brace_expansion: true
minus_negate: false

rules:
  - labels: ['reindex/migration']
    patterns: ['migrations.lock|**/migrations/**|corehq/pillows/mappings/**|**/_design/**|corehq/couchapps/**']

  - labels: [ 'Core Compatibility' ]
    patterns: ['corehq/apps/app_manager/suite_xml/xml_models.py']

  - labels: ['dependencies']
    patterns: ['requirements/**|package.json|yarn.lock']

  - labels: ['Risk: High']
    patterns:
      - 'corehq/apps/registration/*.py'
      - 'corehq/apps/registration/*.js'
      - 'corehq/apps/api/**'
      - 'corehq/apps/case_importer/views.py'   # bulk case importer API
      - 'corehq/form_processor/**'
      - 'corehq/pillows/mappings/**'
      - 'corehq/apps/hqwebapp/templates/hqwebapp/includes/core_libraries.html'
      - 'corehq/apps/hqwebapp/static/hqwebapp/js/bootstrap3/requirejs_config.js'
      - 'corehq/apps/domain/decorators.py'

  - labels: ['Risk: Medium']
    patterns:
      - 'corehq/apps/cloudcare/**'
      - 'corehq/apps/user_importer/**'
      - 'corehq/apps/fixtures/**'
      - 'corehq/apps/custom_data_fields/**'
      - 'corehq/apps/hqwebapp/templates/hqwebapp/base.html'
      - 'corehq/apps/hqwebapp/static/hqwebapp/js/components/*.js'

# WIP
wip:
  - 'Open for review: do not merge'
  - 'awaiting QA'

# Label management
delete_labels: false

colors:
  navy: '#0366d6'
  dark_orange: '#eb6420'
  light_orange: '#fbca04'
  royal: '#5319e7'
  purple: '#9800c6'
  lime: '#75ff68'
  dark_green: '#0e8a16'
  dark_purple: '#71239b'
  sand: '#d38737'
  grey: '#cfd2d6'
  burnt_orange: '#bc4b29'
  green: '#009800'
  tan: '#fef2c0'
  yellow: '#fcfa4e'
  light_yellow: '#fffeb3'

labels:
- name: 'reindex/migration'
  color: dark_orange
  description: 'Reindex or migration will be required during or before deploy'
- name: 'dependencies'
  color: navy
  description: 'Pull requests that update a dependency file'
- name: 'dependencies/javascript'
  color: navy
  description: 'Change in javascript dependency.'
- name: 'awaiting QA'
  color: light_orange
  description: 'QA in progress. Do not merge'
- name: 'Open for review: do not merge'
  color: royal
  description: 'A work in progress'
- name: 'product/ab-test'
  color: purple
  description: 'AB test for product on production devices'
- name: 'QA Passed'
  color: green
  description: ''
- name: 'QA post deploy'
  color: tan
  description: 'Change should be re-tested once live'
# labels below are part of the product triage system
- name: 'product/admin'
  color: lime
  description: 'Change affects admin pages only visible to super users / staff'
- name: 'product/all-users-all-environments'
  color: dark_green
  description: 'Change impacts all users on all environments'
- name: 'product/custom'
  color: dark_purple
  description: 'Change will only impact users on a single project'
- name: 'product/feature-flag'
  color: sand
  description: 'Change will only affect users who have a specific feature flag enabled'
- name: 'product/invisible'
  color: grey
  description: 'Change has no end-user visible impact'
- name: 'product/prod-india-all-users'
  color: burnt_orange
  description: 'Change will only be deployed to Dimagi "SaaS" environments'
- name: 'Risk: High'
  color: yellow
  description: 'Change affects files that have been flagged as high risk.'
- name: 'Risk: Medium'
  color: light_yellow
  description: 'Change affects files that have been flagged as medium risk.'
