BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
    XXXXXXX gettext(u'Case property') 
      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XX
    XXXXXXXX
    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
      XXXXXXXX gettext(u'Case type') XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
              XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXX
      XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add case property') 
      XXXXXXXXX
    XXXXXX
  XXXXXX

XXXXXX
