 #
 #
 #
 #


XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    BBB BBBBBBB BBBBBBBBBB BB BBBBBBBBBBBBBB
    XXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXX
        XXXX
          XXXXXXXXXX XXXXXXXXX
          XXXXX XXXXXXXXXX
          XXXXXXXXXXXXXX
          XXXXXXXXXXXXXX
        XXXXX
      XXXXXXXX
      XXXXXXX
        BBB BBBBBBBBB BB BBBBBBBBBB
        XXXX
          XXXXXXXXX
          XXXX
            X
            XXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
          XXXXX
          XXXXXXXXX
          XXXXXXXXX
        XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXXXX
    BBBBBB
  XXXXXX
XXXXXX
