# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0003_auto_20190215_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggawc',
            name='eligible_couples_using_fp_method',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggawc',
            name='high_risk_pregnancies',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggawc',
            name='institutional_deliveries',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggawc',
            name='registered_children',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggawc',
            name='registered_eligible_couples',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggawc',
            name='registered_pregnancies',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggawc',
            name='total_deliveries',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggvillage',
            name='eligible_couples_using_fp_method',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggvillage',
            name='high_risk_pregnancies',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggvillage',
            name='institutional_deliveries',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggvillage',
            name='phc_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aggvillage',
            name='registered_children',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggvillage',
            name='registered_eligible_couples',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggvillage',
            name='registered_pregnancies',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggvillage',
            name='sc_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aggvillage',
            name='taluka_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aggvillage',
            name='total_deliveries',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aggvillage',
            name='village_id',
            field=models.TextField(),
        ),
    ]
