# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0004_auto_20190222_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
