BBBB BBBB

XXXX
  XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXX XXXXX
  XXXXXXXXXXXXX
  XXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX
X
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'\n              Are you sure you want to delete %(item)s?\n            ') 
              SSS SSS SSSS SSS SSSS SS SSSSSS SSSSSSSSS
            
        XXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
         gettext(u'\n          <p>\n            Deleting this field can cause you to lose data for any %(entity_string)s with information stored in this field.\n          </p>\n          <p>\n            Data will show up on the edit %(entity_string)s page but\n            will be removed the next time the %(entity_string)s is saved.\n          </p>\n        ') 
          SSS
            SSSSSSSS SSSS SSSSS SSS SSSSS SSS SS SSSS SSSS SSS SSS SSSSSSSSSSSSSSSSS SSSS SSSSSSSSSSS SSSSSS SS SSSS SSSSSS
          SSSS
          SSS
            SSSS SSSS SSSS SS SS SSS SSSS SSSSSSSSSSSSSSSSS SSSS SSS
            SSSS SS SSSSSSS SSS SSSS SSSS SSS SSSSSSSSSSSSSSSSS SS SSSSSS
          SSSS
        
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Cancel') XXXX
        XXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXX
           gettext(u'Delete') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
