BBBB BBBB

XXX
  XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXX
     gettext(u'Add a Profile') 
  XXXXXXXXX
XXXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXX XXXXXXXXXXXXXXXXX
           gettext(u'Name') 
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
           gettext(u'Fields') 
        XXXXX
        XXX XXXXXXXXXXXXXXXXX gettext(u'Delete') XXXXX
        XXXX XX XXX XXXXXXXXXXXXXXXXXXX XXX
        XXXX
          
        XXXXX
        XXXX XXX XXX
      XXXXX
    XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXX
        XXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX
          XX XXXXXXXXXXXXX
             XXXXXXXXXX XXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX X XXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XX
          X
            XX XXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Delete') 
          XXXX
        XXXXX
        XXXX XX XXX XXXXXXXXXXXXXXXXXXX XXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXX
        XXXXX
        XXXX XXX XXX
      XXXXX
    XXXXXXXX
  XXXXXXXX
XXXXXX
