# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none
ENABLE_LINTERS:
  - PYTHON_FLAKE8
  - JAVASCRIPT_ES
PYTHON_FLAKE8_CONFIG_FILE: .flake8
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
LINTER_RULES_PATH: .
VALIDATE_ALL_CODEBASE: false
