# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none
ENABLE_LINTERS:
  - PYTHON_FLAKE8
  - JAVASCRIPT_ES
LINTER_RULES_PATH: .
