files:
  ignore:
    - '*/migrations/*'
    - '*/south_migrations/*'
    - '*.min.js'
    - localsettings.py

linters:
  flake8:
    max-line-length: 115
    ignore: E128,E265,F403,W503  # http://pep8.readthedocs.org/en/latest/intro.html#error-codes
  eslint:
    config: ./.eslintrc.js
