files:
  ignore:
    - '*.min.js'
    - '**/_design/**/*.js'
    - '*.xml'

linters:
  flake8:
    python: 3
    config: .flake8
  eslint:
    config: ./.eslintrc.js
#  pytype:  # failing due to timeout
#    config: ./.pytype.cfg
