files:
  ignore:
    - '*.min.js'

linters:
  flake8:
    python: 3
    max-line-length: 115
    ignore: E128,E265,F403,W503,W1618  # http://pep8.readthedocs.org/en/latest/intro.html#error-codes
  eslint:
    config: ./.eslintrc.js
    install_plugins: true
