# Based on Dockerfile. Use diff to compare them.
FROM python:3.6-jessie
MAINTAINER Dimagi <devops@dimagi.com>

ENV PYTHONUNBUFFERED=1 \
    PYTHONUSERBASE=/vendor \
    PATH=/vendor/bin:$PATH \
    NODE_VERSION=5.12.0

RUN mkdir /vendor

RUN ls

COPY . /vendor/

RUN ls

RUN ls /vendor/

RUN ls /vendor/requirements/


