DOMAIN = 'onse-iss'
CASE_TYPE = 'facility_supervision'
CONNECTION_SETTINGS_NAME = 'DHIS2 Facilities Import Server'
MAPPINGS_FILE = 'custom/onse/case_property_map.csv'
LAST_IMPORTED_PROPERTY = 'dhis2_last_imported'
