XXXX XXXXXXXXXXXXXXXXX X FFFFX
    XXXXXX XXXXXXXXXXXXXXXXXXXX  BB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXBBBBBXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
        XXXXXXXX
        BB BBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX
                XXXXXXXXXXXXXXX
            XXXXXXXX
        BBBBB
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBXXXX XXXXXXXXXXXXBBBBB
            
        BB BBBBBBBBBBBBBBXXXXXXBBBBB
        BBB BBBBB BB BBBBBBBBBB
            XXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX
            XXXXXXX
        BBBBBB
    XXXXXX
XXXXXX
