BBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX
  XXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      
    XXXXXXX
  XXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBB BBBBBB BB BBBBBBBBBBBBBBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
               XXXXXXXXXXXXXXXXXBBBBB
               XXXXXXX
               XXXXXXXXX
               XXXXXXXFFFFFFFFFFX BB BBBBBBBBBB FFFFBBBBB XX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          FFFFFFFFFF
        XXXXXXXX
      XXXXX
    BBBBBB
    XXXXX

    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
XXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXX
