BBBB BBBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBB
	
BBBB
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XX
            
        XXXXXXXX
        XXXX XXXXXXXXXXXXXXX XX
            XXXXXX XXXXXXXXXXXXX
                   XXXXXXX
                   XXXXX
                   XXXXXXXFFFFFFFFFFFFFFFFFFX XX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                
            XXXXXX
        XXXXXX
    XXXXXX
BBBBB
