BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB

BBBBB BBBBBXXX XXXXX XXXXX X XXBBBBBBBB

BBBBB BBBBBBBBBBB
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
BBBBBBBB BBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXX XXXXXXXXXXXX
    XXXX
      XX XXXXXXBBB BBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBXX
        
      XXXX
      XXXXXXXXXXXXXXX
    XXXXX

    XXXX XXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX

  XXXXXX
BBBBBBBB BBBBBBB
