BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBB
  XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Domain name') XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Check') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXX

  XXXXXX XXXXXXXXXXXXXX
    XXXX
      XXXX gettext(u'Domain Name') XXXXX
      XXXX gettext(u'Forms') XXXXX
      XXXX gettext(u'Cases') XXXXX
      XXXX gettext(u'Case actions') XXXXX
    XXXXX
    BBB BBBBBB BB BBBB
      XXXX
        XXXXXXXXX
        BB BBBBBBBBBBBB
          XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        BBBB
          BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXX
                  XXX  XX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXX
                  XXXX  XX
                XXXXXX
              XXXXXX
            XXXXX
          BBBBBB
        BBBBB
      XXXXX
    BBBBBB
  XXXXXXXX
BBBBBBBB
