BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBB
  XXXXBBBBB BBBBB gettext(u'Temporarily Disable Two-factor Authentication') BBBBBBBBXXXXX
  XXX gettext(u'You are about to temporarily disable two-factor authentication for %(username)s. This\n    compromises their account security, are you sure?') SSS SSS SSSSS SS SSSSSSSSSSS SSSSSSS SSSSSSSSSS SSSSSSSSSSSSSS SSS SSSSSSSSSSSSS SSSS
    SSSSSSSSSSS SSSSS SSSSSSS SSSSSSSSS SSS SSS SSSSSXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXX XXXXXXXXXX XXXX XX XX XXXXXXXXX XX XXXXXX XXXX XXX XXXXXXX XXX XXXX XX XXX XXXXX XX XXX XXXXXXX XXXX XXX XXXXX XX XXXXXXX XXXXXXXXXX
    XXXXXXXXX XXXXXX XXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX XXXXXXXXXXXXX
  XXXXXX
  BBBBBB BBBB
BBBBBBBB
