BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBB
  XXXXBBBBB BBBBBFFFFF  gettext(u'User Account') BBBBBBBBXXXXX
  XXX gettext(u'You are about to %(verb)s the user account for "%(username)s".') SSS SSS SSSSS SS SSSSSSSS SSS SSSS SSSSSSS SSS SSSSSSSSSSSSSSSXXXX
  XXXXXXX XXXX XXXXXXX XXXX XXXX XXXXX XXXXXXXX XX XX XXX XXX XXXX XX XXXXXXXX XXXXXXXXXXXXXXXX
  BBBBBB BBBB
BBBBBBBB
