BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB

BBBBB BBBBBXXX  BBBBBBBB

BBBBB BBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX X XXX XXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
        XXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XX
        XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXX
      XXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXX XXXXXX  XXXX XXXX XX XXXXXXXXX XXX XXXXXXXXX XXXXXXXXX XX XXXXXXXXXXXXX XXX XXXXXXXXXX
        XXX XXX XXXX XXX XXXXX XXXX
        XX XXXXXXBBB BBBBBBBBBXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
    BB BBBBBB
      XXXXXXX  XXXXX
      XXXXXX XXXXX 
        XXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXX XX XXXXXXXX XXXXXXX
      XXXX
      BBB BBBBBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXXX XX XXXXXX XXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXX
            XXXXXFFFFFFFFFFFF FFFFFFXXXXXX
          XXXXXX
        XXXXXX
      BBBBBB
      BB BBB BBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXX XXXXXXXXX
          XXXXXFFFFFFFFFFFF FFFFFFXXXXXX
        XXXXXX
      BBBBB
    BBBBB
  XXXXXX
BBBBBBBB BBBBBBB
