BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB BBBBBBBBBBBB BBB BBBBBBBBB BBBBBBBBBBBBBBBBBB X BBBBB BBBBBBBBBX XXXXX XXXXXXXBBBBBBBB

BBBBB BB
  BB BBB BBBBBBBBBBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBB
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBB
    BB BBBBBBBBBBBBBBBBBBBBB
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBB
  XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXX gettext(u'Admin Reports') XXXXXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXBB BBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX
  XXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBB
  BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBB XXXXBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Export to Excel') 
        XXXX
      BBBBB

      BB BBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBB XXXXBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Email report') 
        XXXX
      BBBBB

      BB BBBBBBBBBBBBBBBBBBB
        XX XXXXXXXX XXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBB XXXXBBBBBX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Print') 
        XXXX
      BBBBB
    XXXXXX
  BBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBB
  BB BBB BBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBB
  XXXX XXXXXXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBBBBBBBBBBBBB
  XXXXXX
BBBBBBBB
