BBBB BBBBBBBBBBBBBB
BBBB BBBB


XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  BB BBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
BB BBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX
          XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXFFFFFFFFFFFFXX
              XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX
BBBBB
