BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBB
  XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXX
       gettext(u'Enter a month to download all MALT data as csv for that month') 
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Year Month') XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Download as CSV') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXX
BBBBBBBB
