BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBXXXX XXXXX XXXXXBBBBBBBB
BBBBB BBBBBBBBB 
  XXXXXXXX
    XXXXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXX
        X
      XXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXX
    XXX
  XXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBBBBB
  XXXXXXXX
  BB BBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  BBBBB
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXX
      XXXX XX XXX XXXXX XXXXXXX XXXX XXXXX XXXXXX XXXXXXXX XXXXXXX
      XXXX XXXXX XXX
    XXXX
    XXXX
    XXXXX XXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XX XXXX X XXXX
    XXXXX XXXX XX XXXXXXXXX XXXX XX XXXXXX XXX XXXXXXXXX XXXX
    XXXX XXXXXXXXXX XX XXXXXXX XXXXXX XXXXXXX X XXXX XXXXXXXX
    XXXX
  XXXXXX
  XXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
    BBBBBBBBBB
    XXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXX XXX XXX XXX XXXX XXXXXXBBBBBBBBXX XXXXXXXXXX XXBBBBBBBBBBBXXXXXXX XX XXXXXXXXXX XXX XXXXXX XXXXX XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXX
        XXXXXXXX
        XXXXXX
          XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXX
        XXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXX XXXXX
        XXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
          XXXXX XXX XXX XXXXXX
        XXXXXXXX
      XXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXX
  XXXXXXX

  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXX XX XXXXX XXX XX XXX XXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXX
            XX XXXXXXXX XXXX XXX XXX XXX XXXXXX XXX XXXX XX XXXXX XXX
            XXX XXXXXX XXXX XXXXX XXXXX XXXXXXXX XXX XXXX XXX XXX XX
            XXXXX XXX XXXXXX XXXXXXX
          XXXX
          XXX
            XXXXXXX XXXX XXX XXXXXXXXX XXXX XXXX XX XXXXX XX XXXX XXXX
            XX XX XXXXXX XXXXXXXXXXX XXX XXXX X XXXX XXXXXXX XXXX XXXX
            XXXXX XX XXXX XXXX XXX XXXXXXXXXX XX XXXX XXXXX XX XX XXX
            XXXXXXXXX
          XXXX

          XXXX XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX XX XXXXX XXXXXXX XXX XXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXX XX XXXXX XXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
