BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB

BBBBB BBBBBXXX  XXBBBBBBBB

BBBBB BB
  BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBBBBB


BBBBB BBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX X XXX XXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
        XXXXXXXXX
        XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXXX
          XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXX
            XXXX
              XXXXXXXXXXXXXXX
              XXXXXXXXXXXX XXXXXXXXX
            XXXXX
            BBB BB BB BBBBBBBBBB
              XXXX
                XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBB BB BBBBBBB
                  XXXXXX XXXXXXBBB BBBBBBBBBXXXXXXXXXXXXXXX
                    
                  XXXXXXXXX
                BBBB
                  XXXXXXXXX
                BBBBB
              XXXXX
            BBBBBB
          XXXXXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXX
        BB BBBBBB
          XXXXXXX XXXXX
          XXXXXX XXXXX XXXX
          XXXXXXXXXXX XX XXXXXX XXXX
          XXXXXXXXXX XXXX
          XXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
                 XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                 XXXXXXXXXXX XX XXX XX
            XXXX
            XX XXXXXXBBB BBBBBBBBBBBXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXX
          BB BBBBBB
          XXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBB
                  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XX XXXXXXXXXXXXXX
                    
                  XXXXXX
                BBBBBB
            XXXXXX
          XXXXXX
          BBBBB
          XXXXX
            XXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXBBBBBBBBB BBBXXXXXXXX
          XXXXXX
          BB BBBBBBBB
          XXXXX
            XXXXXXXXXXXXXX XXX XXXXXXXXXX
            XXXXXXXXXXX
          XXXXXX
          BBBBB
        BBBB
          XXXXXX XXXXXXXXX
        BBBBB
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB BBBBBBB
