BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBB
  XXX gettext(u"See a user's projects by entering their email address below.") XXXX
  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
    XXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXX
  BB BBBBBBBB
    XXXX
    XXXX gettext(u"%(user_name)s's Information") SSSSSSSSSSSSSSS SSSSSSSSSSSXXXXX
    BB BBB BBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'This account is disabled.') XXXXXX
    BBBBB
    XXXX
      XXXXXXXX gettext(u'ID') XXXXX
        
        XXXXXXXXX XXXXXXBBB BBBBBBBBBXXXXXX gettext(u'couch doc') XXXXXXXXXXXX X
        XXXXXXXXX XXXXXXBBB BBBBBBBBBBBXXXXXX gettext(u'elasticsearch lookup') XXXXXXXXXXXX
      XXXXXX
      XXXXXXXX gettext(u'Is Superuser') XXXXX XXXXXX
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXFFFFFFFFFXXXXXX XXXX XXXXX XXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXXXXXXXXFFFFFFFFFXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXXX BB BBB BBBBBBBBBBBBBBXXXXXXXXBBBBBX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBXXXFFFFFFFFFXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX gettext(u'Domains') XXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX
          XXX XXXXXXXXXXXXXXXXX gettext(u'Domain') XXXXX
          XXX XXXXXXXXXXXXXXXXX gettext(u'Role') XXXXX
        XXXXX
        BBB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX
            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX
            XXXXFFFFFFFFFFFFFFFFFXXXXX
          XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXX
  BBBBB
BBBBBBBB
