BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBB
XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXXX
    X
    XXXXXXXXXXX XX X
      XXXXXXXXXXXX XXXXX
    X



XXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
 gettext(u'Editing CommCare Builds') 
BBBBBBBB

BBBBB BBBBBBBBBBBB
BBBBBBBBBBBBBBBBB BBBBB BBB
BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Editing')  XXXXXXXXXXXXXXX


XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Menu Options') XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXX
        XXXX
          XXXXXXXXX
          XXXX gettext(u'Version') XXXXX
          XXXX gettext(u'Label') XXXXX
          XXXX gettext(u'Superuser Only') XXXXX
          XXXXXXXXX
        XXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXX
          XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXX
                                XX
            XXXXXXXXX
          XXXXX
          XXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
          XXXXX
          XXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXX
          XXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXX
          XXXXX
        XXXXX
        XXXXXXXX
        XXXX
          XXX XXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXX
               gettext(u'Add a Version') 
            XXXXXXXXX
          XXXXX
        XXXXX
      XXXXXXXX

      XXXXX

      XXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Default 1.x Build') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                XXXXXXXX XXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Default 2.x Build') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                    XXXXXXXX XXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXXXXXXX
    XXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB
    XXXXXXX
  XXXXXX
XXXXXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXX
       gettext(u'Import a new build from the build server') 
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Version') 
        XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX
            XXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                 gettext(u'Browse versions') 
              XXXX
            XXXXX
            XXXX gettext(u'Paste the latest version in the box above in the format x.y.z') XXXXX
            XXXX gettext(u'Click Import Build') XXXXX
            XXXX
               gettext(u'\n              You can also automatically fetch the latest build from GitHub using the following management command:\n              <b>./manage.py add_commcare_build --latest </b>\n              ') 
              SSS SSS SSSS SSSSSSSSSSSSS SSSSS SSS SSSSSS SSSSS SSSS SSSSSS SSSSS SSS SSSSSSSSS SSSSSSSSSS SSSSSSSS
              SSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSS SSSSSSSS SSSS
              
            XXXXX
          XXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Import Build') XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXXX
  XXXXXX
XXXXXX

BBBBBBBB
