BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBB
  BBBBBBBB BBB
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
  BBBBBBBBBBB
BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBB
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX
         gettext(u'\n          Welcome Back to %(cc_name)s\n        ') 
          SSSSSSS SSSS SS SSSSSSSSSSS
        
      XXXXX
    XXXXXX
    BB BBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXX
                               XXXXXXXX XXXX
                               XXXXX XXXXXX
                               XXXXX XXXXXX XXXXX
                               XXXXXXXX X
                                    XXXXXX XXXXXX
                                    XXXXXXXX XXXXXXXXX
                                    XXXXXXXXXX XXXXXXXXX
                                    XXXXXXXX XXXXXXXX
                               XX
                           XXXXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX

              XXXX XXXX XX X XXXXXXXXX XXXXXX XXXXXXXXX XXXXX XXXX XXXX XXX
              XX XXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX

              XXXX XXXXXXX XXX
              XX XXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

              XXXX XXXX XX XXXXXX XXXX XXXXXXXXXX XX XXXXX XXX XXXXXXXX XXXXX XXX
              XXXX XX XXX XXXXXXXXXXXXX XXX
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXX X
                                            XXXXXX XXXXXXXXXXX X XXXXXXXXX X XXX
                                            XXXXXXXX XXXXXXXXXXXX
                                            XXXXXXXXXX XXXXXXXX
                                            XXXXXXXX XXXXXXXX
                                         XX
                       XXXXXXXXX
                    XX XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXX XXXXXXXXXX
                  XXXXXX
                XXXXXX

                XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X XXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXX XXXXXXXXX
                                    XXXXXXXX XXXXXXXXXXXXX
                                    XXXXXXXXXXXXXX XX
                                    XXXXXXXXXXX XXXXXXXXXXX
                                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXX XXX

              XXXX XX XXXXX XX XXXX XX XXXXXXX XX XXXXXX XXXX XXXX XX XXXX XXXX XXXXX XXX
              XXXX XX XXX XXXXXXXXXXXX XXX
              XX XXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXX
                                   XXXXX XXXXXX XXXXX
                                   XXXXXXXX X
                                       XXXXXX XXXXXX
                                       XXXXXXXX XXXXXXXXX
                                       XXXXXXXXXX XXXXXX
                                       XXXXXXXX XXXXXXXX
                                   XX
                               XX
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
              XXXX
              XXXX XXX XXX

            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
        BB BBBBBBBBBBBBBBB
           gettext(u'\n            Thanks for using %(cc_name)s!\n          ') 
            SSSSSS SSS SSSSS SSSSSSSSSSSS
          
        BBBB
           gettext(u'\n            Thanks for using CommCare HQ! If you have questions, suggestions,\n            or other thoughts, <br />we invite you to join the discussion on the\n            <a href="https://forum.dimagi.com/"\n               target="_blank">CommCare User Forums</a>.\n          ') 
            SSSSSS SSS SSSSS SSSSSSSS SSS SS SSS SSSS SSSSSSSSSS SSSSSSSSSSSS
            SS SSSSS SSSSSSSSS SSS SSSS SSSSSS SSS SS SSSS SSS SSSSSSSSSS SS SSS
            SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
               SSSSSSSSSSSSSSSSSSSSSSSS SSSS SSSSSSSSSSS
          
        BBBBB
      XXXX
    XXXXXX
  XXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBB
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXX
         XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXFFFFFFFFFFFFFFX
         XXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  BBBBB
  BB BBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXX
         XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXFFFFFFFFFFFFFFX
         XXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XX XXXXXXXXXXXXX
         gettext(u'Check out the new Dashboard for Messaging!') 
      XXXX
    XXXXXX
  BBBBB
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXX
         XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXFFFFFFFFFFFFFFX
         XXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XX XXXXXXXXXXXXX
         gettext(u'Have you ever needed to find a form or a case by its ID? Check out the new "Find Data by ID" page!') 
      XXXX
    XXXXXX
  BBBBB
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXX
         XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXFFFFFFFFFFFFFFX
         XXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XX XXXXXXXXXXXXX
         gettext(u'\n          We have improved our Web User Roles and Permissions to give you more control on your project space. Check it out!\n        ') 
          SS SSSS SSSSSSSS SSS SSS SSSS SSSSS SSS SSSSSSSSSSS SS SSSS SSS SSSS SSSSSSS SS SSSS SSSSSSS SSSSSS SSSSS SS SSSS
        
      XXXX
    XXXXXX
  BBBBB
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXX
         XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXFFFFFFFFFFFFFFX
         XXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XX XXXXXXXXXXXXX
         gettext(u'\n          Ever wanted to explore your case data right within CommCare?\n          Check out our new feature!\n        ') 
          SSSS SSSSSS SS SSSSSSS SSSS SSSS SSSS SSSSS SSSSSS SSSSSSSSS
          SSSSS SSS SSS SSS SSSSSSSS
        
      XXXX
    XXXXXX
  BBBBB
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXX
         XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXFFFFFFFFFFFFFFX
         XXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XX XXXXXXXXXXXXX
         gettext(u'\n          Analyze your data in Power BI and Tableau! Easily connect CommCare\n          to both Power BI and Tableau with the new OData feed integration.\n        ') 
          SSSSSSS SSSS SSSS SS SSSSS SS SSS SSSSSSSS SSSSSS SSSSSSS SSSSSSSS
          SS SSSS SSSSS SS SSS SSSSSSS SSSS SSS SSS SSSSS SSSS SSSSSSSSSSSS
        
      XXXX
    XXXXXX
  BBBBB
BBBBBBBB

