COMMTRACK_REPORT_XMLNS = 'http://commcarehq.org/ledger/v1'

SECTION_TYPE_STOCK = 'stock'

REPORT_TYPE_BALANCE = 'balance'
REPORT_TYPE_TRANSFER = 'transfer'
VALID_REPORT_TYPES = (REPORT_TYPE_BALANCE, REPORT_TYPE_TRANSFER)

TRANSACTION_TYPE_STOCKONHAND = 'stockonhand'
TRANSACTION_TYPE_STOCKOUT = 'stockout'
TRANSACTION_TYPE_RECEIPTS = 'receipts'
TRANSACTION_TYPE_CONSUMPTION = 'consumption'
TRANSACTION_TYPE_LA = 'lossoradjustment'

TRANSACTION_SUBTYPE_INFERRED = '_inferred'
