# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-25 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudcare', '0002_sqlapplicationaccess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SQLApplicationAccess',
            new_name='ApplicationAccess',
        ),
    ]
