BBBB BBBB
BBBB BBBBBBBBBBBBBB

XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  BBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BB BBBBBBB
   gettext(u'\n    You are on the CommCare Community Plan.\n    <a href="%(url_sub)s" id="cta-community-sub">Subscribe to a professional plan</a>.\n  ') 
    SSS SSS SS SSS SSSSSSSS SSSSSSSSS SSSSS
    SS SSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS S SSSSSSSSSSSS SSSSSSSSS
  
XXXXXX
