BBBB BBBB
BB BBBBBBBB
  XXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    BBBBB BBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXX
        BBB B BB BBBBBB
          XXXXXXX
        BBBBBB
      XXXXXX
    BBBBBBBB BBBBBBB
  XXXXXX
BBBB
  XXXXXXXX
    BB BBBBBBBBBBBBBB
      
    BBBB
       gettext(u'Importing your data. This may take some time...') 
    BBBBB
  XXXXXXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB
