BBBB BBBB

BBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BB BBBBBBB
 gettext(u'\n  <a href="%(sub_url)s">Click here</a> to upgrade or reach\n  out to us at <a href="mailto:%(SALES_EMAIL)s">%(SALES_EMAIL)s</a>\n  to learn more!\n') 
  SS SSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSS SS SSSSSSS SS SSSSS
  SSS SS SS SS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
  SS SSSSS SSSSS

