BBBB BBBBBBBBBBBBBB


XXXXXXXX
  XX XXXXXXXXXXXX XXXX XXXXXXX XXXXXXX XXX XXXXXXXXXXXX XX XXXXXXXXX XXXXXXX XX XXX XX XXX XXXXXXXXXX XXX
  XX XXXX XXXXX XXX XXXX XXXXXXXXX XXXXX XXXXXXXXX XXXX XXXXXXXXX XXX XXXXXX XXX XXX XXX XXX XXXXXXXXXXX XXXXX
  XXXXXXXXXXXXXXXXXXXX X FFFFX
  XXXXXXXXXXXXXXXXXXXXX X FFFFX
XXXXXXXXX

BB BBBBBBBBBBBBBB
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  
  BB BBBBBBBBBBBBBB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBB
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXXX
    XXXXXXXXXXXXXXXXXX
      XXXXX X
          XXXXXXXXXXX
          XXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXBBBBBX
      XX
      XXXXXXXXX XXXXXXXX XXXX XXXXXXXBB BBBBBBBBBBBBBBX XXXXXXXXXXBBBBBX X
        XXXXXXXXXX X XXXXXXXX
        BB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXX X XXXXXXXXXXXBBBBB
      X
    XXX
    XXXXXXXXXXX
        BB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBX
    XX XXXXXXXXXX X
      BB BBBBBBBBB
        
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
          XXXXXXXXXXX
            BB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBX
          XX XXXXXXXX XX X
      BBBBB
            XXXXXXXXXXXXXXX XXXXXXXX XX X
              XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXX XXX
            XXX
      BB BBBBBBBBB
          XXX
        XXX
      BBBBB
    XXX
  XXXXXXXXX
BBBBB
