BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBBB
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBB
      XXXXXXXXX
    BBBBB
    XXX gettext(u'Your download is ready.')  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
BBBBBBBB BBBBBBB
