BBBB BBBB
XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXBB BBBB XXXXBBBBBXX
  XXXXXXXX
     gettext(u'The current date and time is') 
    BB BBBBBBBB BBBB XXXBBBBBX
  XXXXXXXXX
  X gettext(u'All dates are in')  BB BBBBBBBBBBBBXXXBBBBBXX
XXXXXX
