BBBB BBBB
BBBB BBBBBBBBBBBBBB

XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  BBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BB BBBBBBB
  BB BBBBBBBBBBBBBBBBBBBBBBBB
    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBB
       gettext(u'\n        You have <a href="%(url_sub)s" id="cta-trial-days-remaining">%(num_trial_days_remaining)s\n        day%(days_plural)s remaining</a> in\n        your CommCare %(trial_edition)s Edition Trial.\n      ') 
        SSS SSSS SS SSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
        SSSSSSSSSSSSSSSSSS SSSSSSSSSSSSS SS
        SSSS SSSSSSSS SSSSSSSSSSSSSSSSS SSSSSSS SSSSSS
      
    BBBBBBB
  BBBB
     gettext(u'\n        You are on a <a href="%(url_sub)s" id="cta-trial-days-remaining">trial</a> of CommCare %(trial_edition)s Edition.\n    ') 
        SSS SSS SS S SS SSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS SSSSSSSS SSSSSSSSSSSSSSSSS SSSSSSSS
    
  BBBBB
XXXXXX
