BBBB BBBB

BB BBB BBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXX XXXXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
     gettext(u'\n      Case Sharing Groups are not available on your subscription. This feature\n      is only available on our Pro plan or higher.\n    ') 
      SSSS SSSSSSS SSSSSS SSS SSS SSSSSSSSS SS SSSS SSSSSSSSSSSSS SSSS SSSSSSS
      SS SSSS SSSSSSSSS SS SSS SSS SSSS SS SSSSSSS
    
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
BBBBB
