BBBB BBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
       gettext(u'\n        This is a <strong>Case Sharing Group</strong>. You subscription no longer supports\n        Case Sharing Groups. Editing this group will be disabled until you either upgrade to our Pro plan or\n        <a href="#disableCaseSharing"\n           data-toggle="modal">change the group type to <strong>Reporting Group</strong> only</a>.\n      ') 
        SSSS SS S SSSSSSSSSSSS SSSSSSS SSSSSSSSSSSSSSS SSS SSSSSSSSSSSS SS SSSSSS SSSSSSSS
        SSSS SSSSSSS SSSSSSS SSSSSSS SSSS SSSSS SSSS SS SSSSSSSS SSSSS SSS SSSSSS SSSSSSS SS SSS SSS SSSS SS
        SS SSSSSSSSSSSSSSSSSSSSSSSSSS
           SSSSSSSSSSSSSSSSSSSSSSSSSS SSS SSSSS SSSS SS SSSSSSSSSSSSSSSSS SSSSSSSSSSSSSS SSSSSSSSS
      
    XXXX
    XXX
      XXXX XXXXXXX XXXXXX XXX XXXXXXXXX XX XXX XXX XXXX XX XXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX
  XXXXXX
BBBBB
