# flake8: noqa
# Generated by Django 1.11.21 on 2019-07-01 20:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import corehq.apps.userreports.models


class Migration(migrations.Migration):

    dependencies = [
        ('userreports', '0014_auto_20190529_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomparisondiff',
            name='filter_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=corehq.apps.userreports.models.FilterValueEncoder),
        ),
        migrations.AlterField(
            model_name='reportcomparisonexception',
            name='filter_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=corehq.apps.userreports.models.FilterValueEncoder),
        ),
        migrations.AlterField(
            model_name='reportcomparisontiming',
            name='filter_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=corehq.apps.userreports.models.FilterValueEncoder),
        ),
    ]
