# Generated by Django 3.2.16 on 2023-01-19 01:47

from django.conf import settings
from django.db import migrations

import corehq.apps.es.migration_operations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop)
    ]