# Generated by Django 3.2.23 on 2024-05-09 12:54
# This migration exists as a placeholder migration which was merged but rolled back before the deploy.
# If any third party hoster has deployed during that time period,
# it ensures that next migration that we add shows up for them.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0008_add_doc_id_to_all_mappings'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=migrations.RunPython.noop)
    ]
