# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_batch_completed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdim',
            name='sql_parent_location_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='locationdim',
            name='location_level_0',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
