# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 11:46
from __future__ import unicode_literals

import corehq.warehouse.etl
import corehq.warehouse.models.shared
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_get_location_level_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLogFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_log_id', models.CharField(max_length=255)),
                ('sync_date', models.DateTimeField(null=True)),
                ('domain', models.CharField(max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255, null=True)),
                ('build_id', models.CharField(max_length=255, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Batch')),
                ('domain_dim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.DomainDim')),
                ('user_dim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.UserDim')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, corehq.warehouse.models.shared.WarehouseTable, corehq.warehouse.etl.CustomSQLETLMixin),
        ),
    ]
