# Generated by Django 1.11.13 on 2018-06-20 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0029_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclogfact',
            name='user_dim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='warehouse.UserDim'),
        ),
    ]
