from __future__ import unicode_literals
SUPERVISOR_APP_ID = '48cc1709b7f62ffea24cc6634a00660c'
VHND_SURVEY_XMLNS = "http://openrosa.org/formdesigner/A1C9EF1B-8B42-43AB-BA81-9484DB9D8293"

CHILDREN_WEIGHED_REPORT_ID = 'static-icds-cas-static-ls_children_weighed'
DAYS_AWC_OPEN_REPORT_ID = 'static-icds-cas-static-ls_awc_days_open'
HOME_VISIT_REPORT_ID = 'static-icds-cas-static-ls_timely_home_visits'
THR_REPORT_ID = 'static-icds-cas-static-ls_thr_30_days'

AWC_LOCATION_TYPE_CODE = 'awc'
SUPERVISOR_LOCATION_TYPE_CODE = 'supervisor'
BLOCK_LOCATION_TYPE_CODE = 'block'
DISTRICT_LOCATION_TYPE_CODE = 'district'
STATE_TYPE_CODE = 'state'

ANDHRA_PRADESH_SITE_CODE = '28'
MAHARASHTRA_SITE_CODE = ''
MADHYA_PRADESH_SITE_CODE = '23'
BIHAR_SITE_CODE = '10'
CHHATTISGARH_SITE_CODE = '22'
JHARKHAND_SITE_CODE = '20'
RAJASTHAN_SITE_CODE = '08'
UTTAR_PRADESH_SITE_CODE = 'state9'

ENGLISH = 'en'
HINDI = 'hin'
TELUGU = 'tel'
MARATHI = 'mar'

FILE_TYPE_CHOICE_ZIP = 1
FILE_TYPE_CHOICE_DOC = 2
DISPLAY_CHOICE_LIST = 1
DISPLAY_CHOICE_FOOTER = 2
