BBBB BBBB
XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXX XXXXXX XXXXX XXX XXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXXXXXXX

        XXX
          XXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXX XXX XXXXXXXXX XXXXXXX XX XXXXX XXXXX XXXXX XX XXX XXXXXX
          XXXX XX XXXXXXX
          XXXXXXXXX XX XXX XXXXXXX XXX XXXXXXX XXX XXX XXXXXXXX XXX XXX XX XXXX XXXXXXXXXXX XXXXXXXXX XX
          XXXXXXX
          XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXX XXXX
          XX XXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Use the Creative Commons website') XXXX
           gettext(u'to choose a Creative Commons license.') 
        XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BB BBBBB
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
BBBBB
