TRANSITION_COLUMN_NAME = 'transition'
MERGE_TRANSITION = 'Merge'
SPLIT_TRANSITION = 'Split'
MOVE_TRANSITION = 'Rename'
EXTRACT_TRANSITION = 'Extract'
VALID_TRANSITIONS = [MERGE_TRANSITION, SPLIT_TRANSITION, MOVE_TRANSITION, EXTRACT_TRANSITION]
