# Generated by Django 2.2.16 on 2020-10-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_gaenotpserversettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaenotpserversettings',
            name='gaen_server_type',
            field=models.CharField(choices=[('NYNJ', 'New York/New Jersey'), ('CO', 'Colorado')], default='NYNJ', max_length=255),
        ),
    ]
