# Generated by Django 5.2.6 on 2025-12-08 10:02

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0013_kycconfig_phone_number_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycconfig',
            name='passing_threshold',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
