# Generated by Django 5.2.14 on 2026-05-28 20:41

import datetime
from django.db import migrations, models

from corehq.apps.tombstones.models import ModelClassField

SLUG_BY_DJANGO_PATH = {
    'form_processor.CommCareCase': 'case',
    'form_processor.XFormInstance': 'xform',
}


class Migration(migrations.Migration):
    dependencies = [
        ('tombstones', '0002_migrate_deleted_sql_docs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tombstone',
            old_name='deleted_on',
            new_name='soft_deleted_on',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='tombstone',
                    name='hard_deleted_on',
                    field=models.DateTimeField(null=False),
                ),
            ],
            # db_default on a new column updates each row
            # once existing rows are updated, we no longer need the default
            database_operations=[
                migrations.AddField(
                    model_name='tombstone',
                    name='hard_deleted_on',
                    field=models.DateTimeField(
                        null=False,
                        db_default=datetime.datetime(2024, 1, 1, 0, 0),
                    ),
                ),
                migrations.AlterField(
                    model_name='tombstone',
                    name='hard_deleted_on',
                    field=models.DateTimeField(null=False),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='tombstone',
                    name='model',
                    field=ModelClassField(max_length=128),
                ),
            ],
            database_operations=[
                migrations.AddField(
                    model_name='tombstone',
                    name='model',
                    field=ModelClassField(max_length=128, null=True),
                ),
                # Before dropping the object_class_path column, update the new
                # model column with the correct values
                migrations.RunSQL(
                    "UPDATE tombstones_tombstone SET model = 'case' WHERE object_class_path = 'form_processor.CommCareCase'"
                ),
                migrations.RunSQL(
                    "UPDATE tombstones_tombstone SET model = 'xform' WHERE object_class_path = 'form_processor.XFormInstance'"
                ),
                migrations.AlterField(
                    model_name='tombstone',
                    name='model',
                    field=ModelClassField(max_length=128),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='tombstone',
            name='tombstone_unique_id_and_type',
        ),
        migrations.RemoveField(
            model_name='tombstone',
            name='object_class_path',
        ),
        migrations.AddConstraint(
            model_name='tombstone',
            constraint=models.UniqueConstraint(
                fields=('doc_id', 'model'),
                name='tombstone_unique_id_and_model',
            ),
        ),
    ]
