BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBB BBB
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XX
BBBBBBBBBBB
