BBBB BBBB
XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  BB BBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Change Project') XXXXX
    BBB B BB BBBBBBBBBBBB
      XXXXXX XXXXXXXXXXXXXXXXX
    BBBBBB
  BBBBB

  BB BBBBBBBBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXX XX
    XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
        XX XXXXXXXXX XXXXXXXXXXXXXX
         gettext(u'All Projects') 
      XXXX
    XXXXX
  BBBBB

  BB BBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXX XX
    XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX
        XX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Add Project') 
      XXXX
    XXXXX
  BBBBB
XXXXX
