BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    BBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        
        XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Go back') XXXX
    XXXXXX
BBBBBBBB
