BBBB BBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBBBBB
XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXX
           XXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBXX
            XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Manage Settings') XXXXXXX
        XXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Logged in As') XXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXX
                        BB BBBBBBBBBBBBBBB
                             
                            XXX XX
                        BBBB
                            
                        BBBBB
                    XXXX
                    BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
                        BB BBBB
                        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                            
                        XXXXXX
                        BBBBB
                    BBBBBBB
                XXXXXX
            XXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBB BBB BBBBBB BB BBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Manage Enterprise') XXXXX
                XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
                        XX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Enterprise Console') 
                    XXXX
                XXXXX
                BBBBB
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Manage Project') XXXXX
            XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
                    XX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Project Settings') 
                XXXX
            XXXXX
            BB BBB BBBBBBBBBBBBBBB
            XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Current Subscription') 
                XXXX
            XXXXX
            BBBBB
            BB BBBBBBBBBBBBBBBBB
            XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Feature Flags and Privileges') 
                XXXX
            XXXXX
            BBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Support Options') XXXXX
            XXXX
                XX XXXXXXBBB BBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'View Domain Doc') 
                XXXX
            XXXXX
            BBBBB
            BBBBB
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Manage Account') XXXXX
            XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
                    XX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'My Account Settings') 
                XXXX
            XXXXX
            XXXX
                XX XXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXX
                    XX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
                     gettext(u'Sign Out') 
                XXXX
            XXXXX
        XXXXX
    XXXXX
    BB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBB BB BBB BBBBBBBBBBBBBBB
        
        
        XXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX
           XXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBB BBB BBBBBBBBBBXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Help &amp; Resources') XXXXXXX
        XXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            BB BBB BBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                     gettext(u'\n                        %(cc_name)s Help\n                    ') 
                        SSSSSSSSSSS SSSS
                    
                XXXXX
                XXXX
                    XX XXXXXX gettext(u'https://wiki.commcarehq.org/display/commcarepublic/Home') X XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXX XXXX XXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Visit the Help Site') 
                    XXXX
                XXXXX
                XXXX
                    XX XXXXXX gettext(u'https://forum.dimagi.com/') X XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXX
                        XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'User Forum') 
                    XXXX
                XXXXX
            BBBBB
            BB BBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBB
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Report an Issue') 
                    XXXX
                XXXXX
            BBBBB
            BB BBB BBBBBBBBBBBBBBB
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Status Page') 
                    XXXX
                XXXXX
              BBBBB
        XXXXX
        XXXXX
    BBBBB
    BB BBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Project') XXXXXXXX
            BB BBBBBB
                BB BBBBBB BB BBBBBBBB
                     gettext(u'CommCare HQ Demo Project') 
                BBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                         gettext(u'\n                            Snapshot of %(snap_name)s\n                        ') 
                            SSSSSSSS SS SSSSSSSSSSSSS
                        
                    BBBB
                        
                    BBBBB
                BBBBB
            BBBB
                 gettext(u'Select Project...') 
            BBBBB
            XX XXXXXXXXXXXXXXXXXX
        XXXX
        BB BBBBBB
            BBBBBBBBBBBBBBBB BBBBBBB BBBBBB
        BBBB
            BBBBBBBBBBBBBBBB BBBBBBB
        BBBBB
    XXXXX
    BBBBB
    BB BBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBXX
            
        XXXX
    XXXXX
    BBBBB
XXXXX
BBBBB
