BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Remove Form Action?') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXX gettext(u'Are you sure you want to remove this action?') XXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXX
        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Remove Action') XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXX XXXXXXXXXX XX XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Open Condition') 
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX X
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX
          XXXXXXXXX
    XXXXXX
  XXXXXX
  XXXX XXX XXX
  XXX XX
  XXXX XXXXXXXXXXXXXX XXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXX XXXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XX XXX  XXXXXXXXXX XXX XXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXX
  XXX XX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Conditions') 
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XX XXX  XXXXXXXXXX XXX XXXXXX XXX
        BB BBBBBBBBBBBBBBBBBBBBB
          XXXX XX XXX  XXXXXXXXXXXXXXXXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
               gettext(u'Display the Product Stock for this Supply Point after it is selected') 
            XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
               gettext(u'Only show products for program') 
            XXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          XXXX XXX XXX
          XXXX XXX XXX
        BBBBB

        XXXX XX XXX  XXXXXXXXXXXX XX XXXXXXXX X X XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXX
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
              XXXXXXX
                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                 gettext(u'This case is a subcase of the previous case') 
              XXXXXXXX
            XXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
             gettext(u'Parent reference ID') 
          XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Relationship') XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                               XXXXXXXXXXXXXXX XXXXXX XXXX XX XXXXXXXXX XXXXXXX
                                               XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXX XX
        XXXX XXX XXX
        XXXX XXX XXX

        XXXX XX XXX  XXXXXXXXXX XXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Parent Indices') XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX
                XXXXXXX gettext(u'Parent Tag') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXX
                XXXXXXXXX
                XXX XX

                XXXXXXX gettext(u'Reference ID') XXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XX

                XXXXXXX gettext(u'Relationship') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                                       XXXXXXXXXXXXXXX X XX
                                                       XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXX XX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXX
                                            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX
                                            XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                            XXXXXXXXXXXXXXX X XX
                                        XXXXXXXXXXX
                XXXXXX
                XXX XX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXX
                   gettext(u'Remove parent index') 
                XXXXXXXXX
              XXXXXX
            XXXXXX

            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXX
               gettext(u'Add parent index') 
            XXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXX XX
        XXXX XXX XXX

        XXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX
        XXXXX
          XXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
             gettext(u'Close this case when the form is complete') 
          XXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX
                        XXX XXXXXXXXXX
                    XXXXXXXXX
        XXXX XXX XXX
      XXXXXX
    XXXXXX
  XXXXXX

  XXXX XXX XXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXX XXXXXX XXX X XXXXXXXXXX X XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXX X XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Case Action Meta') 
          XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Case Tag') XXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXX XX
            XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXX gettext(u'Case Type') XXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                              XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                              XXXXXX XXXXXXXXXX
                              XXXXXXXXXXXXXXX XXXXXXX X XXXX XXXXXXXX
                          XXXXXXXXXXX
            XXXXXX
            XXXX XX XXX XXXXXXXXXX XX XXXXXXXXX
            XXXXXX gettext(u'from') 
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Case List') XXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                              XXXXXXXXXXXX XXXXX
                              XXXXXXXXXXX XXXXXXXXXXXXXX
                              XXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXX
            XXXXXX
            XXXX XXX XXX
            XXXXXXXXXXXXXXXXXXXXX XX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
             gettext(u'Please select a case type.') 
          XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
   gettext(u'Expected Case Type') 
  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX gettext(u'Expected Case Type') X
        XXXXXXXXXXXXXX gettext(u'This is used for case property suggestions and when creating case indexes but\n              it does not get validated against the loaded case.') SSSS SS SSSS SSS SSSS SSSSSSSS SSSSSSSSSSS SSS SSSS SSSSSSSS SSSS SSSSSSS SSS
              SS SSSS SSS SSS SSSSSSSSS SSSSSSS SSS SSSSSS SSSSSX
  XXXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXXXXX
    XXXXXXXX gettext(u'Raw Config') XXXXXXXXXXXXXXXXXXXXXX
     gettext(u'XPath function') 
    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXXXXX
    XXXXXXXX gettext(u'User Data Config') XXXXXXXXXXXXXXXXXXXXXX
     gettext(u'User data key') 
    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXXXXX
    XXXXXXXX gettext(u'Case Index Config') XXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Case containing index') 
    XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXX
     gettext(u'Index name') 
    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXXXXX
    XXXXXXXX gettext(u'Lookup Table Config') XXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Lookup Table Tag') 
    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
     gettext(u'Table Field') 
    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXX XXXXXX XXX X XXXXXXXXXX X XXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXX X XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Case Action Meta') 
          XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Case Tag') XXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXX XX
            XXXXXX
            XXXX XX XXXXX XXXXXXXXXXX XXX
            XXXXXX
            XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXX gettext(u'Autoselect mode') XXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXX
                                XXXXXXXXXXXXXXX XXXXXXX X XXXXXXXX
                            XXXXXXXXXXX
            XXXXXX
            XXXXXXXXXXXXXXXXXX
            XXX XX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXX X XXXXXXX XXXXXXX XXX XXX
            XXXXXX
            XXXX XXX XXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
             gettext(u'Please select an autoselection mode.') 
          XXXXXX
        XXXXXX
      XXXXXX


      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXX XXXXXX XXX X XXXXXXXXXX X XXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXX X XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Case Action Meta') 
          XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Case Tag') XXXXXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXX XX
            XXXXXX
            XXXXXX
            XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXX gettext(u'Case Type') XXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXX
                                XXXXXXXXXXXXXXX XXXXXXX X XXXX XXXXXXXX
                            XXXXXXXXXXX
            XXXXXX

            XXXX XX XXX XXXXXXXXXX XX XXXXXXXXX
            XXXXXX gettext(u'from') 
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Case List') XXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXX XXXXX
                                XXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXX
              XXXXXXXXX
            XXXXXX
            XXXX XXX XXX
            XXXXXXXXXXXXXXXXXXXXX XX
            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
             gettext(u'Please select a case type.') 
          XXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Case Property') XXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
              XXXXXX
              XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                   gettext(u'Autoselect If Only One Case') 
                XXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Fixture Nodeset') XXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
              XXXXXX
              XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Fixture Tag') XXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
              XXXXXX
              XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Fixture Variable') XXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
              XXXXXX
              XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                   gettext(u'Autoselect If Only One Result Returned From Fixture') 
                XXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Arbitrary Datum Function') XXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
              XXXXXX
              XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX gettext(u'Arbitrary Datum id') XXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXX
        XXXXXX gettext(u'Add Action') XXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XX XXX XXXXX XXX XXXXXXXXXXX XXX
        XXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXX XXX
        XXXX XX XXXXXX XXXXX XXX XXXXXXXXXXX XXX
        XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXX XXX
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Add Action') XXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
           gettext(u'Load / Update / Close Cases') 
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XX XXX XXXXXXXXXXX XXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXX XXX
          XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXX XXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXX XXX
          XXXX XX XXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX XXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXX XXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
           gettext(u'Open New Cases') 
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
           gettext(u'Arbitrary Datums') 
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
              XXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX
                   gettext(u'Datum ID') 
                XXXXX
                XXX XXXXXXXXXXXXXXXXX
                   gettext(u'Datum Function') 
                XXXXX
              XXXXX
            XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXX
                  XXXXXXXXX
                XXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX
                XXXXX
                XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX
                XXXXX
              XXXXX
            XXXXXXXX
          XXXXXXXX
          XXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
             gettext(u'Add Datum') 
          XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
