BBBB BBBBBBBBBBBBBB
BBBB BBBB

XXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXX XXXXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX
       XXXXXXXXXX XXXXXXXXXXXX
       XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXX
       gettext(u'Only if the answer to...') 
    XXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'\n      Configuration no longer allowed.\n    ') 
      SSSSSSSSSSSSS SS SSSSSS SSSSSSSS
    
  XXXXXX

  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
       gettext(u'Only if the answer to') 
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                         XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                         XXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXX X
                           XXXXXXXX gettext(u'is') XX XXXXXXXXXXX
                           XXXXXXXX gettext(u'has selected') XX XXXXXXXXXXXXXXXXXX
                           XXXXXXXX gettext(u'is true') XX XXXXXXXXXXXXXXXXXXXXX
                         XX
                         XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                         XXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXX XXX XXXXXXXXXX XXXXXX XXX
    XXXX XXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XX XXXXXXXXXXXXXXXX
      XXXX XXXXXX XXXXXXXXX XXXXXX XX X XXXXXXXX XXX
      XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                           XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                           XXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXX XXXXXX XX X XXXX XXX XXX
      XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXX XXXXXXX
                          XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXX
           XXXXXXXXXX XXXXXXXXXXXX
           XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXX
        XXXX
    XXXXXX
  XXXXXX
  XXXXXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                     XXXXXX XXXXX
                     XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                     XXXXXX X
                       XXXXXXX XXXXXXXXXXXXXX XX X
                         XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
                           XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXX
                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXX XXXXXX X X XXXXXXXX XXXXXXXXXXXXX
                         X
                       X
                     XXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XX XXXXXXXXX
     gettext(u'Required') 
  XXXX
  XX XXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXX XX XXXXXXX
     gettext(u'Not assigned') 
  XXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                      XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXXXXXX XXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
       gettext(u'Load the following properties into the form questions') 
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
      XXXX
        XXXXXXXXX
        XXXX
           gettext(u'Property') 
        XXXXX
        XXXXXXXXX
        XXXX
           gettext(u'Question') 
        XXXXX
      XXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXX X
                       XXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
                     XXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXX X
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX X
                              XXXXXXXXXXX XXXXXX
                              XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                              XXXXXXXXXXXXX XXXXXX
                            X
                          XXXXXXXXX
          XX XXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXX
      XXXXX
      XXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'No properties will be loaded') 
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXX
         gettext(u'Add Property') 
      XXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                              XXXXXXX XXXXXXXXX
                              XXXXXXXXXX XXXXX
                              XXXXXXXXXXXX XBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
       gettext(u'Save Questions to Case Properties') 
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
      XXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXXXX
           gettext(u'Question') 
        XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXXXX
           gettext(u'Case Property') 
        XXXXX
         #
 #

        XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX gettext(u'Save Only If Edited') XXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX X
              XXXXXXXXXXXX X gettext(u'Only save the answer if form submission will change the property from its previous value.') XX
              XXXXXXXXXX XXXXXX
            XXXXXXXXXX
        XXXXX
        XXXX XXX XXX
      XXXXX
      XXXXXXXX

      XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXX X
                      XXXXXXXXXXXX XXXXXXXXX
                      XXXXXXXX XXXXXXXXXXXX XX XXXXXXXXXX XX XXXXXXXX XX XXXXXXXXXXXX XX XXXXXXXXXXX XX XXXXXXX XX XXXXXX
                    XXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXX X
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX X
                              XXXXXXXXX XXXXXX
                              XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                              XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX
                            XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                          XXXXXXXXX
          XX XXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXX XXXXXXXXX
                        XXXXXXXX XXXXXXXXXXXXXX
          XXXX XX XXX XXXXXXXXXXXXXXXXXXXX XXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                XXXXX XX
                                XXXXX XXX
                                XXXXXXXXXXXX X gettext(u'Click here to add a description') XX
                                XXXX XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
                                XXXXXXXXXXX X
                                  XXXXXXXXXXX XXXXXXXXXXXXXXX
                                  XXXXXXX  XXXXXXXXX
                                XX
                                XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXXXXXXXXX X gettext(u'Error updating description. Please try again.') XX
                                XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXX X
                                  XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XX
                                XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          XXXX XXX XXX
          XXXX XX XXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXX XXX
        XXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                  XX
        XXXXX
      XXXXX
      XXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXXXX XXXXXXXXX
                            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'No properties will be saved') 
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXX
         gettext(u'Add Property') 
      XXXXXXXXX
    XXXXXX
    XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XXX
      XXX
         gettext(u'\n          You no longer have permission to save case properties.\n        ') 
          SSS SS SSSSSS SSSS SSSSSSSSSS SS SSSS SSSS SSSSSSSSSSS
        
      XXXX
    XXXX XXX XXX
  XXXXXX
XXXXXXXXX