BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
   gettext(u'Custom Assertions') 
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX gettext(u'Custom Assertions') X
        XXXXXXXXXXXXXX gettext(u'Add custom assertions that you will use elsewhere.') SSS SSSSSS SSSSSSSSSS SSSS SSS SSSS SSS SSSSSSSSSSX
  XXXXXXXX
XXXXXXXX
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX
    XXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Test') XXXXX
      XXX XXXXXXXXXXXXXXXXX
         gettext(u'Message Text') 
      XXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX
      XXX XXXXXXXXXXXXXXXXX
        XXXXXX
          XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXX XXXXXXX
          XXXXXXXXXXXXXXXXX XXXXX
        XXXXXX XXX XXXXXXXX XXXX XX XXXXXX XXXXX XXXXX XX XX XXXXXX XXXXXXXXX XXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXX
        XXXXXX
          XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX XXXXX XXX X XXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXX XXXXX
        XXXXXX XXX XXXXXXXX XXXX XX XXXXXX XXXXX XXXXX XX XX XXXXXX XXXXXXXXX XXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX
           XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXX
    XXXXXXXX
  XXXXXXXX
  XXX
    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add custom assertion') 
    XXXXXXXXX
  XXXX
  XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXX
  XXXXXX XXXXXXXXXX XXXXX XX XXX XXXXXX XXXXXXXXXX XXXXXX XXXX XX XXXXXX XXX
XXXXXX
