BBBB BBBB
XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
   gettext(u'Custom Instances') 
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX gettext(u'Custom Instances') X
        XXXXXXXXXXXXXX gettext(u'Add custom instances that you will use elsewhere.') SSS SSSSSS SSSSSSSSS SSSS SSS SSSS SSS SSSSSSSSSSX
  XXXXXXXX
XXXXXXXX
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX
    XXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'ID') XXXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Instance path') XXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX
      XXX XXXXXXXXXXXXXXXXX
        XXXXXX
          XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX XXXXXXXXXX
          XXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXX XXX XXXXXXXX XXXX XX XXXXXX XXXXX XXXXX XX XX XXXXXX XXXXXXXXX XXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXX
        XXXXXX
          XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXX XXXXXXXX XXXX XX XXXXXX XXXXX XXXXX XX XX XXXXXX XXXXXXXXX XXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX
           XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXX
    XXXXXXXX
  XXXXXXXX
  XXX
    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add custom instance') 
    XXXXXXXXX
  XXXX
  XXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXX
  XXXXXX XXXXXXXXXX XXXXX XX XXX XXXXXX XXXXXXXXX XXXXXX XXXX XX XXXXXX XXX
XXXXXX
