BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
     gettext(u'End of Form Navigation') 
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXX gettext(u'End of Form Navigation') X
          XXXXXXXXXXXXXX gettext(u'After the user completes a form, your application automatically returns to the home screen.\n              Here you can set the application to navigate automatically to a different location in the app.') SSSSS SSS SSSS SSSSSSSSS S SSSSS SSSS SSSSSSSSSSS SSSSSSSSSSSSS SSSSSSS SS SSS SSSS SSSSSSS
              SSSS SSS SSS SSS SSS SSSSSSSSSSS SS SSSSSSSS SSSSSSSSSSSSS SS S SSSSSSSSS SSSSSSSS SS SSS SSSSX
    XXXXXXXX
  XXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXX
                XXXXXXXXXXXXXX XXX
                XXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
         gettext(u'This is an unknown value, possibly a deleted form. Please change this value.') 
      XXXXXX
      XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
         gettext(u"\n          The end of form navigation specified here will override the end of registration\n          action in the menu(s) where this form is a case list registration form.\n          To avoid this, select the default option here ('Home Screen').\n        ") 
          SSS SSS SS SSSS SSSSSSSSSS SSSSSSSSS SSSS SSSS SSSSSSSS SSS SSS SS SSSSSSSSSSSS
          SSSSSS SS SSS SSSSSSS SSSSS SSSS SSSS SS S SSSS SSSS SSSSSSSSSSSS SSSSS
          SS SSSSS SSSSS SSSSSS SSS SSSSSSS SSSSSS SSSS SSSSSS SSSSSSSSS
        
      XXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXX XXXXXXXXXXXXXX
            XX

      XXXX XXXXXXXXX XXX XXXX XXXX XXX XXXX XX XXXXXXXXX XXXX XXXXXXXX XXXX XXXXX XXX XXXXX XXX
          XXXX XXXXX XXXX XX XXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXX X
                    XXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXX XXXXXXXXXX
                    XXX XXXXXXXXXX
                X
                XX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXX
           gettext(u'Navigation Fallback') 
        XXXXXXXXX
        XXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXX
                        XXXXXXXXXXXXXX XXX
                    XXXXXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Add link') 
        XXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXX
    XXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXX gettext(u'XPath Expression') X
                  XXXXXXXX
                  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                  XXXXXXXX XXXXXXXXXXXXXX
                  XXXXXXXXXXXX XXXXXXX
                  XXXXXXXXXXXXX XXXXXXXXXXX
                  XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXX XXX
                  XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
             gettext(u'This form requires manual linking.') 
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
               gettext(u'Enable manual linking') 
            XXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXX
               gettext(u'Disable manual linking') 
            XXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXX XXX
                 gettext(u'Refresh') 
              XXXX XXX XXX
              XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
                 gettext(u'Continue') 
              XXXX XXX XXX
            XXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XXX X XX XXXXXXXXXXXXXXXXXXXXXX
             gettext(u'No additional linking required.') 
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Error fetching link data.') 
          XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXXXXXXX XXXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                          XXXXXXXX
                          XXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX
                          XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXX
    XXXXXX

    XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX
       gettext(u'Remove this link') 
    XXXXXXXXX
  XXXXXX
  XXXXXX
XXXXXXXXX
