BBBB BBBB
BBBB BBBBBBBBBBBBBB
XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
   gettext(u'Auto Capture Location') 
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX gettext(u'Auto Capture Location') X
        XXXXXXXXXXXXXX gettext(u"On CommCare Android, have this form automatically capture the user's current geo-location.") SS SSSSSSSS SSSSSSSS SSSS SSSS SSSS SSSSSSSSSSSSS SSSSSSS SSS SSSSSS SSSSSSS SSSSSSSSSSSSSX
  XXXXXXXX
XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  BB BBBBBBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
       gettext(u"\n        This application is configured to auto capture location for all forms.\n        <br>\n        This can be changed in the application's settings, in the <strong>Advanced Settings</strong> tab,\n        <strong>Android Settings</strong> section.\n      ") 
        SSSS SSSSSSSSSSS SS SSSSSSSSSS SS SSSS SSSSSSS SSSSSSSS SSS SSS SSSSSS
        SSSS
        SSSS SSS SS SSSSSSS SS SSS SSSSSSSSSSSSS SSSSSSSSS SS SSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSS SSSS
        SSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSS SSSSSSSS
      
    XXXXXX
  BBBB
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  BBBBB
  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
XXXXXX
