BBBB BBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBBBBB BBBBBXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX
      XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Show') XXXXX
        XXXX
          XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXX gettext(u'Multimedia') 
          XXXX
        XXXXX
        XXXX
          XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXX gettext(u'Logic') 
          XXXX
        XXXXX
        XXXX
          XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXX gettext(u'Advanced') 
          XXXX
        XXXXX
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Multimedia') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Logic') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Form filtering is disabled for this form') XXXXXX
          BBBBB

          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Advanced') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BBBBB
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX

          BB BBBBBBBBBBBBB BB BBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BBBBB

          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          BBBBB

          BB BBBBBBBBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBB
          BBBBB

        XXXXXX
      XXXXXX
    XXXXXX

  XXXXXXX
XXXXXX
