BBBB BBBB

XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Upload XForm') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXBBB BBBBBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBXX
          BBBBBBBBBB
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX
          XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
             gettext(u'Upload') 
          XXXXXXXXX
        XXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Close') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
