BBBB BBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  BB BBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBXX
        BBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Copy Form') 
          XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXX XXXXXXX
                                XXXXXXXXXXXXXXXXXXX XXXXX
                                           XXXXXXXXXXXX XXXXXXX
                                           XXXXXXXXXXXXX XXXXX
                                           XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XX XXXXX XXXXXXXXXXX XXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXXXX XXXXXXX
                                XXXXXXXXXXXXXXXXXXX XXXXXXXX
                                           XXXXXXXXXXXX XXXXXXX
                                           XXXXXXXXXXXXX XXXXX
                                           XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXX XXX
                    XXXXXXX
          BBBB
            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXBBB BBB BB BBBBBBBBBBBBBBB
              XXXXXXX XXXXXXXFFFFFFFFFFFFFFFFXXXXXXXXX
            BBBBBBXXXXXXXXX
          BBBBB
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXX
             gettext(u'Copy') 
          XXXXXXXXX
        XXXXXX
      XXXXXXX
    XXXXXX
    BBBBBBBBBB
    XXXXXXXXXX

    XXXXXXXXXXX
  BBBBB
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'XForm') 
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX
        XXXX
          XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'Upload') 
          XXXX
        XXXXX
        XXXX
          XX BB BBB BBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBB
             XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Download') 
          XXXX
        XXXXX
      XXXXX
    XXXXXX
  XXXXXX
XXXXXX
