BBBB BBBB
BBBB BBBBBBBBBBBBBB


XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
       gettext(u'Make this my app’s Post-Update form') 
      XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX gettext(u'Post-Update form') X
            XXXXXXXXXXXXXX gettext(u'Users will be entered directly into this form when logging back into CommCare immediately after updating their CommCare app. You can use this to give users information on what has changed in a new app version') SSSSS SSSS SS SSSSSSS SSSSSSSS SSSS SSSS SSSS SSSS SSSSSSS SSSS SSSS SSSSSSSS SSSSSSSSSSS SSSSS SSSSSSSS SSSSS SSSSSSSS SSSS SSS SSS SSS SSSS SS SSSS SSSSS SSSSSSSSSSS SS SSSS SSS SSSSSSS SS S SSS SSS SSSSSSSX
      XXXXXXXX
      XXXX XXX XXX
      XXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX gettext(u'Post-Update form') X
            XXXXXXXXXXXXXX gettext(u'You have already set another form as this app’s Post-Update form') SSS SSSS SSSSSSS SSS SSSSSSS SSSS SS SSSS SSSSS SSSSSSSSSSS SSSSX
      XXXXXXXX
      XXXX XXX XXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXX
      XX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
       gettext(u'Enable the Post-Update form for this release') 
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX gettext(u'Enable this') X
            XXXXXXXXXXXXXX gettext(u'You can disable the Post-Update form if it is not necessary for the current app release, but you don’t want to delete it') SSS SSS SSSSSSS SSS SSSSSSSSSSS SSSS SS SS SS SSS SSSSSSSSS SSS SSS SSSSSSS SSS SSSSSSSS SSS SSS SSSSS SSSS SS SSSSSS SSX
      XXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXX XX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
