BBBB BBBB
BBBB BBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
     gettext(u'Shadow source') 
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX gettext(u'The form which this form will shadow') SSS SSSS SSSSS SSSS SSSS SSSS SSSSSSX
    XXXXXXXX
  XXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXX
      BBB BBBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXX
      BBBBBB
    XXXXXXXXX

    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX
