BBBB BBBB
BBBB BBBBBBBBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB
  XXXXXX
  XX XXXXXXXXXXXXX
     gettext(u'\n      <strong>User Properties</strong> allow you to store data about the user and use that data in forms.\n    ') 
      SSSSSSSSSSSS SSSSSSSSSSSSSSSSSSS SSSSS SSS SS SSSSS SSSS SSSSS SSS SSSS SSS SSS SSSS SSSS SS SSSSSS
    
  XXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXXX
XXXXXX
