BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBB
  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXXXXXX
      XXXXXXXX gettext(u'Attendee') XXXXXXXXX
      BBBBBB BBBB
    XXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXX
           gettext(u'\n            This attendee cannot be deleted as <strong>%(attendee_name)s</strong> has been tracked as\n            having attended one or more events.\n          ') 
            SSSS SSSSSSSS SSSSSS SS SSSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSS SSSS SSSSSSS SS
            SSSSSS SSSSSSSS SSS SS SSSS SSSSSSS
          
        XXXX
      XXXXXX
    BBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
           gettext(u'Update Attendee') 
        XXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXX
           gettext(u'Delete Attendee') 
        XXXX
      XXXXXX
    XXXXXX
  XXXXXXX

BBBBBBBB
BBBBB BBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Delete Attendee')  
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
          XXXXX
        XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXX XX XXXXXXXX XX
              XXXXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBBX
              XXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXX XXXXXXXX
          BBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXX
            XXX
               gettext(u'\n                Are you sure you want to permanently delete <strong>%(attendee_name)s</strong>?\n              ') 
                SSS SSS SSSS SSS SSSS SS SSSSSSSSSSS SSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
              
            XXXX
            XXX
               gettext(u'\n                This action will delete %(attendee_name)s as a potential attendee and will remove them from all\n                future events that they are currently enlisted in.\n              ') 
                SSSS SSSSSS SSSS SSSSSS SSSSSSSSSSSSSSSSS SS S SSSSSSSSS SSSSSSSS SSS SSSS SSSSSS SSSS SSSS SSS
                SSSSSS SSSSSS SSSS SSSS SSS SSSSSSSSS SSSSSSSS SSS
              
            XXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXX
                 gettext(u'\n                  This action cannot be undone.\n                ') 
                  SSSS SSSSSS SSSSSS SS SSSSSSS
                
              XXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Cancel') XXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
               gettext(u'Delete Attendee') 
            XXXXXXXXX
          XXXXXX
        XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
