BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
  
BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBB
XX XXXXXXXXXXXXX
  XXX
     gettext(u'\n    Known potential attendees who can be invited to participate in Attendance\n    Tracking Events.\n    ') 
    SSSSS SSSSSSSSS SSSSSSSSS SSS SSS SS SSSSSSS SS SSSSSSSSSSS SS SSSSSSSSSS
    SSSSSSSS SSSSSSS
    
  XXXX

  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Create Potential Attendee') 
      XXXXXXXXX

      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
        XX XXXXXXXXXXXXXXX gettext(u'Enable Mobile Worker Attendees') 
      XXXX
  XXXXXX
XXXX

  XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXX
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Create Potential Attendee') XXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
              BBBBBB BBBBBBBBBBBBBBBBB
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Create') XXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'New Potential Attendees') 
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXX
        XXXX
            XXX XXXXXXXXXXXXXXXXX gettext(u'Name') XXXXX
            XXX XXXXXXXXXXXXXXXXX gettext(u'Status') XXXXX
        XXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
               gettext(u'Pending...') 
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXX  gettext(u'NEW') 
              XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'ERROR') 
                XXXX XX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX
            XXXXXX
          XXXXX
        XXXXX
        XXXXXXXX
      XXXXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Potential Attendees') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXX XXXXXX
                                XXXXXXX XXXXXXXXXX X XXXXXXXXXXXX XX
                                XXXXXXXXXXXX XBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXX XXX
               XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXXXXX
          XXXX
            XXX XXXXXXXXXXXXXXXXXX gettext(u'Name') XXXXX
          XXXXX
          XXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXX
            XXXX
              XX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXX
            XXXXX
          XXXXX
          XXXXXXXX
        XXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Loading potential attendees ...') 
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
           gettext(u'\n            <strong>There was an issue contacting the server.</strong>\n            Please check your internet connection.\n            If this issue continues, please\n            <a href="#modalReportIssue" data-toggle="modal">report an issue</a>.\n          ') 
            SSSSSSSSSSSSS SSS SS SSSSS SSSSSSSSSS SSS SSSSSSSSSSSSSSSS
            SSSSSS SSSSS SSSS SSSSSSSS SSSSSSSSSSS
            SS SSSS SSSSS SSSSSSSSSS SSSSSS
            SS SSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSS SS SSSSSSSSSS
          
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'\n            You currently have no potential attendees.\n          ') 
            SSS SSSSSSSSS SSSS SS SSSSSSSSS SSSSSSSSSS
          
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           gettext(u'\n            No matching potential attendees found.\n          ') 
            SS SSSSSSSS SSSSSSSSS SSSSSSSSS SSSSSS
          
        XXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXX
                            XXXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB BBBBBBBBBBBB
