BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
  
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXX
         gettext(u'\n          Attendance tracking events can be used to track attendance of all the selected attendees.\n        ') 
          SSSSSSSSSS SSSSSSSS SSSSSS SSS SS SSSS SS SSSSS SSSSSSSSSS SS SSS SSS SSSSSSSS SSSSSSSSSS
        
      XXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add new event') 
      XXXXXXXXX
    XXXX
  XXXXXX
BBBBBBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XXXX XX XXX XXXXXXXXXXX XXX
      XX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXX
      XXXX XXX XXX
      XXXX XX XXXXXX XXXXXXXXXXX XXX
      XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXX XXX
    XXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XXXX XX XXX XXXXXXXXXXXXXXX XXX
        XXXX XX XXX XXXXXXXXXXXXXXXX XXX
        XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'View Attendees') 
          XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXX
        XXXX XXX XXX
        XXXX XX XXXXXX XXXXXXXXXXXXXXXX XXX
           gettext(u'No Attendees Yet') 
        XXXX XXX XXX
      XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
                XXXX
                  XXX XXXXXXXXXXXXXXXXX gettext(u'Date Attended') XXXXX
                  XXX XXXXXXXXXXXXXXXXX gettext(u'Attendee Name') XXXXX
                XXXXX
                XXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                  XXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                XXXXXXXX
                XXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXX
              XXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXX XXX
      XXXX XX XXXXXX XXXXXXXXXXXXXXX XXX
      XXXXXX gettext(u'Event has not yet started') XXXXXXX
      XXXX XXX XXX
    XXXXX
  XXXXXXXXX
BBBBBBBB
