BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX
    XXX
       gettext(u'\n      There was a problem fetching the list of attendees and attendance takers. Please try again.\n      ') 
      SSSSS SSS S SSSSSSS SSSSSSSS SSS SSSS SS SSSSSSSSS SSS SSSSSSSSSS SSSSSSS SSSSSS SSS SSSSSS
      
    XXXX
  XXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    BBBBBB BBBB
  XXXXXXX
BBBBBBBB
