BBBB BBBB

BB BBBBBBB
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXX
      BBB BBBBBBBBBBB BB BBBBBBB
        XXXX
          XXX XXXXXXXXXXXXXXXXXX
            
          XXXXX
          XXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                  BB BBBBBBBBBBBBB
                    XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBBX
                  BBBB
                    XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBBX
                  BBBBB
                  XXXXXXXXXXXXXX
              BBBBBBBBBB
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                BB BBBBBBBBBBBBB
                  XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Enable') 
                BBBB
                  XX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Disable') 
                BBBBB
              XXXXXXXXX
            XXXXXXX
          XXXXX
        XXXXX
      BBBBBB
    XXXXXXXX
  XXXXXXXX
BBBB
  XXXX XXXXXXXXXXXX XXXXXXXXXXXX
     gettext(u'No project spaces found.') 
      SS SSSSSSS SSSSSS SSSSSS
    
  XXXXXX
BBBBB