# Generated by Django 1.10.7 on 2017-07-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_processor', '0064_auto_20170725_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetransaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'form'), (2, 'rebuild_with_reason'), (4, 'user_requested_rebuild'), (8, 'user_archived_rebuild'), (16, 'form_archive_rebuild'), (32, 'form_edit_rebuild'), (2048, 'form_reprocessed_rebuild'), (64, 'ledger'), (128, 'case_create'), (256, 'case_close'), (1024, 'case_attachment'), (512, 'case_index')]),
        ),
    ]
