# Generated by Django 1.11.11 on 2018-03-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_processor', '0069_add_metafields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xformoperationsql',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
