# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-16 20:08
from __future__ import unicode_literals

import corehq.apps.mobile_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQLMobileAuthKeyRecord',
            fields=[
                ('uuid', models.UUIDField(db_column='id', db_index=True, primary_key=True, serialize=False,
                                          default=corehq.apps.mobile_auth.models._default_uuid)),
                ('domain', models.CharField(db_index=True, max_length=126)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('valid', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('type', models.CharField(choices=[('AES256', 'AES256')], default='AES256', max_length=32)),
                ('key', models.CharField(default=corehq.apps.mobile_auth.models._default_key, max_length=127)),
            ],
            options={
                'db_table': 'mobile_auth_mobileauthkeyrecord',
            },
        ),
    ]
