cluster.name: gh_actions_es_6
network.host: 0.0.0.0
http.port: 9200

discovery.type: single-node

# dev-only setting to allow client-side ES front-ends
http.cors.allow-origin: "*"
http.cors.enabled: true

action.auto_create_index: ".watches,.triggered_watches,.watcher-history-*"