COMMTRACK_REPORT_XMLNS = 'http://commtrack.org/stock_report'

SECTION_TYPE_STOCK = 'stock'

REPORT_TYPE_BALANCE = 'balance'
REPORT_TYPE_TRANSFER = 'transfer'


TRANSACTION_TYPE_STOCKONHAND = 'stockonhand'
TRANSACTION_TYPE_RECEIPTS = 'receipts'
TRANSACTION_TYPE_CONSUMPTION = 'consumption'

TRANSACTION_SUBTYPE_INFERRED = '_inferred'