- title: 'Data and Sharing'
  id: app-settings-basic
  settings:
    - hq.application_version # App Version (disabled)
    # Application
    - hq.case_sharing  # Case Sharing
    - hq.cloudcare_enabled  # CloudCare
    - hq.commtrack_requisition_mode
    - hq.use_custom_suite
    - hq.custom_suite
    - hq.custom_base_url
    # RemoteApp
    - hq.profile_url
    - hq.manage_urls

- title: Build Settings
  id: app-settings-general
  collapse: true
  settings:
    - hq.build_spec  # CommCare Version
    - properties.cc-autoup-freq  # Auto Update Frequency
    - properties.unsent-number-limit  # Unsent Form Limit
    - properties.cc-content-valid  # Multimedia Validation
    - properties.server-tether  # Sync Mode
    - properties.cc-autosync-freq  # Auto-Sync Frequency
    - properties.unsent-time-limit  # Unsynced Time Limit
    

- title: 'Java Phone General Settings'
  id: app-settings-j2me-properties
  collapse: true
  settings:
    - hq.use_j2me_endpoint  # Use HTTP
    - hq.platform  # J2ME Platform
    - hq.admin_password  # Admin Password
    - properties.cc-send-procedure  # Send Data
    - properties.password_format  # Password Format
    - properties.logenabled  # Logging Enabled


- title: 'Java Phone User Interface Settings'
  id: app-settings-j2me-ui
  collapse: true
  settings:
    - features.sense  # CommCare Sense
    - properties.extra_key_action  # Extra Key Action
    - properties.cc-entry-mode  # Item Selection Mode
    - properties.cc-send-unsent  # Send Forms Mode
    - hq.text_input  # Text Input
    - properties.ViewStyle  # Form Entry Style
    - properties.cc-user-mode  # User Login Mode
    - properties.cc-login-images # Login Buttons

- title: 'Android Settings'
  id: app-settings-android
  collapse: true
  settings:
    - properties.cc-days-form-retain # Days to Retain for Review
    - properties.cc-show-saved
    - properties.cc-show-incomplete
    - properties.cc-resize-images
    - properties.cc-fuzzy-search-enabled
    - properties.logo_android_home
    - properties.logo_android_login
    - hq.auto_gps_capture
    - properties.cc-login-duration-seconds
    - properties.cc-log-entity-detail-enabled
    - properties.cc-inflation-target-density
    - hq.use_grid_menus
    - hq.grid_form_menus

- title: 'Advanced'
  id: app-settings-advanced
  collapse: true
  settings:
    - properties.advanced_app_builder
    - properties.log_prop_weekly  # Weekly Log Sending Frequency
    - properties.log_prop_daily  # Daily Log Sending Frequency
    - hq.secure_submissions
    - hq.translation_strategy

- title: 'Disabled'
  id: app-settings-disabled
  collapse: true
  always_show: false
  settings:
    - properties.purge-freq  # Purge Frequency (disabled)
    - properties.user_reg_server  # Server User Registration (disabled)
    - properties.restore-tolerance  # OTA Restore Tolerance (disabled)
    - features.users  # No Users Mode (disabled)
    - properties.loose_media  # Loose Media Mode (disabled)
