APP_V1 = '1.0'
APP_V2 = '2.0'

CAREPLAN_GOAL = 'careplan_goal'
CAREPLAN_TASK = 'careplan_task'
CAREPLAN_CASE_NAMES = {
    CAREPLAN_GOAL: 'Goal',
    CAREPLAN_TASK: 'Task'
}

CT_REQUISITION_MODE_3 = '3-step'
CT_REQUISITION_MODE_4 = '4-step'
CT_REQUISITION_MODES = [CT_REQUISITION_MODE_3, CT_REQUISITION_MODE_4]

CT_LEDGER_PREFIX = 'ledger:'
CT_LEDGER_STOCK = 'stock'
CT_LEDGER_REQUESTED = 'ct-requested'
CT_LEDGER_APPROVED = 'ct-approved'