# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 19:39
from __future__ import absolute_import, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_search', '0004_auto_20170518_2018'),
    ]

    operations = []
