XXX
  XXXX XXXXXXXXXX XXXXX
XXXX

XXX
  XXX XXXXXXX XXXXX XX XXXXXXXXXXXX XXX XXXXXXX XXX XXXXXXXXXXXXX
XXXX

XXX
  BB BBBBBBBB
    XXXXXXXXX XXX XXXXX
    XXXX XXX XXXXXXXXX XXX XXXXXXXXX XXXXX
  BBBBB
XXXX

XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
XXX
  BB BBBBBBBBBBBBBBB
    XXXXXXX XXXXX XXXXX
    XXXXXXXXXX XXX XXXXXXXXXXXXX XXXXX
    XXXXXX XXXXXXXX XXXXX
    XXXXXXX XXXXXXXXX 
  BBBB
    XXX XXXXXXXXX
  BBBBB
XXXX

XXXXXXXXXXX XXXXXXXXXXXXXXXX
XXX
  BB BBBBBBBBBBBBBBBB
    XXXXXXXX XXXXX XXXXX
    XXXXXXXXXXXX XXXXX XXXXX
    XXXXX XXXXX XXXXX
    XXX XXXXXXXXXX
    XX XXX XXXXXXXX XXXXX
    XXXX XXXXXXXX XXXXXXXX XXXXX
  BBBB
    XX XXXXXXXX XXXXXXXXXXXX
  BBBBB
XXXX

XXXXXX XXXXXXXXXXXXXXXX
XXX
  BB BBBBBBBBBBBBBBBB
    XXXXXXXX XXXXX XXXXX
    XXXXXXXXXXXX XXXXX XXXXX
    XXXXX XXXXX XXXXX
    XXX XXXXX XXXXX
    XX XXX XXXXXXXX XXXXX
    XXXX XXXXXXXX XXXXXXXX XXXXX
  BBBB
    XX XXX XXXXXXXXXXXX
  BBBBB
XXXX

XXX
  XXX XXX XXXX XXX XXXXXXX XXXXX XXXXX 
XXXX

XXX
  XXXXXXXXXX XX
  XXXXX XXXXXXXX XX XXXX
XXXX
