# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_update_report_builder_included_feature_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaccount',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
