# Generated by Django 1.11.12 on 2018-05-01 18:13

from django.db import migrations

import corehq.apps.accounting.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_add__skip_auto_downgrade_reason'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
                ('visible_objects', corehq.apps.accounting.models.VisibleSubscriptionManager()),
            ],
        ),
    ]
