# Generated by Django 1.11.13 on 2018-06-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_billingaccount_billing_admin_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='invoicing_plan',
            field=models.CharField(
                choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')],
                default='MONTHLY', max_length=25
            )
        ),
    ]
