# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 19:36
from __future__ import unicode_literals
from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_auto_20180629_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, default=list, to='accounting.Subscription'),
        ),
    ]
