# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-10 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0048_populate_invoicepdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlinvoicepdf',
            name='couch_id',
        ),
    ]
