# Generated by Django 2.2.16 on 2020-11-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0010_defaultexportsettings'),
        ('accounting', '0051_hubspot_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='default_export_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='export.DefaultExportSettings'),
        ),
    ]
