# Generated by Django 4.2.11 on 2024-04-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0091_remove_custom_banner_alerts_feature_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultproductplan",
            name="is_annual_plan",
            field=models.BooleanField(default=False),
        ),
    ]
