# Generated by Django 4.2.20 on 2025-07-08 09:07

from django.core.management import call_command
from django.db import migrations

from corehq.apps.accounting.models import SoftwarePlanEdition
from corehq.privileges import CASE_DETAIL_PRINT, SORT_CALCULATION_IN_CASE_LIST, CUSTOM_ICON_BADGES
from corehq.util.django_migrations import skip_on_fresh_install


@skip_on_fresh_install
def _grandfather_privileges(apps, schema_editor):
    call_command('cchq_prbac_bootstrap')

    skip_editions = ','.join((
        SoftwarePlanEdition.PAUSED,
        SoftwarePlanEdition.FREE,
    ))
    call_command(
        'cchq_prbac_grandfather_privs',
        CASE_DETAIL_PRINT,
        SORT_CALCULATION_IN_CASE_LIST,
        CUSTOM_ICON_BADGES,
        skip_edition=skip_editions,
        noinput=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0103_bulk_data_cleaning_priv'),
    ]

    operations = [
        migrations.RunPython(
            _grandfather_privileges,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
