# Generated by Django 5.2.6 on 2025-11-03 19:21

from django.core.management import call_command
from django.db import migrations

from corehq.apps.accounting.models import SoftwarePlanEdition
from corehq.privileges import CUSTOM_ICON_BADGES

from corehq.util.django_migrations import skip_on_fresh_install


@skip_on_fresh_install
def _grandfather_privilege(apps, schema_editor):
    call_command('cchq_prbac_bootstrap')

    skip_editions = ','.join((
        SoftwarePlanEdition.PAUSED,
        SoftwarePlanEdition.FREE,
        SoftwarePlanEdition.STANDARD,
        SoftwarePlanEdition.PRO,
    ))
    call_command(
        'cchq_prbac_grandfather_privs',
        CUSTOM_ICON_BADGES,
        skip_edition=skip_editions,
        noinput=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0111_rename_is_auto_invoiceable_billingaccount_require_auto_pay'),
    ]

    operations = [
        migrations.RunPython(
            _grandfather_privilege,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
