# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMapping',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('stcode', models.IntegerField()),
                ('stname', models.CharField(max_length=255)),
                ('dtcode', models.IntegerField()),
                ('dtname', models.CharField(max_length=255)),
                ('pjcode', models.IntegerField()),
                ('pjname', models.CharField(max_length=255)),
                ('awcid', models.BigIntegerField()),
                ('awcname', models.CharField(max_length=255)),
                ('villcode', models.IntegerField()),
                ('Village_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RCHChild',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Caste', models.CharField(max_length=255, null=True)),
                ('Created_On', models.DateTimeField(null=True)),
                ('District_ID', models.PositiveSmallIntegerField(null=True)),
                ('District_Name', models.CharField(max_length=255, null=True)),
                ('HealthBlock_Name', models.CharField(max_length=255, null=True)),
                ('HealthBlock_ID', models.IntegerField(null=True)),
                ('Taluka_ID', models.IntegerField(null=True)),
                ('Taluka_Name', models.CharField(max_length=255, null=True)),
                ('MDDS_TalukaID', models.IntegerField(null=True)),
                ('MDDS_DistrictID', models.PositiveSmallIntegerField(null=True)),
                ('PHC_Name', models.CharField(max_length=255, null=True)),
                ('PHC_ID', models.IntegerField(null=True)),
                ('Subcentre_Name', models.CharField(max_length=255, null=True)),
                ('Village_ID', models.IntegerField(null=True)),
                ('Mobile_no', models.BigIntegerField(null=True)),
                ('Religion', models.CharField(max_length=255, null=True)),
                ('State_Name', models.CharField(max_length=255, null=True)),
                ('StateID', models.PositiveSmallIntegerField(null=True)),
                ('Updated_On', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ANM_Name', models.CharField(max_length=255, null=True)),
                ('ANM_Phone_No', models.BigIntegerField(null=True)),
                ('ASHA_Name', models.CharField(max_length=255, null=True)),
                ('ASHA_Phone_No', models.BigIntegerField(null=True)),
                ('Birth_Date', models.DateTimeField(null=True)),
                ('Child_Aadhaar_No', models.BigIntegerField(null=True)),
                ('Child_RCH_ID_No', models.BigIntegerField(null=True)),
                ('DPTBooster1_Antibiotics_Given', models.CharField(max_length=255, null=True)),
                ('DPTBooster1_Breastfeeding', models.CharField(max_length=255, null=True)),
                ('DPTBooster1_Complentary_Feeding', models.CharField(max_length=255, null=True)),
                ('DPTBooster1_Diarrhoea', models.CharField(max_length=255, null=True)),
                ('DPTBooster1_ORS_Given', models.CharField(max_length=255, null=True)),
                ('DPTBooster1_Pneumonia', models.CharField(max_length=255, null=True)),
                ('Delete_mother', models.CharField(max_length=255, null=True)),
                ('Fully_Immunized', models.CharField(max_length=255, null=True)),
                ('Gender', models.CharField(max_length=255, null=True)),
                ('MDDS_VillageID', models.IntegerField(null=True)),
                ('Measles1_Antibiotics_Given', models.CharField(max_length=255, null=True)),
                ('Measles1_Breastfeeding', models.CharField(max_length=255, null=True)),
                ('Measles1_Complentary_Feeding', models.CharField(max_length=255, null=True)),
                ('Measles1_Diarrhoea', models.CharField(max_length=255, null=True)),
                ('Measles1_ORS_Given', models.CharField(max_length=255, null=True)),
                ('Measles1_Pneumonia', models.CharField(max_length=255, null=True)),
                ('Mobile_Relates_To', models.CharField(max_length=255, null=True)),
                ('Mother_Case_no', models.SmallIntegerField(null=True)),
                ('Mother_RCH_ID_NO', models.BigIntegerField(null=True)),
                ('Name_Child', models.CharField(max_length=255, null=True)),
                ('Name_Father', models.CharField(max_length=255, null=True)),
                ('Name_Mother', models.CharField(max_length=255, null=True)),
                ('Received_AllVaccines', models.CharField(max_length=255, null=True)),
                ('SubCentre_ID', models.SmallIntegerField(null=True)),
                ('VILLAGE_Name', models.CharField(max_length=255, null=True)),
                ('Weight', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RCHMother',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Caste', models.CharField(max_length=255, null=True)),
                ('Created_On', models.DateTimeField(null=True)),
                ('District_ID', models.PositiveSmallIntegerField(null=True)),
                ('District_Name', models.CharField(max_length=255, null=True)),
                ('HealthBlock_Name', models.CharField(max_length=255, null=True)),
                ('HealthBlock_ID', models.IntegerField(null=True)),
                ('Taluka_ID', models.IntegerField(null=True)),
                ('Taluka_Name', models.CharField(max_length=255, null=True)),
                ('MDDS_TalukaID', models.IntegerField(null=True)),
                ('MDDS_DistrictID', models.PositiveSmallIntegerField(null=True)),
                ('PHC_Name', models.CharField(max_length=255, null=True)),
                ('PHC_ID', models.IntegerField(null=True)),
                ('Subcentre_Name', models.CharField(max_length=255, null=True)),
                ('Village_ID', models.IntegerField(null=True)),
                ('Mobile_no', models.BigIntegerField(null=True)),
                ('Religion', models.CharField(max_length=255, null=True)),
                ('State_Name', models.CharField(max_length=255, null=True)),
                ('StateID', models.PositiveSmallIntegerField(null=True)),
                ('Updated_On', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('Registration_no', models.BigIntegerField(null=True)),
                ('Case_no', models.IntegerField(null=True)),
                ('EC_Register_srno', models.IntegerField(null=True)),
                ('Name_wife', models.CharField(max_length=255, null=True)),
                ('Name_husband', models.CharField(max_length=255, null=True)),
                ('Whose_mobile', models.CharField(max_length=255, null=True)),
                ('Wife_current_age', models.PositiveSmallIntegerField(null=True)),
                ('Wife_marry_age', models.PositiveSmallIntegerField(null=True)),
                ('Hus_current_age', models.PositiveSmallIntegerField(null=True)),
                ('Hus_marry_age', models.PositiveSmallIntegerField(null=True)),
                ('Male_child_born', models.PositiveSmallIntegerField(null=True)),
                ('Female_child_born', models.PositiveSmallIntegerField(null=True)),
                ('Male_child_live', models.PositiveSmallIntegerField(null=True)),
                ('Female_child_live', models.PositiveSmallIntegerField(null=True)),
                ('Young_child_gender', models.CharField(max_length=255, null=True)),
                ('Young_child_age_year', models.SmallIntegerField(null=True)),
                ('EC_ANM_Name', models.CharField(max_length=255, null=True)),
                ('EC_ASHA_Name', models.CharField(max_length=255, null=True)),
                ('EC_ANMPhone_No', models.BigIntegerField(null=True)),
                ('EC_ASHAPhone_No', models.BigIntegerField(null=True)),
                ('EC_Registration_Yr', models.SmallIntegerField(null=True)),
                ('PW_Aadhar_No', models.BigIntegerField(null=True)),
                ('PW_AadhaarLinked', models.CharField(max_length=255, null=True)),
                ('PW_Branch_Name', models.CharField(max_length=255, null=True)),
                ('Hus_AadhaarLinked', models.CharField(max_length=255, null=True)),
                ('Economic_Status', models.CharField(max_length=255, null=True)),
                ('Mother_BirthDate', models.DateTimeField(null=True)),
                ('Mother_Age', models.PositiveSmallIntegerField(null=True)),
                ('Mother_ANM_ID', models.IntegerField(null=True)),
                ('Mother_ASHA_ID', models.IntegerField(null=True)),
                ('JSY_Beneficiary', models.CharField(max_length=255, null=True)),
                ('JSY_Payment_Received', models.CharField(max_length=255, null=True)),
                ('Delete_Mother', models.CharField(max_length=255, null=True)),
                ('Entry_Type', models.CharField(max_length=255, null=True)),
                ('LMP_Date', models.DateTimeField(null=True)),
                ('EDD_Date', models.DateTimeField(null=True)),
                ('BloodGroup_Test', models.CharField(max_length=255, null=True)),
                ('LMP_Registration_Yr', models.PositiveSmallIntegerField(null=True)),
                ('Last_Pregnancy_Complication', models.CharField(max_length=255, null=True)),
                ('Last_Pregnancy_outcome', models.CharField(max_length=255, null=True)),
                ('Expected_delivery_place', models.CharField(max_length=255, null=True)),
                ('No_of_times_Pregnant', models.PositiveSmallIntegerField(null=True)),
                ('ANC3', models.DateTimeField(null=True)),
                ('ANC3_Pregnancy_Week', models.SmallIntegerField(null=True)),
                ('ANC3_Weight', models.FloatField(null=True)),
                ('ANC3_BP_Systolic', models.SmallIntegerField(null=True)),
                ('ANC3_BP_Distolic', models.SmallIntegerField(null=True)),
                ('ANC3_Hb_gm', models.FloatField(null=True)),
                ('TT1', models.DateTimeField(null=True)),
                ('Maternal_Death', models.SmallIntegerField(null=True)),
                ('Death_Reason', models.CharField(max_length=255, null=True)),
                ('PPMC', models.CharField(max_length=255, null=True)),
                ('Delivery_date', models.DateTimeField(null=True)),
                ('Delivery_Place_Name', models.CharField(max_length=255, null=True)),
                ('Delivery_Conducted_By', models.CharField(max_length=255, null=True)),
                ('Delivery_Type', models.CharField(max_length=255, null=True)),
                ('Delivery_Outcomes', models.SmallIntegerField(null=True)),
                ('Live_Birth', models.SmallIntegerField(null=True)),
                ('Still_Birth', models.SmallIntegerField(null=True)),
                ('Discharge_Date', models.DateTimeField(null=True)),
                ('Delivery_Time', models.TimeField(null=True)),
                ('Discharge_Time', models.TimeField(null=True)),
                ('Delivery_Complication', models.CharField(max_length=255, null=True)),
                ('Infant1_Id', models.BigIntegerField(null=True)),
                ('Infant1_Name', models.CharField(max_length=255, null=True)),
                ('Infant1_Baby_Cried', models.CharField(max_length=255, null=True)),
                ('Infant1_Resucitation_Done', models.CharField(max_length=255, null=True)),
                ('Infant1_Gender', models.CharField(max_length=255, null=True)),
                ('Infant1_Weight', models.FloatField(null=True)),
                ('Infant1_Breast_Feeding', models.CharField(max_length=255, null=True)),
                ('Infant2_Baby_Cried', models.CharField(max_length=255, null=True)),
                ('Infant2_Gender', models.CharField(max_length=255, null=True)),
                ('Subcentre_ID', models.IntegerField(null=True)),
                ('Village_Name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
