# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-12 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rch', '0004_auto_20170219_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='rchchild',
            name='icds_case_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rchmother',
            name='icds_case_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
