# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.11.14 on 2018-07-30 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_merge_20180601_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.SQLLocation', to_field='location_id')),
                ('location_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.SQLLocation', to_field='location_id')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='locationrelation',
            unique_together=set([('location_a', 'location_b')]),
        ),
    ]
