# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 08:55
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_locationrelation_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqllocation',
            name='restricted_app_releases',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
