# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_locationrelation_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationtype',
            name='has_user',
        ),
    ]
