# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couchforms', '0005_index_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='unfinishedarchivestu',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
