state_codes = {
    # STOCode : (StateCode, STOStateName)
    'AN': ('35', 'Andman and Nicobar Islands'),
    'AP': ('28', 'Andhra Pradesh'),
    'AR': ('12', 'Arunachal Pradesh'),
    'AS': ('18', 'Assam'),
    'BI': ('10', 'Bihar'),
    'CG': ('22', 'Chhattisgarh'),
    'CH': ('4', 'Chandigarh'),
    'DD': ('25', 'Daman and  Diu'),
    'DL': ('7', 'Delhi'),
    'DN': ('26', 'Dadra and Nagar Haveli'),
    'GA': ('30', 'Goa'),
    'GU': ('24', 'Gujarat'),
    'HP': ('2', 'Himachal Pradesh'),
    'HR': ('6', 'Haryana'),
    'JH': ('20', 'Jharkhand'),
    'JK': ('1', 'Jammu and Kashmir'),
    'KA': ('29', 'Karnataka'),
    'KE': ('32', 'Kerala'),
    'LK': ('31', 'Lakshadweep'),
    'MG': ('17', 'Meghalaya'),
    'MH': ('27', 'Maharashtra'),
    'MN': ('14', 'Manipur'),
    'MP': ('23', 'Madhya Pradesh'),
    'MZ': ('15', 'Mizoram'),
    'NG': ('13', 'Nagaland'),
    'OR': ('21', 'Odisha'),
    'PD': ('34', 'Puducherry'),
    'PN': ('3', 'Punjab'),
    'RJ': ('8', 'Rajasthan'),
    'SK': ('11', 'Sikkim'),
    'TN': ('33', 'Tamil Nadu'),
    'TR': ('16', 'Tripura'),
    'TS': ('36', 'Telangana'),
    'UP': ('9', 'Uttar Pradesh'),
    'UR': ('5', 'Uttarakhand'),
    'WB': ('19', 'West bengal')
}

district_codes = {
    # DTOCode : (DistrictCode, DistrictName, STOCode, STOStateName)
    'ABD': ('515', 'Aurangabad-MH', 'MH', 'Maharashtra'),
    'ABM': ('515', 'Aurangabad MC', 'MH', 'Maharashtra'),
    'ABN': ('178', 'Ambedkar Nagar', 'UP', 'Uttar Pradesh'),
    'ADB': ('1017', 'Adilabad', 'TS', 'Telangana'),
    'AGB': ('237', 'Aurangabad-BI', 'BI', 'Bihar'),
    'AGL': ('384', 'Anugul', 'OR', 'Odisha'),
    'AGM': ('1015', 'Agar Malwa ', 'MP', 'Madhya Pradesh'),
    'AGR': ('146', 'Agra', 'UP', 'Uttar Pradesh'),
    'AHB': ('175', 'Allahabad', 'UP', 'Uttar Pradesh'),
    'AJM': ('119', 'Ajmer', 'RJ', 'Rajasthan'),
    'AKC': ('501', 'Akola MC', 'MH', 'Maharashtra'),
    'AKL': ('501', 'Akola', 'MH', 'Maharashtra'),
    'ALG': ('143', 'Aligarh', 'UP', 'Uttar Pradesh'),
    'ALW': ('104', 'Alwar', 'RJ', 'Rajasthan'),
    'AMB': ('70', 'Ambala', 'HR', 'Haryana'),
    'AMC': ('474', 'Ahmadabad MC', 'GU', 'Gujarat'),
    'AMD': ('474', 'Ahmadabad', 'GU', 'Gujarat'),
    'AML': ('480', 'Amreli', 'GU', 'Gujarat'),
    'AMR': ('64', 'Almora', 'UR', 'Uttarakhand'),
    'AMT': ('1006', 'Amethi', 'UP', 'Uttar Pradesh'),
    'ANC': ('522', 'Ahmednagar MC', 'MH', 'Maharashtra'),
    'AND': ('482', 'Anand', 'GU', 'Gujarat'),
    'ANE': ('650', 'Andheri East', 'MH', 'Maharashtra'),
    'ANG': ('522', 'Ahmadnagar', 'MH', 'Maharashtra'),
    'ANI': ('639', 'Andamans & Nicobars', 'AN', 'Andman and Nicobar Islands'),
    'ANP': ('461', 'Anuppur', 'MP', 'Madhya Pradesh'),
    'ANW': ('651', 'Andheri West', 'MH', 'Maharashtra'),
    'APR': ('553', 'Anantapur', 'AP', 'Andhra Pradesh'),
    'APZ': ('598', 'Alappuzha', 'KE', 'Kerala'),
    'ARP': ('465', 'Alirajpur', 'MP', 'Madhya Pradesh'),
    'ARR': ('209', 'Araria', 'BI', 'Bihar'),
    'ARW': ('236', 'Arwal', 'BI', 'Bihar'),
    'ARY': ('162', 'Auraiya', 'UP', 'Uttar Pradesh'),
    'ASB': ('1028', 'Asifabad', 'TS', 'Telangana'),
    'ASN': ('459', 'Ashoknagar', 'MP', 'Madhya Pradesh'),
    'ASR': ('49', 'Amritsar', 'PN', 'Punjab'),
    'ATN': ('14', 'Anantnag', 'JK', 'Jammu and Kashmir'),
    'AVC': ('503', 'Amravati MC', 'MH', 'Maharashtra'),
    'AVL': ('679', 'Arvalli', 'GU', 'Gujarat'),
    'AVR': ('503', 'Amravati', 'MH', 'Maharashtra'),
    'AZG': ('191', 'Azamgarh', 'UP', 'Uttar Pradesh'),
    'AZW': ('283', 'Aizawl', 'MZ', 'Mizoram'),
    'BAD': ('149', 'Budaun', 'UP', 'Uttar Pradesh'),
    'BAE': ('648', 'Bandra East', 'MH', 'Maharashtra'),
    'BAL': ('193', 'Ballia', 'UP', 'Uttar Pradesh'),
    'BAN': ('469', 'Banaskantha', 'GU', 'Gujarat'),
    'BAW': ('649', 'Bandra West', 'MH', 'Maharashtra'),
    'BBK': ('176', 'Barabanki', 'UP', 'Uttar Pradesh'),
    'BBR': ('658', 'Bail Bazar Road', 'MH', 'Maharashtra'),
    'BCL': ('1027', 'Bhadrachalam', 'TS', 'Telangana'),
    'BDB': ('668', 'Baloda Bazar', 'CG', 'Chhattisgarh'),
    'BDI': ('121', 'Bundi', 'RJ', 'Rajasthan'),
    'BDN': ('335', 'Barddhaman', 'WB', 'West bengal'),
    'BDR': ('558', 'Bidar', 'KA', 'Karnataka'),
    'BED': ('523', 'Bid', 'MH', 'Maharashtra'),
    'BEL': ('555', 'Belgaum', 'KA', 'Karnataka'),
    'BGH': ('370', 'Bargarh', 'OR', 'Odisha'),
    'BGL': ('224', 'Bhagalpur', 'BI', 'Bihar'),
    'BGM': ('2', 'Badgam', 'JK', 'Jammu and Kashmir'),
    'BGP': ('139', 'Baghpat', 'UP', 'Uttar Pradesh'),
    'BGS': ('222', 'Begusarai', 'BI', 'Bihar'),
    'BGW': ('63', 'Bageshwar', 'UR', 'Uttarakhand'),
    'BHD': ('420', 'Bhind', 'MP', 'Madhya Pradesh'),
    'BIJ': ('557', 'Bijapur', 'KA', 'Karnataka'),
    'BIL': ('406', 'Bilaspur-CG', 'CG', 'Chhattisgarh'),
    'BJN': ('134', 'Bijnor', 'UP', 'Uttar Pradesh'),
    'BJR': ('90', 'BJRM Chest Clinic', 'DL', 'Delhi'),
    'BJW': ('665', 'Bijwasan', 'DL', 'Delhi'),
    'BKN': ('101', 'Bikaner', 'RJ', 'Rajasthan'),
    'BKR': ('339', 'Bankura', 'WB', 'West bengal'),
    'BKS': ('677', 'Baksa', 'AS', 'Assam'),
    'BLA': ('8', 'Baramula', 'JK', 'Jammu and Kashmir'),
    'BLC': ('572', 'Bangalore City', 'KA', 'Karnataka'),
    'BLD': ('500', 'Buldana', 'MH', 'Maharashtra'),
    'BLG': ('457', 'Balaghat', 'MP', 'Madhya Pradesh'),
    'BLK': ('556', 'Bagalkot', 'KA', 'Karnataka'),
    'BLP': ('406', 'Bilaspur-HP', 'HP', 'Himachal Pradesh'),
    'BLR': ('583', 'Bangalore Rural', 'KA', 'Karnataka'),
    'BLS': ('142', 'Bulandshahar', 'UP', 'Uttar Pradesh'),
    'BLU': ('572', 'Bangalore Urban', 'KA', 'Karnataka'),
    'BLW': ('122', 'Bhilwara', 'RJ', 'Rajasthan'),
    'BLY': ('565', 'Bellary', 'KA', 'Karnataka'),
    'BMC': ('386', 'Bhubaneshwar MC', 'OR', 'Odisha'),
    'BMT': ('669', 'Bemetara', 'CG', 'Chhattisgarh'),
    'BNA': ('170', 'Banda', 'UP', 'Uttar Pradesh'),
    'BND': ('506', 'Bhandara', 'MH', 'Maharashtra'),
    'BNG': ('319', 'Bongaigaon', 'AS', 'Assam'),
    'BNK': ('225', 'Banka', 'BI', 'Bihar'),
    'BOK': ('355', 'Bokaro', 'JH', 'Jharkhand'),
    'BOL': ('393', 'Balangir', 'OR', 'Odisha'),
    'BOU': ('391', 'Baudh', 'OR', 'Odisha'),
    'BPL': ('444', 'Bhopal', 'MP', 'Madhya Pradesh'),
    'BPR': ('275', 'Bishnupur', 'MN', 'Manipur'),
    'BPT': ('303', 'Barpeta', 'AS', 'Assam'),
    'BRB': ('334', 'Birbhum', 'WB', 'West bengal'),
    'BRC': ('180', 'Bahraich', 'UP', 'Uttar Pradesh'),
    'BRH': ('488', 'Bharuch', 'GU', 'Gujarat'),
    'BRK': ('378', 'Bhadrak', 'OR', 'Odisha'),
    'BRL': ('150', 'Bareilly', 'UP', 'Uttar Pradesh'),
    'BRM': ('115', 'Barmer', 'RJ', 'Rajasthan'),
    'BRN': ('128', 'Baran', 'RJ', 'Rajasthan'),
    'BRP': ('182', 'Balrampur', 'UP', 'Uttar Pradesh'),
    'BRW': ('441', 'Barwani', 'MP', 'Madhya Pradesh'),
    'BSA': ('90', 'BSA Chest Clinic', 'DL', 'Delhi'),
    'BSR': ('377', 'Baleshwar', 'OR', 'Odisha'),
    'BST': ('185', 'Basti', 'UP', 'Uttar Pradesh'),
    'BSW': ('125', 'Banswara', 'RJ', 'Rajasthan'),
    'BTD': ('46', 'Bathinda', 'PN', 'Punjab'),
    'BTL': ('447', 'Betul', 'MP', 'Madhya Pradesh'),
    'BTP': ('105', 'Bharatpur', 'RJ', 'Rajasthan'),
    'BTR': ('414', 'Bastar', 'CG', 'Chhattisgarh'),
    'BVD': ('517', 'Bhiwandi Nizampur', 'MH', 'Maharashtra'),
    'BVI': ('655', 'Borivali', 'MH', 'Maharashtra'),
    'BVN': ('481', 'Bhavnagar', 'GU', 'Gujarat'),
    'BWN': ('81', 'Bhiwani', 'HR', 'Haryana'),
    'BXR': ('232', 'Buxar', 'BI', 'Bihar'),
    'CAL': ('342', 'Kolkata', 'WB', 'West bengal'),
    'CAP': ('685', 'Alipore', 'WB', 'West bengal'),
    'CBB': ('686', 'Bagbazar', 'WB', 'West bengal'),
    'CBE': ('614', 'Coimbatore', 'TN', 'Tamil Nadu'),
    'CBL': ('687', 'Behala', 'WB', 'West bengal'),
    'CCP': ('274', 'Churachandpur', 'MN', 'Manipur'),
    'CDC': ('90', 'CD Chest Clinic', 'DL', 'Delhi'),
    'CDG': ('566', 'Chitradurga', 'KA', 'Karnataka'),
    'CDL': ('280', 'Chandel', 'MN', 'Manipur'),
    'CDP': ('551', 'Cuddapah', 'AP', 'Andhra Pradesh'),
    'CDU': ('196', 'Chandauli', 'UP', 'Uttar Pradesh'),
    'CDW': ('455', 'Chhindwara', 'MP', 'Madhya Pradesh'),
    'CHA': ('259', 'Changlang', 'AR', 'Arunachal Pradesh'),
    'CHB': ('23', 'Chamba', 'HP', 'Himachal Pradesh'),
    'CHD': ('55', 'Chandigarh', 'CH', 'Chandigarh'),
    'CHG': ('678', 'Chirang', 'AS', 'Assam'),
    'CHK': ('570', 'Chikmagalur', 'KA', 'Karnataka'),
    'CHR': ('316', 'Cachar', 'AS', 'Assam'),
    'CHT': ('554', 'Chittoor', 'AP', 'Andhra Pradesh'),
    'CHZ': ('688', 'Hazi', 'WB', 'West bengal'),
    'CKB': ('582', 'Chikkaballapur', 'KA', 'Karnataka'),
    'CLB': ('641', 'Colaba', 'MH', 'Maharashtra'),
    'CMB': ('661', 'Chembur', 'MH', 'Maharashtra'),
    'CMK': ('689', 'Maniktala', 'WB', 'West bengal'),
    'CML': ('57', 'Chamoli', 'UR', 'Uttarakhand'),
    'CMP': ('284', 'Champhai', 'MZ', 'Mizoram'),
    'CMS': ('690', 'Manshatala', 'WB', 'West bengal'),
    'CMT': ('691', 'MTMTB', 'WB', 'West bengal'),
    'CNC': ('1001', 'Centeral Chennai', 'TN', 'Tamil Nadu'),
    'CNI': ('603', 'Chennai', 'TN', 'Tamil Nadu'),
    'CNN': ('1000', 'North Chennai', 'TN', 'Tamil Nadu'),
    'CNS': ('1002', 'South Chennai', 'TN', 'Tamil Nadu'),
    'CPE': ('204', 'Purba Champaran', 'BI', 'Bihar'),
    'CPR': ('509', 'Chandrapur', 'MH', 'Maharashtra'),
    'CPV': ('65', 'Champawat', 'UR', 'Uttarakhand'),
    'CPW': ('203', 'Pashchim Champaran', 'BI', 'Bihar'),
    'CRK': ('171', 'Chitrakoot', 'UP', 'Uttar Pradesh'),
    'CRN': ('578', 'Chamarajanagar', 'KA', 'Karnataka'),
    'CRU': ('102', 'Churu', 'RJ', 'Rajasthan'),
    'CSB': ('692', 'Strand Bank', 'WB', 'West bengal'),
    'CTG': ('693', 'Tollygunge', 'WB', 'West bengal'),
    'CTK': ('381', 'Cuttack', 'OR', 'Odisha'),
    'CTN': ('659', 'Centenary', 'MH', 'Maharashtra'),
    'CTP': ('425', 'Chhatarpur', 'MP', 'Madhya Pradesh'),
    'CTR': ('694', 'Tangra', 'WB', 'West bengal'),
    'CUD': ('621', 'Cuddalore', 'TN', 'Tamil Nadu'),
    'CUP': ('486', 'Chhota Udepur', 'GU', 'Gujarat'),
    'DBB': ('301', 'Dhubri', 'AS', 'Assam'),
    'DBD': ('354', 'Dhanbad', 'JH', 'Jharkhand'),
    'DBG': ('215', 'Darbhanga', 'BI', 'Bihar'),
    'DBR': ('310', 'Dibrugarh', 'AS', 'Assam'),
    'DDJ': ('331', 'Dakshin Dinajpur', 'WB', 'West bengal'),
    'DDN': ('60', 'Dehradun', 'UR', 'Uttarakhand'),
    'DDR': ('453', 'Dindori', 'MP', 'Madhya Pradesh'),
    'DDU': ('96', 'DDU Chest Clinic', 'DL', 'Delhi'),
    'DFI': ('97', 'Damien Foundation India Trust', 'DL', 'Delhi'),
    'DGH': ('350', 'Deoghar', 'JH', 'Jharkhand'),
    'DGL': ('616', 'Dindigul', 'TN', 'Tamil Nadu'),
    'DGP': ('124', 'Dungarpur', 'RJ', 'Rajasthan'),
    'DGR': ('373', 'Debagarh', 'OR', 'Odisha'),
    'DHA': ('562', 'Dharwad', 'KA', 'Karnataka'),
    'DHC': ('498', 'Dhule MC', 'MH', 'Maharashtra'),
    'DHD': ('485', 'Dahod', 'GU', 'Gujarat'),
    'DHL': ('498', 'Dhule', 'MH', 'Maharashtra'),
    'DHR': ('438', 'Dhar', 'MP', 'Madhya Pradesh'),
    'DHS': ('656', 'Dahisar', 'MH', 'Maharashtra'),
    'DIU': ('494', 'Diu', 'DD', 'Daman and  Diu'),
    'DIV': ('255', 'Dibang Valley', 'AR', 'Arunachal Pradesh'),
    'DJL': ('327', 'Darjiling', 'WB', 'West bengal'),
    'DKN': ('575', 'Dakshina Kannada', 'KA', 'Karnataka'),
    'DLI': ('291', 'Dhalai', 'TR', 'Tripura'),
    'DLP': ('106', 'Dhaulpur', 'RJ', 'Rajasthan'),
    'DMH': ('428', 'Damoh', 'MP', 'Madhya Pradesh'),
    'DMJ': ('308', 'Dhemaji', 'AS', 'Assam'),
    'DMK': ('362', 'Dumka', 'JH', 'Jharkhand'),
    'DMN': ('495', 'Daman', 'DD', 'Daman and  Diu'),
    'DNG': ('489', 'The Dangs', 'GU', 'Gujarat'),
    'DNK': ('383', 'Dhenkanal', 'OR', 'Odisha'),
    'DNV': ('496', 'Dadra & Nagar Haveli', 'DN', 'Dadra and Nagar Haveli'),
    'DOD': ('16', 'Doda', 'JK', 'Jammu and Kashmir'),
    'DOR': ('190', 'Deoria', 'UP', 'Uttar Pradesh'),
    'DPI': ('606', 'Dharmapuri', 'TN', 'Tamil Nadu'),
    'DPR': ('268', 'Dimapur', 'NG', 'Nagaland'),
    'DRG': ('325', 'Darrang', 'AS', 'Assam'),
    'DSA': ('109', 'Dausa', 'RJ', 'Rajasthan'),
    'DTA': ('422', 'Datia', 'MP', 'Madhya Pradesh'),
    'DTR': ('412', 'Dhamtari', 'CG', 'Chhattisgarh'),
    'DTW': ('416', 'South Bastar Dantewada', 'CG', 'Chhattisgarh'),
    'DUR': ('409', 'Durg', 'CG', 'Chhattisgarh'),
    'DVG': ('567', 'Davanagere', 'KA', 'Karnataka'),
    'DWK': ('681', 'Devbhumi dwarka', 'GU', 'Gujarat'),
    'DWS': ('437', 'Dewas', 'MP', 'Madhya Pradesh'),
    'EGH': ('294', 'East Garo Hills', 'MG', 'Meghalaya'),
    'EGV': ('545', 'East Godavari', 'AP', 'Andhra Pradesh'),
    'EKA': ('247', 'East Kameng', 'AR', 'Arunachal Pradesh'),
    'EKH': ('298', 'East Khasi Hills', 'MG', 'Meghalaya'),
    'ENK': ('595', 'Ernakulam', 'KE', 'Kerala'),
    'ERD': ('612', 'Erode', 'TN', 'Tamil Nadu'),
    'ESI': ('253', 'East Siang', 'AR', 'Arunachal Pradesh'),
    'EST': ('244', 'East District', 'SK', 'Sikkim'),
    'ETA': ('201', 'Etah', 'UP', 'Uttar Pradesh'),
    'ETW': ('161', 'Etawah', 'UP', 'Uttar Pradesh'),
    'FAI': ('177', 'Faizabad', 'UP', 'Uttar Pradesh'),
    'FBD': ('88', 'Faridabad', 'HR', 'Haryana'),
    'FER': ('147', 'Firozabad', 'UP', 'Uttar Pradesh'),
    'FGS': ('40', 'Fatehgarh Sahib', 'PN', 'Punjab'),
    'FKB': ('159', 'Farrukhabad', 'UP', 'Uttar Pradesh'),
    'FRK': ('45', 'Faridkot', 'PN', 'Punjab'),
    'FTB': ('78', 'Fatehabad', 'HR', 'Haryana'),
    'FTP': ('172', 'Fatehpur', 'UP', 'Uttar Pradesh'),
    'FZK': ('676', 'Fazilka', 'PN', 'Punjab'),
    'FZP': ('43', 'Firozpur', 'PN', 'Punjab'),
    'GBG': ('579', 'Gulbarga', 'KA', 'Karnataka'),
    'GBN': ('141', 'Gautam Budh Nagar', 'UP', 'Uttar Pradesh'),
    'GDA': ('351', 'Godda', 'JH', 'Jharkhand'),
    'GDG': ('561', 'Gadag', 'KA', 'Karnataka'),
    'GDL': ('508', 'Gadchiroli', 'MH', 'Maharashtra'),
    'GDP': ('35', 'Gurdaspur', 'PN', 'Punjab'),
    'GDW': ('1029', 'Gadwal', 'TS', 'Telangana'),
    'GDY': ('507', 'Gondiya', 'MH', 'Maharashtra'),
    'GGN': ('99', 'Ganganagar', 'RJ', 'Rajasthan'),
    'GHW': ('293', 'West Garo Hills', 'MG', 'Meghalaya'),
    'GJM': ('388', 'Ganjam', 'OR', 'Odisha'),
    'GJP': ('389', 'Gajapati', 'OR', 'Odisha'),
    'GKP': ('662', 'Ghatkopar', 'MH', 'Maharashtra'),
    'GLB': ('91', 'Gulabi Bagh', 'DL', 'Delhi'),
    'GLP': ('302', 'Goalpara', 'AS', 'Assam'),
    'GLR': ('421', 'Gwalior', 'MP', 'Madhya Pradesh'),
    'GLT': ('313', 'Golaghat', 'AS', 'Assam'),
    'GML': ('366', 'Gumla', 'JH', 'Jharkhand'),
    'GMT': ('1013', 'Gomati', 'TR', 'Tripura'),
    'GND': ('183', 'Gonda', 'UP', 'Uttar Pradesh'),
    'GNR': ('473', 'Gandhinagar', 'GU', 'Gujarat'),
    'GON': ('585', 'North Goa', 'GA', 'Goa'),
    'GOS': ('586', 'South Goa', 'GA', 'Goa'),
    'GPG': ('217', 'Gopalganj', 'BI', 'Bihar'),
    'GRB': ('670', 'Gariyaband', 'CG', 'Chhattisgarh'),
    'GRD': ('349', 'Giridih', 'JH', 'Jharkhand'),
    'GRG': ('652', 'Goregaon', 'MH', 'Maharashtra'),
    'GRH': ('346', 'Garhwa', 'JH', 'Jharkhand'),
    'GRP': ('188', 'Gorakhpur', 'UP', 'Uttar Pradesh'),
    'GRW': ('61', 'Garhwal', 'UR', 'Uttarakhand'),
    'GSN': ('682', 'Gir Somnath', 'GU', 'Gujarat'),
    'GTB': ('92', 'GTB Chest Clinic', 'DL', 'Delhi'),
    'GTR': ('642', 'Grant Road', 'MH', 'Maharashtra'),
    'GUN': ('458', 'Guna', 'MP', 'Madhya Pradesh'),
    'GUR': ('86', 'Gurgaon', 'HR', 'Haryana'),
    'GVN': ('660', 'Govandi', 'MH', 'Maharashtra'),
    'GYA': ('238', 'Gaya', 'BI', 'Bihar'),
    'GZA': ('140', 'Ghaziabad', 'UP', 'Uttar Pradesh'),
    'GZP': ('195', 'Ghazipur', 'UP', 'Uttar Pradesh'),
    'HAN': ('100', 'Hanumangarh', 'RJ', 'Rajasthan'),
    'HAR': ('448', 'Harda', 'MP', 'Madhya Pradesh'),
    'HAS': ('574', 'Hassan', 'KA', 'Karnataka'),
    'HCC': ('93', 'Hedgewar Chest Clinic', 'DL', 'Delhi'),
    'HDO': ('155', 'Hardoi', 'UP', 'Uttar Pradesh'),
    'HGL': ('338', 'Hugli', 'WB', 'West bengal'),
    'HLK': ('318', 'Hailakandi', 'AS', 'Assam'),
    'HMP': ('28', 'Hamirpur-UP', 'UP', 'Uttar Pradesh'),
    'HMR': ('28', 'Hamirpur-HP', 'HP', 'Himachal Pradesh'),
    'HNL': ('512', 'Hingoli', 'MH', 'Maharashtra'),
    'HPR': ('1007', 'Hapur', 'UP', 'Uttar Pradesh'),
    'HRA': ('341', 'Haora', 'WB', 'West bengal'),
    'HRD': ('68', 'Hardwar', 'UR', 'Uttarakhand'),
    'HSB': ('449', 'Hoshangabad', 'MP', 'Madhya Pradesh'),
    'HSP': ('38', 'Hoshiarpur', 'PN', 'Punjab'),
    'HSR': ('80', 'Hisar', 'HR', 'Haryana'),
    'HTR': ('144', 'Hathras', 'UP', 'Uttar Pradesh'),
    'HVR': ('564', 'Haveri', 'KA', 'Karnataka'),
    'HYD': ('1021', 'Hyderabad', 'TS', 'Telangana'),
    'HZB': ('360', 'Hazaribagh', 'JH', 'Jharkhand'),
    'IDK': ('596', 'Idukki', 'KE', 'Kerala'),
    'IDR': ('439', 'Indore', 'MP', 'Madhya Pradesh'),
    'IME': ('278', 'Imphal East', 'MN', 'Manipur'),
    'IMW': ('277', 'Imphal West', 'MN', 'Manipur'),
    'JAL': ('165', 'Jalaun', 'UP', 'Uttar Pradesh'),
    'JAM': ('21', 'Jammu', 'JK', 'Jammu and Kashmir'),
    'JBA': ('464', 'Jhabua', 'MP', 'Madhya Pradesh'),
    'JBD': ('235', 'Jehanabad', 'BI', 'Bihar'),
    'JBP': ('451', 'Jabalpur', 'MP', 'Madhya Pradesh'),
    'JDP': ('113', 'Jodhpur', 'RJ', 'Rajasthan'),
    'JDW': ('95', 'Jhandewalan', 'DL', 'Delhi'),
    'JGC': ('405', 'Janjgir', 'CG', 'Chhattisgarh'),
    'JGY': ('1030', 'Jagityal', 'TS', 'Telangana'),
    'JHP': ('402', 'Jashpur', 'CG', 'Chhattisgarh'),
    'JHT': ('312', 'Jorhat', 'AS', 'Assam'),
    'JJN': ('103', 'Jhunjhunun', 'RJ', 'Rajasthan'),
    'JJP': ('382', 'Jajapur', 'OR', 'Odisha'),
    'JJR': ('83', 'Jhajjar', 'HR', 'Haryana'),
    'JLC': ('499', 'Jalgaon MC', 'MH', 'Maharashtra'),
    'JLD': ('37', 'Jalandhar', 'PN', 'Punjab'),
    'JLG': ('499', 'Jalgaon', 'MH', 'Maharashtra'),
    'JLN': ('514', 'Jalna', 'MH', 'Maharashtra'),
    'JLR': ('116', 'Jalore', 'RJ', 'Rajasthan'),
    'JLW': ('129', 'Jhalawar', 'RJ', 'Rajasthan'),
    'JMD': ('477', 'Jamnagar', 'GU', 'Gujarat'),
    'JMI': ('240', 'Jamui', 'BI', 'Bihar'),
    'JND': ('77', 'Jind', 'HR', 'Haryana'),
    'JNG': ('1031', 'Janagaon', 'TS', 'Telangana'),
    'JNH': ('299', 'Jaintia Hills', 'MG', 'Meghalaya'),
    'JNP': ('194', 'Jaunpur', 'UP', 'Uttar Pradesh'),
    'JNS': ('166', 'Jhansi', 'UP', 'Uttar Pradesh'),
    'JPC': ('110', 'Jaipur DTC II', 'RJ', 'Rajasthan'),
    'JPG': ('328', 'Jalpaiguri', 'WB', 'West bengal'),
    'JPN': ('137', 'Jyotiba Phule Nagar', 'UP', 'Uttar Pradesh'),
    'JPR': ('110', 'Jaipur', 'RJ', 'Rajasthan'),
    'JSG': ('371', 'Jharsuguda', 'OR', 'Odisha'),
    'JSK': ('1032', 'Jayashankar', 'TS', 'Telangana'),
    'JSM': ('114', 'Jaisalmer', 'RJ', 'Rajasthan'),
    'JSP': ('380', 'Jagatsinghapur', 'OR', 'Odisha'),
    'JTR': ('363', 'Jamtara', 'JH', 'Jharkhand'),
    'JUN': ('479', 'Junagadh', 'GU', 'Gujarat'),
    'KAG': ('314', 'Karbi Anglong', 'AS', 'Assam'),
    'KAR': ('4', 'Kargil', 'JK', 'Jammu and Kashmir'),
    'KBR': ('329', 'Koch Bihar', 'WB', 'West bengal'),
    'KCC': ('91', 'Kingsway', 'DL', 'Delhi'),
    'KDA': ('483', 'Kheda', 'GU', 'Gujarat'),
    'KDG': ('671', 'Kondagaon', 'CG', 'Chhattisgarh'),
    'KDM': ('390', 'Kandhamal', 'OR', 'Odisha'),
    'KDP': ('379', 'Kendrapara', 'OR', 'Odisha'),
    'KDR': ('348', 'Kodarma', 'JH', 'Jharkhand'),
    'KDV': ('654', 'Kandivali', 'MH', 'Maharashtra'),
    'KDW': ('466', 'Khandwa', 'MP', 'Madhya Pradesh'),
    'KGN': ('440', 'Khargone', 'MP', 'Madhya Pradesh'),
    'KGR': ('24', 'Kangra', 'HP', 'Himachal Pradesh'),
    'KHA': ('223', 'Khagaria', 'BI', 'Bihar'),
    'KHN': ('365', 'Khunti', 'JH', 'Jharkhand'),
    'KHW': ('1010', 'Khowai', 'TR', 'Tripura'),
    'KIS': ('210', 'Kishanganj', 'BI', 'Bihar'),
    'KJR': ('300', 'Kokrajhar', 'AS', 'Assam'),
    'KKM': ('633', 'Kanniyakumari', 'TN', 'Tamil Nadu'),
    'KKR': ('72', 'Kurukshetra', 'HR', 'Haryana'),
    'KLH': ('395', 'Kalahandi', 'OR', 'Odisha'),
    'KLM': ('600', 'Kollam', 'KE', 'Kerala'),
    'KLP': ('530', 'Kolhapur', 'MH', 'Maharashtra'),
    'KLS': ('282', 'Kolasib', 'MZ', 'Mizoram'),
    'KLU': ('26', 'Kullu', 'HP', 'Himachal Pradesh'),
    'KMA': ('269', 'Kohima', 'NG', 'Nagaland'),
    'KMC': ('530', 'Kolhapur MC', 'MH', 'Maharashtra'),
    'KMM': ('1026', 'Khammam', 'TS', 'Telangana'),
    'KMP': ('321', 'Kamrup', 'AS', 'Assam'),
    'KMR': ('1019', 'Karimnagar', 'TS', 'Telangana'),
    'KMU': ('233', 'Kaimur', 'BI', 'Bihar'),
    'KNG': ('607', 'Krishnagiri', 'TN', 'Tamil Nadu'),
    'KNJ': ('375', 'Kendujhar', 'OR', 'Odisha'),
    'KNK': ('413', 'Uttar Bastar Kanker', 'CG', 'Chhattisgarh'),
    'KNL': ('74', 'Karnal', 'HR', 'Haryana'),
    'KNN': ('160', 'Kannauj', 'UP', 'Uttar Pradesh'),
    'KNR': ('34', 'Kinnaur', 'HP', 'Himachal Pradesh'),
    'KNU': ('589', 'Kannur', 'KE', 'Kerala'),
    'KOD': ('576', 'Kodagu', 'KA', 'Karnataka'),
    'KOL': ('581', 'Kolar', 'KA', 'Karnataka'),
    'KOT': ('597', 'Kottayam', 'KE', 'Kerala'),
    'KPD': ('163', 'Kanpur Dehat', 'UP', 'Uttar Pradesh'),
    'KPH': ('264', 'Kiphire', 'NG', 'Nagaland'),
    'KPM': ('604', 'Kancheepuram', 'TN', 'Tamil Nadu'),
    'KPN': ('164', 'Kanpur Nagar', 'UP', 'Uttar Pradesh'),
    'KPP': ('560', 'Koppal', 'KA', 'Karnataka'),
    'KPT': ('36', 'Kapurthala', 'PN', 'Punjab'),
    'KRA': ('107', 'Karauli', 'RJ', 'Rajasthan'),
    'KRB': ('404', 'Korba', 'CG', 'Chhattisgarh'),
    'KRD': ('386', 'Khordha', 'OR', 'Odisha'),
    'KRI': ('153', 'Kheri', 'UP', 'Uttar Pradesh'),
    'KRL': ('657', 'Kurla', 'MH', 'Maharashtra'),
    'KRN': ('202', 'Kanshiram Nagar', 'UP', 'Uttar Pradesh'),
    'KRP': ('398', 'Koraput', 'OR', 'Odisha'),
    'KRR': ('617', 'Karur', 'TN', 'Tamil Nadu'),
    'KRY': ('1033', 'Kamareddy', 'TS', 'Telangana'),
    'KSB': ('174', 'Kaushambi', 'UP', 'Uttar Pradesh'),
    'KSG': ('588', 'Kasaragod', 'KE', 'Kerala'),
    'KSN': ('189', 'Kushinagar', 'UP', 'Uttar Pradesh'),
    'KTA': ('127', 'Kota', 'RJ', 'Rajasthan'),
    'KTC': ('468', 'Kachchh', 'GU', 'Gujarat'),
    'KTH': ('212', 'Katihar', 'BI', 'Bihar'),
    'KTL': ('73', 'Kaithal', 'HR', 'Haryana'),
    'KTN': ('450', 'Katni', 'MP', 'Madhya Pradesh'),
    'KUA': ('7', 'Kathua', 'JK', 'Jammu and Kashmir'),
    'KUP': ('1', 'Kupwara', 'JK', 'Jammu and Kashmir'),
    'KWD': ('407', 'Kabirdham (Kawardha)', 'CG', 'Chhattisgarh'),
    'KWL': ('92', 'Karawal Nagar', 'DL', 'Delhi'),
    'KXJ': ('317', 'Karimganj', 'AS', 'Assam'),
    'KZK': ('591', 'Kozhikode', 'KE', 'Kerala'),
    'LDN': ('41', 'Ludhiana', 'PN', 'Punjab'),
    'LEH': ('3', 'Leh', 'JK', 'Jammu and Kashmir'),
    'LGT': ('287', 'Lawngtlai', 'MZ', 'Mizoram'),
    'LHD': ('356', 'Lohardaga', 'JH', 'Jharkhand'),
    'LKD': ('587', 'Lakshadweep', 'LK', 'Lakshadweep'),
    'LKR': ('307', 'Lakhimpur', 'AS', 'Assam'),
    'LKS': ('227', 'Lakhisarai', 'BI', 'Bihar'),
    'LLG': ('263', 'Longleng', 'NG', 'Nagaland'),
    'LLI': ('286', 'Lunglei', 'MZ', 'Mizoram'),
    'LLP': ('167', 'Lalitpur', 'UP', 'Uttar Pradesh'),
    'LNC': ('95', 'LN Chest Clinic', 'DL', 'Delhi'),
    'LNO': ('157', 'Lucknow', 'UP', 'Uttar Pradesh'),
    'LOH': ('257', 'Lohit', 'AR', 'Arunachal Pradesh'),
    'LRS': ('97', 'LRS', 'DL', 'Delhi'),
    'LSP': ('25', 'Lahul & Spiti', 'HP', 'Himachal Pradesh'),
    'LSU': ('249', 'Lower Subansiri', 'AR', 'Arunachal Pradesh'),
    'LTH': ('359', 'Lathehar', 'JH', 'Jharkhand'),
    'LTR': ('524', 'Latur', 'MH', 'Maharashtra'),
    'MAI': ('148', 'Mainpuri', 'UP', 'Uttar Pradesh'),
    'MAU': ('192', 'Mau', 'UP', 'Uttar Pradesh'),
    'MBB': ('1034', 'Mahabubabad', 'TS', 'Telangana'),
    'MBD': ('333', 'Murshidabad', 'WB', 'West bengal'),
    'MBR': ('1023', 'Mahbubnagar', 'TS', 'Telangana'),
    'MCR': ('1035', 'Mancherial', 'TS', 'Telangana'),
    'MDB': ('207', 'Madhubani', 'BI', 'Bihar'),
    'MDC': ('1036', 'Medchal', 'TS', 'Telangana'),
    'MDK': ('1020', 'Medak', 'TS', 'Telangana'),
    'MDL': ('454', 'Mandla', 'MP', 'Madhya Pradesh'),
    'MDP': ('213', 'Madhepura', 'BI', 'Bihar'),
    'MDS': ('433', 'Mandsaur', 'MP', 'Madhya Pradesh'),
    'MDU': ('627', 'Madurai', 'TN', 'Tamil Nadu'),
    'MDY': ('573', 'Mandya', 'KA', 'Karnataka'),
    'MGA': ('42', 'Moga', 'PN', 'Punjab'),
    'MGL': ('672', 'Mungeli', 'CG', 'Chhattisgarh'),
    'MHB': ('169', 'Mahoba', 'UP', 'Uttar Pradesh'),
    'MHG': ('187', 'Maharajganj', 'UP', 'Uttar Pradesh'),
    'MHL': ('52', 'Mohali', 'PN', 'Punjab'),
    'MHN': ('84', 'Mahendragarh', 'HR', 'Haryana'),
    'MHS': ('684', 'Mahisagar', 'GU', 'Gujarat'),
    'MKG': ('399', 'Malkangiri', 'OR', 'Odisha'),
    'MKK': ('265', 'Mokokchung', 'NG', 'Nagaland'),
    'MKS': ('44', 'Muktsar', 'PN', 'Punjab'),
    'MLD': ('332', 'Maldah', 'WB', 'West bengal'),
    'MLG': ('516', 'Malegoan Corporation', 'MH', 'Maharashtra'),
    'MMD': ('411', 'Mahasamund', 'CG', 'Chhattisgarh'),
    'MMT': ('281', 'Mamit', 'MZ', 'Mizoram'),
    'MND': ('27', 'Mandi', 'HP', 'Himachal Pradesh'),
    'MNE': ('345', 'Medinipur East', 'WB', 'West bengal'),
    'MNH': ('98', 'MNCH Chest Clinic', 'DL', 'Delhi'),
    'MNS': ('47', 'Mansa-PN', 'PN', 'Punjab'),
    'MNW': ('344', 'Medinipur West', 'WB', 'West bengal'),
    'MON': ('261', 'Mon', 'NG', 'Nagaland'),
    'MPM': ('592', 'Malappuram', 'KE', 'Kerala'),
    'MRB': ('683', 'Morbi', 'GU', 'Gujarat'),
    'MRD': ('135', 'Moradabad', 'UP', 'Uttar Pradesh'),
    'MRG': ('304', 'Marigaon', 'AS', 'Assam'),
    'MRN': ('419', 'Morena', 'MP', 'Madhya Pradesh'),
    'MRT': ('138', 'Meerut', 'UP', 'Uttar Pradesh'),
    'MSN': ('471', 'Mahesana', 'GU', 'Gujarat'),
    'MTI': ('96', 'Moti Nagar', 'DL', 'Delhi'),
    'MTR': ('145', 'Mathura', 'UP', 'Uttar Pradesh'),
    'MUL': ('664', 'Mulund', 'MH', 'Maharashtra'),
    'MUN': ('226', 'Munger', 'BI', 'Bihar'),
    'MWT': ('87', 'Mewat', 'HR', 'Haryana'),
    'MYB': ('376', 'Mayurbhanj', 'OR', 'Odisha'),
    'MYS': ('577', 'Mysore', 'KA', 'Karnataka'),
    'MZ1': ('519', 'Mumbai Zone1', 'MH', 'Maharashtra'),
    'MZ2': ('519', 'Mumbai Zone2', 'MH', 'Maharashtra'),
    'MZ3': ('519', 'Mumbai Zone3', 'MH', 'Maharashtra'),
    'MZ4': ('519', 'Mumbai Zone4', 'MH', 'Maharashtra'),
    'MZ5': ('519', 'Mumbai Zone5', 'MH', 'Maharashtra'),
    'MZ6': ('519', 'Mumbai Zone6', 'MH', 'Maharashtra'),
    'MZF': ('216', 'Muzaffarpur', 'BI', 'Bihar'),
    'MZN': ('133', 'Muzaffarnagar', 'UP', 'Uttar Pradesh'),
    'MZP': ('199', 'Mirzapur', 'UP', 'Uttar Pradesh'),
    'NAG': ('622', 'Nagapattinam', 'TN', 'Tamil Nadu'),
    'NAM': ('611', 'Namakkal', 'TN', 'Tamil Nadu'),
    'NCB': ('638', 'Nicobars', 'AN', 'Andman and Nicobar Islands'),
    'NCH': ('327', 'North Cachar Hills', 'AS', 'Assam'),
    'NDA': ('336', 'Nadia', 'WB', 'West bengal'),
    'NDB': ('497', 'Nandurbar', 'MH', 'Maharashtra'),
    'NDC': ('511', 'Nanded Waghela MC', 'MH', 'Maharashtra'),
    'NDD': ('511', 'Nanded', 'MH', 'Maharashtra'),
    'NDM': ('94', 'NDMC', 'DL', 'Delhi'),
    'NGC': ('505', 'Nagpur MC', 'MH', 'Maharashtra'),
    'NGD': ('1024', 'Nalgonda', 'TS', 'Telangana'),
    'NGN': ('305', 'Nagaon', 'AS', 'Assam'),
    'NGR': ('112', 'Nagaur', 'RJ', 'Rajasthan'),
    'NIL': ('613', 'The Nilgiris', 'TN', 'Tamil Nadu'),
    'NKN': ('1037', 'Nagarkurnool', 'TS', 'Telangana'),
    'NLA': ('90', 'Narela', 'DL', 'Delhi'),
    'NLB': ('323', 'Nalbari', 'AS', 'Assam'),
    'NLD': ('229', 'Nalanda', 'BI', 'Bihar'),
    'NLR': ('550', 'Nellore', 'AP', 'Andhra Pradesh'),
    'NMA': ('1005', 'North & Middle Andaman', 'AN', 'Andman and Nicobar Islands'),
    'NMC': ('432', 'Neemuch', 'MP', 'Madhya Pradesh'),
    'NMD': ('487', 'Narmada', 'GU', 'Gujarat'),
    'NML': ('1038', 'Nirmal', 'TS', 'Telangana'),
    'NNT': ('66', 'Nainital', 'UR', 'Uttarakhand'),
    'NPG': ('337', 'North 24 Parganas', 'WB', 'West bengal'),
    'NRP': ('397', 'Nabarangapur', 'OR', 'Odisha'),
    'NRU': ('98', 'Nehru Nagar', 'DL', 'Delhi'),
    'NSC': ('516', 'Nashik Corp', 'MH', 'Maharashtra'),
    'NSK': ('516', 'Nashik', 'MH', 'Maharashtra'),
    'NSP': ('452', 'Narsinghpur', 'MP', 'Madhya Pradesh'),
    'NSR': ('39', 'Nawanshahr', 'PN', 'Punjab'),
    'NTH': ('241', 'North District', 'SK', 'Sikkim'),
    'NUP': ('394', 'Nuapada', 'OR', 'Odisha'),
    'NVM': ('517', 'Navi Mumbai', 'MH', 'Maharashtra'),
    'NVS': ('490', 'Navsari', 'GU', 'Gujarat'),
    'NWD': ('239', 'Nawada', 'BI', 'Bihar'),
    'NYG': ('385', 'Nayagarh', 'OR', 'Odisha'),
    'NZD': ('1018', 'Nizamabad', 'TS', 'Telangana'),
    'OBD': ('525', 'Osmanabad', 'MH', 'Maharashtra'),
    'PAN': ('426', 'Panna', 'MP', 'Madhya Pradesh'),
    'PAT': ('470', 'Patan', 'GU', 'Gujarat'),
    'PBD': ('646', 'Prabhadevi', 'MH', 'Maharashtra'),
    'PBN': ('513', 'Parbhani', 'MH', 'Maharashtra'),
    'PBR': ('619', 'Perambalur', 'TN', 'Tamil Nadu'),
    'PCH': ('5', 'Poonch', 'JK', 'Jammu and Kashmir'),
    'PDK': ('625', 'Pudukkottai', 'TN', 'Tamil Nadu'),
    'PDP': ('1039', 'Peddapalli', 'TS', 'Telangana'),
    'PHK': ('271', 'Phek', 'NG', 'Nagaland'),
    'PIL': ('151', 'Pilibhit', 'UP', 'Uttar Pradesh'),
    'PIM': ('521', 'Pimpri Chinchwad', 'MH', 'Maharashtra'),
    'PKL': ('69', 'Panchkula', 'HR', 'Haryana'),
    'PKM': ('549', 'Prakasam', 'AP', 'Andhra Pradesh'),
    'PKR': ('353', 'Pakur', 'JH', 'Jharkhand'),
    'PLI': ('118', 'Pali', 'RJ', 'Rajasthan'),
    'PLK': ('593', 'Palakkad', 'KE', 'Kerala'),
    'PLM': ('358', 'Palamu', 'JH', 'Jharkhand'),
    'PML': ('484', 'Panch Mahals', 'GU', 'Gujarat'),
    'PMP': ('248', 'Papumpare', 'AR', 'Arunachal Pradesh'),
    'PNA': ('521', 'Pune', 'MH', 'Maharashtra'),
    'PNP': ('75', 'Panipat', 'HR', 'Haryana'),
    'PNR': ('521', 'Pune Rural', 'MH', 'Maharashtra'),
    'PNY': ('635', 'Puducherry', 'PD', 'Puducherry'),
    'PPG': ('93', 'Patparganj', 'DL', 'Delhi'),
    'PRG': ('62', 'Pithoragarh', 'UR', 'Uttarakhand'),
    'PRL': ('340', 'Puruliya', 'WB', 'West bengal'),
    'PRN': ('270', 'Peren', 'NG', 'Nagaland'),
    'PTG': ('131', 'Pratapgarh', 'UP', 'Uttar Pradesh'),
    'PTK': ('675', 'Pathankot', 'PN', 'Punjab'),
    'PTL': ('48', 'Patiala', 'PN', 'Punjab'),
    'PTM': ('599', 'Pathanamthitta', 'KE', 'Kerala'),
    'PTN': ('230', 'Patna', 'BI', 'Bihar'),
    'PUL': ('12', 'Pulwama', 'JK', 'Jammu and Kashmir'),
    'PUR': ('387', 'Puri', 'OR', 'Odisha'),
    'PWL': ('89', 'Palwal', 'HR', 'Haryana'),
    'RAJ': ('6', 'Rajouri', 'JK', 'Jammu and Kashmir'),
    'RAM': ('630', 'Ramanathapuram', 'TN', 'Tamil Nadu'),
    'RBH': ('297', 'Ri Bhoi', 'MG', 'Meghalaya'),
    'RBL': ('158', 'Rae Bareli', 'UP', 'Uttar Pradesh'),
    'RCR': ('559', 'Raichur', 'KA', 'Karnataka'),
    'RDP': ('58', 'Rudraprayag', 'UR', 'Uttarakhand'),
    'RGD': ('403', 'Raigarh-MH', 'MH', 'Maharashtra'),
    'RGH': ('403', 'Raigarh-CG', 'CG', 'Chhattisgarh'),
    'RGY': ('1022', 'Rangareddi', 'TS', 'Telangana'),
    'RJG': ('442', 'Rajgarh', 'MP', 'Madhya Pradesh'),
    'RJT': ('476', 'Rajkot', 'GU', 'Gujarat'),
    'RKM': ('95', 'RK Mission', 'DL', 'Delhi'),
    'RMG': ('361', 'Ramgarh', 'JH', 'Jharkhand'),
    'RMN': ('584', 'Ramanagara', 'KA', 'Karnataka'),
    'RMP': ('136', 'Rampur', 'UP', 'Uttar Pradesh'),
    'RNC': ('364', 'Ranchi', 'JH', 'Jharkhand'),
    'RNG': ('408', 'Rajnandgaon', 'CG', 'Chhattisgarh'),
    'RPN': ('51', 'Rupnagar', 'PN', 'Punjab'),
    'RPR': ('410', 'Raipur', 'CG', 'Chhattisgarh'),
    'RSM': ('123', 'Rajsamand', 'RJ', 'Rajasthan'),
    'RSN': ('446', 'Raisen', 'MP', 'Madhya Pradesh'),
    'RTG': ('528', 'Ratnagiri', 'MH', 'Maharashtra'),
    'RTK': ('82', 'Rohtak', 'HR', 'Haryana'),
    'RTM': ('434', 'Ratlam', 'MP', 'Madhya Pradesh'),
    'RTR': ('97', 'RTRM Chest Clinic', 'DL', 'Delhi'),
    'RTS': ('234', 'Rohtas', 'BI', 'Bihar'),
    'RWA': ('430', 'Rewa', 'MP', 'Madhya Pradesh'),
    'RWR': ('85', 'Rewari', 'HR', 'Haryana'),
    'RYG': ('396', 'Rayagada', 'OR', 'Odisha'),
    'SAG': ('427', 'Sagar', 'MP', 'Madhya Pradesh'),
    'SAH': ('214', 'Saharsa', 'BI', 'Bihar'),
    'SAM': ('221', 'Samastipur', 'BI', 'Bihar'),
    'SAN': ('53', 'Sangrur', 'PN', 'Punjab'),
    'SAR': ('219', 'Saran', 'BI', 'Bihar'),
    'SAW': ('108', 'Sawai Madhopur', 'RJ', 'Rajasthan'),
    'SBD': ('200', 'Sonbhadra', 'UP', 'Uttar Pradesh'),
    'SBE': ('357', 'Purbi Singhbhum', 'JH', 'Jharkhand'),
    'SBG': ('352', 'Sahibganj', 'JH', 'Jharkhand'),
    'SBK': ('472', 'Sabarkantha', 'GU', 'Gujarat'),
    'SBP': ('372', 'Sambalpur', 'OR', 'Odisha'),
    'SBR': ('311', 'Sibsagar', 'AS', 'Assam'),
    'SBW': ('368', 'Pashchimi Singhbhum', 'JH', 'Jharkhand'),
    'SDG': ('529', 'Sindhudurg', 'MH', 'Maharashtra'),
    'SDH': ('462', 'Sidhi', 'MP', 'Madhya Pradesh'),
    'SDL': ('460', 'Shahdol', 'MP', 'Madhya Pradesh'),
    'SDN': ('184', 'Siddharthnagar', 'UP', 'Uttar Pradesh'),
    'SDP': ('1041', 'Siddipet', 'TS', 'Telangana'),
    'SEH': ('445', 'Sehore', 'MP', 'Madhya Pradesh'),
    'SGH': ('295', 'South Garo Hills', 'MG', 'Meghalaya'),
    'SGL': ('463', 'Singrauli', 'MP', 'Madhya Pradesh'),
    'SGM': ('90', 'SGM Chest Clinic', 'DL', 'Delhi'),
    'SGR': ('1040', 'Sngareddy', 'TS', 'Telangana'),
    'SHA': ('152', 'Shahjahanpur', 'UP', 'Uttar Pradesh'),
    'SHD': ('93', 'Shahadra', 'DL', 'Delhi'),
    'SHI': ('568', 'Shimoga', 'KA', 'Karnataka'),
    'SHP': ('132', 'Saharanpur', 'UP', 'Uttar Pradesh'),
    'SHR': ('205', 'Sheohar', 'BI', 'Bihar'),
    'SIN': ('288', 'Saiha', 'MZ', 'Mizoram'),
    'SIT': ('206', 'Sitamarhi', 'BI', 'Bihar'),
    'SJP': ('436', 'Shajapur', 'MP', 'Madhya Pradesh'),
    'SKK': ('369', 'Saraikela-Kharsawan', 'JH', 'Jharkhand'),
    'SKM': ('673', 'Sukma', 'CG', 'Chhattisgarh'),
    'SKN': ('186', 'Sant Kabir Nagar', 'UP', 'Uttar Pradesh'),
    'SKP': ('228', 'Sheikhpura', 'BI', 'Bihar'),
    'SKR': ('111', 'Sikar', 'RJ', 'Rajasthan'),
    'SLC': ('526', 'Solapur MC', 'MH', 'Maharashtra'),
    'SLM': ('610', 'Salem', 'TN', 'Tamil Nadu'),
    'SLN': ('31', 'Solan', 'HP', 'Himachal Pradesh'),
    'SLR': ('526', 'Solapur', 'MH', 'Maharashtra'),
    'SMB': ('1008', 'Sambhal', 'UP', 'Uttar Pradesh'),
    'SML': ('1009', 'Shamli', 'UP', 'Uttar Pradesh'),
    'SMR': ('32', 'Sirmaur', 'HP', 'Himachal Pradesh'),
    'SNC': ('531', 'Sangli MC', 'MH', 'Maharashtra'),
    'SNG': ('531', 'Sangli', 'MH', 'Maharashtra'),
    'SNI': ('456', 'Seoni', 'MP', 'Madhya Pradesh'),
    'SNP': ('76', 'Sonipat', 'HR', 'Haryana'),
    'SNR': ('392', 'Sonapur', 'OR', 'Odisha'),
    'SOP': ('418', 'Sheopur', 'MP', 'Madhya Pradesh'),
    'SPG': ('343', 'South 24 Parganas', 'WB', 'West bengal'),
    'SPH': ('92', 'SPMH Chest Clinic', 'DL', 'Delhi'),
    'SPJ': ('1003', 'Sepahijala', 'TR', 'Tripura'),
    'SPL': ('208', 'Supaul', 'BI', 'Bihar'),
    'SPM': ('92', 'SPM Marg', 'DL', 'Delhi'),
    'SPR': ('306', 'Sonitpur', 'AS', 'Assam'),
    'SPT': ('272', 'Senapati', 'MN', 'Manipur'),
    'SRC': ('1042', 'Siricilla', 'TS', 'Telangana'),
    'SRD': ('198', 'Sant Ravidas Nagar', 'UP', 'Uttar Pradesh'),
    'SRG': ('401', 'Sarguja', 'CG', 'Chhattisgarh'),
    'SRH': ('117', 'Sirohi', 'RJ', 'Rajasthan'),
    'SRN': ('475', 'Surendranagar', 'GU', 'Gujarat'),
    'SRP': ('285', 'Serchhip', 'MZ', 'Mizoram'),
    'SRS': ('79', 'Sirsa', 'HR', 'Haryana'),
    'SRT': ('492', 'Surat', 'GU', 'Gujarat'),
    'SRW': ('181', 'Shravasti', 'UP', 'Uttar Pradesh'),
    'STH': ('243', 'South District', 'SK', 'Sikkim'),
    'STM': ('1016', 'Singtam', 'SK', 'Sikkim'),
    'STN': ('429', 'Satna', 'MP', 'Madhya Pradesh'),
    'STP': ('154', 'Sitapur', 'UP', 'Uttar Pradesh'),
    'STR': ('527', 'Satara', 'MH', 'Maharashtra'),
    'SUL': ('179', 'Sultanpur', 'UP', 'Uttar Pradesh'),
    'SUN': ('374', 'Sundargarh', 'OR', 'Odisha'),
    'SVG': ('626', 'Sivaganga', 'TN', 'Tamil Nadu'),
    'SVP': ('423', 'Shivpuri', 'MP', 'Madhya Pradesh'),
    'SWN': ('218', 'Siwan', 'BI', 'Bihar'),
    'SYP': ('1043', 'Suryapet', 'TS', 'Telangana'),
    'TAM': ('273', 'Tamenglong', 'MN', 'Manipur'),
    'TBL': ('276', 'Thoubal', 'MN', 'Manipur'),
    'TGL': ('59', 'Tehri Garhwal', 'UR', 'Uttarakhand'),
    'THN': ('517', 'Thane', 'MH', 'Maharashtra'),
    'THR': ('594', 'Thrissur', 'KE', 'Kerala'),
    'TKM': ('424', 'Tikamgarh', 'MP', 'Madhya Pradesh'),
    'TLR': ('602', 'Thiruvallur', 'TN', 'Tamil Nadu'),
    'TMC': ('517', 'Thane MC', 'MH', 'Maharashtra'),
    'TNI': ('628', 'Theni', 'TN', 'Tamil Nadu'),
    'TNJ': ('624', 'Thanjavur', 'TN', 'Tamil Nadu'),
    'TNK': ('120', 'Tonk', 'RJ', 'Rajasthan'),
    'TNV': ('632', 'Tirunelveli', 'TN', 'Tamil Nadu'),
    'TRM': ('601', 'Thiruvananthapuram', 'KE', 'Kerala'),
    'TRN': ('292', 'North Tripura', 'TR', 'Tripura'),
    'TRP': ('260', 'Tirap', 'AR', 'Arunachal Pradesh'),
    'TRS': ('290', 'South Tripura', 'TR', 'Tripura'),
    'TRW': ('289', 'West Tripura', 'TR', 'Tripura'),
    'TRY': ('618', 'Tiruchirappalli', 'TN', 'Tamil Nadu'),
    'TSG': ('262', 'Tuensang', 'NG', 'Nagaland'),
    'TSK': ('309', 'Tinsukia', 'AS', 'Assam'),
    'TTC': ('631', 'Thoothukudi', 'TN', 'Tamil Nadu'),
    'TUM': ('571', 'Tumkur', 'KA', 'Karnataka'),
    'TUP': ('615', 'Tiruppur', 'TN', 'Tamil Nadu'),
    'TVM': ('608', 'Tiruvannamalai', 'TN', 'Tamil Nadu'),
    'TVR': ('623', 'Thiruvarur', 'TN', 'Tamil Nadu'),
    'TWN': ('245', 'Tawang', 'AR', 'Arunachal Pradesh'),
    'UDG': ('326', 'Udalguri', 'AS', 'Assam'),
    'UDJ': ('330', 'Uttar Dinajpur', 'WB', 'West bengal'),
    'UDM': ('19', 'Udhampur', 'JK', 'Jammu and Kashmir'),
    'UDP': ('130', 'Udaipur', 'RJ', 'Rajasthan'),
    'UDS': ('67', 'Udhamsingh Nagar', 'UR', 'Uttarakhand'),
    'UDU': ('569', 'Udupi', 'KA', 'Karnataka'),
    'UJN': ('435', 'Ujjain', 'MP', 'Madhya Pradesh'),
    'UKL': ('279', 'Ukhrul', 'MN', 'Manipur'),
    'UKN': ('563', 'Uttara Kannada', 'KA', 'Karnataka'),
    'UKS': ('56', 'Uttarkashi', 'UR', 'Uttarakhand'),
    'UKT': ('1014', 'Unakoti', 'TR', 'Tripura'),
    'UMC': ('517', 'Ulhasnagar MC', 'MH', 'Maharashtra'),
    'UMR': ('431', 'Umaria', 'MP', 'Madhya Pradesh'),
    'UNA': ('29', 'Una', 'HP', 'Himachal Pradesh'),
    'UNN': ('156', 'Unnao', 'UP', 'Uttar Pradesh'),
    'USI': ('254', 'Upper Siang', 'AR', 'Arunachal Pradesh'),
    'USU': ('251', 'Upper Subansiri', 'AR', 'Arunachal Pradesh'),
    'VDC': ('486', 'Vadodara Corp', 'GU', 'Gujarat'),
    'VDD': ('486', 'Vadodara', 'GU', 'Gujarat'),
    'VDS': ('443', 'Vidisha', 'MP', 'Madhya Pradesh'),
    'VKB': ('1044', 'Vikarabad', 'TS', 'Telangana'),
    'VKL': ('663', 'Vikhroli', 'MH', 'Maharashtra'),
    'VLD': ('491', 'Valsad', 'GU', 'Gujarat'),
    'VLR': ('605', 'Vellore', 'TN', 'Tamil Nadu'),
    'VPM': ('609', 'Viluppuram', 'TN', 'Tamil Nadu'),
    'VRD': ('629', 'Virudhunagar', 'TN', 'Tamil Nadu'),
    'VRN': ('197', 'Varanasi', 'UP', 'Uttar Pradesh'),
    'VSL': ('220', 'Vaishali', 'BI', 'Bihar'),
    'VSM': ('544', 'Visakhapatnam', 'AP', 'Andhra Pradesh'),
    'VVM': ('1012', 'Vasai Virar', 'MH', 'Maharashtra'),
    'VYR': ('492', 'Vyara (Surat)', 'GU', 'Gujarat'),
    'VZM': ('543', 'Vizianagaram', 'AP', 'Andhra Pradesh'),
    'WDH': ('504', 'Wardha', 'MH', 'Maharashtra'),
    'WGV': ('546', 'West Godavari', 'AP', 'Andhra Pradesh'),
    'WKA': ('246', 'West Kameng', 'AR', 'Arunachal Pradesh'),
    'WKH': ('296', 'West Khasi Hills', 'MG', 'Meghalaya'),
    'WNP': ('1045', 'Wanaparthy', 'TS', 'Telangana'),
    'WOK': ('267', 'Wokha', 'NG', 'Nagaland'),
    'WRL': ('1025', 'Warangal', 'TS', 'Telangana'),
    'WRR': ('1046', 'Warangal(Rural)', 'TS', 'Telangana'),
    'WRU': ('1047', 'Wrangal(Urban)', 'TS', 'Telangana'),
    'WSI': ('252', 'West Siang', 'AR', 'Arunachal Pradesh'),
    'WSM': ('502', 'Washim', 'MH', 'Maharashtra'),
    'WST': ('242', 'West District', 'SK', 'Sikkim'),
    'WYD': ('590', 'Wayanad', 'KE', 'Kerala'),
    'YAD': ('580', 'Yadgiri', 'KA', 'Karnataka'),
    'YDR': ('1048', 'Yadadri', 'TS', 'Telangana'),
    'YNR': ('71', 'Yamunanagar', 'HR', 'Haryana'),
    'YTL': ('510', 'Yavatmal', 'MH', 'Maharashtra'),
    'ZTO': ('266', 'Zunheboto', 'NG', 'Nagaland')
}
