BBBB BBBB
BBBB BBBBBBBBBBBBBB

XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Application Release Logs') 
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXXX
        XXX XXXXXXXXXX XXXXXXXXXXXX
          XXXX gettext(u'Version Number') XXXXX
          XXXX gettext(u'Update Type') XXXXX
          XXXX gettext(u'Time') XXXXX
          XXXX gettext(u'User') XXXXX
          XXXX gettext(u'Info') XXXXX
        XXXXX
      XXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXX
          XXX XXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXX
        XXXXX
      XXXXXXXX
    XXXXXXXX
  XXXXXX
XXXXXX

XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX XXXXXXXXX
                      XXXXXXXX XXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX XXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
