BBBB BBBB
BBBB BBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Current Profiles') 
    XXXXX

  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXX
         gettext(u'\n          Remote applications only support one build profile. Please remove all but one profile before saving.\n        ') 
          SSSSSS SSSSSSSSSSSS SSSS SSSSSSS SSS SSSSS SSSSSSSS SSSSSS SSSSSS SSS SSS SSS SSSSSSS SSSSSS SSSSSSS
        
      XXXXXX
    BBBBB
    XXXX XXXXXXXXXXXXXXXXXXX
       gettext(u'\n        Application profiles let you install the same application with different languages\n        and options on different phones. Application profiles will appear in <em>new</em> versions\n        of the application.\n      ') 
        SSSSSSSSSSS SSSSSSSS SSS SSS SSSSSSS SSS SSSS SSSSSSSSSSS SSSS SSSSSSSSS SSSSSSSSS
        SSS SSSSSSS SS SSSSSSSSS SSSSSSS SSSSSSSSSSS SSSSSSSS SSSS SSSSSS SS SSSSSSSSSSSS SSSSSSSS
        SS SSS SSSSSSSSSSSS
      
      BB BBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX gettext(u'Manage application profiles here.') XXXX
      BBBBB
       gettext(u"\n        Learn more about Application Profiles on our <a href='https://confluence.dimagi.com/display/commcarepublic/Application+Profiles'>Help Site</a>\n      ") 
        SSSSS SSSS SSSSS SSSSSSSSSSS SSSSSSSS SS SSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSS
      
    XXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXXX
      XXX XXXXXXXXXX XXXXXXXXXXXX
        XXXX gettext(u'Profile Name') XXXXX
        XXXX gettext(u'Languages') XXXXX
        XXXX gettext(u'Default Language') XXXXX
        XXXX gettext(u'Practice Mobile Worker') 
          XXXX XXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Upgrade to CommCare 2.30!') 
          XXXXXX
        XXXXX
        XXXXXXXXX
      XXXXX
      XXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXX XXXXXXXXXX XXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX
                             gettext(u'Latest Enabled Version:') 
                            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX
                        XXXXXX
                      BBBBB
                    XXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXX XXXXXXXXXX X XXXXXXXXXXX
          XXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  XXXXX XXXX XXXXXXXXXXXXXXXX X XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXXX
        XXXXX
        XXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXXXX
        XXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX
      XXXXX
      XXXXXXXX
    XXXXXXXX
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXX
       gettext(u'Add Profile') 
    XXXXXXXXX
  XXXXXX
XXXXXX

