BBBB BBBBBBBBBBBBBB
BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXX
    XXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'\n        One or more of your versions is broken, please make sure it is\n        not marked as released. Make a new version if needed, and update\n        any live deployments as soon as possible.\n      ') 
        SSS SS SSSS SS SSSS SSSSSSSS SS SSSSSSS SSSSSS SSSS SSSS SS SS
        SSS SSSSSS SS SSSSSSSSS SSSS S SSS SSSSSSS SS SSSSSSS SSS SSSSSS
        SSS SSSS SSSSSSSSSSS SS SSSS SS SSSSSSSSS
      
    XXXX
    XXX
      XXXXXXX
         gettext(u'\n          All new versions should work, so if problems persist, please report the issue.\n        ') 
          SSS SSS SSSSSSSS SSSSSS SSSSS SS SS SSSSSSSS SSSSSSSS SSSSSS SSSSSS SSS SSSSSS
        
      XXXXXXXX
    XXXX
  XXXXXX
  XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Show only released versions') XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'Released versions only') 
        XXXXXXX
    XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX gettext(u'show all') XXXX

    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXX XXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XX XXX XXXXXXXXXXX XXX XXXXXXX XX XXX XX XXXXX XX XXXXXXX XXX XXXXXXXXXXX XXXXXXXX XXXX XXX XXXXXX XX XXXXXXXX XXXX XXXXXX XX XXX XXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXX XXX XXXX XXXXXX XXXXXXX XXXX XXXX XXXXXXX XXX XXXXXX XXXXXXXX XXXXXXX XXXX XX XXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
  XXXX
  XXX
    BB BBBBBBBBBBBBBBBBB
      XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXX XX X XXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXX X
                XX
        XX XXXXXXXXX XXXXXXXXXXXXXXXXX
         gettext(u'Preview') 
      XXXX
    BBBBB
    BB BBBBBBBBBBBBBBBBB
      XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXX
         gettext(u'Timing') 
      XXXX
    BBBBB
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXX X
              XXXXXXXXXXXXXXXXXXX XXXX XXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXX
            XX
            XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX X XXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXX
       gettext(u'Make New Version') 
    XXXXXXXXX
  XXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
       gettext(u'\n        The new application build contains the following deprecated case types:\n      ') 
        SSS SSS SSSSSSSSSSS SSSSS SSSSSSSS SSS SSSSSSSSS SSSSSSSSSS SSSS SSSSSS
      
    XXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXX
    XXXX XXXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXXXX XX XXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXX XXX
       gettext(u'\n        For more information on deprecated case types, see the following\n        <a target="_blank" href="https://confluence.dimagi.com/display/commcarepublic/Data+Dictionary">documentation</a>.\n      ') 
        SSS SSSS SSSSSSSSSSS SS SSSSSSSSSS SSSS SSSSSS SSS SSS SSSSSSSSS
        SS SSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
      
    XXXX XXX
  XXXXXX

  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXX XXXXXXXXXXXXX
                          XXXXXXX XXXXXXXXXX X XXXXXXXXXXXX XX
                          XXXXXXXXXXXX XBBBBBBBBBBBBBBB BBBBBBBB BB BBBBBBBBXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXX
       XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX XXXXXXXX XXXX XXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXX
       gettext(u"Sorry, you don't have permission to do this action!") 
    XXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXX XXXXX XXXXXXXXXXXXXX
    XXXXXXX
  XXXXXX

  XXX XXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXX
    XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
     gettext(u'Loading versions...') 
  XXXXX

  XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXX
       XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXX XXXX XXXXXX XXXXXXXX
     gettext(u'An error occurred while fetching versions. Reload the page to try again.') 
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXX XXXXXX XXXXXXX
                    XXXXXXXXX XXXXXXXXX XXXXXXXXXXX X

    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
         XXXXXXXXXXXXXXX X
                XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXXXX
            XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX
               XXXXXXXXXXX XXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                  XXXXXXXX XXXXXXXXXXXXXXXX
                                  XXXX XXXXXX XXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXX
            XXXX
            XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXX XXXX XXXXXX XXXXXXXX
              XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
               XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXXX
                                  XXXX XXXXXX XXXXXXXXXXXX
          XXXXXX
        BBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXX XXXXXXXXXXXXX XX XXXXXXX XXX

          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Could not update') XXXXXXX

          XXXXXXXXXX
          XXXXXX XXX XXXXXXXXXXXXX XX XXXXXXX XXX

          XXXXX XXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Latest') XXXXXXX

          XX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXX
                    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                           XXXX X
                                              XXXXXXXXX XXXXXXXXXXXXXX
                                              XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                              XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                           XXX
               gettext(u'Released') 
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                           XXXX X
                                              XXXXXXXXX XXXXXXXXXXXXXXX
                                              XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                              XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                           XXX
               gettext(u'In Test') 
            XXXXXXXXX
          XXXXXX

          XXXXXXXXXX
        XXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXX gettext(u'Version')  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX
          X
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  gettext(u'by') 
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXX XXXXXXXXXXXXXXXXX XXX
           gettext(u'with CommCare v.') 
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXX
          XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Unsigned Jar') XXXXXXX
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXX XXXXXXXX
                  XXXXXX XXXXXXXXXXXXXX
                  XXXXXXXXXX XXX XXXXXXXXXXXX
                  XXXXX XX
                  XXXXXXXXXXXX X gettext(u'(Click here to add a comment)') XX
                  XXXX XBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBXX
                  XXXXXXXXXXX XXXXXXXXXXXX XXXX
                  XXXXXXXXXXXXXX XXXXXXXXXX
                  XXXXXXXXXXXXXX gettext(u'Error updating comment.  Please try again.') XX
                  XXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFX
              XXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXXXXXX XXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        BB BBBBBBBBBBBBBBBBB
          XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                    XXXXX XXXXXX XXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX
                          XX
                    XXXXXX XXXXXXXX XX X
                        XXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXX XXXX XXXXXXXXXX
                    X
                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'View Changes') 
          XXXX
        BBBBB
        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX
                XXXXXXXXXXX
                             XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                             XXXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                             XXXX XXXXXX XXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Revert to this Version') 
        XXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXX
             XXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX
                    XX
              XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX
                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXX XXXXXXXX
              XXXXXXX
               gettext(u'Publish') 
          XXXX
        XXXXXXX
      XXXXXXXXXX XXXXXXXXXXXXX XXX
    XXXXXXXXXX XXXXXXXXXXXXXX XXX
  XXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXX

  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX XXXXXXXXX
                      XXXXXXXX XXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXX
                      XXXXXXXXXXX XXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Delete Version?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXX gettext(u'Are you sure you want to delete this version')  XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXX
          XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Delete Version') XXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Revert to Version?') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'\n              This version uses an outdated form of case management.\n              We advise against reverting back to this version.\n            ') 
              SSSS SSSSSSS SSSS SS SSSSSSSS SSSS SS SSSS SSSSSSSSSSS
              SS SSSSSS SSSSSSS SSSSSSSSS SSSS SS SSSS SSSSSSSS
            
          XXXXXX
          XXX gettext(u'\n            Are you sure you want to revert to version <span data-bind="text: version"></span>?</p>\n          ') 
            SSS SSS SSSS SSS SSSS SS SSSSSS SS SSSSSSS SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSS
          
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXX
          XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Revert') XXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXXXXX
XXXXXXXXXX XXXXXXXXXXXXXXX XXX
