BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB


BB BBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
     gettext(u'\n      <p class="lead">\n        Please click <i class="fa fa-plus"></i> <strong>Add...</strong> to start building your App!\n      </p>\n    ') 
      SS SSSSSSSSSSSSS
        SSSSSS SSSSS SS SSSSSSSSS SSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSS SS SSSSS SSSSSSSS SSSS SSSS
      SSSS
    
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
     gettext(u'\n      <p class="lead">\n        As you build your App, check out the <strong>App Preview</strong> to demo it in real time!\n      </p>\n    ') 
      SS SSSSSSSSSSSSS
        SS SSS SSSSS SSSS SSSS SSSSS SSS SSS SSSSSSSSSSS SSSSSSSSSSSSSSSS SS SSSS SS SS SSSS SSSSS
      SSSS
    
  XXXXXX
BBBB

  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXX
         XXXXXXXXXXXFFFFFFFFFFFFFFX
         XXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XX XXXXXXXXXXXXX gettext(u'Updates to Publishing Apps') XXXX
      XX XXXXXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'\n          Instead of starring versions of your app, you can now mark them\n          as "Released" or "In Test." "Released" has the same effect as\n          starring a version.  Any version you do not mark as "Released"\n          will default to "In Test."\n        ') 
          SSSSSSS SS SSSSSSSS SSSSSSSS SS SSSS SSSS SSS SSS SSS SSSS SSSS
          SS SSSSSSSSSS SS SSS SSSSSS SSSSSSSSSS SSS SSS SSSS SSSSSS SS
          SSSSSSSS S SSSSSSSS  SSS SSSSSSS SSS SS SSS SSSS SS SSSSSSSSSS
          SSSS SSSSSSS SS SSS SSSSSS
        
      XXXX
    XXXXXX
  BBBBB

  BB BBB BBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBB
    XXXX XXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
           gettext(u'Versions') XXXX
        XXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Manage Update Settings') XXXXXXXXX
        BBBBB
        BB BBBBBBBBBBBBBBBBBBBB
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Application Profiles') XXXXXXXXX
        BBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Application Release Logs') XXXXXXXXX
        BBBBB
      XXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            BBBBBB BBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXX
        BBBBB
        BB BBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX
        BBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX
        BBBBB
      XXXXXX
    XXXXXXXXXX XXXXXXXXX XXX
  BBBBB

BBBBBXXXX XXXXXXXXXX XXXXXXXXX XXX

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXX XXXXX XXXXXXXX XXXXXX XXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
