from __future__ import absolute_import
from .test_dbaccessors import *
from .test_delete_domain import *
from .test_domain_copy import *
from .test_domain_name_generation import *
from .test_domain_transfer import *
from .test_forms import *
from .test_guess_phone_type import *
from .test_transform_domain_for_elasticsearch import *
from .test_views import *
