BBBB BBBB BBBBBBBBBB
XXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX

  BB BBBBBBBBBBBBB
    XXX gettext(u'Or, alternatively, use one of your backup phones:') XXXX
    BBB BBBBB BB BBBBBBBBBBBBB
      XXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
          FFFFFFFFFFFFF
        XXXXXXXXX
      XXXX
    BBBBBB
  BBBBB
  BB BBBBBBBBBBBBB
    XXX gettext(u'Please contact your domain administrator if you need a backup token.') XXXX
    XXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'Use Backup Token') 
      XXXXXXXXX
    XXXX

  BBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
XXXXXXX
