BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  XXXXBBBBB BBBBB gettext(u'Add Backup Phone') BBBBBBBBXXXXX

  BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
    XXX gettext(u'Your backup phone number will be used if your primary method of\n      registration is not available. Please enter a valid phone number.') SSSS SSSSSS SSSSS SSSSSS SSSS SS SSSS SS SSSS SSSSSSS SSSSSS SS
      SSSSSSSSSSSS SS SSS SSSSSSSSSS SSSSSS SSSSS S SSSSS SSSSS SSSSSSSXXXX
  BBBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB
    XXX gettext(u"We've sent a token to your phone number. Please\n      enter the token you've received.") SSSSS SSSS S SSSSS SS SSSS SSSSS SSSSSSS SSSSSS
      SSSSS SSS SSSSS SSSSSS SSSSSSSSSXXXX
  BBBBB

  XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBB
    
    BBBBBB BBBBBBBBBBB
  XXXXXXX

BBBBBBBB
