BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBB
  XXXXBBBBB BBBBB gettext(u'Enable Two-Factor Authentication') BBBBBBBBXXXXX

  XXX gettext(u"Congratulations, you've successfully enabled two-factor\n    authentication.") SSSSSSSSSSSSSSSS SSSSSS SSSSSSSSSSSS SSSSSSS SSSSSSSSSS
    SSSSSSSSSSSSSSS

    BB BBB BBBBBBBBBBBBB
      BB BBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Begin Using CommCare Now') XXXX
      BBBBB
      XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX
            XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX gettext(u'Back to Profile') XXXXXXXX
    BBBB
      XXX gettext(u'To enable account recovery, generate backup tokens.') SS SSSSSS SSSSSSS SSSSSSSSS SSSSSSSS SSSSSS SSSSSSSXXXX
      BB BBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Begin Using CommCare Now') XXXX
      BBBBB
      XXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBX
         XXXXXXXXXXXXXXXXX XXX XXXXXXXXXX gettext(u'Back to Profile') XXXXXXXX
      XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX
            XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Generate Backup Tokens') XXXXXXXX
    BBBBB

BBBBBBBB
