# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-12 10:35

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartEnterpriseDeliveryReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.CharField(db_index=True, max_length=126)),
                ('message_id', models.CharField(db_index=True, max_length=126, unique=True)),
                ('received_on', models.DateTimeField(db_index=True, null=True)),
                ('info', jsonfield.fields.JSONField(default=dict, null=True)),
            ],
        ),
    ]
