# Generated by Django 4.2.20 on 2025-09-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsforms', '0003_make_fields_not_null'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sqlxformssession',
            new_name='smsforms_sq_session_5286fb_idx',
            old_fields=('session_is_open', 'connection_id'),
        ),
        migrations.RenameIndex(
            model_name='sqlxformssession',
            new_name='smsforms_sq_session_9e10f1_idx',
            old_fields=('session_is_open', 'current_action_due'),
        ),
    ]
