BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBB
  XXXXBBBBB BBBBB gettext(u'Remove Two-factor Authentication') BBBBBBBBXXXXX
  XXX gettext(u'You are about to <strong>remove</strong> two-factor authentication. This\n    compromises your account security, are you sure?') SSS SSS SSSSS SS SSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSS SSSSSSSSSSSSSSS SSSS
    SSSSSSSSSSS SSSS SSSSSSS SSSSSSSSS SSS SSS SSSSSXXXX
  XXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXX gettext(u'Remove') XXXXXXXXX
  XXXXXXX
BBBBBBBB
