# Generated by Django 3.2.18 on 2023-05-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motech', '0012_alter_connectionsettings_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionsettings',
            name='throttle_window',
            field=models.IntegerField(null=True),
        ),
    ]
