USER_DATETIME_FORMAT = "%b %d, %Y %H:%M %Z"
USER_DATETIME_FORMAT_WITH_SEC = "%b %d, %Y %H:%M:%S %Z"

USER_DATE_FORMAT = "%b %d, %Y"
USER_TIME_FORMAT = "%H:%M %Z"
USER_MONTH_FORMAT = "%B %Y"

SERVER_DATE_FORMAT = "%Y-%m-%d"
SERVER_DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
SERVER_DATETIME_FORMAT_NO_SEC = "%Y-%m-%d %H:%M"
