USER_DATETIME_FORMAT = "%b %d, %Y %H:%M %Z"
USER_DATETIME_FORMAT_WITH_SEC = "%b %d, %Y %H:%M:%S %Z"

USER_DATE_FORMAT = "%b %d, %Y"
USER_TIME_FORMAT = "%H:%M %Z"
USER_MONTH_FORMAT = "%B %Y"

SERVER_DATE_FORMAT = "%Y-%m-%d"
SERVER_DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
SERVER_DATETIME_FORMAT_NO_SEC = "%Y-%m-%d %H:%M"

FILENAME_DATETIME_FORMAT = "%Y-%m-%d %I-%M-%S %p"

MISSING_APP_ID = '_MISSING_APP_ID'

OPENROSA_VERSION_1 = "1.0"
OPENROSA_VERSION_2 = "2.0"
OPENROSA_VERSION_3 = "3.0"
OPENROSA_VERSION_2_1 = "2.1"
OPENROSA_DEFAULT_VERSION = OPENROSA_VERSION_1
OPENROSA_VERSION_MAP = {
    'ASYNC_RESTORE': OPENROSA_VERSION_2,
    # Indexed fixture also applies when OR version not specified
    'INDEXED_PRODUCTS_FIXTURE': OPENROSA_VERSION_2_1,
}

ONE_DAY = 60 * 60 * 24
DEFAULT_PARALLEL_EXECUTION_TIMEOUT = 60 * 60  # one hour


USER_CHANGE_VIA_API = "api"
USER_CHANGE_VIA_WEB = "web"
USER_CHANGE_VIA_SMS = "sms"
USER_CHANGE_VIA_BULK_IMPORTER = "bulk_importer"
USER_CHANGE_VIA_INVITATION = "invitation"
USER_CHANGE_VIA_SSO_NEW_USER = "sso_new"
USER_CHANGE_VIA_SSO_INVITE = "sso_invitation"
USER_CHANGE_VIA_AUTO_DEACTIVATE = "auto_deactivate"
USER_CHANGE_VIA_CLONE = "clone_user"

LOADTEST_HARD_LIMIT = 500_000  # max cases a loadtest user can sync
