XXXXXXXXXX
    XXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXBB BBB BBBBBBBBBB XXXXXXXXXBBBBBX
           XXXXXXXXXXXXXXXXXXXXXX
           BB BBBBBBBBBBBBBBB
           XXXXXXXXXXXXXXX
           BBBBB
           XXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            
        XXXX
    XXXXXXXXX
    XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXBB BBBBBBBBBB XXBBBBBX X
        XXXXX
            FFFF
        XXXXXX
    XXXXXX
XXXXXXXXXXX
