BBBB BBBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBB
    
BBBB
    XXXX
        XXXXXXXXX
        XXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBB XXXXX XXXXXXXXXBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBX
    X
        BB BBBBBBBBBBB BBB BBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXX  BB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXBBBBBXX
                XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
                XXXXXXXX
            XXXXXX
        BBBBB

        XXXX XXXXXXXXXXXXXXX XX
          BB BBBBBBBBB BB BBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXBBBBB
            BB BBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
            BBBBBBBBBBBB BBBBB BBBBBBB BBBBBBBBBBBBBB
            BB BBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
          BB BBBBBBBBB BB BBBBBBBBBBXXXXXXBBBBB
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
    XXXXXX
BBBBB
