# Generated by Django 2.2.16 on 2021-04-06 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerUserCaseRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerUserInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('case_id', models.CharField(max_length=255)),
                ('demographic_case_id', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('accepted', models.BooleanField(default=False)),
                ('invited_by', models.CharField(max_length=255)),
                ('invited_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='consumeruserinvitation',
            constraint=models.UniqueConstraint(
                condition=models.Q(('accepted', False), ('active', True)),
                fields=('demographic_case_id',),
                name='multiple_open_invites'
            ),
        ),
        migrations.AddField(
            model_name='consumerusercaserelationship',
            name='consumer_user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='case_relationships',
                to='consumer_user.ConsumerUser'
            ),
        ),
        migrations.AddField(
            model_name='consumeruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
