# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0003_remove_sqldefaultconsumption_couch_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SQLDefaultConsumption',
            new_name='DefaultConsumption',
        ),
        migrations.AlterModelTable(
            name='defaultconsumption',
            table=None,
        ),
    ]
