BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Account') XXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Subscriptions') XXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Credits') XXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Autopay') XXXXXXXXX
    BBBBB
  XXXXX

  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXX XXXX XXXX
        
      XXXXXX
      XXXX XXXXXXXXXXXXXX XXXX XXXX
        BBBBBB BBBBBBBBBBBB
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    BB BBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXX
        XXXXXXXXX XXX XXXXX XXXXXX
        XXXX
        XXX
        XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXX XXXX XXXXXXX XXXXXX
        XXXXXXXXXXX XXXXXX
        XXXXXXXXXXXXXXXX  X XXXXXX
        XXXX
        XXXXX
          XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBB BBBBBBBBBBBBBBBBBBB
          XXXXXXX
        XXXXXX
      XXXXXX
    BBBBB
  XXXXXX

BBBBBBBB
