BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB 

BBBBB BBBBBBBBBBBB
  BB BBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBB

  XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'\n              Resend Invoice #%(invoice_number)s Email?\n            ') 
              SSSSSS SSSSSSS SSSSSSSSSSSSSSSSSSS SSSSSS
            
          XXXXX
        XXXXXX
        BBBBBB BBBBBBBBBBBBBBBBB
      XXXXXX
    XXXXXX
  XXXXXX

  XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Invoice') XXXXXXXXX
    BB BBBBBBBBBBBBBBB
      XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Adjustments') XXXXXXXXX
    BBBBB
    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Suppress') XXXXXXXXX
    BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Hide From Client') XXXXXXXXX
    BBBBB
  XXXXX

  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      BBBBBB BBBBBBBBBBBBBBBBB

      XXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXX
        XXXX
          XXXX gettext(u'Date') XXXXX
          XXXX gettext(u'Recipients') XXXXX
          XXXX gettext(u'View PDF') XXXXX
        XXXXX
        XXXXXXXX
        XXXXXXX
        BBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
          XXXX
            XXXX XXXXXXXX
            XXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
                  XXXX XXX
                XXXX
              XXXXX
            BBBB
              XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
                  XXXX XXX
                XXXX
              XXXXX
            BBBBB
          XXXXX
        BBBBBB
        XXXXXXXX
      XXXXXXXX
      BB BBBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
        X
          XXXXXXX XXXXX
        XXXXXXXXX
      BBBB
        XXXXXX XXXXX XXXX XXX XXXXXXX XX XXXX
          XXXXXXXXXXXX XX XXXXXX XX XXX XXX XXXXXXXXXXXXX
      BBBBB
    XXXXXX

    BB BBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXXX
          XXXX
            XXXX gettext(u'Date') XXXXX
            XXXX gettext(u'Reason') XXXXX
            XXXX gettext(u'Note') XXXXX
            XXXX gettext(u'User') XXXXX
            XXXX gettext(u'Amount') XXXXX
          XXXXX
          XXXXXXXX
          XXXXXXX
          BBB BBBBBBBBBB BB BBBBBBBBBBBBBBB
            XXXX
              XXXX XXXXXXXX
              XXXXXXXXX
              XXXXXXXXX
              XXXXXXXXX
              XXXXXXXXX
            XXXXX
          BBBBBB
          XXXXXXXX
        XXXXXXXX
      XXXXXX
    BBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      BBBBBB BBBBBBBBBBBBBBBBBBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
      BBBBBB BBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX
BBBBBBBB
