BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Plan Information') XXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Roles and Features') XXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Version Summary') XXXXXXXXX
  XXXXX

  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
      BBBBBB BBBBBBBBBBBBBBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXX
      XXXXXX
      BBBBBB BBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXX
      XXXXXX
      BBBBBB BBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXX XXXXXXXX XXXX
    XXXXXXXX
    XXXXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXX XXX XXXX
    XXXXXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXX XX XXXXXXXXXX XXX XXXX XXXXX
      XXXX
    XXXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXX XXXXXXXXXX XXXXX XXX XXXXXXXX XXX XXX XXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXXXXX
BBBBBBBB
