BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXX XXXXXXXXX
            XXXXXXXXXXXXXXXXXXX gettext(u'Generating Report...') X
            XXXXXXXXXXXXXXXXXXXX gettext(u'Apply') XX
       gettext(u'Apply') 
    XXXXXXXXX
  XXXXXX
BBBBBBBB
