BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Subscription') XXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Invoices') XXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX gettext(u'Upgrade / Downgrade') XXXX
      XXXXX
    BBBBB
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Credits') XXXXXXXXX
    XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Suppress') XXXXXXXXX
  XXXXX

  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXX XXXXX XXX XXXXXXXXXXXXX XX XXXXXXXX XXX XXXXXX XXXXXXX XXX
    BBB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBB

    BB BBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXX
          XXXX XXXX XXXXXXXX XXX XXXXXXXX XXXX XXXX XXXXXX XXX XXXXXXX
          XXXXXXXXXXXX XXX XXXXXX X XXX XXX XXXX XXX XXX XXXX XXXXXXXXXXXX
          XX XXXX XXXX XXXXX XXXXXXXX X XXXXXXXXXX XX XXXXXXXX
          XXXXXXX XXX XXXXXXXXX XXXXXXXXXX XXXX XXX XXX XXXX XXXXXXXXX
        XXXXXX
        BBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
    BBBBB

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXX XXXXXX
        XXXXXX
      BBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
        XX XXXX XXXX XX XXXXXXXXXX XXXXXXXXXX
        XX XXX XXXXXX XXXXXXXXXXXXX XXXX XX XXXXXX XXXXX XXXXXX
        XXXXXXXXX XXXX XXXX XXXX XXXX XXXXXXX XX XXX XXXXXX XXXX
        XXXXXXXX XXX XXXXXXXXXX
      XXXXXX
      XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBB
      XXXXXXX
      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
          XXXXXXXXXXXX XXX XXXX XXXXXXXXX
        XXXXXX
      BBBB BBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXX
          XXXXXXXXXXXX XXX XXXXXXX XXXXXX
        XXXXXX
      BBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        BBBBBB BBBBBBBBBBBBB
      XXXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
