BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBB BBB
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
  BBBBBBBBBBB

  BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBB BBB
      XXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX
            XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    BBBBBBBBBBB
  BBBBB

  BBBBB BBBBBBBBBBB

  XXXXX XXXXXXXXXXXXXXXX
        XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
  XXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
        XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX

  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX

  BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBB BBBBBBB BBBBBBBBBBBBBB
  XXXXXXX XXXXXBBBBBBBBBB BBBBBBBBBBBBBXXXXXXXXXXX 

  BBBBBBBB BB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBBBBBBBB

  BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBB
    BBBBBBBB BB
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBBBBBBBB
  BBBBB

  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXX XXXXXXXXXXXX XXX XXXXXXX XXX

XXXXXXX
XXXXXX
BBBBB BBBBBBBBBBBB


BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  BBBBB BBBBBBBBBBBBBBBBB
    
  BBBBBBBB
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  BBBBB BBBBBBBBBBBBBBB
    
  BBBBBBBB
XXXXXX
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
  BBBBB BBBBBBBBBBBBBBBBBBBBBB
    
  BBBBBBBB
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
  BBBBB BBBBBBBBBBBBBBBBB
    
  BBBBBBBB
XXXXXX
XXXXXXX
XXXXXXX


