# Generated by Django 4.2.17 on 2025-03-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('case_type', models.CharField(max_length=126)),
                ('geo_case_property', models.CharField(max_length=126)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='campaign.dashboard')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
