BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBB

  XXXX XXXXXXXXXXXX
    BBB BBBBBB BB BBBBBBB
      XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXFFFFFFFFFFFFFFFFXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
            XXXXX
            XXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXX
               gettext(u'Email Report') 
            XXXX
          XXXXXX
        XXXXXX
      XXXXXX
    BBBBBB
  XXXXXX
BBBBBBBB
