BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  XX XXXXXXXXXXXXX
     gettext(u'Enterprise Permissions') 
      SSSSSSSSSS SSSSSSSSSSS
    
  XXXX

  XX XXXXXXXXXXXXXXXXXXX
     gettext(u'Give web users who have access to a controlling project space the same level of access to your other project spaces. Such users will neither get email invitations to join these project spaces, nor will they appear as members in those project spaces.') 
      SSSS SSS SSSSS SSS SSSS SSSSSS SS S SSSSSSSSSSS SSSSSSS SSSSS SSS SSSS SSSSS SS SSSSSS SS SSSS SSSSS SSSSSSS SSSSSSS
      SSSS SSSSS SSSS SSSSSSS SSS SSSSS SSSSSSSSSSS SS SSSS SSSSS SSSSSSS SSSSSSS SSS SSSS SSSS SSSSSS SS SSSSSSS SS SSSSS SSSSSSS SSSSSSS
    
  XXXX

  BB BBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
      BBBBBBBBBB
      XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXX
         gettext(u'Disable Enterprise Permissions') 
      XXXXXXXXX
    XXXXXXX
  BBBB
    XX XXXXXXXXXXXXXXXXXXX
       gettext(u'To turn on enterprise permissions, select the controlling project space.') 
        SS SSSS SS SSSSSSSSSS SSSSSSSSSSSS SSSSSS SSS SSSSSSSSSSS SSSSSSS SSSSSS
      
    XXXX
  BBBBB

  XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          BB BBB BBBBBBBBBBBBB
            XXXXXXX XXXXXXXXX gettext(u'Select the controlling project space') XXXXXXXXX
          BBBBB
          BBB BBBBBB BB BBBBBBBBBBB
            XXXXXXXBB BBBBBB BB BBBBBBBBBBBBB XXXXXXXXBBBBBXXXXXXXXXX
          BBBBBB
        XXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
           gettext(u'Update') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXX

  XXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBB
           gettext(u'Web users in <strong>%(source_domain)s</strong> will also have permissions in the following project spaces.') 
            SSS SSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSS SSSS SSSS SSSSSSSSSSS SS SSS SSSSSSSSS SSSSSSS SSSSSSS
          
        BBBB
           gettext(u'Web users in the controlling project space will also have permissions in the following project spaces.') 
            SSS SSSSS SS SSS SSSSSSSSSSS SSSSSSS SSSSS SSSS SSSS SSSS SSSSSSSSSSS SS SSS SSSSSSSSS SSSSSSS SSSSSSS
          
        BBBBB
      XXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBB
           gettext(u'Web users in <strong>%(source_domain)s</strong> will <strong>not</strong> have permissions in the following project spaces.') 
            SSS SSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSS SSSSSSSSSSSSSSSSSSSS SSSS SSSSSSSSSSS SS SSS SSSSSSSSS SSSSSSS SSSSSSS
          
        BBBB
           gettext(u'Web users in the controlling project space will <strong>not</strong> have permissions in the following project spaces.') 
            SSS SSSSS SS SSS SSSSSSSSSSS SSSSSSS SSSSS SSSS SSSSSSSSSSSSSSSSSSSS SSSS SSSSSSSSSSS SS SSS SSSSSSSSS SSSSSSS SSSSSSS
          
        BBBBB
      XXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX

BBBBBBBB
