XXXX
  XXXX
    BB BBBBBBBBBBBBB
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB
    XXXX
    XXXXXXX
      XX XXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXX
    XXXXXXXX
  XXXXX
  XXXX XXXXX
  XXXX
    XXXXXBB BBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXBBBBBXXXXXX
  XXXXX
XXXXX
