BBBB BBBBBBBB

XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXX
        XXXX
          XXXXXXXXXXXXX
          XXXXXXXXXXXXX
          XXXXXXXX XXXXXXXX
        XXXXX
        XXXXXXXX
        XXXXXXX
        BBB BBBBBB BB BBBBBBBBBBBBBB
          XXXX
            XXXX
              FFFFFFFFFFFXXXXX
              XXXXXXXXXXXXXXX
            XXXXX
            XXXXXXXXX
            XXXX
              BB BBBBBBBBBBBBBBB
                XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX
              BBBBB
            XXXXX
          XXXXX
        BBBBBB
        XXXXXXXX
      XXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
