BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXX gettext(u'Are you sure you want to continue?') XXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'If this fails you may have to perform the operation manually!') XXXX
        XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'This may invoke a huge indexing task that could slow down many parts of the site!') XXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXX XXX
                XXXX X XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Go!') 
        XX XXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXX
    XXXXXX
  XXXXXX
XXXXXX
