XXXXXX
XXXXXX
XXXXXXX
XXXXXX
XXXXXXXXXXXX XX X XXXXXXXXXXXX
BB BBBBBBBBB
  XXXXX XXXX XXXXXXXX XXX XXXXXXXXX XXXXXXXX
  XXXX
    BBB BB BB BBBBBBBBB
      XXXX
        XX XXXXXXXXX XXXX
        XXXXXXXXX XXXXXX X
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                      X
                    XXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                      X
                    XXXXXXX
                XXXXXXX
        BBB BBBBB BB BBBBBBBBB
          XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    
                XXXXXXX
        BBBBBB
      XXXXX
    BBBBBB
  XXXXX
  BBB BBBBBB BBB BB BBBBBBBBBBBBBBBBBB
    XXXXXXX
    XXXX
      BBB BB BB BBB
        XXXX
          XX XXXXXXXXX XXXX
          X 
        XXXXX
      BBBBBB
    XXXXX
  BBBBBB
BBBB
  XXXXX XXX XXXX XXXXXX XXXXX XXXX XXXXXXXXXXX
BBBBB
XXXXXXXXX XXX XXXXXXXX XXXX XX XXXXXXX XX XXXXXXXXXXXXXXXX
XXXXXXX
XXXXXXX
