 #
 #
 #
 #
 #


XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXXXXX
  XXXX
    XXXXXXXXX XXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XX XXXXXXXXXXX
    XXXXXXXXXXX XX XXXXXXXXXX
  XXXXX
  XXXXXXXX
  XXXXXXX
  BBB BBBBB BB BBBBBBBBBBB
    XXX XXXXXXXXXXXXX BB BBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXBBBBBX
      XXXXXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
      XXXXFFFFFFFFFFFFFFFFFFXXXXX
    XXXXX
  BBBBBB
  XXXXXXXX
XXXXXXXX
