from .test_delete_domain import *
from .handlers.translation import *
from .handlers.arrived import *
from .handlers.delivered import *
from .handlers.language import *
from .handlers.loss_adjust import *
from .handlers.not_recognized import *
from .handlers.randr import *
from .handlers.stockonhand import *
from .handlers.stop import *
from .handlers.supervision import *
from .handlers.yes import *
from .handlers.stockout import *
from .handlers.messageinitatior import *
from .handlers.bugs import *
from .handlers.deliverygroups import *
from .handlers.help import *
from .handlers.register import *
from .handlers.transfer import *
from .handlers.soh_slab import *
from .test_reminders import *
from .test_report_runner import *
from .test_reminders2 import *
from .test_report_reminders import *
from .test_parse_report import *
