BBBB BBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBBBBB BBBBBBBBBBB BBBBBB BBBBBB BBBBB

XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  BBBB BBBBBB BB BBBBBBBBBBBBBBB
    BBB BBBBBB BB BBBBBBBBBBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
          XXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXFFFFFFFFFFXX

        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXX
                   BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBBXX
          BBBB BBBBBBBB BB BBBBBBBBBBBBB
            BBB BBBB BB BBBBBBBBBBBBBBBB
              XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXX
                  XXXXXXXXXXX
                  BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXXXXXXXBBBBBX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XXXXX
            BBBBBB
          BBBBBBB
        XXXXX
      XXXXX
    BBBBBB
  BBBBBBB
XXXXX
XXX XXXXXXXXXXXXXXXXXXXX
  BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXXXBBB BBBBBBBBBBBB BBBBBB BBBBBBX
              XXXXXXXXXXXXX
              XXXXXXXXXXXXX
          BBBBBBBBBB
          XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
        XXXXXXX
        XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
           gettext(u'Add...') 
        XXXX
      XXXXXX
    XXXXX
  BBBBB
XXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX
                     gettext(u'Your menus were reordered') 
                XXXXX
            XXXXXX
            XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBX
                  XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXX
                     gettext(u'\n                    <p>\n                        Sub-menus are now displayed nested under their parent menu. The order\n                        of your menus has been changed to reflect that.\n                    </p>\n                    <p>\n                        Click "Rearrange" to make this change permanent.  You won\'t be able to modify the order of your menus until you do so.\n                    </p>\n                    <p>\n                        Please contact support or report an issue if you have any concerns.\n                    </p>\n                    ') 
                    SSS
                        SSSSSSSSS SSS SSS SSSSSSSSS SSSSSS SSSSS SSSSS SSSSSS SSSSS SSS SSSSS
                        SS SSSS SSSSS SSS SSSS SSSSSSS SS SSSSSSS SSSSS
                    SSSS
                    SSS
                        SSSSS SSSSSSSSSSS SS SSSS SSSS SSSSSS SSSSSSSSSS  SSS SSSSS SS SSSS SS SSSSSS SSS SSSSS SS SSSS SSSSS SSSSS SSS SS SSS
                    SSSS
                    SSS
                        SSSSSS SSSSSSS SSSSSSS SS SSSSSS SS SSSSS SS SSS SSSS SSS SSSSSSSSS
                    SSSS
                    
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Not Now') 
                    XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX
                         gettext(u'Rearrange') 
                    XXXXXXXXX
                XXXXXX
            XXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXX XXX
    XXXXXXXXXX XXXXXXXXXXXXXX XXX
XXXXXXXXXX XXXXXXX XXX
