BBBB BBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXX BB BBBB BB BBBBBBBBBBBBB XXXXXXBB BBB BBBBBBBBBBBB XXXXXXXXXXXXXBBBBBBBBBBXX

    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX

    XX XXXXXXXXXXXXXXXXXXXXXXXX
       BB BBBBBBBBBBBBBBBBBBBBBBB
         XXXXXXBBB BBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBX
       BBBB
         XXXXXXBBB BBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBX
       BBBBB
       XXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXX XXXXXXXX
       XXXXXXXXXXXXXXXXX XXXXX
       XXXXXXXXXXXXXXXX XXXX
       XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXX BBBBB
              XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XX
        BB BBBBBBBBBBBBBBBBBBBB BB BBBBBB
            XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBB
            XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
            XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBB
            XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBB
            XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBBB
            XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'This is form %(index)s<br>') SSSS SS SSSS SSSSSSSSSSSSS BBBBBX
            XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXX
            X
        XXXX
        XXXXX BB BBBB BB BBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBX
            FFFFFFFFFFFFFFFFFFFFFFF
        XXXXXXX
    XXXX

    BB BBBBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXBBB BBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBX
       XXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXX XXXXXXXX
       XXXXXXXXXXXXXXXXX XXXXX
       XXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
    BBBBB

    XXXX XXXXXXXX XXXXXXXXXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
               gettext(u'\n                Are you sure you want to delete this form?\n              ') 
                SSS SSS SSSS SSS SSSS SS SSSSSS SSSS SSSSS
              
            XXXXX
          XXXXXX

          XXXXX XXXXXXXXBBB BBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBX
                XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXX
                 gettext(u'You are about to delete the form') SSS SSS SSSSS SS SSSSSS SSS SSSS
                XXXXXXXXFFFFFFFFFFFFFFFFXXXXXXXXXX
              XXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Cancel') 
              XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXX
                 gettext(u'Delete Form') 
              XXXXXXXXX
            XXXXXX
          XXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXX XXX
      XXXXXXXXXX XXXXXXXXXXXXXX XXX
    XXXXXXXXXX XXXXXXX XXX

XXXXXX
