BBBB BBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBXXXXXXBBBBBBBBBBXX
  BB BBBBBBBBBBBBBBBBBBBBB
    
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX
  BBBB
    XX XXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXX
    XXXX
  BBBBB

    XX XXXXXXBBB BBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBBBX
       XXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
          XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBB
          XX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBB
          XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBB BBBBBBBBBBBBBBBBBBBBBBBBB
          XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBB BBB BBBBBBBBBBBBBBBBB
          XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBB
          XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBBB
            XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB gettext(u'This is menu %(index)s') SSSS SS SSSS SSSSSSSSSBBBBBX
            XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBX
            FFFFFFFFFFFFFFFFFFFFFFF
        XXXXXXX
    XXXX

    BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB
    XX XXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBBBX
       XXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBXBBBBBX
       XXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBXBBBBBX
       XXXXXXXXXXXXXXXXXXXXXXBB BBB BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBXBBBBBX
       XXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBXBBBBBX
       XXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBXBBBBBX
    X
        XX XXXXXXXXX XXXXXXXXXXXXX
    XXXX
    BBBBB

    XXXX XXXXXXXX XXXXXXXXXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBB BB BBBBBBB
              BB BBBBBBBBBBBBBBBBB
                 gettext(u'Survey Menu') 
              BBBB
                 gettext(u'Case List') 
              BBBBB
            BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBB
               gettext(u'Report Menu') 
            BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
               gettext(u'Advanced Menu') 
            BBBB BBBBBBBBBBBBBBBBBB BB BBBBBBBB
               gettext(u'Shadow Menu') 
            BBBB
               gettext(u'menu') 
            BBBBB
            XXX XXXXXXXXXXXXXXXXXXXX
               gettext(u'\n                Are you sure you want to delete this %(menu)s?\n              ') 
                SSS SSS SSSS SSS SSSS SS SSSSSS SSSS SSSSSSSSS
              
            XXXXX
          XXXXXX
          XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBBBX
                XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXX
                 gettext(u'You are about to delete') SSS SSS SSSSS SS SSSSSS
                XXXXXXXXFFFFFFFFFFFFFFFFXXXXXXXXXX
              XXXX
              XXX
                 gettext(u'\n                This action will also delete all forms in this %(menu)s.\n                ') 
                SSSS SSSSSS SSSS SSSS SSSSSS SSS SSSSS SS SSSS SSSSSSSSS
                
              XXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Cancel') 
              XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXX
                   gettext(u'Delete')  FFFFFFFFFFFFFFFF
              XXXXXXXXX
            XXXXXX
          XXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXX XXX
      XXXXXXXXXX XXXXXXXXXXXXXX XXX
    XXXXXXXXXX XXXXXXX XXX

XXXXXX
