# Generated by Django 2.2.24 on 2021-10-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_interfaces', '0022_domaincaserulerun_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticupdaterule',
            name='upstream_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
