# Generated by Django 2.2.24 on 2021-10-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_interfaces', '0023_auto_20210914_1726'),
        ('data_interfaces', '0023_add_automaticupdaterule_upstream_id'),
    ]

    operations = [
    ]
