# Generated by Django 2.2.27 on 2022-04-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('data_interfaces', '0028_auto_20220420_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationfilterdefinition',
            name='include_child_locations',
            field=models.BooleanField(default=True),
        ),
    ]
