# Generated by Django 3.2.23 on 2023-12-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_interfaces', '0034_case_name_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseduplicate',
            name='match_values',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
