# Generated by Django 5.2.14 on 2026-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_importer', '0014_rename_caseuploadrecord_domain_created_case_import_domain_21a470_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseuploadrecord',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='When set, this upload is hidden from the Recent Uploads list.'),
        ),
    ]
