# Generated by Django 3.2.16 on 2022-11-28 12:57

from django.db import migrations
from django.core.management import call_command


def _populate_repeater_names_command(_apps, _schema_editor):
    call_command('populate_repeater_names')


def _down(_apps, _schema_editor):
    # This function only exists to allow the migration to be reverted. Technically this function should delete
    # all repeater names (since the forward function populates it), but if we want to change the values for
    # whatever reason, we should create a new data migration. If we want to revert the `00010_add_repeater_name`
    # migration, it will in anycase drop the `name` column, rendering anything we do in this function useless.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0011_alter_sqlrepeater_name'),
    ]

    operations = [
        migrations.RunPython(_populate_repeater_names_command, _down),
    ]
