# Generated by Django 3.2.20 on 2023-08-21 19:39

from django.db import migrations, models
from django.db.models.deletion import DO_NOTHING


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0002_repeaters_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlrepeatrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sqlrepeatrecordattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunSQL(
            sql="""
            ALTER TABLE repeaters_repeatrecord
                DROP CONSTRAINT repeaters_repeatreco_repeater_id_01b51f9d_fk_repeaters,
                ADD CONSTRAINT repeaters_repeatreco_repeater_id_01b51f9d_fk_repeaters
                    FOREIGN KEY (repeater_id) REFERENCES repeaters_repeater(id)
                    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE repeaters_repeatrecordattempt
                DROP CONSTRAINT repeaters_repeatrecordattempt_repeat_record_id_cc88c323_fk,
                ADD CONSTRAINT repeaters_repeatrecordattempt_repeat_record_id_cc88c323_fk
                    FOREIGN KEY (repeat_record_id) REFERENCES repeaters_repeatrecord(id)
                    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
            ALTER TABLE repeaters_repeatrecord
                DROP CONSTRAINT repeaters_repeatreco_repeater_id_01b51f9d_fk_repeaters,
                ADD CONSTRAINT repeaters_repeatreco_repeater_id_01b51f9d_fk_repeaters
                    FOREIGN KEY (repeater_id) REFERENCES repeaters_repeater(id)
                    DEFERRABLE INITIALLY DEFERRED;
            ALTER TABLE repeaters_repeatrecordattempt
                DROP CONSTRAINT repeaters_repeatrecordattempt_repeat_record_id_cc88c323_fk,
                ADD CONSTRAINT repeaters_repeatrecordattempt_repeat_record_id_cc88c323_fk
                    FOREIGN KEY (repeat_record_id) REFERENCES repeaters_repeatrecord(id)
                    DEFERRABLE INITIALLY DEFERRED;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name='sqlrepeatrecord',
                    name='repeater',
                    field=models.ForeignKey(
                        on_delete=DO_NOTHING,
                        related_name='repeat_records',
                        to='repeaters.repeater',
                    ),
                ),
                migrations.AlterField(
                    model_name='sqlrepeatrecordattempt',
                    name='repeat_record',
                    field=models.ForeignKey(on_delete=DO_NOTHING, to='repeaters.sqlrepeatrecord'),
                ),
            ],
        ),
    ]
