# Generated by Django 3.2.14 on 2022-08-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motech', '0011_connectionsettings_is_deleted'),
        ('repeaters', '0007_migrate_to_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqlrepeater',
            name='connection_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repeaters', to='motech.connectionsettings'),
        ),
    ]
