# Generated by Django 3.2.23 on 2024-01-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0008_sqlrepeatrecords'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='sqlrepeatrecord',
                    name='unique_couch_id',
                ),
                migrations.RemoveField(
                    model_name='sqlrepeatrecord',
                    name='couch_id',
                ),
            ],
        ),
    ]


# SQL operations to be done later
#
# DROP INDEX IF EXISTS "unique_couch_id";
# ALTER TABLE "repeaters_repeatrecord" DROP COLUMN "couch_id" CASCADE;
