# Generated by Django 3.2.25 on 2024-04-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0010_rm_couch_artifacts'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS "unique_couch_id";
                ALTER TABLE "repeaters_repeatrecord" DROP COLUMN "couch_id" CASCADE;
            """,
            reverse_sql="""
                ALTER TABLE "repeaters_repeatrecord" ADD COLUMN "couch_id" varchar(36) NULL;
                CREATE UNIQUE INDEX "unique_couch_id" ON "repeaters_repeatrecord" ("couch_id")
                    WHERE "couch_id" IS NOT NULL;
            """,
        ),
    ]
