
CREATE TABLE IF NOT EXISTS public."config_report_icds-cas_static-child_health_cases_a46c129f"
(
  doc_id text NOT NULL,
  inserted_at text,
  person_name text,
  modified_on date,
  opened_on date,
  closed_on date,
  closed integer,
  owner_id text,
  case_id text NOT NULL,
  household_id text NOT NULL,
  mother_id text,
  awc_id text NOT NULL,
  supervisor_id text,
  block_id text,
  district_id text,
  state_id text,
  dob date,
  sex text,
  zscore_grading_wfa text,
  open_count integer,
  birth_weight numeric(64,16),
  weighed_birth_open_count integer,
  lbw_open_count integer,
  last_date_gmp date,
  open_weighed integer,
  is_ebf_open_count integer,
  diet_diversity_open_count integer,
  diet_quantity_open_count integer,
  hand_washing_open_count integer,
  timely_bf_open_count integer,
  comp_feeding_yes_open_count integer,
  is_pretem_or_lbw_open_count integer,
  sev_mal_open_count integer,
  mod_mal_open_count integer,
  norm_mal_open_count integer,
  open_not_weighed_count integer,
  date_death date,
  age_at_death_yrs integer,
  dead_child_count integer,
  resident text,
  disabled text,
  caste text,
  minority text,
  name text,
  mother_name text,
  bf_at_birth text,
  fully_immunized_date date,
  CONSTRAINT "config_report_icds-cas_static-child_health_cases_a46c129f_pkey" PRIMARY KEY (doc_id, case_id)
);