DROP TABLE IF EXISTS agg_awc_daily CASCADE;
CREATE TABLE agg_awc_daily
(
  state_id text NOT NULL,
  district_id text NOT NULL,
  block_id text NOT NULL,
  supervisor_id text NOT NULL,
  awc_id text NOT NULL,
  aggregation_level integer,
  date date NOT NULL,
  cases_household integer,
  cases_person integer,
  cases_person_all integer,
  cases_person_has_aadhaar integer,
  cases_child_health integer,
  cases_child_health_all integer,
  cases_ccs_pregnant integer,
  cases_ccs_pregnant_all integer,
  cases_ccs_lactating integer,
  cases_ccs_lactating_all integer,
  cases_person_adolescent_girls_11_14 integer,
  cases_person_adolescent_girls_15_18 integer,
  cases_person_adolescent_girls_11_14_all integer,
  cases_person_adolescent_girls_15_18_all integer,
  daily_attendance_open integer,
  num_awcs integer,
  num_launched_states integer,
  num_launched_districts integer,
  num_launched_blocks integer,
  num_launched_supervisors integer,
  num_launched_awcs integer
);