OPERATION_COLUMN = 'operation'
OLD_SITE_CODE_COLUMN = 'site_code'
NEW_SITE_CODE_COLUMN = 'new_site_code'
MERGE_OPERATION = 'Merge'
SPLIT_OPERATION = 'Split'
MOVE_OPERATION = 'Move'
EXTRACT_OPERATION = 'Extract'
VALID_OPERATIONS = [MERGE_OPERATION, SPLIT_OPERATION, MOVE_OPERATION, EXTRACT_OPERATION]
