BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBB
  BBBBBBBB BBB
  XXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXXXX
        XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
  BBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BB BBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXX
         gettext(u'\n          Excel mapping is disabled for bulk case imports. Excel columns will be used to directly\n          map to the relevant case properties.\n        ') 
          SSSSS SSSSSSS SS SSSSSSSS SSS SSSS SSSS SSSSSSSS SSSSS SSSSSSS SSSS SS SSSS SS SSSSSSSS
          SSS SS SSS SSSSSSSS SSSS SSSSSSSSSSS
        
      XXXX
    XXXXXX
  BBBBB

  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB

  XXXXX XXXXXXXXBBB BBBBBBBBBBBBBB BBBBBBX
        XXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX

    XXXXXXXXXX
      BB BBB BBBBBBBBBBBBBB
      XXXXXXXX
         gettext(u'Match Excel Columns to Case Properties') 
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBB BB BBBBBBBBXX
           gettext(u'Reset to default matching') 
        XXXXXXXXX
      XXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Excel Field') XXXXX
        XXXXXXXXX
        XXXX gettext(u'Case Property') XXXXX
        XXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXBBBBBX
           gettext(u'Create new property') 
        XXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXX
        BBBBB
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXXX
      XXXXXXXX
      XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add another matching') 
      XXXX
      BBBBB
    XXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Back') 
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Confirm Import') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXX
BBBBBBBB
