BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
  
BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXBBB BBBBBBBBBBBBBB BBBBBBX
        XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXXXXXX
      XXXXXXXX
         gettext(u'Upload an Excel File From Your Computer to Import From') 
      XXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
           gettext(u'Select a file to upload') 
        XXXXXXXX
        XXXX XXXXXXXXXX XXX XX XXXXXXXXXXXXXX XX XXXXXXXXXX XXXXX XXX XXXX XXXXX XXXX XXX XXXXXX XXXXX XXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XX
        XXXXXX
      XXXXXX
    XXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXX  gettext(u'Next step') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXX


  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB
