# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 20:12
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_add_broadcast_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertschedule',
            name='ui_type',
            field=models.CharField(default=b'X', max_length=1),
        ),
        migrations.AddField(
            model_name='timedschedule',
            name='ui_type',
            field=models.CharField(default=b'X', max_length=1),
        ),
    ]
