# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_casepropertytimedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='immediatebroadcast',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledbroadcast',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
