# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0018_minutes_to_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertschedule',
            name='use_utc_as_default_timezone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timedschedule',
            name='use_utc_as_default_timezone',
            field=models.BooleanField(default=False),
        ),
    ]
