BBBB BBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXX
    XXXX
      XXXX gettext(u'Name') XXXXX
      XXXX gettext(u'SMS Keyword') XXXXX
      XXXX gettext(u'Action Type') XXXXX
      XXXXXXXXX
    XXXXX
    XXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXXX XXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXXX XXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXXX
      XXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
      XXXXX
    XXXXX
    XXXXXXXX
  XXXXXXXX
XXXXXX
