BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'SMS Pricing') BBBBBBBB

BBBBB BBBBBBBBBB gettext(u'SMS Pricing') BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBB
  XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Pricing') XXXXXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXX
       gettext(u'SMS Pricing') 
    XXXXX
  XXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBB
  XX XXXXXXXXXXXXX
     gettext(u"\n      View SMS prices for using Dimagi's connections in each country.\n    ") 
      SSSS SSS SSSSSS SSS SSSSS SSSSSSSS SSSSSSSSSSS SS SSSS SSSSSSSS
    
  XXXX
  XXX
     gettext(u'\n      You can choose a connection for your project under Messaging -> SMS Connectivity\n    ') 
      SSS SSS SSSSSS S SSSSSSSSSS SSS SSSS SSSSSSS SSSSS SSSSSSSSS SS SSS SSSSSSSSSSSS
    
  XXXX
  XXX XX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBB BBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
       gettext(u'\n        Calculating SMS Rate...\n      ') 
        SSSSSSSSSSS SSS SSSSSSS
      
    XXXXXX
    XXXX XXXXXXXXXXXXX
         XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXX X XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXX XX
                        XXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXX
      XXXX
        XXXX
           gettext(u'Connection') 
        XXXXX
        XXXX
           gettext(u'Incoming') 
        XXXXX
        XXXX
           gettext(u'Outgoing') 
        XXXXX
      XXXXX
      XXXXXXXX
      XXXXXXX
      XXXX XX XXXXXXXX XXXXXXXXXX XXX
      XXXX
        XXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXX
        XXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXX
        XXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXX
      XXXXX
      XXXX XXX XXX
      XXXX
        XXXX
          XXXXXX gettext(u'Your own Android Gateway') XXXXXXX
        XXXXX
        XXXX
          XXXXXXXXX XXXXXXXXXXX
        XXXXX
        XXXX
          XXXXXXXXX XXXXXXXXXXX
      XXXXX
      XXXXXXXX
    XXXXXXXX
    XXX XX
    XXXX XXXXXXXXXXXX XXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXX
       gettext(u'\n        Pricing is per message sent or received. Fees are subject to change based on provider rates and exchange rates and are computed at the time the SMS is sent or received.\n      ') 
        SSSSSSS SS SSS SSSSSSS SSSS SS SSSSSSSSS SSSS SSS SSSSSSS SS SSSSSS SSSSS SS SSSSSSSS SSSSS SSS SSSSSSSS SSSSS SSS SSS SSSSSSSS SS SSS SSSS SSS SSS SS SSSS SS SSSSSSSSS
      
    XXXXXX
  XXXXXX
BBBBBBBB
