BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXXXXXX
      XXXXXXXX gettext(u'Stock Actions') XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX gettext(u'Edit Actions') XXXXXXXX
        XXXX XXXXXXXBBBBBBBBBBBBBBBXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'New Action') 
          XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXBBBBBBBBBBBBBBBBXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Save Settings') 
        XXXXXXXXX
      XXXXXX
    XXXXXX

    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX
  XXXXXXX
BBBBBBBB
