BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB


BBBBB BBBBBBBBBBBB
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX
         gettext(u'\n          You have a pending transfer with %(username)s\n        ') 
          SSS SSSS S SSSSSSS SSSSSSSS SSSS SSSSSSSSSSSS
        
      XXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
         gettext(u'\n          Resend Transfer Request\n        ') 
          SSSSSS SSSSSSSS SSSSSSS
        
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Cancel Transfer') X XX
      XXXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB


