BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB


BBBBB BBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXX
    XXXX
       gettext(u'\n        Use this to transfer your project to another user.\n      ') 
        SSS SSSS SS SSSSSSSS SSSS SSSSSSS SS SSSSSSS SSSSS
      
    XXXXX
  XXXXXX
  BBBBBB BBBB
BBBBBBBB

