# Generated by Django 4.2.20 on 2025-06-30 18:00

import corehq.preindex.django_migrations
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preindex', '0002_initial'),
    ]

    operations = [
        corehq.preindex.django_migrations.RequestReindex(
        ),
    ]
