BBBB BBBBBBBBBBBBBB
BBBB BBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
  XXXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXX XXXXXXX
  XX XX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX X XX
  XXXXXXXXXXX XXXXXXXXXXX XXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XX X XXXX XX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX X XX
  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
  XX X XXXX XX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXX X XX
  XXXXXX XXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXX
  XX X XXXX XX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXXX X XX
  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX
  XX X XXXX X XX
  XXXXXXX XXXX XXXXXXX
  XX X XX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
  XXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXX
      XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX gettext(u'Select') XXXXXXXXX
  XXXXXXX XXXXXXXXXXXXX
      XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXX
          XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXX gettext(u'Continue') XXXXXXXXX
XXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Case Detail') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
