BBBB BBBB
BBBB BBBBBBBBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXX X
            XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXXX
        X
        XX
    XXXX XXX XXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXX gettext(u'Expand Data Preview Section.') XXXXXXX
      XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Data Preview') XXXXXXX
      XXXXXX
    XXXXXXXXX

    XXXX XXXXXXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXX XXX

      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX

          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
              XXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXX XXXX
            XXXXXXXXX
          XXXXXX

          XXXX XXX XXXXX XXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXXXXX XXXXXXXX XXX X XXX
                XX
                  XXXXXXXXXX
                  XXXXXXXXXXXXXXXXX
                  XXXXXXXXXXX
                                XXXXX X
                                    XXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXX
                                XX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                            XX
                XXXX
              XXXXX
            XXXXX
          XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
      XXXXXX

      XXXX XXX XXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXX
                        XXXXX X
                            XXX XXXXXXXXXXXXXXXXXXXXXXX
                        XX
                        XXXX X XXXXXXX XXXXXXXX XXX X X
                    XX
          XXXX XXXXXXXXXXXXXXXXXXXX X
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXX
                    XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX
  XXXXXXXXX gettext(u'Empty String') XXXXXXXXXXX
  XXXXXXXXXX
  XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXX
  XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX
  XXXXX
    XXXX gettext(u'Showing the first')  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'lines...') XXXXX
    XX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Copy Full Evaluation to Clipboard') 
    XXXX
  XXXXXX
  XXXXXXXXXX
  XXXXXX XXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
  XXXXXXXXXX
  XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX
  XXXXX
    XXXX gettext(u'Showing the first')  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'lines...') XXXXX
    XX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Copy Full Trace to Clipboard') 
    XXXX
  XXXXXX
  XXXXXXXXXX
  XXXXXX XXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
  XXXXXXXXXX
  XXXXXX XXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXX XXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
                  XXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX XXXXXX XXXXXX X XXXXXXXX XXXXXXXXX XX XXXXXXXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXX
          XXXXXXXXXX XXXXXXXXXXXX
          XXXXXXXXXXXXXXX XXXXXXXXXX
          XXXXXXXXXXXXX
          XXXXXXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX
            XXX XXXXXXXXXXXX
        XXX
    XXXXXX
  XXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX gettext(u'Recent Queries') XXXXX
    XXXXXX
  XXXXXX
  XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                            XXXX X
                                XXXXXXXXXXX XXXXXXXXXX
                                XXXXXXXXXXX XXXXXXXXXXX
                                XXXXXXXXXXXXXXX XXXXXXXXXX
                                XXXXXXXXXXXXXX XXXXXXXXXX
                            X
                        XXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXX
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXX
                    XXXXXXXX
      XXXXX
      XXXXXXXX
    XXXXXXXX
  XXXXXX
  XXXX XXX XXX
  XXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXX gettext(u'No recent queries') XXXX
    XXXXXX
  XXXXXX
  XXXX XXX XXX
  XXXXXXXXXX
XXXXXXXXX
