BBBB BBBBBBBBBBBBBB
BBBB BBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX
    XXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX
    XXXXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XX
  XXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXX
  XXXXXX XX XXXXX XXX XXXXXXXXX XXXXXX
  XXXXXX X XXX XXXXXXXXXXX XXXXX XXXX XXXXXXXX XXXXXX XXXX XXXXXXXXX
  XXX XX XXXXXXXXX XXXX X XXX XXXXXXXXXX
  XX XX
  XX XX XXXXXXX XXXXXXXXX XXX XXXXXXXXXXX XX XXXXXXXXXX X XX
  XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
  XX X XX

XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XX XX XXXXXXXXXX X XX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXX
    XX X XXXX X XX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXX
    XX X XX
  XXXXX
  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXX X XXXXXXXXXXX X XX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXXXXX
      XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XX XX XXXXXXXXXX X XX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXX
    XX X XXXX X XX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XX XX XXXXXXXXX XXX XXXXXXX X XX
      XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XX X XXXX X XX
      XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XX X XX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXX
    XX X XX
  XXXXX
  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXX X XXXXXXXXXXX X XX XXXXXXX
  XXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
    XX XX XXXXXXXXXX X XX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXX
    XX X XXXX X XX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XX XX XXXXXXXXX XXX XXXXXXX X XX
      XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XX X XXXX X XX
      XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XX X XX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXX
    XX X XX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXX X XXXXXXXXXXX X XX XXXXXXX
    XXXXXX
  XXXXXX
  XX XX XXXXXXXXXX X X XXX XX X XX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XX X XX
  XX XX XXXXXXXXXX X X XXX XX X XX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XX X XX
  XX XX XXXXXXXXXX X X XXX XX X XX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
  XX X XX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX
    XXXXXX
    XXXX XXXXXXXXX XX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXXX
      XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXX XX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXX gettext(u'Dropdown toggle') XXXXXXX
    XXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Print') XXXXX
      XX XX XXXXXXXXXXXXXXXXXXXXXXXX X XX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Languages') XXXXX
      XX X XX
    XXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XX XXXXXXXXXXXXXXXXXXXXXXXX X XX
  XX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXX
  XX X XX
XXXXXXXXX
