BBBB BBBB
XXXXXXX
  XXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XX XXXXXXXXXXXX XX XXXXX X XX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXX gettext(u'List is empty.') XXXXXX
      XX X XXXX X XX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
      XX X XX
    XXXXX
  XXXXX
XXXXXXXX
