BBBB BBBBBBBBBBBBBB
BBBB BBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
    XX XX XXXXXXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX gettext(u'Clear') XXXXXX
        XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX gettext(u'Search') XXXXXX
        XXXXXXXXX
      XXXXXX
    XX X XX
    XX XX XXXXXXXXXXXXX X X XX XXXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXX XXXXX XXXXXXX
    XX X XX
    XX XX XXXXXXXXXXXXXXXXXXX X X XX XXXXXXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXXXX XX
      XXXXXX
    XX X XX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX
    XXXXXXXX
    XX XX XXXXXXXXXXXXXXXXX XXX
      XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX gettext(u'Clear') XXXXXX
      XXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX gettext(u'Search') XXXXXX
      XXXXXXXXX
    XX X XX
  XXXXXXX
XXXXXXXXX



XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXX XX
    XXXXXXXXX XX XXXXXXXXXXX XXX XXXXX X XXXXXXXXXX XX X XXXXXXXXXXXXXXX
           XX XX XXXXXXXXXX X XX XXXXXXXXXX X XX
           XX XX XXXXXXXXXXXXXX X XX XXXXXXXXXXX X XXXX
    XXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX X XXXX X XX XXXX
        XXX XXXX X XXXX X XX XX
      XXXXXXXX
      XX XX XXXXXXX XXXX XXX XXXXXXXXXXX XX XXXX XXX XXXXX X XX
      XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXXXXX  XXXXXXXXXXXXXXX XXXX X XXXX X XX XXX XXXXXXXXXXXXXXXXX XXXX X XXXX X XX XXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
      XXXXXX
      XX X XX
    XXXXXX
  XXXXX XXXXXXXXXX XXX
  XXXX XXXXXXXXXX XX
    XXXXXXXXX XX XXXXXXXXXXX XXX XXXXX X XXXXXXXXXX XX X XXXX X XXXXXXXXXXXXXXXX XX X XXXXXXXXXXXXXXXXXXX
           XX XX XXXXXXXXXXXXXX X XX XXXXXXXXXXX X XXXX

    XX XX XXXXXX XX XXXXXXXXXX X XX
    XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XX XXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXX X XXX
        XXXXXXX XXXXXXXXXXXXXXXXXX
        XX XXX XXXX XXX XX XXXXXXXXXXXXXXXXXXX X XX
        XXXXXXX XXXXXXXXXX XXX XXX XX XX XXXXXX XXX XXXXXXXXXXXX X XXXXXXXXXXXX X XXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX XX
        XXXXXXXXX
        XX X XX
    XXXXXXXXX

    XX X XXXX XX XXXXXX XX XXXXXXXXX X XX
    XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXX XX XXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXX X XXX
        XX XXX XXXX XXX XX XXXXXXXXXXXXXXXXXXX X XX
        XXXXXXX XXXXXXXXXX XXX XXX XX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXX X XXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX XX
        XXXXXXXXX
        XX X XX
    XXXXXXXXX

    XX X XXXX XX XXXXXX XXX XXXXXXX X XX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXX XXXX X XXXX X XX XXX
             XXXXXXXXXXX
             XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
             XXXXXXXXXX XXXXX XXX
             XX XX XXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXX X XXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XX X XXXX XX XXXXXX XXX XXXXXXXXXXXX X XX
    XXXXXX XXXXXXX XXXX X XXXX X XX XXX
           XXXXXXXXXXX
           XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
           XXXXXXXXXX XXXXX XXX
           XX XX XXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXX X XXX

    XX X XXXX XX XXXXXX XXX XXXXXXXXXXX X XX
    XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXX X XXXX X XX XXX XX XX XXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXX X XXX
      XXXXXXX XXXXXXXXXXXXXXXXXXX XXXX X XXXX X XX XXXXXXXXXXX
      XX XXX XXXX XXX XX XXXXXXXXXXXXXXXXXXX X XX
      XXXX XXXXXXX XXXX X XXXX X XXXXXXXXXX XXXXXX XXX XXX XXXXXXXXXXXXXXXXX
        XXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXX XXX XX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX X XXXXXXXXXXX X XXX
          XXX XXXXXXXXXXXXXXXXXXXXXXX XX
        XXXXXXXX
      XXXXXX
      XX X XX
    XXXXXXXXXXX

    XX X XXXX XX XXXXXX XX XXXXXXXXXX X XX
    XXXX XXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXX XXX XXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXX XXXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXX
    XXXXXX

    XX X XXXX X XX
    XXXXXX XXXXXXX XXXX X XXXX X XX XXX
           XXXXXXXXXXX
           XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
           XXXXXXXXXX XXXXX XXX
           XXXXXXXXXXXXXXXXX XXXXXXX XXX
           XX XX XXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXX X XXX
           XX X XX
           XX XX XXXXXXXXXXXXXX X XX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXXX XX XX XX XXXXXX XX X XX
           XX XX XXXXXXXXXXXXXXXXXXX X XX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXX X XXXXXXXXXXX X XXX
               gettext(u"Include results where '<%%- text %%>' is blank") 
            XXXXXXXX
            XX X XX
  XXXXX XXXXXXXXXX XXX
XXXXXXXXX
