BBBB BBBBBBBBBBBBBB
BBBB BBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXX X XX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Incomplete Forms') XXXXX
    XXXXX
  XXXXXX
  XX X XXXX X XX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
    XXXXXX
         gettext(u'\n          Web Apps deletes any Incomplete Forms that are more than 7 days old.\n          Please submit any forms with important data before then to avoid data loss.\n        ') 
          SSS SSSS SSSSSSS SSS SSSSSSSSSS SSSSS SSSS SSS SSSS SSSS S SSSS SSSS
          SSSSSS SSSSSS SSS SSSSS SSSS SSSSSSSSS SSSS SSSSSS SSSS SS SSSSS SSSS SSSSS
        
    XXXXXXX
  XXXXXX
  XX X XX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XX XXXXXXXXXXXXXXX X XX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXX gettext(u'Incomplete Forms') XXXXX
    XXXXXX
    XX X XX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXXXX
      XXXXXXXX
    XXXXXXXX
    XX XX XXXXXXXXX X XX
      BBBBB BBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBB
    XX X XX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXX
  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXX XXXXX XXXXXX
      XX XX XXXXXXXXXX X XXXXXX XXXXXXXX XXXXX X XX
      XXXXXX XXX XXXXXXXXXXXXXXX XX
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBB BBBBBXX
      XX XXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXX
XXXXXXXXX
