BBBB BBBBBBBBBBBBBB
BBBB BBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXXXX
      XXXXXXXX
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
         gettext(u'Done') 
      XXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX gettext(u'Use one question per screen') XXXXX
  XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX gettext(u'Set the application language') XXXXX
  XXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XX XXXXXXXXXXXXX XXXXXXXXXXXXXX X XX
      XXXXXXX XX XX XXXXX XXX XXXXXXXXXXXX X XXXXXXXXXXXX X XXX
      XXX XXXX XX
      XXXXXXXXX
      XX XX XX
    XXXXXXXXX
  XXXXX
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX gettext(u'Clear user data') XXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXX gettext(u'Clear') XXXXXXXXXXXXXX
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX gettext(u'Break Pending Request Locks') XXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXX gettext(u'Break') XXXXXXXXXXXXXX
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX gettext(u'Sync User Data') XXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXX gettext(u'Sync') XXXXXXXXXXXXXX
XXXXXXXXX
