BBBB BBBBBBBBBBBBBB
BBBB BBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXX
    XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX
          XXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXXXXXX XXXXX XXX
          XXXXXXXXXXXXXXXXXXX XXXXXXXX XX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXXXX
      XXXXXXXX
    XXXXXXXX
    XX XX XXXXXXXXX X XX
      BBBBB BBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBBBBB
    XX X XX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXX
  XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX
      XXXXXX XXXXXXXX XXXXXX
      XXXXXXXXX XXXXXXXXXX X X X X XXXXXXXXX XXXXXXXXX
      XXXXXXXXXXXXX XXXXXXXX X XXXXXXXXXXXXX X X XX X XXXXXXXXXXXXXXXXXXXXXX X XXX X XX XXXXXXXXXXXXXX
    XXXXX
  XXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
    XXXX
      XXXX gettext(u'Name') XXXXX
      XXXXXXX XXXXXXXXXXXXXXX X X X X XXXXXXXXXXXXXX XXXXXXX
    XXXXX
    XX XX XXXXXXXXXXXXXXX X XX
    XXXX
      XXXX gettext(u'Organization') XXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXX
    XXXX
      XXXX gettext(u'Organization Type') XXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXX
    XX X XX
    XXXX
      XXXX gettext(u'Date Registered') XXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX X XX
    XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX X XX
    XXXX
      XXXXXXX XXX XXXXXXX
      XXXXXXX XXXXX XXXXXXX
    XXXXX
    XX X XX
    XX XX XX
    XXXXXXXX
  XXXXXXXX

XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BB BBBBBBBBBBBBBBBBBBBBBBBBBB
    XX XX XXXXXXXXXXX X XX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXX XXXXXXX XX
    XXXXXX
    XX X XX
  BBBBB
XXXXXXXXX
