# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-15 13:22
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


from pillowtop.utils import safe_force_seq_int


def set_seq_int(apps, schema_editor):
    HistoricalPillowCheckpoint = apps.get_model('hqadmin', 'HistoricalPillowCheckpoint')
    for checkpoint in HistoricalPillowCheckpoint.objects.all():
        checkpoint.seq_int = safe_force_seq_int(checkpoint.seq)
        checkpoint.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hqadmin', '0008_delete_vcmmigration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PillowCheckpointSeqStore',
        ),
        migrations.AlterModelOptions(
            name='esrestorepillowcheckpoints',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AddField(
            model_name='esrestorepillowcheckpoints',
            name='seq_int',
            field=models.IntegerField(default=None, null=True),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='ESRestorePillowCheckpoints',
            new_name='HistoricalPillowCheckpoint',
        ),
        migrations.RunPython(set_seq_int),
    ]
