BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBB
XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
     gettext(u'Filter by Saved Area') XXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXX
                        XX
        XXXXXXXXX
    XXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXXXX XXX
         gettext(u'Export Area') 
    XXXX
    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXXXX XXX
         gettext(u'Save Area') 
    XXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX

XXXX XXX XXXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BBBBB BBBBBBBBBBB
    BB BBBBBBBBBBBBBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBB
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXBBBBBX
      XXXXXXXX
    BBBBB
  BBBBBBBB BBBBBBBBBBB
XXXXXX

XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Cases Missing GPS Data') 
        XXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Cases Missing GPS Data') XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX gettext(u'Case Name') XXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                            XXXXXXXX
                        XXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X XXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Selected Cases') 
        XXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Selected Cases') XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXX gettext(u'Case Name') XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX
                    XXXXXXXX
                XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX gettext(u'Cases on Map') 
        XXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'All Cases on Map') XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXX gettext(u'Case Name') XXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXX
                        XXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
XXXXXXXXX
BBBBBBBB
