# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 18:22
from __future__ import absolute_import, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = []
