# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-22 18:53

from django.core.management import call_command
from django.db import migrations, models

from corehq.util.django_migrations import skip_on_fresh_install


@skip_on_fresh_install
def _populate_sql_global_app_config(apps, schema_editor):
    call_command('populate_sql_global_app_config')


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0008_remove_uses_master_app_form_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLGlobalAppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('app_prompt', models.CharField(default='off', max_length=32, null=True,
                                                choices=[('on', 'on'), ('off', 'off'), ('forced', 'forced')])),
                ('apk_prompt', models.CharField(default='off', max_length=32, null=True,
                                                choices=[('on', 'on'), ('off', 'off'), ('forced', 'forced')])),
                ('apk_version', models.CharField(max_length=32, null=True)),
                ('app_version', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sqlglobalappconfig',
            unique_together=set([('domain', 'app_id')]),
        ),
        migrations.RunPython(_populate_sql_global_app_config,
                             reverse_code=migrations.RunPython.noop,
                             elidable=True),
    ]
