# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-12 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0010_sqlglobalappconfig'),
        ('app_manager', '0010_merge_20191211_1921'),
    ]

    operations = [
    ]
