BBBB BBBBBBBBBBBBBB
BBBB BBBB
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBB BB BBBBBB
             gettext(u'Show Deleted Questions') 
          BBBB
             gettext(u'Show Deleted Properties') 
          BBBBB
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXX
          BB BBBBBBBBBBBBBBBBBBBB BB BBBBBB
             gettext(u'\n              In order to show you your deleted questions, we need to process all of your old applications that have\n              had submissions. This operation can sometimes take a few minutes.\n            ') 
              SS SSSSS SS SSSS SSS SSSS SSSSSSS SSSSSSSSSS SS SSSS SS SSSSSSS SSS SS SSSS SSS SSSSSSSSSSSS SSSS SSSS
              SSS SSSSSSSSSSSS SSSS SSSSSSSSS SSS SSSSSSSSS SSSS S SSS SSSSSSSS
            
          BBBB
             gettext(u'\n              In order to show you your deleted properties, we need to process all of your old applications that have\n              had submissions. This operation can sometimes take a few minutes.\n            ') 
              SS SSSSS SS SSSS SSS SSSS SSSSSSS SSSSSSSSSSS SS SSSS SS SSSSSSS SSS SS SSSS SSS SSSSSSSSSSSS SSSS SSSS
              SSS SSSSSSSSSSSS SSSS SSSSSSSSS SSS SSSSSSSSS SSSS S SSS SSSSSSSS
            
          BBBBB
        XXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX X XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX
           gettext(u'Unable to process applications. Please report an issue if this persists') 
        XXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXXX X
                  XXXXXX XXXXXXXXXXXXXXXXXXXXX X XXX
              X
          XXXXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX
            XX
           gettext(u'Process') 
        XXXXXXXXX
      XXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXX XXX
  XXXXXXXXXX XXXXXXXXXXXXXX XXX
XXXXXXXXXX XXXXXXX XXX
