BBBB BBBBBBBBBBBBBB
BBBB BBBB
XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
           gettext(u'Show Deprecated Properties') 
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXX
           gettext(u'\n            In order to show you your deprecated properties, we need to refresh the page and\n            load in all the properties. This operation can sometimes take a few minutes.\n          ') 
            SS SSSSS SS SSSS SSS SSSS SSSSSSSSSS SSSSSSSSSSS SS SSSS SS SSSSSSS SSS SSSS SSS
            SSSS SS SSS SSS SSSSSSSSSSS SSSS SSSSSSSSS SSS SSSSSSSSS SSSS S SSS SSSSSSSS
          
        XXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX
            XX
           gettext(u'Refresh') 
        XXXXXXXXX
      XXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXX XXX
  XXXXXXXXXX XXXXXXXXXXXXXX XXX
XXXXXXXXXX XXXXXXX XXX
