BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXX XXXX XX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
       gettext(u'\n        Something went wrong! There was an error. If you see this error repeatedly please report it as issue.\n      ') 
        SSSSSSSSS SSSS SSSSSS SSSSS SSS SS SSSSSS SS SSS SSS SSSS SSSSS SSSSSSSSSS SSSSSS SSSSSS SS SS SSSSSS
      
    XXXX
    XXXXX XXXXXXXXXXXXX
          XXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBBBBBBB
      BB BBBBBBBBBBBB B B
        XXXX XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX
          XXXXX
            XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXX X
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXFFFFFFFFFX XXXXXXXXXXXXXXXXXXX XXXXXX
               gettext(u'Select all %(total_xForms)s forms') SSSSSS SSS SSSSSSSSSSSSSSSS SSSSS
            XXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                         gettext(u'(<span class="selectedCount ">0</span> forms selected)') SSSSSS SSSSSSSSSSSSSSSSSSSS SSSSSSSSSS SSSSS SSSSSSSSS
                        XXXXXXX
          XXXXXX
          XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
        XXXXXX
      BBBBB
      
    XXXXXXX
  XXXXXX
BBBBBBBB
