BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
           gettext(u'\n          <!-- ko if: selectAllMatches -->\n            Reassign %(total_cases)s selected cases to\n          <!-- /ko -->\n          <!-- ko ifnot: selectAllMatches -->\n            Reassign <span data-bind="text: selectedCount"></span> selected cases to\n          <!-- /ko -->\n          ') 
          SSSS SS SSS SSSSSSSSSSSSSSSS SSS
            SSSSSSSS SSSSSSSSSSSSSSS SSSSSSSS SSSSS SS
          SSSS SSS SSS
          SSSS SS SSSSSS SSSSSSSSSSSSSSSS SSS
            SSSSSSSS SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSS SSSSSSSS SSSSS SS
          SSSS SSS SSS
          
        XXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
             gettext(u'Select all')   XXXXX
          XXXXXXXX
        XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXX XXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                             XXXXXXXXXXXXX XXXXXXXXXX
                             XXXXXXXXXXXXXXX X gettext(u'Select New Owner...') XX
                             XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX gettext(u'Reassign') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Reassign') XXXXXXXXX
      XXXXXXX
    XXXXXX
    
  XXXXXX
BBBBBBBB

BBBBB BBBBBB 
  XXXX XXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX gettext(u'Case Reassignment') XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
