# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 06:45
from __future__ import absolute_import, unicode_literals

from django.db import migrations

from corehq.sql_db.operations import RawSQLMigration

migrator = RawSQLMigration(('custom', 'icds_reports', 'migrations', 'sql_templates'))


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0035_add_pnc_aggregate_models'),
    ]

    operations = [
        migrator.get_migration('update_tables17.sql'),
    ]
