# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 20:32
from __future__ import absolute_import, unicode_literals

from django.db import migrations

from corehq.sql_db.operations import RawSQLMigration

migrator = RawSQLMigration(('custom', 'icds_reports', 'migrations', 'sql_templates'))


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0036_allow_null_for_pnc_tables'),
    ]

    operations = [
        migrator.get_migration('update_tables18.sql'),
    ]
