# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 9:25
from __future__ import absolute_import, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0041_added_num_anc_visits_to_agg_awc_montlhy_view'),
    ]

    operations = []
