# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 12:43
from __future__ import unicode_literals
from __future__ import absolute_import

import jsonfield
from architect.commands import partition

from django.db import migrations, models
from corehq.sql_db.operations import HqRunPython


def add_partitions(apps, schema_editor):
    partition.run({'module': 'custom.icds_reports.models'})


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0047_added_new_wasting_and_stunting_columns_to_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICDSAuditEntryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(db_index=True, max_length=254)),
                ('assigned_location', models.CharField(max_length=256, null=True)),
                ('ip_address', models.CharField(max_length=15, null=True)),
                ('url', models.TextField()),
                ('post_data', jsonfield.fields.JSONField(default=dict)),
                ('get_data', jsonfield.fields.JSONField(default=dict)),
                ('session_key', models.CharField(max_length=32)),
                ('time_of_use_start', models.DateTimeField(auto_now_add=True)),
                ('time_of_use_end', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'icds_audit_entry_record',
            },
            bases=(models.Model,)
        ),
        migrations.AddIndex(
            model_name='icdsauditentryrecord',
            index=models.Index(fields=['username'], name='icds_audit__usernam_65400c_idx'),
        ),
        HqRunPython(add_partitions),
    ]
