# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-12 09:26
from __future__ import unicode_literals
from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0060_disha_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatesqlprofile',
            name='latest_aggregation',
            field=models.DateTimeField(null=True),
        ),
    ]
