# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-21 13:50
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0067_ccsrecordmonthly_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='CcsRecordMonthlyView',
            name='lactating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
