# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-11 14:35
from __future__ import unicode_literals
from __future__ import absolute_import

from django.db import migrations, models
from corehq.sql_db.operations import RawSQLMigration
from custom.icds_reports.utils.migrations import get_view_migrations

migrator = RawSQLMigration(('custom', 'icds_reports', 'migrations', 'sql_templates'))


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0069_valid_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='CcsRecordMonthlyView',
            name='open_in_month',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
    operations.extend(get_view_migrations())
