# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 09:20
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations

from corehq.sql_db.operations import RawSQLMigration


def get_disha_migration():
    migrator = RawSQLMigration(('custom', 'icds_reports', 'migrations', 'sql_templates', 'database_views'))
    return migrator.get_migration('disha_indicators.sql')


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0084_anc_abnormalities'),
    ]

    operations = [
        get_disha_migration(),
        migrations.RemoveField(
            model_name='dishaindicatorview',
            name='awc_id',
        ),
        migrations.RemoveField(
            model_name='dishaindicatorview',
            name='awc_name',
        ),
        migrations.RemoveField(
            model_name='dishaindicatorview',
            name='supervisor_id',
        ),
        migrations.RemoveField(
            model_name='dishaindicatorview',
            name='supervisor_name',
        )
    ]
