# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 06:17
from __future__ import unicode_literals
from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0088_child_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatechildhealthdailyfeedingforms',
            name='lunch_count',
            field=models.PositiveSmallIntegerField(help_text='Number of days the child had the lunch', null=True),
        ),
    ]
