# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 06:17
from __future__ import unicode_literals
from __future__ import absolute_import

from django.db import migrations, models
from corehq.sql_db.operations import RawSQLMigration


migrator = RawSQLMigration(('custom', 'icds_reports', 'migrations', 'sql_templates'))


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0090_auto_20190205_0442'),
    ]

    operations = [
        migrator.get_migration('update_tables38.sql')
    ]
