# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 10:41
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models

from corehq.sql_db.operations import RawSQLMigration

migrator = RawSQLMigration(('custom', 'icds_reports', 'migrations', 'sql_templates'))


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0100_add_supervisor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregateawcinfrastructureforms',
            name='supervisor_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aggregatechildhealthdailyfeedingforms',
            name='supervisor_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aggregatechildhealthpostnatalcareforms',
            name='supervisor_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aggregatechildhealththrforms',
            name='supervisor_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aggregategrowthmonitoringforms',
            name='supervisor_id',
            field=models.TextField(null=True),
        ),
        migrator.get_migration('update_tables43.sql')
    ]
