# Generated by Django 1.11.16 on 2018-10-04 21:18

from django.db import migrations, models

from corehq.sql_db.operations import RawSQLMigration

migrator = RawSQLMigration(('custom', 'icds_reports', 'migrations', 'sql_templates'))


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0149_auto_20191115_1142')
    ]

    operations = [
        migrations.AddField(
            model_name='aggregateccsrecorddeliveryforms',
            name='num_children_del',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of children born'),
        ),
        migrations.AddField(
            model_name='aggregateccsrecorddeliveryforms',
            name='still_live_birth',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of children alive'),
        ),
        migrations.RunSQL("ALTER table ccs_record_monthly ADD COLUMN husband_name text"),
        migrations.RunSQL("ALTER table ccs_record_monthly ADD COLUMN lmp DATE"),
        migrations.RunSQL("ALTER table ccs_record_monthly ADD COLUMN migration_status SMALLINT"),
        migrations.RunSQL("ALTER table ccs_record_monthly ADD COLUMN where_born SMALLINT"),
        migrations.RunSQL("ALTER table ccs_record_monthly ADD COLUMN num_children_del SMALLINT"),
        migrations.RunSQL("ALTER table ccs_record_monthly ADD COLUMN still_live_birth SMALLINT"),
    ]
