# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 21:31
from __future__ import unicode_literals

import os

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('icds_reports', '0150_update_agg_awc_monthly_view'),
    ]

    operations = [
        migrations.RunSQL(
            open(os.path.join(
                'custom', 'icds_reports', 'migrations',
                'sql_templates', 'drop_duplicate_indexes.sql')).read(),
            "SELECT 1",
        )
    ]
