# Generated by Django 1.11.16 on 2019-10-28


from django.db import migrations, models
import custom.icds_reports.models.aggregate
from corehq.sql_db.operations import RawSQLMigration
from custom.icds_reports.utils.migrations import (
    get_composite_primary_key_migrations,
)
from corehq.sql_db.connections import is_citus_db
from custom.icds_reports.const import AGG_PRIMARY_PRIVATE_SCHOOL_FORMS
from custom.icds_reports.utils.migrations import (
    create_citus_distributed_table
)


migrator = RawSQLMigration(('custom', 'icds_reports', 'migrations', 'sql_templates', 'database_views'))


def _distribute_citus_tables(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if not is_citus_db(cursor):
            return

        for table, col in [(AGG_PRIMARY_PRIVATE_SCHOOL_FORMS, 'supervisor_id')]:
            create_citus_distributed_table(cursor, table, col)


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0150_update_agg_awc_monthly_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatePrimaryPrivateSchoolForms',
            fields=[
                ('state_id', models.CharField(max_length=40)),
                ('supervisor_id', models.TextField(null=True)),
                ('month', models.DateField(help_text='Will always be YYYY-MM-01')),
                ('person_case_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('admitted_private_school', models.NullBooleanField(null=True)),
                ('date_admission_private_school', models.DateField(null=True, help_text='Will always be YYYY-MM-01')),
                ('returned_private_school', models.NullBooleanField(null=True)),
                ('date_return_private_school', models.DateField(null=True, help_text='Will always be YYYY-MM-01')),
                ('admitted_primary_school', models.NullBooleanField(null=True)),
                ('date_admission_primary_school', models.DateField(null=True)),
            ],
            options={
                'db_table': 'icds_dashboard_primary_private_school_forms',
            },
            bases=(models.Model, custom.icds_reports.models.aggregate.AggregateMixin),
        ),
        migrations.AlterUniqueTogether(
            name='aggregateprimaryprivateschoolforms',
            unique_together=set([('supervisor_id', 'person_case_id', 'month')]),
        ),
        migrations.RunSQL("ALTER table child_health_monthly ADD COLUMN primary_private_school INTEGER"),
        migrator.get_migration('child_health_monthly.sql')
    ]
    
    #below to steps are to make primaryprivateschool table distributed
    operations.extend(get_composite_primary_key_migrations(['aggregateprimaryprivateschoolforms']))
    operations.append(migrations.RunPython(_distribute_citus_tables, migrations.RunPython.noop))



