# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-24
from __future__ import unicode_literals

from corehq.sql_db.operations import RawSQLMigration
from django.db import migrations

from custom.icds_reports.const import SQL_TEMPLATES_ROOT

migrator = RawSQLMigration((SQL_TEMPLATES_ROOT, 'database_views'))


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0157_updated_unique_constraint'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE agg_ccs_record ADD COLUMN lactating_all_registered_in_month INTEGER'),
        migrations.RunSQL('ALTER TABLE agg_ccs_record ADD COLUMN pregnant_all_registered_in_month INTEGER'),
        migrations.RunSQL('ALTER TABLE agg_ccs_record ADD COLUMN lactating_registered_in_month INTEGER'),
        migrations.RunSQL('ALTER TABLE agg_ccs_record ADD COLUMN pregnant_registered_in_month INTEGER'),
        migrations.RunSQL('ALTER TABLE agg_awc ADD COLUMN cases_ccs_lactating_all_reg_in_month INTEGER'),
        migrations.RunSQL('ALTER TABLE agg_awc ADD COLUMN cases_ccs_pregnant_all_reg_in_month INTEGER'),
        migrations.RunSQL('ALTER TABLE agg_awc ADD COLUMN cases_ccs_lactating_reg_in_month INTEGER'),
        migrations.RunSQL('ALTER TABLE agg_awc ADD COLUMN cases_ccs_pregnant_reg_in_month INTEGER'),

    ]
