# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-16
from __future__ import unicode_literals

import custom.icds_reports.models.aggregate
from django.db import migrations, models
from custom.icds_reports.utils.migrations import (
    get_composite_primary_key_migrations,
)
from custom.icds_reports.const import BIHAR_API_MOTHER_DETAILS_TABLE


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0176_kpi_api_view'),
    ]

    operations = [

        migrations.CreateModel(
            name='BiharAPIMotherDetails',
            fields=[
                ('state_id', models.TextField(null=True)),
                ('supervisor_id', models.TextField(null=True)),
                ('month', models.DateField()),
                ('household_id', models.TextField(null=True)),
                ('ccs_case_id', models.TextField(primary_key=True, serialize=False)),
                ('person_id', models.TextField(null=True)),
                ('married', models.SmallIntegerField(null=True)),
                ('husband_id', models.TextField(null=True)),
                ('husband_name', models.TextField(null=True)),
                ('last_preg_year', models.IntegerField(null=True)),
                ('last_preg_tt', models.SmallIntegerField(null=True)),
                ('is_pregnant', models.SmallIntegerField(null=True)),
                ('preg_reg_date', models.DateField(null=True)),
                ('tt_1', models.DateField(null=True)),
                ('tt_2', models.DateField(null=True)),
                ('tt_booster', models.DateField(null=True)),
                ('hb', models.SmallIntegerField(null=True)),
                ('add', models.DateField(null=True)),
            ],
            options={
                'db_table': 'bihar_api_mother_details',
            },
            bases=(models.Model, custom.icds_reports.models.aggregate.AggregateMixin),
        ),
        migrations.AlterUniqueTogether(
            name='biharapimotherdetails',
            unique_together=set([('month', 'state_id', 'supervisor_id', 'ccs_case_id')]),
        ),
    ]

    operations.extend(get_composite_primary_key_migrations(['biharapimotherdetails']))

    operations += [
        migrations.RunSQL(f"ALTER TABLE {BIHAR_API_MOTHER_DETAILS_TABLE} RENAME TO {BIHAR_API_MOTHER_DETAILS_TABLE}_old"),
        migrations.RunSQL(f"CREATE TABLE {BIHAR_API_MOTHER_DETAILS_TABLE} (LIKE {BIHAR_API_MOTHER_DETAILS_TABLE}_old INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING INDEXES) PARTITION BY LIST (month)"),
        migrations.RunSQL(f"SELECT create_distributed_table('{BIHAR_API_MOTHER_DETAILS_TABLE}', 'supervisor_id')"),
        migrations.RunSQL(f"DROP TABLE {BIHAR_API_MOTHER_DETAILS_TABLE}_old"),
    ]
