# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 19:55
from __future__ import unicode_literals

import custom.icds_reports.models.aggregate
from django.db import migrations, models

from custom.icds_reports.utils.migrations import get_view_migrations, get_composite_primary_key_migrations
from custom.icds_reports.const import BIHAR_API_CHILD_VACCINE_TABLE


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0177_auto_20200408_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiharAPIChildVaccine',
            fields=[
                ('month', models.DateField()),
                ('supervisor_id', models.TextField(null=True)),
                ('time_birth', models.TextField(null=True)),
                ('child_alive', models.SmallIntegerField(null=True)),
                ('father_name', models.TextField(null=True)),
                ('father_id', models.TextField(null=True)),
                ('mother_id', models.TextField(null=True)),
                ('mother_name', models.TextField(null=True)),
                ('case_id', models.TextField(null=True)),
                ('dob', models.DateField(null=True)),
                ('private_admit', models.SmallIntegerField(null=True)),
                ('primary_admit', models.SmallIntegerField(null=True)),
                ('date_last_private_admit', models.DateField(null=True)),
                ('date_return_private', models.DateField(null=True))
            ],
            options={
                'db_table': 'bihar_api_child_vaccine',
            },
            bases=(models.Model, custom.icds_reports.models.aggregate.AggregateMixin),
        ),
        migrations.AlterUniqueTogether(
            name='biharapichildvaccine',
            unique_together=set([('month', 'supervisor_id', 'case_id')]),
        )
    ]

    operations.extend(get_composite_primary_key_migrations(['biharapichildvaccine']))

    operations += [
        migrations.RunSQL(f"SELECT create_distributed_table('{BIHAR_API_CHILD_VACCINE_TABLE}', 'supervisor_id')"),
    ]

    operations += get_view_migrations()
