# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0178_rebuild_chm_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='biharapidemographics',
            name='last_class_attended_ever',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='biharapidemographics',
            name='out_of_school_status',
            field=models.SmallIntegerField(null=True),
        ),
    ]
