# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-21 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0189_new_fields_to_bihar_demogrpahics'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='child_thr_0_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='child_thr_15_20_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='child_thr_1_7_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='child_thr_21_24_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='child_thr_25_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='child_thr_8_14_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='child_thr_eligible',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='lw_thr_0_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='lw_thr_15_20_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='lw_thr_1_7_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='lw_thr_21_24_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='lw_thr_21_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='lw_thr_25_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='lw_thr_8_14_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='lw_thr_eligible',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='pw_thr_0_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='pw_thr_15_20_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='pw_thr_1_7_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='pw_thr_21_24_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='pw_thr_25_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='pw_thr_8_14_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aggservicedeliveryreport',
            name='pw_thr_eligible',
            field=models.IntegerField(null=True),
        ),
    ]
