# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models
from custom.icds_reports.utils.migrations import get_view_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0200_update_chm_ccs_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='awwincentivereport',
            name='awc_site_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]

    operations.extend(get_view_migrations())
