BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB

BBBBB BBBBBBBBBBB
  BBBBBBBB BBB
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
  BBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBB BBBBBBBBBBBBBBBB
  XXX XXXXXXXXXXXXXXXXXXX
    BBB BBBB BB BBBBB
      XXXX
        XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    BBBBBB
  XXXXX
  BBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
  XXXXXX
  BBBBB BBBBBBBBBBBB
  BBBBBBBB
BBBBBBBB
