BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'Total Due:') 
      XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    BB BBB BBBBBBBBBBBBBBBBBBBBBBBBB
      XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX
           gettext(u'Pay by Credit Card') 
        XXXXXXXXX
      XXXX
      XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Pay by Wire') 
        XXXXXXXXX
      XXXX
    BBBB
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             gettext(u"Not Billing Admin, Can't Make Payment") 
        XXXXXXX
    BBBBB
  XXXXXX
  XXXX gettext(u'Billing Statements')  XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Unpaid') XXXXXXXXXXXXX
  XXX
    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                           XXXXXXXX XXXXXXXXXXXXXX
       gettext(u'Show Only Unpaid Statements') 
    XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
                           XXXXXXXX XXXXXXXXXXXXXXXXX
       gettext(u'Show All Statements') 
    XXXXXXXXX
  XXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBB
      XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    BBBBB
    XXX XXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXX XX XXX XXXXXXXXXXXXXX XXX
      BB BBB BBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Make Payment') 
        XXXXXXXXX
      BBBB
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                     gettext(u"Not Billing Admin, Can't Make Payment") 
                XXXXXXX
      BBBBB
      XXXX XXX XXX
    XXXXX
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXXXX
         XXXXXXXXXXXXXXXX X XXXXX XXXXXX XX
         XXXXXXXXXXXXXXXX gettext(u'Download') XXXX
    XXXXX
  XXXXXXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXX XXX XX
      XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
         gettext(u'Payment Amount') 
      XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX
          XXXXXXX
            XXXXXX XXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXX
             gettext(u'\n              Pay the full balance: $<span data-bind="text: balance"></span>\n            ') 
              SSS SSS SSSS SSSSSSSS SSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSS
            
          XXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXX
             gettext(u'\n              Pay a portion of the balance:\n            ') 
              SSS S SSSSSSS SS SSS SSSSSSSS
            
            XXXX XXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                   XXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXXX XX XX
            XXXXXX
          XXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'\n              Please enter an amount that\'s between $0.50 and $<span data-bind="text: balance"></span>.\n            ') 
              SSSSSS SSSSS SS SSSSSS SSSSSS SSSSSSS SSSSS SSS SSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSS
            
          XXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'\n              You can\'t enter an amount between $<span data-bind="text: maxPartialAmount"></span>\n              and $<span data-bind="text: balance"></span> because\n              the next transfer will be below the minimum amount of $0.50.\n            ') 
              SSS SSSSS SSSSS SS SSSSSS SSSSSSS SSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSS
              SSS SSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSS SSSSSSS
              SSS SSSS SSSSSSSS SSSS SS SSSSS SSS SSSSSSS SSSSSS SS SSSSSS
            
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'\n      Payment for Statement No. <span data-bind="text: invoiceNumber"></span>\n    ') 
      SSSSSSS SSS SSSSSSSSS SSS SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSS
    
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Bulk Wire Payment') 
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Bulk Payment') 
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Thank you for your payment!') 
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'\n      Thank you for your upcoming wire payment.\n      An invoice with your total balance and the instructions to do the wire payment\n      has just been sent to your email address.\n    ') 
      SSSSS SSS SSS SSSS SSSSSSSS SSSS SSSSSSSS
      SS SSSSSSS SSSS SSSS SSSSS SSSSSSS SSS SSS SSSSSSSSSSSS SS SS SSS SSSS SSSSSSS
      SSS SSSS SSSS SSSS SS SSSS SSSSS SSSSSSSS
    
  XXXXXXXXX
BBBBBBBB

BBBBB BBBBBB
  BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB
  BBBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB
  BBBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB
BBBBBBBB
