BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBB BBBB
  BBBBBBBBBBBBBBBBB BBBBBBB BBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBB BBBBBB
  XX XXXXXXXXXXX XXXXXXXXXXXXX
     gettext(u'\n      You are about to subscribe to the <strong>%(p)s Software Plan</strong>.<br/>\n      Please update your billing information below before continuing.\n    ') 
      SSS SSS SSSSS SS SSSSSSSSS SS SSS SSSSSSSSSSSSS SSSSSSSS SSSSSSSSSSSSSSSSSSS
      SSSSSS SSSSSS SSSS SSSSSSS SSSSSSSSSSS SSSSS SSSSSS SSSSSSSSSSS
    
  XXXX

  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX
BBBBBBBB
