BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB

  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB

    XXXXX XXXXXXXXBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
          XXXXXXXXXXXXX
          XXXXXXXXXXXXX
      BBBBBBBBBB
      XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XX
      XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      BB BBB BBBBBBBBB
        XXX XX
        XX XXXXXXXXXXXXXXXXXXXX
           gettext(u"\n            Clicking the 'Confirm Plan' button below will bring you to a page where you can confirm your billing information.\n          ") 
            SSSSSSSS SSS SSSSSSSS SSSSS SSSSSS SSSSS SSSS SSSSS SSS SS S SSSS SSSSS SSS SSS SSSSSSS SSSS SSSSSSS SSSSSSSSSSSS
          
        XXXX
      BBBBB
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
          BB BBBBBBBBB
             gettext(u'Select different option') 
          BBBB
             gettext(u'Select different plan') 
          BBBBB
        XXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBB
             gettext(u'Confirm Pause') 
          BBBB
             gettext(u'Confirm Plan') 
          BBBBB
        XXXXXXXXX
      XXXXXX
    XXXXXXX

  XXXXXX
BBBBBBBB

BBBBB BBBBBB
  XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXX
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBB
               gettext(u'Before you pause...') 
            BBBB
               gettext(u'Downgrading?') 
            BBBBB
          XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXX
             gettext(u"\n              We'd love to make CommCare work better for you.\n              Please help us by answering these simple questions.\n            ") 
              SSSS SSSS SS SSSS SSSSSSSS SSSS SSSSSS SSS SSSS
              SSSSSS SSSS SS SS SSSSSSSSS SSSSS SSSSSS SSSSSSSSSS
            
          XXXX

          XXX
            BB BBBBBBBBB
               gettext(u'\n                Why are you pausing your subscription today?\n              ') 
                SSS SSS SSS SSSSSSS SSSS SSSSSSSSSSSS SSSSSS
              
            BBBB
               gettext(u'\n                Why are you downgrading your subscription today?\n              ') 
                SSS SSS SSS SSSSSSSSSSS SSSS SSSSSSSSSSSS SSSSSS
              
            BBBBB
            XXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                               XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX

          XXXX XX XXX XXXXXXXXXXXXX XXX
            XXX
               gettext(u'\n                Do you think your project may start again?\n              ') 
                SS SSS SSSSS SSSS SSSSSSS SSS SSSSS SSSSSS
              
              XXXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXX
                   gettext(u'Yes') 
                XXXXXXXXX
                XXXXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXX
                   gettext(u'No') 
                XXXXXXXXX
              XXXXXXXXX
            XXXX
          XXXX XXX XXX

          XXXX XX XXX XXXXXXXXXXXXXX XXX
            XXX
               gettext(u'\n                Could you indicate which new tool you’re using?\n              ') 
                SSSSS SSS SSSSSSSS SSSSS SSS SSSS SSSSSS SSSSSS
              
              XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXX
            XXX
               gettext(u'\n                Why are you switching to a new tool?\n              ') 
                SSS SSS SSS SSSSSSSSS SS S SSS SSSSS
              
              XXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                 XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
          XXXX XXX XXX

          XXXX XX XXX XXXXXXXXXXXXXX XXX
            XXX
               gettext(u'\n                Please specify\n              ') 
                SSSSSS SSSSSSS
              
              XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
          XXXX XXX XXX

          XXX
             gettext(u'\n              Please let us know any other feedback you have\n            ') 
              SSSSSS SSS SS SSSS SSS SSSSS SSSSSSSS SSS SSSS
            
            XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX

        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
               gettext(u'Continue') 
            XXXXXXXXX
          XXXX XXX XXX
          XXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXXX
               gettext(u'Continue') 
            XXXXXXXXX
          XXXX XXX XXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
