BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  XX XXXXXXXXXXX XXXXXXXXXXXXX
     gettext(u'\n      You are renewing your plan to the <strong>%(p_name)s</strong>.\n    ') 
      SSS SSS SSSSSSSS SSSS SSSS SS SSS SSSSSSSSSSSSSSSSSSSSSSSSSSSS
    
    BB BBBBBBBBBBBBBB BB BBBBBBBBB
       gettext(u'— which matches your current feature usage.') 
    BBBBB
    XXX XX
     gettext(u'\n      It will be renewed automatically on <strong>%(start_date)s</strong>.\n    ') 
      SS SSSS SS SSSSSSS SSSSSSSSSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
    
  XXXX
  BB BBBBBBBBBBBBBB BB BBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
       gettext(u'\n        <h4>Note: You are renewing to a different plan</h4>\n        <p>The new plan will take effect on <strong>%(start_date)s</strong> and will cost <strong>%(monthly_fee)s</strong>/month.</p>\n      ') 
        SSSSSSSSS SSS SSS SSSSSSSS SS S SSSSSSSSS SSSSSSSSS
        SSSSSS SSS SSSS SSSS SSSS SSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSS SSSS SSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
      
    XXXXXX
  BBBBB
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      BBBBBB BBBBBBBBBBBB
    XXXXXX
  XXXXXX
BBBBBBBB
