BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBB
  BB BBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBB
    XX XXXXXXXXXXXXX
       gettext(u'\n        <strong>%(feature_name)s</strong> is only available to projects\n        subscribed to <strong>%(plan_name)s</strong> plan or higher.\n        To access this feature, you must subscribe to the\n        <strong>%(plan_name)s</strong> plan.\n      ') 
        SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SS SSSS SSSSSSSSS SS SSSSSSSS
        SSSSSSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSS SS SSSSSSS
        SS SSSSSS SSSS SSSSSSSS SSS SSSS SSSSSSSSS SS SSS
        SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSS
      
    XXXX
    BB BBB BBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'\n          You must be a Project Administrator to make Subscription changes.\n        ') 
          SSS SSSS SS S SSSSSSS SSSSSSSSSSSSS SS SSSS SSSSSSSSSSSS SSSSSSSS
        
      XXXXXX
    BBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Read more about our plans') XXXX
      BB BBBBBBBBBBBBBBB
        XX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Change My Plan') XXXX
      BBBBB
    XXXXXX
  BBBBB
BBBBBBBB
