BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBB
  XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Load EVERYTHING') XXXXXXXXXXXXX
    XXX XX
    BBB BBBBBBBB BB BBBBB
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXFFFFFFFFFFFFFFFFFFFFXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXX
               XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
             gettext(u'Load Property') 
          XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    BBBBBB
  XXXXXX
BBBBBBBB
