BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBB

  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXXXXXXXXX
            BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXXXX
              XXXX
                XXX XXXXXXXXXXXXXXXXX gettext(u'Application') XXXXX
                XXX XXXXXXXXXXXXXXXXX gettext(u'Location') XXXXX
                XXX XXXXXXXXXXXXXXXXX gettext(u'Version') XXXXX
                XXX XXXXXXXXXXXXXXXXX gettext(u'Last Activity') XXXXX
                XXX XXXXXXXXXXXXXXXXX gettext(u'Action') XXXXX
              XXXXX
              XXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXX XXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX
                  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                     gettext(u'Activated On : ') 
                    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                     gettext(u'Deactivated On : ') 
                    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXX
                XXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                          XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
                                            XXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXX
                       XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXX
                  XXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
                     gettext(u'Could not update!') 
                    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX
                XXXXX
              XXXXX
              XXXXXXXX
            XXXXXXXX
          BBBBB
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
