BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBB BBBBB
    XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Search') XXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Add') XXXXXXXXX
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBB BBBBBBBBBBB
        XXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBB BBBBBBBBBBBBB
        XXXXXXX
      XXXXXX
    XXXXXX

    BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXX
        XXXX
          XXX XXXXXXXXXXXXXXXXX gettext(u'Application') XXXXX
          XXX XXXXXXXXXXXXXXXXX gettext(u'Profile') XXXXX
          XXX XXXXXXXXXXXXXXXXX gettext(u'Version') XXXXX
          XXX XXXXXXXXXXXXXXXXX gettext(u'Status') XXXXX
          XXX XXXXXXXXXXXXXXXXX gettext(u'Action') XXXXX
        XXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXXXXXXX XXXXXX XXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
                                      XXXXXXXX XXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXX XXXXXXX XX XXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            XXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
               gettext(u'Could not update!') 
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
          XXXXX
        XXXXX
        XXXXXXXX
      XXXXXXXX
    BBBBB

BBBBBBBB
