BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBB
BBBB BBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  XX XXXXXXXXXXX XXXXXXXXXXXXX
     gettext(u'\n      You are renewing your <strong>%(p)s Edition</strong> subscription.\n    ') 
      SSS SSS SSSSSSSS SSSS SSSSSSSSSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSS
    
  XXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  XXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXX
        XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
    BBBBBBBBBB

    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
         gettext(u'Next') 
      XXXXXXXXX
    XXXXXX
  XXXXXXX
BBBBBBBB
