BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'My Projects') BBBBBBBB BBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB

XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXX
    XX XXXXXXXXXX XXXXXXXXXXXX
       XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXXX
       gettext(u'Accept All Invitations') 
    XXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XX
      XXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'My Invitations') 
      XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX
          XX XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXX
            XXXX
             gettext(u'Accept') 
          XXXX
          XXXX XX XXXXX XXXXXXXXXXXX XXX
          XXXX XXX XXX
        XXXXX
      XXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
             gettext(u'My Projects') 
          XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXX XXXXXX
                              XXXXXXX XXXXXXX
                              XXXXXXXXXX XXXXX
                              XXXXXXXXXXXX XBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBBBXXX
          XXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX
          XX XXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXX XXXXXXXXXXXXXXXXXX
        XXXXX
      XXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
