BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBB

  XX XXXXXXXXXXX XXXXXXXXXXXXX
    
    XX XXXXXXBBBBBBBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXX
       gettext(u'Learn More') 
    XXXX
  XXXX

  XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX

    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
       gettext(u'Pay Monthly') 
      XXXXXX XXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX
       gettext(u'Pay Annually') 
    XXXX

    XX XXXXXXXXXXXXXXXXXXXX
       gettext(u'\n        Save close to 20%% when you pay annually.\n      ') 
        SSSS SSSSS SS SSSS SSSS SSS SSS SSSSSSSSS
      
    XXXX

    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
       XXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXX XXXXXX
         gettext(u'90 day refund policy') 
      XXXX
    XXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XX XXXXXXXX XXXXXXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXX
           XXXXXXXXXXXX
           XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

          XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'monthly') 
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'discounted') XXXXXXXX
          XXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u'\n              This plan will be downgrading to\n              <span data-bind="text: oNextPlan"></span> on\n              <span data-bind="text: oNextDate"></span>.\n            ') 
              SSSS SSSS SSSS SS SSSSSSSSSSS SS
              SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSS SS
              SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSS
            
          XXXX

          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u'\n              This plan will be pausing on<br />\n              <span data-bind="text: oNextDate"></span>.\n            ') 
              SSSS SSSS SSSS SS SSSSSSS SSSSS SS
              SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSS
            
          XXXX

          XXXX XXXXXXXXXX XXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u'Current Plan') 
          XXXXXX

          XXXX XXXXXXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Select Plan') 
          XXXXXX
        XXXX
      XXXXXX
      XXXX XXX XXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXX
         XXXXXXXXXXX XXXXXXXXXXXX
         XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
           gettext(u'\n            Pause Subscription\n          ') 
            SSSSS SSSSSSSSSSSS
          
        XXXXX
        XXX
           gettext(u'\n            What happens after you pause?\n          ') 
            SSSS SSSSSSS SSSSS SSS SSSSSS
          
        XXXX
        XXXX
          XXXX
             gettext(u'\n              You will lose access to your project space, but you will be\n              able to re-subscribe anytime in the future.\n            ') 
              SSS SSSS SSSS SSSSSS SS SSSS SSSSSSS SSSSSS SSS SSS SSSS SS
              SSSS SS SSSSSSSSSSSS SSSSSSS SS SSS SSSSSSS
            
          XXXXX
          XXXX
             gettext(u'\n              You will no longer be billed.\n            ') 
              SSS SSSS SS SSSSSS SS SSSSSSS
            
          XXXXX
        XXXXX
      XXXX
    XXXXXX

    XXXX XXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBXXXXXXXXXXBBBBXXXXXXXXXXXXBBBBB XXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBB
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'\n            Your subscription is currently paused.\n          ') 
            SSSS SSSSSSSSSSSS SS SSSSSSSSS SSSSSSS
          
        BBBB
          BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BB BBBBBBBBBBBBBB
          XX XXXXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'\n            Your subscription is currently paused because you have\n            <a href="%(url_statements)s">past-due invoices</a>.\n          ') 
            SSSS SSSSSSSSSSSS SS SSSSSSSSS SSSSSS SSSSSSS SSS SSSS
            SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSS
          
            XXX XX
           gettext(u'\n            You will not be allowed to un-pause your project until\n            these invoices are paid.\n          ') 
            SSS SSSS SSS SS SSSSSSS SS SSSSSSSS SSSS SSSSSSS SSSSS
            SSSSS SSSSSSSS SSS SSSSS
          
        BBBBB
      XXXX
    XXXXXX

    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
       gettext(u'\n        Your subscription will be pausing on\n        <span data-bind="text: oStartDateAfterMinimumSubscription"></span> unless\n        you select a different plan above.\n      ') 
        SSSS SSSSSSSSSSSS SSSS SS SSSSSSS SS
        SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSS
        SSS SSSSSS S SSSSSSSSS SSSS SSSSSS
      
    XXXXXX

    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXX XXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
       gettext(u'\n        Your subscription will be downgrading to\n        <span data-bind="text: oNextSubscription"></span> on\n        <span data-bind="text: oStartDateAfterMinimumSubscription"></span> unless\n        you select a different plan above.\n      ') 
        SSSS SSSSSSSSSSSS SSSS SS SSSSSSSSSSS SS
        SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSS SS
        SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSS
        SSS SSSSSS S SSSSSSSSS SSSS SSSSSS
      
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXX
         gettext(u'\n          You are currently on the FREE CommCare Community plan.\n        ') 
          SSS SSS SSSSSSSSS SS SSS SSSS SSSSSSSS SSSSSSSSS SSSSS
        
      XXXX
    XXXXXX

    XXXXX
      BB BBBBBBBBBB
        XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBX
      BBBB
        XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBX
      BBBBB
        XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBXX
      BBBBBBBBBB
      BB BBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      BBBBB

      BB BBBBBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXX XXXXXXXXXXX XXXXXXX
                  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
             gettext(u'Next') 
          XXXXXXXXX
        XXXXXX
      BBBB
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXX XXXXXXXXXXX XXXXXXX
                  XXXXXXXXXXXXXXXXXXXX
             gettext(u'Next') 
          XXXXXXXXX
        XXXXXX
      BBBBB
    XXXXXXX

    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBX
          XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      BBBBBBBBBB
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
           gettext(u'Talk to Sales') 
        XXXXXXXXX
      XXXXXX
    XXXXXXX

  XXXXXXXXXX
BBBBBBBB

BBBBB BBBBBB
  XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXX
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Dismiss') XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Continue') XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
