BBBB BBBBBBBBBBBBBB
BBBB BBBB

XXXXXXXXXX
  XXXXXXXX gettext(u'Saved Credit Cards') XXXXXXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
  XXXXXXXX

  XXXX XX XXXXX XXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add Card') 
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXX XXX
XXXXXXXXXXX

XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Credit Card') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
           gettext(u'Your request was successful!') 
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Close') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Delete Card') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Processing your request') 
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX XXX
                            XXXXX XXXXXXXXXXXXXXXX
        XXXXXX
         gettext(u'\n          Actually remove <strong><span data-bind=\'text: brand\'></span></strong> card\n          ************<strong><span data-bind="text: last4"></span></strong>?\n        ') 
          SSSSSSSS SSSSSS SSSSSSSSSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSS SSSS
          SSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSS
        
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Cancel') 
        XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                               XXXXXXX XXXXXXXXXXXXXXX
           gettext(u'Delete') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX
    XXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                 gettext(u'Autopay card') 
            XXXXXXX
    XXXXX
    XXXX
      XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                               XXXXXX XXXXXXXXXXXXX
                               XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
         gettext(u'Remove Autopay') 
      XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                               XXXXXX XXXXXXXXXXX
                               XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
         gettext(u'Set as autopay card') 
      XXXXXXXXX
    XXXXX
    XXXX
      XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Delete Card') 
      XXXXXXXXX
    XXXXX
  XXXXX
XXXXXXXXX
