BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXX XXXXXXXXXXXXXXX XXXXXX XXXXX XX XX XXXXX XXXXXXXXXX XXX
      XXXX
      BBBBBB BBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBB BBBBB BBBBBBBB BB BBBBBBB
        XXXX
          XXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBB BB B
              XXXXXXX XXXX XXX XXXXX
            BBBB BBBBBBBBBBBBBBB BB B
              BBBB BBBBBBBBBB BB BBBBBBB
                BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
                  XXXXXXX XXXXXXXXX
                BBBB
                  XXXXXX XXXXXXX
                BBBBB
                XXX XXXXXXBBB BBBBBBBBBXXXXXXXXX XXXXXXXX
              BBBBBBB
            BBBB
              XXXXXXXX XXXXXXXX XXXX XXXX XXXXX
              BBBBBBB BBBBBBBB BB BBBBBBBB BB BBBBBBBBBBBBB
              XXXX
              BBB BBBBBBBB BB BBBBBBBBBBBBB
                XXXX
                BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
                  XXXXXXX XXXXXXXXXXX
                BBBB
                  XXXXXX XXXXXXXXX
                BBBBB
                FFFFFF
                XBBB BBBBBBB BB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBX BBBBBXX XXXXXXBBB BBBBBBBBBXXXXXXXXX XXXXXXXBBBBBBX
                XXXXX
              BBBBBB
              XXXXX
            BBBBB
          XXXXX
          XXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBXX
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
            BB BBB BBBBBBBBBBBBBBBXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXBBBBB
            XXXXXXX
          XXXXX
        XXXXX
        BBBBBB
      XXXXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
