BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBB BBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXX
    BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
BBBBBBBB
