BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBB BBB
  XXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXXXX
        XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
  XXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXXXX
        XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
  XXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXXXX
        XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
BBBBBBBBBBB
