BBBB BBBB
XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
  BB BBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Change Project') XXXXX
    BBB B BB BBBBBBBBBBBB
      XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBB
  BBBBB

  BB BBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXX
         gettext(u'All Projects') 
      XXXX
    XXXXX
  BBBBB

  BB BBB BBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Add Project') 
      XXXX
    XXXXX
  BBBBB
XXXXX
