BBBB BBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBBBBB
XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XX XXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXX XXXX
         XXXXXXXXXXXXXXXXXX XXXX XXXXXX
          XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX


      XXXX
      XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Logged in As') XXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
              BB BBBBBBBBBBBBBBB
                 
                XXX XX
              BBBB
                
              BBBBB
            XXXXXX
            BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
              BB BBBB
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                
              XXXXXXX
              BBBBB
            BBBBBBB
          XXXXXX
        XXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBB BBB BBBBBB BB BBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBBBBBBBBBB
              XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Manage Enterprise') XXXXX
              XXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBX XXXXXXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Enterprise Console') 
                XXXX
              XXXXX
            BBBBB
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Manage Project') XXXXX
          XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
              XX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Project Settings') 
            XXXX
          XXXXX
          BB BBB BBBBBBBBBBBBBBB
          XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Current Subscription') 
            XXXX
          XXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBB
          XXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'Feature Flags and Privileges') 
            XXXX
          XXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Support Options') XXXXX
            XXXX
              XX XXXXXXBBB BBBBBBBBBXXXXX
                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'View Domain Doc') 
              XXXX
            XXXXX
          BBBBB
        BBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Manage Account') XXXXX
        XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX
            XX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX  gettext(u'My Account Settings') 
          XXXX
        XXXXX
        XXXX
          XX XXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXX
            XX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
             gettext(u'Sign Out') 
          XXXX
        XXXXX
      XXXXX
    XXXXX
    BB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBB BB BBB BBBBBBBBBBBBBBB
        
        
      XXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XX XXXXXXXX
           XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXX XXXX
           XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX

        XXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX
          BB BBB BBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
               gettext(u'\n                %(cc_name)s Help\n              ') 
                SSSSSSSSSSS SSSS
              
            XXXXX
            XXXX
              XX XXXXXX gettext(u'https://wiki.commcarehq.org/display/commcarepublic/Home') X
                 XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXX XXXX
                 XXXXXXXXXXXXXXXXXXXXX XXXXX
                 XXXXXXXXXXXXXXXXX XXX XXXX XXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   gettext(u'Visit the Help Site') 
              XXXX
            XXXXX
            XXXX
              XX XXXXXX gettext(u'https://forum.dimagi.com/') X
                 XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXX XXXX
                 XXXXXXXXXXXXXXXXXXXXX XXXXX
                 XXXXXXXXXXXXXXXX XXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   gettext(u'User Forum') 
              XXXX
            XXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBB
            XXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXX XXXX
                 XXXXXXXXXXXXXXXXXXXXX XXXXX
                 XXXXXXXXXXXXXXXXXX XX XXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   gettext(u'Report an Issue') 
              XXXX
            XXXXX
          BBBBB
          BB BBB BBBBBBBBBBBBBBB
            XXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXX XXXX
                 XXXXXXXXXXXXXXXXXXXXX XXXXX
                 XXXXXXXXXXXXXXXXXX XXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                   gettext(u'Status Page') 
              XXXX
            XXXXX
          BBBBB
          XXXXX
        XXXXX
    BBBBB
    BB BBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXXXXX
      XX XXXXXXXX
         XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXX

        BB BBBBBB
          BB BBBBBB BB BBBBBBBB
             gettext(u'CommCare HQ Demo Project') 
          BBBB
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
               gettext(u'\n                Snapshot of %(snap_name)s\n              ') 
                SSSSSSSS SS SSSSSSSSSSSSS
              
            BBBB
              
            BBBBB
          BBBBB
        BBBB
           gettext(u'Select Project...') 
        BBBBB
      XXXX
      BB BBBBBB
        BBBBBBBBBBBBBBBB BBBBBBB BBBBBB
      BBBB
        BBBBBBBBBBBBBBBB BBBBBBB
      BBBBB
    XXXXX
    BBBBB
    BB BBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
      XX XXXXXXBBB BBBBBBBBBBX
         XXXXXXXXXXXXXXXXX
        
      XXXX
    XXXXX
    BBBBB
XXXXX
BBBBB
