BBBB BBBB

XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXX XX XXXXXXXXXXXXXX XXXX XX X XXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXX XXX XXXXXXX XXXX XXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Done') XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Session expiring soon') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
         gettext(u"\n          You're about to be logged out due to inactivity.\n          Please click below to extend your session.\n        ") 
          SSSSSS SSSSS SS SS SSSSSS SSS SSS SS SSSSSSSSSSS
          SSSSSS SSSSS SSSSS SS SSSSSS SSSS SSSSSSSS
        
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Extend session') XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
