# Generated by Django 4.2.18 on 2025-02-25 12:35

from django.db import migrations, models
import uuid


def delete_columns_and_filters(apps, schema_editor):
    # this migration was written when none of these models are used in production,
    # or even generated by a non-local UI
    # Therefore, it's safe to just delete everything and start over.
    BulkEditColumnFilter = apps.get_model("data_cleaning", "BulkEditColumnFilter")
    BulkEditColumnFilter.objects.all().delete()
    BulkEditColumn = apps.get_model("data_cleaning", "BulkEditColumn")
    BulkEditColumn.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_cleaning', '0002_update_fields_and_ordering'),
    ]

    operations = [
        migrations.RunPython(delete_columns_and_filters, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='bulkeditcolumn',
            name='column_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='bulkeditcolumnfilter',
            name='filter_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bulkeditcolumnfilter',
            name='match_type',
            field=models.CharField(choices=[('exact', 'exact'), ('is_not', 'is_not'), ('starts', 'starts'), ('starts_not', 'starts_not'), ('is_empty', 'is_empty'), ('is_not_empty', 'is_not_empty'), ('missing', 'missing'), ('not_missing', 'not_missing'), ('fuzzy', 'fuzzy'), ('not_fuzzy', 'not_fuzzy'), ('phonetic', 'phonetic'), ('not_phonetic', 'not_phonetic'), ('lt', 'lt'), ('gt', 'gt'), ('lte', 'lte'), ('gte', 'gte'), ('is_any', 'is_any'), ('is_not_any', 'is_not_any'), ('is_all', 'is_all'), ('is_not_all', 'is_not_all')], default='exact', max_length=12),
        ),
    ]
