from __future__ import absolute_import
from __future__ import unicode_literals
from corehq.util.elastic import es_index
from pillowtop.es_utils import ElasticsearchIndexInfo

DOMAIN_INDEX = es_index("hqdomains_2016-08-08")
DOMAIN_MAPPING = {'_meta': {'comment': '',
                            'created': None},
 'date_detection': False,
 'date_formats': ['yyyy-MM-dd',
                  "yyyy-MM-dd'T'HH:mm:ssZZ",
                  "yyyy-MM-dd'T'HH:mm:ss.SSSSSS",
                  "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'",
                  "yyyy-MM-dd'T'HH:mm:ss'Z'",
                  "yyyy-MM-dd'T'HH:mm:ssZ",
                  "yyyy-MM-dd'T'HH:mm:ssZZ'Z'",
                  "yyyy-MM-dd'T'HH:mm:ss.SSSZZ",
                  "yyyy-MM-dd'T'HH:mm:ss",
                  "yyyy-MM-dd' 'HH:mm:ss",
                  "yyyy-MM-dd' 'HH:mm:ss.SSSSSS",
                  "mm/dd/yy' 'HH:mm:ss"],
 'dynamic': False,
 'properties': {'area': {'type': 'text'},
                'attribution_notes': {'type': 'text'},
                'author': {'fields': {'author': {'type': 'text'},
                                      'exact': {'type': 'keyword'}},
                           'type': 'text'},
                'cached_properties': {'dynamic': False, 'type': 'object'},
                'call_center_config': {'dynamic': False,
                                       'properties': {'case_owner_id': {'type': 'text'},
                                                      'use_fixtures': {'type': 'boolean'},
                                                      'case_type': {'type': 'text'},
                                                      'doc_type': {'type': 'keyword'},
                                                      'enabled': {'type': 'boolean'}},
                                       'type': 'object'},
                'case_display': {'dynamic': False,
                                 'properties': {'case_details': {'dynamic': False,
                                                                 'type': 'object'},
                                                'doc_type': {'type': 'keyword'},
                                                'form_details': {'dynamic': False,
                                                                 'type': 'object'}},
                                 'type': 'object'},
                'case_sharing': {'type': 'boolean'},
                'cda': {'dynamic': False,
                        'properties': {'date': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                                'type': 'date'},
                                       'doc_type': {'type': 'keyword'},
                                       'signed': {'type': 'boolean'},
                                       'type': {'type': 'keyword'},
                                       'user_id': {'type': 'text'},
                                       'user_ip': {'type': 'text'},
                                       'version': {'type': 'text'}},
                        'type': 'object'},
                'commconnect_enabled': {'type': 'boolean'},
                'commtrack_enabled': {'type': 'boolean'},
                'copy_history': {'type': 'text'},
                'cp_first_form': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                  'type': 'date'},
                'cp_first_domain_for_user': {'type': 'boolean'},
                'cp_has_app': {'type': 'boolean'},
                'cp_is_active': {'type': 'boolean'},
                'cp_last_form': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                 'type': 'date'},
                'cp_n_30_day_cases': {'type': 'long'},
                'cp_n_60_day_cases': {'type': 'long'},
                'cp_n_90_day_cases': {'type': 'long'},
                'cp_n_active_cases': {'type': 'long'},
                'cp_n_active_cc_users': {'type': 'long'},
                'cp_n_cases': {'type': 'long'},
                'cp_n_cc_users': {'type': 'long'},
                'cp_n_forms': {'type': 'long'},
                'cp_n_forms_30_d': {'type': 'long'},
                'cp_n_forms_60_d': {'type': 'long'},
                'cp_n_forms_90_d': {'type': 'long'},
                'cp_n_j2me_30_d': {'type': 'long'},
                'cp_n_j2me_60_d': {'type': 'long'},
                'cp_n_j2me_90_d': {'type': 'long'},
                'cp_j2me_90_d_bool': {'type': 'boolean'},
                'cp_n_inactive_cases': {'type': 'long'},
                'cp_n_users_submitted_form': {'type': 'long'},
                'cp_n_web_users': {'type': 'long'},
                'cp_n_out_sms': {'type': 'long'},
                'cp_n_in_sms': {'type': 'long'},
                'cp_n_sms_ever': {'type': 'long'},
                'cp_n_sms_30_d': {'type': 'long'},
                'cp_n_sms_60_d': {'type': 'long'},
                'cp_n_sms_90_d': {'type': 'long'},
                'cp_n_sms_in_30_d': {'type': 'long'},
                'cp_n_sms_in_60_d': {'type': 'long'},
                'cp_n_sms_in_90_d': {'type': 'long'},
                'cp_n_sms_out_30_d': {'type': 'long'},
                'cp_n_sms_out_60_d': {'type': 'long'},
                'cp_n_sms_out_90_d': {'type': 'long'},
                'cp_sms_ever': {'type': 'boolean'},
                'cp_sms_30_d': {'type': 'boolean'},
                'cp_last_updated': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                    'type': 'date'},
                'cp_300th_form_submission': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                             'type': 'date'},
                'creating_user': {'type': 'text'},
                'customer_type': {'type': 'text'},
                'date_created': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                 'type': 'date'},
                'default_timezone': {'type': 'text'},
                'deployment': {'dynamic': False,
                               'properties': {'city': {'fields': {'city': {'type': 'text'},
                                                                  'exact': {'type': 'keyword'}},
                                                       'type': 'text'},
                                              'countries': {'fields': {
                                                  'countries': {'type': 'keyword'},
                                                  'exact': {'type': 'keyword'}
                                              },
                                                            'type': 'text'},
                                              'description': {'fields': {'description': {'type': 'text'},
                                                                         'exact': {'type': 'keyword'}},
                                                              'type': 'text'},
                                              'doc_type': {'type': 'keyword'},
                                              'public': {'type': 'boolean'},
                                              'region': {'fields': {'exact': {'type': 'keyword'},
                                                                    'region': {'type': 'text'}},
                                                         'type': 'text'}},
                               'type': 'object'},
                'description': {'type': 'text'},
                'doc_type': {'type': 'keyword'},
                'downloads': {'type': 'long'},
                'dynamic_reports': {'dynamic': False,
                                    'properties': {'doc_type': {'type': 'keyword'},
                                                   'reports': {'dynamic': False,
                                                               'properties': {'doc_type': {'type': 'keyword'},
                                                                              'kwargs': {'dynamic': False,
                                                                                         'type': 'object'},
                                                                              'name': {'type': 'text'},
                                                                              'report': {'type': 'text'}},
                                                               'type': 'object'},
                                                   'section_title': {'type': 'text'}},
                                    'type': 'object'},
                'full_downloads': {'type': 'long'},
                'hipaa_compliant': {'type': 'boolean'},
                'hr_name': {'type': 'text'},
                'image_path': {'type': 'text'},
                'image_type': {'type': 'text'},
                'internal': {'dynamic': False,
                             'properties': {'area': {'fields': {'area': {'type': 'text'},
                                                                'exact': {'type': 'keyword'}},
                                                     'type': 'text'},
                                            'can_use_data': {'type': 'boolean'},
                                            'commcare_edition': {'type': 'text'},
                                            'custom_eula': {'type': 'boolean'},
                                            'doc_type': {'type': 'keyword'},
                                            'goal_time_period': {'type': 'long'},
                                            'goal_followup_rate': {'type': 'double'},
                                            'commconnect_domain': {'type': 'boolean'},
                                            'commtrack_domain': {'type': 'boolean'},
                                            'initiative': {'fields': {'exact': {'type': 'keyword'},
                                                                      'initiative': {'type': 'text'}},
                                                           'type': 'text'},
                                            'workshop_region': {'fields': {'exact': {'type': 'keyword'},
                                                                'workshop_region': {'type': 'text'}},
                                                           'type': 'text'},
                                            'notes': {'type': 'text'},
                                            'organization_name': {'fields': {
                                                'exact': {'type': 'keyword'},
                                                'organization_name': {'type': 'text'}
                                            },
                                                                  'type': 'text'},
                                            'phone_model': {'fields': {'exact': {'type': 'keyword'},
                                                                       'phone_model': {'type': 'text'}},
                                                            'type': 'text'},
                                            'platform': {'type': 'text'},
                                            'project_manager': {'type': 'text'},
                                            'project_state': {'type': 'text'},
                                            'self_started': {'type': 'boolean'},
                                            'sf_account_id': {'type': 'text'},
                                            'sf_contract_id': {'type': 'text'},
                                            'sub_area': {'fields': {'exact': {'type': 'keyword'},
                                                                    'sub_area': {'type': 'text'}},
                                                         'type': 'text'},
                                            'using_adm': {'type': 'boolean'},
                                            'using_call_center': {'type': 'boolean'}},
                             'type': 'object'},
                'is_active': {'type': 'boolean'},
                'is_approved': {'type': 'boolean'},
                'is_shared': {'type': 'boolean'},
                'is_sms_billable': {'type': 'boolean'},
                'is_snapshot': {'type': 'boolean'},
                'is_test': {'type': 'text'},
                'is_starter_app': {'type': 'boolean'},
                'last_modified': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                  'type': 'date'},
                'license': {'type': 'text'},
                'migrations': {'dynamic': False,
                               'properties': {'doc_type': {'type': 'keyword'},
                                              'has_migrated_permissions': {'type': 'boolean'}},
                               'type': 'object'},
                'multimedia_included': {'type': 'boolean'},
                'name': {'fields': {'exact': {'type': 'keyword'},
                                    'name': {'type': 'text'}},
                         'type': 'text'},
                'organization': {'type': 'text'},
                'phone_model': {'type': 'text'},
                'project_type': {'analyzer': 'comma', 'type': 'text'},
                'published': {'type': 'boolean'},
                'publisher': {'type': 'text'},
                'allow_domain_requests': {'type': 'boolean'},
                'restrict_superusers': {'type': 'boolean'},
                'secure_submissions': {'type': 'boolean'},
                'short_description': {'fields': {'exact': {'type': 'keyword'},
                                                 'short_description': {'type': 'text'}},
                                      'type': 'text'},
                'sms_case_registration_enabled': {'type': 'boolean'},
                'sms_case_registration_owner_id': {'type': 'text'},
                'sms_case_registration_type': {'type': 'text'},
                'sms_case_registration_user_id': {'type': 'text'},
                'sms_mobile_worker_registration_enabled': {'type': 'boolean'},
                'snapshot_time': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                  'type': 'date'},
                'snapshot_head': {'type': 'boolean'},
                'sub_area': {'type': 'text'},
                'subscription': {'type': 'text'},
                'survey_management_enabled': {'type': 'boolean'},
                'tags': {'type': 'text'},
                'title': {'fields': {'exact': {'type': 'keyword'},
                                     'title': {'type': 'text'}},
                          'type': 'text'},
                'use_sql_backend': {'type': "boolean"},
                'yt_id': {'type': 'text'}}}


DOMAIN_INDEX_INFO = ElasticsearchIndexInfo(
    index=DOMAIN_INDEX,
    alias='hqdomains',
    type='hqdomain',
    mapping=DOMAIN_MAPPING,
)
