from __future__ import absolute_import
from __future__ import unicode_literals
from corehq.util.elastic import es_index
from pillowtop.es_utils import ElasticsearchIndexInfo


REPORT_CASE_INDEX = es_index("report_cases_czei39du507m9mmpqk3y01x72a3ux4p0")

REPORT_CASE_MAPPING={'_meta': {'comment': '2013-11-05 dmyung',
           'created': None},
 'date_detection': False,
 'date_formats': ['yyyy-MM-dd',
                  "yyyy-MM-dd'T'HH:mm:ssZZ",
                  "yyyy-MM-dd'T'HH:mm:ss.SSSSSS",
                  "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'",
                  "yyyy-MM-dd'T'HH:mm:ss'Z'",
                  "yyyy-MM-dd'T'HH:mm:ssZ",
                  "yyyy-MM-dd'T'HH:mm:ssZZ'Z'",
                  "yyyy-MM-dd'T'HH:mm:ss.SSSZZ",
                  "yyyy-MM-dd'T'HH:mm:ss",
                  "yyyy-MM-dd' 'HH:mm:ss",
                  "yyyy-MM-dd' 'HH:mm:ss.SSSSSS",
                  "mm/dd/yy' 'HH:mm:ss"],
 'dynamic': True,
 'dynamic_templates': [{'everything_else': {'mapping': {'{name}': {'type': 'keyword'}},
                                            'match': '*',
                                            'match_mapping_type': 'string'}}],
 'properties': {'actions': {'dynamic': True,
                            'properties': {'action_type': {'type': 'text'},
                                           'attachments': {'dynamic': False,
                                                           'properties': {'attachment_from': {'type': 'text'},
                                                                          'attachment_name': {'type': 'text'},
                                                                          'attachment_properties': {'dynamic': False,
                                                                                                    'type': 'object'},
                                                                          'attachment_size': {'type': 'long'},
                                                                          'attachment_src': {'type': 'text'},
                                                                          'doc_type': {'type': 'keyword'},
                                                                          'identifier': {'type': 'text'},
                                                                          'server_md5': {'type': 'text'},
                                                                          'server_mime': {'type': 'text'}},
                                                           'type': 'object'},
                                           'date': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                                    'type': 'date'},
                                           'doc_type': {'type': 'keyword'},
                                           'indices': {'dynamic': False,
                                                       'properties': {'doc_type': {'type': 'keyword'},
                                                                      'identifier': {'type': 'text'},
                                                                      'referenced_id': {'type': 'text'},
                                                                      'referenced_type': {'type': 'text'}},
                                                       'type': 'object'},
                                           'server_date': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                                           'type': 'date'},
                                           'sync_log_id': {'type': 'text'},
                                           'updated_known_properties': {'dynamic': False,
                                                                        'type': 'object'},
                                           'updated_unknown_properties': {'dynamic': False,
                                                                          'type': 'object'},
                                           'user_id': {'type': 'text'},
                                           'xform_id': {'type': 'text'},
                                           'xform_name': {'type': 'text'},
                                           'xform_xmlns': {'type': 'text'}},
                            'type': 'nested'},
                'case_attachments': {'dynamic': True,
                                     'properties': {'attachment_from': {'type': 'text'},
                                                    'attachment_name': {'type': 'text'},
                                                    'attachment_properties': {'dynamic': False,
                                                                              'type': 'object'},
                                                    'attachment_size': {'type': 'long'},
                                                    'attachment_src': {'type': 'text'},
                                                    'doc_type': {'type': 'keyword'},
                                                    'identifier': {'type': 'text'},
                                                    'server_md5': {'type': 'text'},
                                                    'server_mime': {'type': 'text'}},
                                     'type': 'object'},
                'closed': {'type': 'boolean'},
                'closed_by': {'type': 'text'},
                'closed_on': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                              'type': 'date'},
                'computed_': {'enabled': False, 'type': 'object'},
                'computed_modified_on_': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                          'type': 'date'},
                'doc_type': {'type': 'keyword'},
                'domain': {'fields': {'domain': {'type': 'text'},
                                      'exact': {'type': 'keyword'}},
                           'type': 'text'},
                'export_tag': {'type': 'text'},
                'external_id': {'fields': {'exact': {'type': 'keyword'},
                                           'external_id': {'type': 'text'}},
                                'type': 'text'},
                'indices': {'dynamic': True,
                            'properties': {'doc_type': {'type': 'keyword'},
                                           'identifier': {'type': 'text'},
                                           'referenced_id': {'type': 'text'},
                                           'referenced_type': {'type': 'text'}},
                            'type': 'object'},
                'initial_processing_complete': {'type': 'boolean'},
                'location_id': {'type': 'text'},
                'modified_on': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                'type': 'date'},
                'name': {'fields': {'exact': {'type': 'keyword'},
                                    'name': {'type': 'text'}},
                         'type': 'text'},
                'opened_by': {'type': 'text'},
                'opened_on': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                              'type': 'date'},
                'owner_id': {'type': 'text'},
                'referrals': {'enabled': False, 'type': 'object'},
                'server_modified_on': {'format': "yyyy-MM-dd||yyyy-MM-dd'T'HH:mm:ssZZ||yyyy-MM-dd'T'HH:mm:ss.SSSSSS||yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'||yyyy-MM-dd'T'HH:mm:ss'Z'||yyyy-MM-dd'T'HH:mm:ssZ||yyyy-MM-dd'T'HH:mm:ssZZ'Z'||yyyy-MM-dd'T'HH:mm:ss.SSSZZ||yyyy-MM-dd'T'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss||yyyy-MM-dd' 'HH:mm:ss.SSSSSS||mm/dd/yy' 'HH:mm:ss",
                                       'type': 'date'},
                'type': {'fields': {'exact': {'type': 'keyword'},
                                    'type': {'type': 'text'}},
                         'type': 'text'},
                'user_id': {'type': 'text'},
                'version': {'type': 'text'},
                'xform_ids': {'type': 'keyword'}}}

REPORT_CASE_ES_ALIAS = "report_cases"
REPORT_CASE_ES_TYPE = "report_case"

REPORT_CASE_INDEX_INFO = ElasticsearchIndexInfo(
    index=REPORT_CASE_INDEX,
    alias=REPORT_CASE_ES_ALIAS,
    type=REPORT_CASE_ES_TYPE,
    mapping=REPORT_CASE_MAPPING,
)
