from __future__ import absolute_import
from __future__ import unicode_literals
from corehq.pillows.core import DATE_FORMATS_ARR, DATE_FORMATS_STRING
from corehq.util.elastic import es_index
from pillowtop.es_utils import ElasticsearchIndexInfo

SMS_INDEX = es_index("smslogs_2017-02-09")
SMS_MAPPING = {
    '_meta': {
       'comment': 'Autogenerated [corehq.apps.sms.models.SMSLog] mapping from ptop_generate_mapping 09/23/2013',
       'created': None
    },
    'date_detection': False,
    'date_formats': DATE_FORMATS_ARR,
    'dynamic': False,
    'properties': {
        'backend_api': {'type': 'text'},
        'backend_id': {'type': 'text'},
        'base_doc': {'type': 'text'},
        'billed': {'type': 'boolean'},
        'couch_recipient': {'type': 'text'},
        'couch_recipient_doc_type': {'type': 'text'},
        'date': {
            'format': DATE_FORMATS_STRING,
            'type': 'date'
        },
        'direction': {'type': 'text'},
        'doc_type': {'type': 'keyword'},
        'domain': {
            'fields': {
                'domain': {'type': 'text'},
                'exact': {'type': 'keyword'}
            },
            'type': 'text'
        },
        'phone_number': {'type': 'text'},
        'processed': {'type': 'boolean'},
        'reminder_id': {'type': 'text'},
        'text': {'type': 'text'},
        'workflow': {'type': 'text'},
        'xforms_session_couch_id': {'type': 'text'}
    }
}

SMS_TYPE = 'sms'

SMS_INDEX_INFO = ElasticsearchIndexInfo(
    index=SMS_INDEX,
    alias="smslogs",
    type=SMS_TYPE,
    mapping=SMS_MAPPING,
)
