# Generated by Django 5.2.14 on 2026-07-17 15:17

from django.db import migrations

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('builds', '0002_populate_commcaremobilebuild'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='CommCareMobileBuild',
                    name='couch_id',
                ),
            ],
            database_operations=[
                # Empty - don't touch database yet
            ],
        ),
    ]
