BBBB BBBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBBBBB
	
BBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
            
        XXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXX XXXXXXXXXXXXX
                   XXXXXXX
                   XXXXX
                   XXXXXXXFFFFFFFFFFFFFFFFFFX XX
            
        XXXXXX
    XXXXXX
BBBBB
