BBBB BBBBBBBBBBBBBBBBBB
BBBB BBBB

BB BBBBBBBBBBBBBBB
    
    BB BBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXX gettext(u'Errors') XXXXXXXXX
            
        XXXXXX
    BBBBB
BBBB
    BB BBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBB XXXXXXXXXXXXXBBBBBXX
                BBBBBBBBBBBB BBBBB BBBBBBB BBBBBBBBBB
                
            XXXXXXXX
        XXXXXX
    BBBB
        XXXX XXXXXXXXXX
            BBBBBBBBBBBB BBBBB BBBBBBBBBBBBB BBBBBBBBBBB
        XXXXXX
    BBBBB
BBBBB
