# Generated by Django 2.2.13 on 2020-09-24 17:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_data_fields', '0005_customdatafieldsprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdatafieldsprofile',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
