# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hqwebapp', '0005_auto_20170426_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedpasswords',
            name='user',
        ),
        migrations.DeleteModel(
            name='UsedPasswords',
        ),
    ]
