# Generated by Django 2.2.16 on 2021-01-28 19:13

from architect.commands import partition
from django.db import migrations, models


def add_partitions(apps, schema_editor):
    partition.run({'module': 'corehq.apps.hqwebapp.models'})


class Migration(migrations.Migration):

    dependencies = [
        ('hqwebapp', '0005_delete_apikeysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('action', models.CharField(choices=[('login', 'Login'),
                    ('logout', 'Logout'), ('failure', 'Login Failure')], max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(add_partitions),
    ]
