BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB

BBBBB BBBBBBB BBBBBBBBBBBBBBBBBBX BBBBBBBBBBBBB

BBBBB BBBBBBB
  BBBBB BBBBBBBBBBBBBBBB
    BB BBBBBBBBBBBBBBBBBBBB
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBB
          XXXX
            XX XXXXXXXXXXXX
          XXXXX
        BBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXX
            XX XXXXXXXXXXXX
          XXXXX
        BBBBB
      XXXXX
    BBBBB
  BBBBBBBB BBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXBBBBB BBBBBBBBBBBBBBBBBXXXXX
    XXXXXX
    BBBBB BBBBBBBBBBBB
    BBBBBBBB
  XXXXXX
BBBBBBBB
