BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBB

BBBBB BBBBBBB
  BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      BBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
      BB BBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX
          XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
      BBBB
        BBBBB BBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXBBBBBBBB
      BBBBB
      BBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB
    XXXXXX
  XXXXXX
BBBBBBBB BBBBBBB
