# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-19 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperuserProjectEntryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('project', models.CharField(max_length=256)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
