# Generated by Django 2.2.13 on 2020-09-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_fix_domain_es_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdomainrequest',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
