BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBB
  
  XXXXXXX
    XXXXXXXXXXXXXXXXXX X XX X
      XXXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXX XXXX
    X
  XXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Unlock Linked Fields For Me') 
        XXXXXXXXX
      XXXXXXX
      XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Lock Linked Fields For Me') 
        XXXXXXXXX
      XXXXXXX

    XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXX XX XXX XXXXXXXXX XXX
        XXXX XX XXXXXX XXXXXXXXXXXXXXXX XXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXX
             gettext(u'Unlock Linked Fields For Me') 
          XXXXXXXXX
        XXXX XXX XXX
        XXXX XX XXX XXXXXXXXXXXXXXXX XXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXX
             gettext(u'Lock Linked Fields For Me') 
          XXXXXXXXX
        XXXX XXX XXX
      XXXX XXX XXX
      XXXX XX XXXXXX XXXXXXXXX XXX
        XX XXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXX XXXXXX XXXXX
      XXXX XXX XXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXX gettext(u'Linked Configurations') X
          XXXXXXXXXXXXXX
             gettext(u"\n              Linked configurations are controlled from a separate, linked project space.\n                <a href='https://confluence.dimagi.com/display/commcarepublic/Enterprise+Release+Management' target='_blank'>Learn more</a>.\n            ") 
              SSSSSS SSSSSSSSSSSSSS SSS SSSSSSSSSS SSSS S SSSSSSSSS SSSSSS SSSSSSS SSSSSS
                SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSS SSSSSSSSS
            XX
      XXXXXXX
    XXXX

  XXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX
        XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
    BBBBBBBBBB

    XX XXXXXXXXXXXXXXXXX

    BB BBBBBBBBBBBBBBBBBBBBBBBBB
      BBB BBBBBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBB BBBBB BB BBBBBB
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        BBBBBB
      BBBBBB
    BBBBB

    BB BBBBBBBBBBBBB
      XXX XXXXXXXXXX XXXXXXXXXX
        XXX BB BBB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Fields') XXXXXXXXX
        XXX BB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXBBBBBXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Profiles') XXXXXXXXX
      XXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
    BBBBB

    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXBB BBB BBBBBBBBBBBBB BB BBB BBBBBBBBBBBBBBB XX XXXXXXBBBBBX XXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBB
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBB
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXBB BBBBBBBBBBBBB BBB BBBBBBBBBBBBBBB XX XXXXXXBBBBBX XXXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXBB BBBBBBBBBBBB XXXXXXXXBBBBBX
             gettext(u'Save') 
        XXXXXXXXX
      XXXXXX
    XXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXXX
BBBBBBBB
