BBBB BBBB
XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
  XXXXXXXX gettext(u'Multimedia Sharing Options') XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'License') XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXX gettext(u'Creative Commons Attribution, Non-Commercial (CC BY-NC)') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXX gettext(u'Creative Commons Attribution, No Derivatives (CC BY-ND)') XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Creative Commons Attribution (CC BY)') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Creative Commons Attribution, Non-Commercial, and Share Alike (CC BY-NC-SA)') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX gettext(u'Creative Commons Attribution, Non-Commercial, and No Derivatives (CC BY-NC-ND)') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXX gettext(u'Creative Commons Attribution, Share Alike (CC BY-SA)') XXXXXXXXX
      XXXXXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Author') XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Enter the name of the author') X XX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Attribution Notes') XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXXXX
