# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 19:05
from __future__ import absolute_import, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_auto_20190318_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transifexblacklist',
            name='display_text',
            field=models.TextField(blank=True, help_text="The default language's translation for this detail/list. If display_text is not filled out then all translations that match the field_type and field_name will be blacklisted"),
        ),
        migrations.AlterField(
            model_name='transifexblacklist',
            name='field_name',
            field=models.TextField(help_text="\nThis is the same string that appears in the bulk translations download.\nUsually the string in either case list or detail under 'property'.\nThis could be an xpath or case property name.\nIf it is an ID Mapping then the property should be '<property> (ID Mapping Text)'.\nFor the values each value should be '<id mapping value> (ID Mapping Value)'.\nExample: case detail for tasks_type would have entries:\n\n    tasks_type (ID Mapping Text)\n\n    child (ID Mapping Value)\n\n    pregnancy (ID Mapping Value)\n\n"),
        ),
    ]
