# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_user_reporting_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreportingmetadatastaging',
            name='app_version',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userreportingmetadatastaging',
            name='build_profile_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userreportingmetadatastaging',
            name='commcare_version',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userreportingmetadatastaging',
            name='last_heartbeat',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userreportingmetadatastaging',
            name='num_quarantined_forms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userreportingmetadatastaging',
            name='num_unsent_forms',
            field=models.IntegerField(null=True),
        ),
    ]
