# Generated by Django 2.2.20 on 2021-06-04 11:49

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_role_permission_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, null=True)),
                ('object_type', models.CharField(max_length=255)),
                ('object_id', models.CharField(max_length=128)),
                ('by_user_id', models.CharField(max_length=128)),
                ('details', jsonfield.fields.JSONField(default=dict)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.PositiveSmallIntegerField(
                    choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')])),
            ],
        ),
        migrations.AddIndex(
            model_name='hqlogentry',
            index=models.Index(fields=['domain'], name='users_hqlog_domain_50b1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='hqlogentry',
            index=models.Index(fields=['object_id'], name='users_hqlog_object__46c17f_idx'),
        ),
        migrations.AlterIndexTogether(
            name='hqlogentry',
            index_together={('domain', 'by_user_id')},
        ),
    ]
