# Generated by Django 3.2.13 on 2022-05-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_add_release_management_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_commcare_user_default',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
