# Generated by Django 3.2.18 on 2023-02-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_add_attendance_tracking_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='hqapikey',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
