# Generated by Django 3.2.25 on 2024-03-31 06:32

from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion

from corehq.util.django_migrations import skip_on_fresh_install


@skip_on_fresh_install
def copy_invitation_supply_point(apps, schema_editor):
    call_command('copy_invitation_supply_point')


class Migration(migrations.Migration):

    dependencies = [
        ('custom_data_fields', '0008_custom_data_fields_upstream_ids'),
        ('users', '0057_populate_sql_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='location_id',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_data_fields.customdatafieldsprofile'),
        ),
        migrations.RunPython(copy_invitation_supply_point, migrations.RunPython.noop),
    ]
