# Generated by Django 4.2.11 on 2024-06-12 18:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0021_add_fixture_queryset_case_sync_restriction'),
        ('custom_data_fields', '0008_custom_data_fields_upstream_ids'),
        ('users', '0068_grant_web_apps_to_default_mobile_worker_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='custom_user_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email_status',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='primary_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.sqllocation', to_field='location_id'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_data_fields.customdatafieldsprofile'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='program',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='supply_point',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='tableau_group_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='tableau_role',
            field=models.CharField(blank=True, choices=[('Explorer', 'Explorer'), ('Explorer - Can Publish', 'ExplorerCanPublish'), ('Server Administrator', 'ServerAdministrator'), ('Site Administrator - Explorer', 'SiteAdministratorExplorer'), ('Site Administrator - Creator', 'SiteAdministratorCreator'), ('Unlicensed', 'Unlicensed'), ('Read Only', 'ReadOnly'), ('Viewer', 'Viewer')], max_length=32, null=True),
        ),
    ]
