# Generated by Django 4.2.15 on 2024-10-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0072_remove_invitation_supply_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectiduserlink",
            name="messaging_consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="connectiduserlink",
            name="messaging_key",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
