# Generated by Django 4.2.14 on 2024-08-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_remove_invitation_supply_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiduserlink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
