# Generated by Django 4.2.17 on 2025-01-31 21:28

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0076_connectiduserlink_messaging_consent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("user_id", models.CharField(max_length=128, null=True)),
                ("changed_by", models.CharField(max_length=128)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("changed_via", models.CharField(blank=True, max_length=255)),
                (
                    "action",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Create"), (2, "Update"), (3, "Delete")]
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.invitation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["domain"], name="users_invit_domain_176861_idx"
                    )
                ],
            },
        ),
    ]
