# Generated by Django 4.2.18 on 2025-01-24 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_invitationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hqapikey',
            name='key',
        ),
    ]
