# Generated by Django 4.2.20 on 2025-04-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_sqluserdata_deleted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectiduserlink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
