BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  
  
  XXXX XXXXXX XXXXXXXXX XXX
  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXXX XXX XXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXX
  XXXXXXXXX
  XXXX XXX XXXXXX XXXXXXXXX XXX
BBBBB
