BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBB
  XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XXXXXXXXXXXXX
    X
    XXXXXXXXXXX X
      XXXXXXXXXXXXX XXXX
    X
  XXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBB

  XX XXXXXXXXXXXXXXXXX

  XXX gettext(u"Use this tool to upload ZIP files of your multimedia, so you don't have to\n    upload each file one-by-one.") SSS SSSS SSSS SS SSSSSS SSS SSSSS SS SSSS SSSSSSSSSSS SS SSS SSSSS SSSS SS
    SSSSSS SSSS SSSS SSSSSSSSSSSXXXX
  XXX gettext(u'The bulk uploader will compare the file paths in your form with the file paths\n    in your zip to find a matching file.') SSS SSSS SSSSSSSS SSSS SSSSSSS SSS SSSS SSSSS SS SSSS SSSS SSSS SSS SSSS SSSSS
    SS SSSS SSS SS SSSS S SSSSSSSS SSSSSXXXX
  XXX gettext(u"For example, <code>jr://file/commcare/images/hin/image.jpg</code> and your zip's\n    <code>commcare/images/hin/image.jpg</code> file would match, but it would <strong>not</strong> match\n    <code>commcare/images/image.jpg</code>.") SSS SSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSS SSSS SSSSS
    SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSS SSSSS SSSSSS SSS SS SSSSS SSSSSSSSSSSSSSSSSSSS SSSSS
    SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSXXXX

  BBB BBBBBBBB BB BBBBBBBBB
    XXXX XXXXXX
      XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'\n          Your browser does not support this uploader.\n          We recommend <a href="https://www.google.com/intl/en/chrome/browser/">Google Chrome</a>.\n        ') 
          SSSS SSSSSSS SSSS SSS SSSSSSS SSSS SSSSSSSSS
          SS SSSSSSSSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSS
        
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Select Files') XXXXXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX  gettext(u'Begin Upload') 
        XXXX
      XXXXXX
      XXXX gettext(u'Bulk Upload File Queue') XXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXX
          XXX XXXXXXXXXXXXXXXXX gettext(u'Filename') XXXXX
          XXX XXXXXXXXXXXXXXXXX gettext(u'Size') XXXXX
          XXX XXXXXXXXXXXXXXXXX gettext(u'Upload Progress') XXXXX
          XXX XXXXXXXXXXXXXXXXX gettext(u'Match Status') XXXXX
          XXX XXXXXXXXXXXXXXXXX gettext(u'Details') XXXXX
        XXXXX
        XXXXXXXX
        XXXXXXX
        XXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX  XXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Queued Files') XXXXX
        XXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXX gettext(u'Select files above to add to the queue.') SSSSSS SSSSS SSSSS SS SSS SS SSS SSSSSSXXXXX
        XXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXX gettext(u'Processing Upload') XXXXX
        XXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXX gettext(u'Uploaded Files') XXXXX
        XXXXX
        XXXXXXXX
      XXXXXXXX
    XXXXXX
  BBBBBB
BBBBBBBB
