COMPUTED_USER_NAME_PROPERTY_ID = "computed/user_name"
COMPUTED_OWNER_NAME_PROPERTY_ID = "computed/owner_name"

UI_AGG_AVERAGE = "Average"
UI_AGG_COUNT_PER_CHOICE = "Count per Choice"
UI_AGG_GROUP_BY = "Group By"
UI_AGG_SUM = "Sum"
UI_AGGREGATIONS = (
    UI_AGG_AVERAGE,
    UI_AGG_COUNT_PER_CHOICE,
    UI_AGG_GROUP_BY,
    UI_AGG_SUM,
)

UCR_AGG_AVG = 'avg'
UCR_AGG_EXPAND = 'expand'
UCR_AGG_SIMPLE = "simple"
UCR_AGG_SUM = 'sum'
UCR_AGGREGATIONS = (
    UCR_AGG_AVG,
    UCR_AGG_EXPAND,
    UCR_AGG_SIMPLE,
    UCR_AGG_SUM,
)

PROPERTY_TYPE_META = "meta"
PROPERTY_TYPE_CASE_PROP = "case_property"
PROPERTY_TYPE_QUESTION = "question"
PROPERTY_TYPE_RAW = "raw"
