BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Log In :: CommCare HQ') BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
         XXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBB
  XXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXXXX
        XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX

  BBBBBBBB BBB
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
  BBBBBBBBBBB
BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBB BBBBBBBBBBBBB
    XXXX BB BBBBBBBBBBBBBBBBB
         XXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX
         BBBBBX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  BBBBBBBB
BBBBBBBB BBBBBBB
