BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Password Reset') BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBBBBBB
  XXX XXXXXXXXXXXXXXXXXXXX
     gettext(u'Reset Password') 
  XXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB
