BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Password Reset Complete') BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBBBBBB
  XXX XXXXXXXXXXXXXXXXXXXX
     gettext(u'Reset Password') 
  XXXXX

  XX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Your password was successfully changed.') XXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
       gettext(u'Sign In') 
    XXXX
  XXXXXX
BBBBBBBB
