BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Password Reset Confirmation') BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBBBBBB
  BB BBBBBBBBB
    XXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
      BBBBBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXX
         gettext(u'Reset Password') 
      XXXXX
      BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
          
        XXXXXX
      BBBBBB
      XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXBB BBBBBBBBBBBB XXXXXXXXXBBBBBXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXX
              
              BBB BBBBB BB BBBBBBBBBBBB
                XX XXXXXXXXXXXXXXXXXXXXXXX
              BBBBBB
              BB BBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXXXXXXX
                  
                XXXX
              BBBBB
            XXXXXX
          XXXXXX
        BBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX
             gettext(u'Reset Password') 
          XXXXXXXXX
        XXXXXX
      XXXXXXXXXXX
    XXXXXXX
  BBBB

    XXX XXXXXXXXXXXXXXXXXXXX
       gettext(u'Reset Password Unsuccessful') 
    XXXXX
    XX XXXXXXXXXXXXX
       gettext(u'\n        The password reset link was invalid, possibly because\n        it has already been used.\n      ') 
        SSS SSSSSSSS SSSSS SSSS SSS SSSSSSSS SSSSSSSS SSSSSSS
        SS SSS SSSSSSS SSSS SSSSS
      
    XXXX
    XX XXXXXXXXXXXXX
       gettext(u'\n        Please request a new password reset.\n      ') 
        SSSSSS SSSSSSS S SSS SSSSSSSS SSSSSS
      
    XXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXX XXXXXXXXXXXX
         XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX
         gettext(u'\n          Request Password Reset\n        ') 
          SSSSSSS SSSSSSSS SSSSS
        
      XXXX
    XXXXXX
  BBBBB
BBBBBBBB
