BBBBBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Password Change Complete') BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBB
  XXXX XXXXXXXXXXXX
    XXX gettext(u'Your password was successfully changed.') XXXX
    XX XXXXXXBBB BBBBBBBX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Sign In') XXXX
  XXXXXX
BBBBBBBB
