#!/bin/bash

command=$1

# verify command is valid and print usage otherwise
case $command in
  stop|start|restart)
    ;;
  *)
    # This is bash's way of printing a multiline string
    cat << EOF
usage: $0 [stop|start|restart]

This script stops, starts, or restarts all pillowtop processes using supervisorctl

EOF
    exit 1
    ;;
esac

# grep supervisor status for all processes containing '-pillowtop-'
# strip away everything except just the process name
# and pass that to supervisorctl as args
sudo supervisorctl status | grep '\-pillowtop-' | cut -d' ' -f1 | xargs sudo supervisorctl $command
