#!/bin/bash

if [[ -z "$1" ]]; then
    echo "usage: $0 path/to/staging.yaml [--deploy]"
    exit
fi

f=$1
shift

if [[ $1 = "--deploy" ]]; then
    deploy='y'
    shift
fi

function rebuildstaging() {
    python scripts/rebuildstaging.py < $f "$@"
}

if [[ $deploy = "y" ]]; then
    rebuildstaging && fab --linewise staging preindex_views && printf 'y\ny\n' | fab --linewise staging deploy
else
    rebuildstaging
fi
