#!/bin/bash

if [[ $1 = "--deploy" ]]; then
    deploy='y'
    shift
fi

function rebuildstaging() {
    python scripts/rebuildstaging.py < scripts/staging.yaml "$@"
}

if [[ $deploy = "y" ]]; then
    rebuildstaging && fab staging awesome_deploy:confirm=no
else
    rebuildstaging
fi
