########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud --control staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
    # see https://confluence.dimagi.com/display/GTD/Deploy+Process#DeployProcess-vellum
    - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
    # - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
    - sr/case-reindex-staging # Sravan Oct 14
    - sr/es-alias # Sravan Nov 18
    - sr/cs-multiselect  # Sravan May 31
    - ce/bulk-case-search # Cal July 6
    #- sr/memoized-toggle # Sravan July 26
    - bmb/sso-login-v2  # Biyeun July 26
    - jls/caktus-data-dictionary-release-2 # Jenny Sept 21
    - cs/SC-1567-bulk-export-filters # Charl Aug 26
    - smh/cross-domain-ucr-report-builder-ui # Steph Sept 14
    - dmr/throttle-system-forms  # Danny Sept 24
    - smh/remove-extra-spinner-icons # Steph Oct 6
    - ml/remove-pickles-phonelog # Minha Oct 7
    - dependabot/npm_and_yarn/moment-2.29.1 # Amit Oct 8
    - dependabot/pip/requirements/certifi-2021.10.8   # SK / Joel Oct 12
    - ml/remove-pickles-user-importer # Minha Oct 13
    - ml/remove-pickles-reports # Minha Oct 21
    - jls/enable-usercase-button # Jenny Oct 27
    - bmb/update-datatables-dt  # Biyeun Nov 2
    - rc/store-usernames-in-log # Robert Nov 4
    - gh/use-email-for-all-comms # Graham Nov 8 (passive QA testing: check back on Dec 6)
    - rp/status-embed # Rynhard Nov 9
    - jls/smart-linking-in-web-apps # Jenny Sept 22
    - ad/tab-structure-for-check-boxes # Addison Nov 11
    - revert-30687-revert-30182-jm/remove-es-scan  # Joel Nov 12
    - gh/mrm/only-admins-can-link # Graham Nov 16
    - fr/generic-repeater         # Farid Nov 16
    - sk/check-correct-db # Simon Nov 17
submodules: { }
