########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging --deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.


trunk: master
name: autostaging
branches:
  - b3-app-manager+xpath-error-message  # Danny 1/27
  - xpath-error-message  # Danny 1/27
  - kill-x_over_time  # Danny 12/11
  - vellum-staging # J$ 11/13
  #- fix-toggle+two-factor-otp-only #wsp 11/17
  #- two-factor-otp-only+add-tableau-dashboard  # Ethan 11/24
  #- two-factor-otp-only # j$ 10/2
  - requests #Simon 11/3
  - add-tableau-dashboard # TS 11/5
  - location-delete+location-cases  # Ethan 1/19
  #- tabular-reports-b3-migrate  # Biyeun 1/15
  - location-cases  # Ethan 1/19
#  - b3-app-manager+new-footer-nav # Jenny 1/25
  - b3-app-manager # Jenny 1/20
#  - new-footer-nav # Biyeun 1/4
#  - formplayer-toggle # Ben/Will 1/21/16
#  - java-tf-deploy # Ben/Will 1/21/16
  # B3 Report Migration branches
  - b3-reports-worker-monitoring  # Biyeun 1/21
  - b3-reports-inspect-data  # Biyeun 1/21
  - b3-reports-manage-deployments  # Biyeun 1/21
  - b3-reports-messaging  # Biyeun 1/21
  - finish-two-factor # Cal 1/21
  - lazy-jar # Nick P 1/25
submodules:
  submodules/touchforms-src:
    # let's leave this here even when empty
    # just so we always get latest master
    branches: []
  submodules/formtranslate-src:
    # let's leave this here even when empty
    # just so we always get latest master
    branches: []
  submodules/ctable-src:
    branches: []
  submodules/django-digest-src:
    branches: []
  submodules/dimagi-utils-src:
    branches: []
  submodules/django-prbac-src:
    branches: []
