########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging (--deploy)
#     OR run deploy separately
#     $ commcare-cloud --control staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
    # see https://confluence.dimagi.com/display/GTD/Deploy+Process#DeployProcess-vellum
    - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
    # - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
    # - sr/es-alias # Sravan Nov 18
    - ce/bulk-case-search # Cal July 6
    # - sr/memoized-toggle # Sravan July 26
    # - dependabot/pip/requirements/certifi-2021.10.8   # SK / Joel Oct 12
    # - mk/support-expanded-cols-in-mobile-ucr # MK Feb 2
    - bmb/sso/api/test-001  # Biyeun June 15
    - dmr/add-support-for-ses-django-email-backend  # Danny Aug 26
    - do/migrate-apps # Dominic Sep 2
    - smh/remove-setSelectedValue-import # Steph Sept 20
    - akj/release-mode-toggle # Akash 7 Oct
    - akj/migrations-fix # Akash Oct 11
    - mk/support-expanded-cols-in-mobile-ucr-2 # MK Oct 31
    # - akj/abdm-api-for-mobile-app # Akash Sep 28
    - es/redirect-domain  # Ethan Nov 21
    #- jls/web-apps-requirejs  # Jenny Jan 17
    - gh/remove-duplicate-kafka-seq-code # Graham Dec 26
    - gh/refactor-orphaned-ucr-code # Graham Dec 26
    - jls/new-instance-connectors # Steph Dec 27
    - smh/allow-eof-form-lining-multi-select # Steph Jan 4
    - jm/refactor-api-es  # [QA] Joel Jan 10
    - jm/refactor-user-pillow  # [QA] Joel Jan 10
    - pkv/data-dictionary-labels-cle-integration # Pawan Jan 11
    #- ad/user-syncing-task # Addison Jan 13  # conflicts with 'ad/user-syncing-UI' disabled by Joel Jan 23
    - em/case-search-filter-feature-flag # Evan Jan 18
    - akj/ush-2613-commcare-user-case # Akash Jan 19
    - rp/mobile-worker-bulk-download-ui-change # Rynhard Jan 20
    - akj/case-detail-close-accessibility # Akash Jan 21
    - jm/refactor-user-signals  # [QA] Joel Jan 23
    - em/switching-project-spaces-bugfix # Evan Jan 25
    - ap/rename-sql-repeaters # Amit Jan 26
    - ad/remove-entered-wrap-functions # Addison Jan 26
    - revert-32492-ad/incomplete-forms-hotfix # Jonathan T. Jan 26
    - pkv/accessibility-tree-change-1932 # Pawan Jan 27
    - pkv/sync-complete-action-indicator-sr # Pawan Jan 27
    - revert-32548-revert-32435-sk/sentry-js  # Simon Jan 27
    - akj/ush-1508-checkbox-accessibility # Akash Jan 29
    - jls/remove-a-lot-of-wrapping # Jenny Jan 30
    - revert-32543-revert-32491-jt/ush-2683_custom_text_for_case_list_empty_state # Jonathan T. Jan 30
    - dm/reindex-migrations # Daniel Jan 31
submodules: { }
