########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging --deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.


trunk: master
name: autostaging
branches:
  - devicereportentry  # Danny 2/18
  - vellum-staging # J$ 11/13
  - java-tf-deploy # Ben/Will 1/21/16
  # B3 Report Migration branches
  - b3-reports-worker-monitoring  # Biyeun 1/21
  - b3-reports-inspect-data  # Biyeun 1/21
  - b3-reports-manage-deployments  # Biyeun 1/21
  - b3-reports-messaging  # Biyeun 1/21
  - finish-two-factor # Cal 1/21
  - show-form-case-refs-in-summary # j$ 1/29
  - revamp-multimedia # Jenny 2/16
  - analytics-retry # Cal 2/18
  - upgrade-django-tastypie # Nick P 2/22
  - raw-forms-es # Ben 2/23
  - email_list-soft_assert # Nick P 2/23
  - j2me # j$ 2/23
  # B3 Changes round 2
  - b3-reports-data  # BB 2/23
  - b3-data-import-cases  # BB 2/23
  - b3-data-lookup-tables  # BB 2/23
  - b3-reports-case-form+b3-reports-home  # BB 2/24
  - b3-reports-home  # BB 2/23
  - b3-reports-case-form  # BB 2/24
  - b3-billing-views
submodules:
  submodules/touchforms-src:
    # let's leave this here even when empty
    # just so we always get latest master
    branches:
      - 2.26-jars # wsp 2.23
  submodules/formtranslate-src:
    # let's leave this here even when empty
    # just so we always get latest master
    branches:
      - 2.26_jar  # wsp 2.23
  submodules/ctable-src:
    branches: []
  submodules/django-digest-src:
    branches: []
  submodules/dimagi-utils-src:
    branches: []
  submodules/django-prbac-src:
    branches: []
  corehq/apps/prelogin:
    branches: []
