########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
branches:
  - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
  - bmb/odata-qa-feedback  # Biyeun April 15
  - dmr/require_can_edit_or_view_commcare_users-download_commcare_users  # Danny April 27
  - sr-es-alias # Sravan April 29
  - jls/migrate-CustomDataFieldsDefinition-2 # Jenny April 29
  - bmb/SAAS-10813  # Biyeun April 30
  - mk/location-reassignment-realign # MK May 4
  - mk/location-reassignment-add-view # MK May 3
  - rn_update_perfect_scrollbar # Rohit Negi May 4
  - bmb/SAAS-10674  # Biyeun May 4
  - dmr/case-upload-success-result-followup  # Danny May 5
  - ce/refer-case-repeater # Cal May 7
  - dmr/formplayer-browser-errors-extra-info  # Danny May 8
  - dmr/consistently-add-username-to-sentry-reports  # Danny May 8

submodules: {}
