########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on
# to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging --deploy
# Both commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.


trunk: master
name: autostaging
branches:
  - archive-products+explicit_case_processing # tw 8/14
  - explicit_case_processing # danny?
  - master+schedule # Nick P 9/11
  - schedule # SK 7/17
#  - add-build-ui
  - hq-dropdown # sravan 5/7
  - refactor-domain-copy2  # Brian 5/20
  - logos+master # tw
  - logos # Nick P 5/28
  - admin-reports # Nick P 8/13
#  - subscription-no-contact-info # bb 8/4
  - increase-es-timeout # Nick P 8/11
  - archive-products # tw 8/14
  - archive-programs # tw 9/30 (branched from archive-products)
  - custom-exports-better-ordering  # (lwyszomi/86347-2) Danny 8/26
  - subscription-no-contact-info # bb 8/4
  - fix-timeout # Nick P 8/26
  - custom_user_data # tw+Ethan 9/9
  - lwyszomi:better_date_filters_improvment
  - master+uservoice-pending-invitations # Nick P 9/24
  - lwyszomi:uservoice-pending-invitations
  # - lwyszomi:b3-mobile-layout
  - revert-4205-revert-3841-86347-2 # Daniel 9/11
  - bulk-app-translate # Noah 9/18
  - callcenter # SK 9/22
  - fixture-prop # sravan 9/2e
  - users_es  # Ethan 9/24 (depends on pillowtop-src - save-to-es)
  - status-only-celery # ts 9/30
submodules:
  submodules/couchlog-src:
    branches:
      - static-tags # Nick P 5/20
  submodules/django-soil-src:
    branches:
      - static-tags # Nick P 5/20
#  submodules/formdesigner:
#    branches:
#      - develop-staging # Daniel 6/12 (major refactor + itemsets?)
#      - universal-analytics-upgrade # Nick P 7/8
  submodules/formtranslate-src:
    branches:
      - static-tags # Nick P 5/20
      # Danny 8/12. If form validation seems wonky on staging, just remove this
      - clean-up-api
  submodules/touchforms-src:
    branches:
      - static-tags # Nick P 5/20
#  submodules/dimagi-utils-src:
#    branches:
#      - json_response-status
  submodules/dimagi-utils-src:
    branches:
      # Danny 8/12. If there's weird errors or issues in saving forms
      # or saving apps, just remove this
      - faster-lazy-attachments
  submodules/pillowtop-src:
   branches:
      - request_timeout+save-to-es  # Ethan 9/25
      - request_timeout  # Ethan 9/24
      - save-to-es  # Ethan 9/24
  # corehq/apps/hqmedia/static/hqmedia/MediaUploader:
  #   branches:
  #     - allowclose # SK 9/23
