########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
branches:
  - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
  - jls/sync-mixins-hard-fail # Jenny May 24
  - jls/migrate-CustomDataFieldsDefinition-2 # Jenny April 29
  - rn_update_perfect_scrollbar # Rohit Negi May 4
  - jls/migrate-MobileAuthKeyRecord-2 # Jenny May 16
  - bmb/SAAS-10882  # Biyeun May 20 (updates knockout, bootstrap, jquery, DOMPurify)
  - nh/repeaters_ui  # Norman May 28
  - nh/charset  # Norman May 27
  - ce/web-apps-permission # Cal May 27
  - jls/push-linked-apps # Jenny May 31
  #- orangejenny-patch-3 # Jenny May 28; this is the 3-minute timeout branch
  - ap/lazy-load-multimedia # Amit June 5
  - fr/multiple-api-keys  # Conflicting migrations with ce/web-apps-permissions
  # - fr/multiple-api-keys+ce/web-apps-permission # FR Jun 8 -- adds merge migration for users app
  # ^^^ NH: Commenting out for now because migration from ce/web-apps-permission is missing. I can't see why.
  - jls/DRYer-case-config-ui-3 # Jenny June 6
  - revert-27725-jls/kill-configurable-timeout # Jenny June 9
  - nemanja1040:turn_gateway_improvements  # Nemanja Stancic June 10

submodules: {}
