########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud staging fab deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
branches:
  - vellum-staging # J$ 11/13
  - jls/privacy-policy  # Jenny 3/19
#  - jls/data-corrections-forms  # Jenny 3/27
  - fr/property-changes-paginated # FR 29/3
  - np/training-module  # NP 4/2
  - je/report-builder-button # J$ 4/3
  - np/flavor  # NP 4/5
  - sr-couch-synclogs+ce/user-loc-query # cal April 9
  - sr-couch-synclogs  # Sravan April 6
  - ce/auto-batches # Cal April 6
  - jls/externalize-js-more-report-filters # Jenny April 6
  - ce/user-loc-query # Cal April 9
submodules:
  submodules/touchforms-src:
    # let's leave this here even when empty
    # just so we always get latest master
    branches: []
  submodules/django-digest-src:
    branches: []
  corehq/apps/hqmedia/static/hqmedia/MediaUploader:
    branches: []
  submodules/commcare-translations:
    branches: []
