########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
    # see https://confluence.dimagi.com/display/commcarehq/Deploy+Process#DeployProcess-DeployingVellumtoStaging
    - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
    # - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
    #- fr/user-data-jit            # Farid September 2
    - sr/case-reindex-staging # Sravan Oct 14
    - sr/es-alias # Sravan Nov 18
    - dmr/count-email-sends-bounces-by-domain  # Danny Dec 18
    - dmr/add-metric-for-new-repeat-records  # Danny Apr 14
    - dependabot/pip/requirements/certifi-2021.5.30 # SK / Joel May 31
    - sr/cs-multiselect  # Sravan May 31
    - gh/improve-erm-ui # Graham June 16 [QA]
    - rn_disallow_yui_cors # Rohit Negi
    - jm/repeater-domain-admins  # Joel June 21
    - sp/csrf # Amit + Shivam June 30
    - cs/SC-1580-improve-dhis2-complete-date-workflow  # Charl June 25
    - cs/SC-691-add-support-for-geolocation  # Charl July 5
    - gh/add-app-id-behind-ff # Graham July 6 [QA]
    - ce/bulk-case-search # Cal July 6
    - ap/auditcare-migration # Amit July 8
    - rc/explain-before-entering # Robert July 8 [QA]
    - revert-30036-revert-30004-sr/default-filters # Sravan July 12
    - rp/enterprize-sms-report # Rynhard July 12
    - bmb/hubspot-privacy  # Biyeun July 12
    - jls/smart-linking-login-as # Jenny July 12
    - jls/wip # Jenny July 16
    - bmb/sso-domain-login-update  # Biyeun July 15
    - smh/tableau-server-dropdown-modification # Steph July 19
    - bmb/sso-alternate-login  # Biyeun July 19
    - revert-30073-revert-29936-gh/split-toggles-and-previews # Graham July 19
submodules: { }
