########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
    # see https://confluence.dimagi.com/display/commcarehq/Deploy+Process#DeployProcess-DeployingVellumtoStaging
    - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
    # - jls/sync-mixins-hard-fail # Jenny May 24
    - jls/migrate-MobileAuthKeyRecord-2 # Jenny May 16
    # - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
    - fr/user-data-jit            # Farid September 2
    - sr/case-reindex-staging # Sravan Oct 14
    # - gh/improve-queueing-repeaters # Graham Oct 22
    - sr/es-alias # Sravan Nov 18
    - dmr/count-email-sends-bounces-by-domain  # Danny Dec 18
    - smh/modify_admin_role_display_web_invite_download # Steph Mar 2
    - dmr/add-metric-for-new-repeat-records  # Danny Apr 14
    - dependabot/pip/requirements/certifi-2020.12.5 # Joel Apr 19
    - jls/refactor-details-js-retry # Jenny May 5
    - jls/detail-nodeset-rebased # Jenny May 6
    - orangejenny-patch-8 # Jenny May 27
    - jls/cross-domain-web-user-download # Jenny April 24
    - smh/embedded-tableau # Steph May 7
    - gh/add-app-id-to-downstream-report # Graham May 18
    - sk/sql-user-role  # Simon May 19
    - mk/case_search_labels/migrate # MK May 21
    - mk/case_search_labels/multimedia # MK May 21
    - sr/hide-geo  # Sravan May 25
    - bmb/sso-new-user-page  # Biyeun 25th May
    - bmb/sso-remove-toggle  # Biyeun 25th May
    - cs/dhis-readable-response  # Charl 26 May
    - bmb/sso-cleanup-errors  # Biyeun 26 May
    - bmb/sso-fix-iframe-login  # Biyeun 27 May
    - bmb/sso-next-redirect-test  # Biyeun 27 May
    - cs/annote-route  # Charl 28 May
    - sk/test_role_create_update  # Simon May 28
submodules: { }
