########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging --deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.


trunk: master
name: autostaging
branches:
  - vellum-staging # J$ 11/13
  - fixtures-spike  # cz 1/29
  - update-submodules # TS 5/6
  - languageMedia # Sravan 6/10
  - web-user-requests # Jenny, July 16
  - template-apps # Jenny, July 20
  - opbeat # Simon 7/22
  - FormArchive # Sravan 7/22
  - icds/scheduler # Farid 7/22
  - ckeditor # J$ 7/24
  - dropbox # Ben 7/27
  - notify-exception  # Ethan 7/27
submodules:
  submodules/touchforms-src:
    # let's leave this here even when empty
    # just so we always get latest master
    branches:
      - django17
      - revert-148-revert-147-2.22_jars  # cz 7/23. also love this branch name.
  submodules/formtranslate-src:
    # let's leave this here even when empty
    # just so we always get latest master
    branches: []
  submodules/ctable-src:
    branches: []
  submodules/django-digest-src:
    branches:
      - django17
  submodules/pillowtop-src:
    branches:
      - django17
  submodules/django-soil-src:
    branches:
      - dropbox # Ben 7/27

