########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
    # see https://confluence.dimagi.com/display/commcarehq/Deploy+Process#DeployProcess-DeployingVellumtoStaging
  - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
  # - jls/sync-mixins-hard-fail # Jenny May 24
  - jls/migrate-MobileAuthKeyRecord-2 # Jenny May 16
  # - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
  - fr/user-data-jit            # Farid September 2
  - sr/case-reindex-staging # Sravan Oct 14
  # - gh/improve-queueing-repeaters # Graham Oct 22
  - sr/es-alias # Sravan Nov 18
  - dmr/count-email-sends-bounces-by-domain  # Danny Dec 18
  - nh/dhis2/sqldataset_maps  # Norman Dec 18
  - nh/reminders  # Norman Jan 26
  - smh/bulk-upload-web-users # Steph Feb 22
  - nh/fhir/repeater  # Norman Mar 1
  - smh/modify_admin_role_display_web_invite_download # Steph Mar 2
  - fr/consumer-user             # Farid March 17
  - mjr/xss_accounting # Matt Mar 24
  - solleks:cdg/accessible_links2 # Charlie/Steph Mar 25
  - solleks:cdg/upgrade_select2 # Charlie/Staph/Jenny April 7
  - sk/get_display_data # Simon March 30
  - sk/consolidate-doc-lookup # Simon March 30
  - sr/ucr-cs  # Sravan March 31
  - bmb/sso-token-encryption  # Biyeun Apr 1
  - sr/pagedSessions  # Sravan April 2
  - nh/wfp/api_manager  # Norman Apr 2
  - ap/escape-html-in-app-manager # Amit Apr 2
  - ap/escape-html-in-cloudcare # Amit Apr 2
  - ap/escape-html-in-hqwebapp # Amit Apr 2
  - ap/escape-html-in-multimedia # Amit Apr 2
  - ap/escape-html-in-reports # Amit Apr 2
  - ap/escape-html-in-users # Amit Apr 2
  - ap/escape-templates-in-datainterfaces # Amit Apr 2
  - ap/escape-html-in-remaining-apps # Amit Apr 5
  - smh/missing-queryData # Steph Apr 2
  - revert-29446-revert-29218-mjr/xss_app_manager # Matt April 5
  - mjr/xss_reports  # Matt April 7
  - sr/jumptoErrors # Sravan April 6
  - fr/smart-oauth-prep         # Farid April 7
  - mk/form-mm-exports-filters # MK April 8
  - fr/smart-oauth-views        # Farid April 7
  - mjr/xss_custom_fields  # Matt April 7
  - dmr/remove-vestigial-reference-to-session-cookie  # Danny Apr 7
  - ap/fix-ko-html-parsing-issues # Amit April 8
  - rp/fix-2fa-hyperlink # Rynhard April 8
  - rp/fix-broken-link-2.0 # Rynhard April 8
  - dmr/remove-unused-url  # Danny Apr 8

submodules: {}
