########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
  # DO NOT REMOVE this is similar to "autostaging", but for vellum
  # If this branch conflicts, run: scripts/vellum-to-hq staging --push --fix-staging
  - vellum-staging
  
  - jls/sync-mixins-hard-fail # Jenny May 24
  - jls/migrate-MobileAuthKeyRecord-2 # Jenny May 16
  - jls/migrateCommtrackConfig-2 # Jenny Sept 27
#  - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
  - fr/user-data-jit            # Farid September 2
  - sr/case-reindex-staging # Sravan Oct 14
  - gh/improve-queueing-repeaters # Graham Oct 22
  - sr/es-alias # Sravan Nov 18
  - nh/dhis2/sqldataset_maps  # Norman Dec 18
  - dmr/count-email-sends-bounces-by-domain  # Danny Dec 18
  - prem-fissionhq:dedicated_migration_process # Prem/Amit Dec 23
  - sr/parent-select # Jenny Dec 29
  - dependabot/npm_and_yarn/markdown-it-12.0.4 # Amit Dec 28
  - bmb/sso-architecture  # Biyeun Dec 30
  - sr/ext-import # Sravan Jan 7
  - jls/web-apps-case-claim-itemsets+smh/query-screen-prompt-defaults
  - smh/query-screen-prompt-defaults # Steph Jan 5
  - jls/web-apps-case-claim-itemsets # Jenny Jan 12
  #- bmb/sso-architecture+lxml-upgrade  # Biyeun Jan 8
  #- dependabot/pip/requirements/lxml-4.6.2  # Biyeun Jan 8
  #- solleks:cdg/accessible_pagination  # Ben / Charlie Jan 11
  - mk/remove-aaa # MK Jan 18
  - gh/filetype-migration # Graham Jan 12
  - bmb/sso-debug  # Biyeun Jan 12
  #- sr/casesearch  # Sravan Jan 18
  - dmr/formplayer-sync-db  # SK Jan 18
submodules: {}
