########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud --control staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
    # see https://confluence.dimagi.com/display/GTD/Deploy+Process#DeployProcess-vellum
    - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
    # - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
    #- fr/user-data-jit            # Farid September 2
    - sr/case-reindex-staging # Sravan Oct 14
    - sr/es-alias # Sravan Nov 18
    - dependabot/pip/requirements/certifi-2021.5.30 # SK / Joel May 31
    - sr/cs-multiselect  # Sravan May 31
    - cs/SC-1580-improve-dhis2-complete-date-workflow  # Charl June 25
    - ce/bulk-case-search # Cal July 6
    - rp/enterprize-sms-report # Rynhard July 12
    - ml/add-bulk-delete-form-export-report # Minha July 20
    #- sr/memoized-toggle # Sravan July 26
    - bmb/sso-login-v2  # Biyeun July 26
    - cs/SC-1640-send-unique-identifier-telerivit  # Charl Aug 6
    - jls/caktus-data-dictionary-release-2 # Jenny Sept 21
    - dependabot/pip/requirements/python3-saml-1.12.0  # Joel Aug 24
    - cs/SC-1567-bulk-export-filters # Charl Aug 26
    - ml/add-bulk-action-scheduled-reports # Minha Aug 30
    - gh/remove-pickles-from-accounting # Graham Sep 3
    - gh/erm/allow-text-input-for-new-domain # Graham Sept 13
    - smh/cross-domain-ucr-ui-updates # Steph Sept 14
    - smh/cross-domain-ucr-report-builder-ui # Steph Sept 14
    - rp/improve-deleted-odata-feed-error-message # Rynhard Sept 15
    - gh/erm/link-reports-and-keywords-on-push+gh/erm/fix-bug-when-pulling # Graham Sept 27
    - gh/erm/link-reports-and-keywords-on-push # Graham Sept 15
    - fr/dedupe  # Farid Sept 17
    - jm/remove-es-scan  # Joel Sep 17 [QA]
    - ap/add-permission-to-edit-ucrs # Amit Sept 21
    - smh/extract-messaging-permission # Steph Sept 21
    - jls/smart-linking-in-web-apps # Jenny Sept 22
    - dmr/throttle-system-forms  # Danny Sept 24
    - gh/erm/fix-bug-when-pulling # Graham Sept 27
    - jls/merge-migrations # Jenny Sept 28
submodules: { }
