########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud --control staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
    # see https://confluence.dimagi.com/display/GTD/Deploy+Process#DeployProcess-vellum
    - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
    # - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
    - sr/es-alias # Sravan Nov 18
    - ce/bulk-case-search # Cal July 6
    # - sr/memoized-toggle # Sravan July 26
    - smh/remove-extra-spinner-icons # Steph Oct 6
    # - dependabot/pip/requirements/certifi-2021.10.8   # SK / Joel Oct 12
    - es/mobile-auth # Simon Nov 23
    # - mk/support-expanded-cols-in-mobile-ucr # MK Feb 2
    - nh/loadtest_users_postmigration  # Norman March 25
    - ml/all-in-one-offboarding # Minha April 13
    - rp/gsheet/create-livegooglesheetview # Rynhard March 23
    - rp/gsheet/create-refresh-google-sheet-task # Rynhard Apr 19
    - ml/dhis2-error-handling # Minha April 21
    - rp/gsheet/update-project-info-form # Rynhard April 22
    - cs/SC-1945-ability-to-add-filter-to-rules+ad/autoupdate-criteria-operator # Addison April 26
    - cs/SC-1945-ability-to-add-filter-to-rules # Charl April 26
    - ad/autoupdate-criteria-operator # Addison April 26
    - bmb/sso-oidc-endpoints  # Biyeun May 2 DO NOT REMOVE. PEN TEST IN PROGRESS!!
    - ml/case-property-bug # Minha April 28
    - es/datums+jls/multiple-referrals-eof-nav
    - jls/multiple-referrals-eof-nav # Jenny May 5
    - es/datums # Ethan/Jenny May 12
    - cs/SC-1789_webusers_domain_memberships_assigned_location_ids # Charl May 9
    - dependabot/pip/requirements/phonenumberslite-8.12.46  # Joel May 10
    # - dependabot/pip/requirements/reportlab-3.6.9  # Joel May 10
    - gh/use-release-management-permission # [QA] Graham May 10
    - mjr/all_safe_fixes  # Matt May 11
    - bmb/sso-test-users-pt2  # [QA] Biyeun May 13
submodules: { }
