########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on
# to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging --deploy
# Both commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.


trunk: master
name: autostaging
branches:
  - subscription-no-contact-info # bb 8/4
  - vellum-staging # J$ 11/13
  - fixtures-spike  # cz 1/29
  - update-submodules # TS 5/6
  - locations-for-robber-barons  # Ethan 5/7
  - form-context-simple # Ben 5/13
  - languageMedia # Sravan 6/10
  - renew-plan # Farid 6/4
  - index-phonelog-reportentry # Ben 6/8
  - add-proxy4 # ts 6/9
  - debug-sync # Nick P 6/9
  - case-list-filter  # Ethan 6/10
submodules:
  submodules/touchforms-src:
    # let's leave this here even when empty
    # just so we always get latest master
    branches:
      - tf-persistence  # wsp 5/7
      - use-classes # ben 5/7
      - 221-jars # wsp 5/20
  submodules/formtranslate-src:
    # let's leave this here even when empty
    # just so we always get latest master
    branches: []
