########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on
# to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging --deploy
# Both commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.


trunk: master
name: autostaging
branches:
  - usec  # danny 4/13
  - subscription-no-contact-info # bb 8/4
  - vellum-staging # J$ 11/13
  - locations-as-groups # tw 1/20
  - fixtures-spike  # cz 1/29
  - usercase # Norman 3/27
  - commcare-supply  # Ethan 4/13
  - new-location  # Ethan 4/14
  - fm-facing-interface+bulk-wire-invoice # Ben 4/23
  - fm-facing-interface # Nick P 4/23
  - bulk-wire-invoice # Ben 4/23
  - commcarehq-prelogin # Biyeun 4/29
  - grunt-task-fabric # Ben 4/29
submodules:
  submodules/touchforms-src:
    # let's leave this here even when empty
    # just so we always get latest master
    branches:
    #  - tf-persistence  # wsp 3/10
      - use-templates # Ben 4/29

  submodules/formtranslate-src:
    # let's leave this here even when empty
    # just so we always get latest master
    branches: []
  submodules/auditcare-src:
    branches:
      - usec  # danny 4/13
  submodules/couchexport-src:
    branches:
      - usec  # danny 4/13
  submodules/couchlog-src:
    branches:
      - usec  # danny 4/13
  submodules/ctable-src:
    branches:
      - usec  # danny 4/13
  submodules/django-digest-src:
    branches:
      - atomic  # Ethan 4/22
  submodules/fluff-src:
    branches:
      - usec  # danny 4/13
  submodules/pillowtop-src:
    branches:
      - usec  # danny 4/13
      - atomic  # Ethan 4/22
  submodules/toggle:
    branches:
      - usec  # danny 4/13
