########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
    # see https://confluence.dimagi.com/display/commcarehq/Deploy+Process#DeployProcess-DeployingVellumtoStaging
    - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
    # - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
    #- fr/user-data-jit            # Farid September 2
    - sr/case-reindex-staging # Sravan Oct 14
    # - gh/improve-queueing-repeaters # Graham Oct 22
    - sr/es-alias # Sravan Nov 18
    - dmr/count-email-sends-bounces-by-domain  # Danny Dec 18
    - smh/modify_admin_role_display_web_invite_download # Steph Mar 2
    - dmr/add-metric-for-new-repeat-records  # Danny Apr 14
    - dependabot/pip/requirements/certifi-2021.5.30 # SK / Joel May 31
    - smh/embedded-tableau # Steph May 7
    - bmb/sso-remove-toggle  # Biyeun 25th May, in pilot & QA please do not remove!
    - cs/dhis-readable-response  # Charl 26 May
    - sr/cs-multiselect  # Sravan May 31
    - sk/test_role_create_update  # Simon May 31
    - bmb/sso-remove-toggle+rp/enterprize-sms-report+jls/move-enterprise-permissions-2-of-3 # Jenny June 4
    - bmb/sso-remove-toggle+rp/enterprize-sms-report  # Biyeun June 2, fixes conflicts
    - rp/enterprize-sms-report #Rynhard June 2
    - cs/SC-1335-dataset-workflow  # Charl June 3
    - fr/remote-linked-ucr      # Farid June 4
    - jls/move-enterprise-permissions-1-of-3  # Jenny June 4
    - jls/move-enterprise-permissions-2-of-3  # Jenny June 4
    - sk/messaging-event-api  # Simon June 7
    - smh/multi-domain-user-upload-update  # Steph June 7
    - bmb/sso-invitation-new  # Biyeun June 9, in pilot & QA please do not remove!
    - jm/remove-es7  # Joel June 9
    - cs/SC-1390-put_turn_behind_ff  # Charl June 10
    - bmb/sso-documentation-links  # Biyeun June 11, in pilot & QA please do not remove!
    - mjr/report-access  # Matt June 14
    - sr/mixed-case-types  # Sravan June 15
    - es/reminders  # Ethan June 15
    - mjr/hidden-report-columns  # Matt June 15
    - gh/improve-erm-ui # Graham June 16
    - gh/fix-b3-modal-bug # Graham June 16
submodules: { }
