########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
deploy_env: staging
branches:
  - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
  - jls/sync-mixins-hard-fail # Jenny May 24
  - rn_update_perfect_scrollbar # Rohit Negi May 4
  - jls/migrate-MobileAuthKeyRecord-2 # Jenny May 16
  - nh/repeaters_ui  # Norman May 28
  - nh/charset  # Norman May 27
  - jls/turn-off-analytics-logging # Jenny June 19
  - fr/shadow-module-child-versioned # Farid July 22
#  - nemanja1040:infobip_fallback_backend  # Nemanja Stancic Jul 29
  - kev/combobox-add-ors # Kevin July 30
  - fr/authenticated-soil-downloads # Farid July 31
  - jls/linked-domains-parallel-release # Jenny July 31
  - jls/view-apps-permission # Jenny July 31
  - ml/SAAS-11077-deleted-case-properties-position # Michelle July 31
  - ml/SAAS-10954-show-all-filter # Michelle July 31
  - jls/CustomDataFieldsProfile # Jenny July 24
  - sr/es7-ref1 # Sravan Aug 4
#  - sk/remove-icds  # Simon Aug 3
submodules: {}
