########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud staging fab deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
branches:
  - nh/omrs/levenshtein # Norman June 29
  - es/location-upload  # Ethan July 6
  - jls/unify-tab-history  # Jenny July 10
  - jls/appcues-template-apps  # Jenny July 16
  - jls/requirejs-case-importer  # Jenny July 17
  - revert-21236-fr/add-secure-urllib3  # Danny July 18
  - jls/requirejs-domain-billing  # Jenny July 19
  - nh/lw/dhis  # Norman July 20
  - np/attachments-soft_assert  # NP July 20
  - dmr/fix-package-security-vulnerabilities  # Danny July 21
  #- jls/requirejs-login  # Jenny July 22
  - jls/enterprise-settings  # Jenny July 23
  - nh/fix_staging/why  # Norman July 24
submodules:
  submodules/django-digest-src:
    branches: []
  corehq/apps/hqmedia/static/hqmedia/MediaUploader:
    branches: []
  submodules/commcare-translations:
    branches: []
