########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on and master
# checked out to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to check if your branch causes any conflicts before rebuilding
#     $ scripts/rebuildstaging --no-push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging
#     $ commcare-cloud staging deploy
# Above commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar --no-track origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.

# FORMPLAYER
# From the formplayer, repo, call `./scripts/rebuildstaging`
# This rebuilds the `autostaging` branch of formplayer and runs the formplayer-staging job on jenkins

trunk: master
name: autostaging
branches:
  - vellum-staging  # DO NOT REMOVE this is similar to "autostaging", but for vellum
  - jls/migrate-DefaultConsumption-3 # Jenny April 24
  #- jls/use-textinput # Jenny March 10
  - mk/location-reassignment-13 # MK April 17
    #- mk/location-reassignment-11-followup
  - bmb/SAAS-10712  # Biyeun April 1
  - ap/remove-delete-in-name # Amit April 8
  - bmb/odata-qa-feedback  # Biyeun April 15
    #  - fr/turn-backend        # Farid April 17 # Removed April 25 from conflict
    #- dmr/track-sms-by-backend  # Danny April 22
  - revert-27273-revert-27244-dmr/case-upload-success-result  # Danny April 27
  - dmr/fix-build_full_schema-poll-condition  # Danny April 27
  - dmr/require_can_edit_or_view_commcare_users-download_commcare_users  # Danny April 27

submodules: {}
