#!/bin/bash

MODULE_NAME=$1
MODULE_URI=$2
OLD_PATH=$3
NEW_PATH=$4

function subtree-merge() {
  module_name=$1
  module_uri=$2
  old_path=$3
  new_path=$4

  git remote add -f $module_name $module_uri
  git merge -s ours --no-commit $module_name/master
  git read-tree --prefix=$new_path -u $module_name/master:$old_path
  git commit -m "subtree merge $module_name:$old_path into $new_path"
}

subtree-merge $MODULE_NAME $MODULE_URI $OLD_PATH $NEW_PATH

echo "Merge complete. If this was a submodule, remember to also"
echo "- remove it, e.g.:"
echo "  git rm --cached submodules/django-soil-src"
echo "  rm -rf submodules/django-soil-src"
echo "  vim .gitmodules  # remove 'submodules/django-soil-src' section"
echo "- ensure its tests run along with the rest of commcarehq's tests, e.g."
echo "  vim settings.py  # remove from APPS_TO_EXCLUDE_FROM_TESTS
