from memoized import memoized

from custom.inddex.ucr.data_providers.mixins import GapsReportByItemDataMixin


class GapsReportByItemSummaryData(GapsReportByItemDataMixin):
    total_row = None
    title = 'Gaps By Item Summary'
    slug = 'gaps_by_item_summary'
    headers_in_order = [
        'food_code', 'food_name', 'fao_who_gift_food_group_code', 'fao_who_gift_food_group_desc',
        'user_food_group',
        'food_type', 'number_of_occurrences', 'conv_factor_gap_code', 'conv_factor_gap_desc',
        'fct_gap_code', 'fct_gap_desc'
    ]

    def __init__(self, config):
        super().__init__()
        self.config = config

    @property
    @memoized
    def rows(self):
        return [
            ['', 'Nước luộc,rau', '1', 'Cereals and their products (1)', '', 'non_std_recipe', '1', '1',
             'conversion factor available', '1', 'fct data available'],
            ['9001008060081', 'Cơm,tẻ,nấu', '2', 'Roots, tubers, plantains and their products (2)', '',
             'std_recipe',
             '1', '1', 'conversion factor available', '2', 'using fct data from base term food code'],
            ['5001', 'Ruốc,cá', '3', 'Pulses, seeds and nuts and their products (3) ', '', 'food_item', '1', '1',
             'conversion factor available', '3', 'using fct data from reference food code'],
            ['5017', 'Nước luộc,Khác', '4', 'Milk and milk products (4)', '', 'food_item', '1', '2',
             'using conversion factor from base term food code', '1', 'fct data available'],
            ['', 'Nước luộc,Khác', '5', 'Eggs and their products (5)', '', 'non_std_food_item', '3', '2',
             'using conversion factor from base term food code', '2', 'using fct data from base term food code'],
            ['', 'Bánh mỳ,que,không ngọt', '6', 'Fish, shellfish and their products (6)', '', 'food_item', '1',
             '2',
             'using conversion factor from base term food code', '8', 'no fct data available'],
            ['', 'Bánh mỳ,que,không ngọt', '7', 'Meat and meat products (7)', '', 'food_item', '1', '8',
             'no conversion factor available', '1', 'fct data available'],
            ['', 'Đu đủ chín', '8', 'Insects, grubs and their products (8)', '', 'food_item', '1', '1',
             'conversion factor available', '1', 'fct data available'],
            ['1004002', 'Dưa,cải bẹ', '9', 'Vegetables and their products (9)', '', 'food_item', '1', '1',
             'conversion factor available', '2', 'using fct data from base term food code'],
            ['5040', 'Ổi', '10', 'Fruits and their products (10)', '', 'food_item', '1', '1',
             'conversion factor available', '8', 'no fct data available'],
            ['', 'Khoai sọ,nấu canh', '11', 'Fats and oils (11)', '', 'non_std_food_item', '3', '2',
             'using conversion factor from base term food code', '1', 'fct data available'],
            ['', 'Bánh quy,Khác', '12', 'Sweets and sugars (12)', '', 'non_std_recipe', '1', '2',
             'using conversion factor from base term food code', '7', 'ingredient(s) contain fct data gaps'],
            ['', 'Bánh quy,Khác', '13', 'Spices and condiments (13', '', 'non_std_recipe', '1', '2',
             'using conversion factor from base term food code', '8', 'using fct data from base term food code'],
            ['', 'Bánh mỳ,Khác,không ngọt', '14', 'Beverages (14)', '', 'food_item', '1', '8',
             'no conversion factor available', '1', 'Success'],
            ['', 'Bánh mỳ,Khác,không ngọt', '15', 'Foods for particular nutritional uses (15)', '', 'food_item',
             '1',
             '1', 'conversion factor available', '9', 'not applicable'],
            ['', 'Bưởi', '16', 'Food supplements and similar (16)', '', 'food_item', '1', '1',
             'conversion factor available', '1', 'fct data available'],
            ['', 'Egg,local hen,raw', '18', 'Composite foods (18)', '', 'food_item', '1', '1',
             'conversion factor available', '1', 'fct data available'],
            ['2013002', 'Bánh mỳ,que,không ngọt', '19', 'Savoury snacks (19)', '', 'food_item', '1', '1',
             'conversion factor available', '1', 'fct data available'],
            ['8058', 'QUẢ SUNG MUỐI', '1', 'Cereals and their products (1)', '', 'food_item', '1', '1',
             'conversion factor available', '1', 'fct data available'],
            ['', 'Bánh mỳ,que,không ngọt', '2', 'Roots, tubers, plantains and their products (2)', '', 'food_item',
             '1',
             '1', 'conversion factor available', '9', 'not applicable'],
            ['', 'Bánh quy,Khác', '3', 'Pulses, seeds and nuts and their products (3) ', '', 'food_item', '1', '1',
             'conversion factor available', '1', 'fct data available'],
            ['', 'Bánh quy,Khác', '4', 'Milk and milk products (4)', '', 'food_item', '1', '1',
             'conversion factor available', '8', 'no fct data available'],
            ['13039', 'Bánh mỳ,que,không ngọt', '5', 'Eggs and their products (5)', '', 'food_item', '1', '1',
             'conversion factor available', '9', 'not applicable'],
            ['4116', 'NƯỚC NGHỆ MẬT ONG', '6', 'Fish, shellfish and their products (6)', '', 'food_item', '1', '1',
             'conversion factor available', '2', 'using fct data from base term food code'],
            ['7170', 'Nước luộc,rau', '7', 'Meat and meat products (7)', '', 'food_item', '1', '1',
             'conversion factor available', '1', 'fct data available'],
            ['', 'Ruốc,cá', '2', 'Roots, tubers, plantains and their products (2)', '', '', '', '8',
             'no conversion factor available', '8', 'no fct data available'],
            ['', 'Nước luộc,Khác', '3', 'Pulses, seeds and nuts and their products (3) ', '', '', '', '1',
             'conversion factor available', '1', 'fct data available'],
            ['', 'Nước luộc,Khác', '4', 'Milk and milk products (4)', '', '', '', '1',
             'conversion factor available',
             '1', 'fct data available'],
        ]


class GapsReportByItemDetailsData(GapsReportByItemDataMixin):
    total_row = None
    title = 'Gaps By Item Details'
    slug = 'gaps_by_item_details'
    headers_in_order = [
        'gap_type', 'gap_code', 'gap_desc', 'food_type', 'caseid', 'food_code', 'food_name', 'short_name',
        'time_of_day', 'time_block', 'fao_who_gift_food_group_code', 'fao_who_gift_food_group_desc',
        'user_food_group', 'food_base_term', 'tag_1', 'tag_1_other', 'tag_2', 'tag_2_other', 'tag_3',
        'tag_3_other',
        'tag_4', 'tag_4_other', 'tag_5', 'tag_5_other', 'tag_6', 'tag_6_other', 'tag_7', 'tag_7_other', 'tag_8',
        'tag_8_other', 'tag_9', 'tag_9_other', 'tag_10', 'tag_10_other', 'conv_method_code', 'conv_method_desc',
        'conv_option_code', 'conv_option_desc', 'conv_size', 'conv_units', 'quantity',
        'nsr_conv_method_code_post_cooking', 'nsr_conv_method_desc_post_cooking',
        'nsr_conv_option_code_post_cooking',
        'nsr_conv_option_desc_post_cooking', 'nsr_conv_size_post_cooking', 'nsr_consumed_cooked_fraction',
        'conv_factor_used', 'conv_factor_food_code', 'conv_factor_base_term_food_code', 'fct_data_used',
        'fct_food_code_exists', 'fct_base_term_food_code_exists', 'fct_refernce_food_code_exists',
        'base_term_food_code', 'reference_food_code', 'unique_respondent_id', 'recall_case_id',
        'opened_by_username',
        'owner_name', 'recall_date'
    ]

    def __init__(self, config):
        super().__init__()
        self.config = config

    @property
    @memoized
    def rows(self):
        return [
            ['conversion factor', '1', 'conv factor available', 'food_item',
             '63069d9d-e46d-4566-b788-b794a2c7f67a',
             '7170', 'Nước luộc,rau', 'nước rau cải bắp luộc', '07:46', '6 am - 8:59 am', '1',
             'Cereals and their products (1)', '', 'Nước luộc', 'rau', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '50', 'Proxy weight (g) - water', '', '', '299', 'grams', '1',
             '',
             '', '', '', '', '', 'food_code', '1', '1.0337', 'base_term_food_code', 'no', 'no', 'yes', '712499',
             '712499', '666_1', '36271593-cb0d-4a99-ac35-260db7d4b63e', 'mary', 'mary', '8/14/2019'],
            ['conversion factor', '1', 'conv factor available', 'food_item',
             'ea7ea242-b196-4cfb-8e65-2bfe66b8e199',
             '1004002', 'Cơm,tẻ,nấu', 'cơm', '06:30', '6 am - 8:59 am', '2',
             'Roots, tubers, plantains and their products (2)', '', 'Cơm', 'tẻ', '', 'nấu', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '51', 'Proxy weight (g) - rice', '', '', '172', 'grams', '1',
             '', '',
             '', '', '', '', 'food_code', '0.8588', '0.8588', 'none', 'no', 'no', 'no', '100400299', '100400299',
             '666_1', '36271593-cb0d-4a99-ac35-260db7d4b63e', 'sue', 'sue', '8/14/2019'],
            ['conversion factor', '1', 'conv factor available', 'food_item',
             '126394a1-a907-45fb-9249-663216062664',
             '8058', 'Ruốc,cá', 'ruốc cá', '19:20', '6 pm - 8:59 pm', '3',
             'Pulses, seeds and nuts and their products (3) ', '', 'Ruốc', 'cá', '', 'I DONT KNOW', '',
             'I DONT KNOW',
             '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '51', 'Proxy weight (g) - rice', '', '', '52', 'grams', '1', '',
             '',
             '', '', '', '', 'base_term_food_code', '', '1.1765', 'food_code', 'yes', 'yes', 'no', '805999',
             '805999',
             '555_2', 'f3bfc88d-6cb1-4ae8-acdc-9715a9411b13', 'bob', 'bob', '8/12/2019'],
            ['conversion factor', '2', 'using conversion factor from base term food code', 'food_item',
             '667c59d9-eebf-4073-be45-9c73950415af', '', 'Nước luộc,Khác', 'nước rau luộc', '04:05',
             '3 am - 5:59 am',
             '4', 'Milk and milk products (4)', '', 'Nước luộc', 'Khác', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '50', 'Proxy weight (g) - water', '', '', '200', 'grams', '1',
             '',
             '', '', '', '', '', 'base_term_food_code', '', '1.0337', 'base_term_food_code', 'no', 'no', 'no',
             '712499',
             '712499', '666_1', '36271593-cb0d-4a99-ac35-260db7d4b63e', 'mary', 'mary', '8/14/2019'],
            ['conversion factor', '2', 'using conversion factor from base term food code', 'food_item',
             '667c59d9-eebf-4073-be45-9c73950415af', '', 'Nước luộc,Khác', 'nước rau luộc', '04:05',
             '3 am - 5:59 am',
             '5', 'Eggs and their products (5)', '', 'Nước luộc', 'Khác', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '50', 'Proxy weight (g) - water', '', '', '200', 'grams', '1',
             '',
             '', '', '', '', '', 'base_term_food_code', '', '1.0337', 'base_term_food_code', 'no', 'no', 'no',
             '712499',
             '712499', '666_1', '36271593-cb0d-4a99-ac35-260db7d4b63e', 'sue', 'sue', '8/14/2019'],
            ['conversion factor', '2', 'using conversion factor from base term food code', 'food_item',
             '499f034b-95e3-4d02-909d-af382b1cd46e', '', 'Bánh mỳ,que,không ngọt', 'bánh mì trắng', '09:42',
             '9 am - 11:59 am', '6', 'Fish, shellfish and their products (6)', '', 'Bánh mỳ', 'que', '',
             'không ngọt',
             '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '10', 'Direct weight (g)', '', '', '250',
             'grams',
             '1', '', '', '', '', '', '', 'base_term_food_code', '', '1', 'none', 'no', 'no', 'no', '101299',
             '101299',
             '888_1', 'de16bd5b-51bc-4dac-ba81-50e04ac858e5', 'bob', 'bob', '8/14/2019'],
            ['conversion factor', '8', 'no conversion factor available', 'food_item',
             '499f034b-95e3-4d02-909d-af382b1cd46e', '', 'Bánh mỳ,que,không ngọt', 'bánh mì trắng', '09:42',
             '9 am - 11:59 am', '7', 'Meat and meat products (7)', '', 'Bánh mỳ', 'que', '', 'không ngọt', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '10', 'Direct weight (g)', '', '', '250',
             'grams',
             '1', '', '', '', '', '', '', 'base_term_food_code', '', '1', 'none', 'no', 'no', 'no', '101299',
             '101299',
             '888_1', 'de16bd5b-51bc-4dac-ba81-50e04ac858e5', 'mary', 'mary', '8/14/2019'],
            ['conversion factor', '1', 'conv factor available', 'food_item',
             '1e1d14d3-a801-4249-ab62-c05f2e92e53b',
             '5017', 'Đu đủ chín', 'đu đủ', '19:33', '6 pm - 8:59 pm', '8',
             'Insects, grubs and their products (8)', '',
             'Đu đủ chín', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW',
             '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             '10',
             'Direct weight (g)', '', '', '154', 'grams', '1', '', '', '', '', '', '', 'none', '', '', 'food_code',
             'yes', 'yes', 'no', '5017', '5017', '8003_1', '832b98ad-303f-458d-a400-1f8453b358c6', 'sue', 'sue',
             '8/14/2019'],
            ['conversion factor', '1', 'conv factor available', 'food_item',
             '964416e8-6a98-49d4-86df-cd667bad102a',
             '4116', 'Dưa,cải bẹ', 'dưa muối', '09:19', '9 am - 11:59 am', '9',
             'Vegetables and their products (9)', '',
             'Dưa', 'cải bẹ', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '90',
             'Photo substitutes (g)', '7', 'KC04-07', '1', 'grams', '7', '', '', '', '', '', '', 'food_code',
             '82.08',
             '152', 'base_term_food_code', 'no', 'no', 'no', '411599', '411599', '12345_1',
             'fbcc5cd9-3d8c-43c8-908d-abb1c0b21089', 'bob', 'bob', '8/17/2019'],
            ['conversion factor', '1', 'conv factor available', 'food_item',
             'ac63f5a8-4aec-4551-a843-e7f0b5f10515',
             '5040', 'Ổi', 'ổi', '04:51', '3 am - 5:59 am', '10', 'Fruits and their products (10)', '', 'Ổi',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '40',
             'Photos (g)', '4', 'NC07-03', '1', 'grams', '1', '', '', '', '', '', '', 'food_code', '34.2', '34.2',
             'none', 'no', 'no', 'no', '5040', '5040', '8007_1', '225281cf-ae7e-4d20-9516-0e64c228467e', 'mary',
             'mary',
             '8/17/2019'],
            ['conversion factor', '2', 'using conversion factor from base term food code', 'food_item',
             '9bfdd247-a9a4-48bd-91a1-3ae83c164a32', '2013002', 'Khoai sọ,nấu canh', 'khoai sọ', '04:38',
             '3 am - 5:59 am', '11', 'Fats and oils (11)', '', 'Khoai sọ', 'nấu canh', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '40', 'Photos (g)', '1', 'NC06-01', '1',
             'grams',
             '5', '', '', '', '', '', '', 'base_term_food_code', '', '24.6', 'food_code', 'yes', 'yes', 'no',
             '201399',
             '201399', '8007_1', '225281cf-ae7e-4d20-9516-0e64c228467e', 'sue', 'sue', '8/17/2019'],
            ['conversion factor', '2', 'using conversion factor from base term food code', 'food_item',
             '075922bb-3837-4b56-88d4-f7f61478e891', '', 'Bánh quy,Khác', 'bánh quy', '09:49', '9 am - 11:59 am',
             '12',
             'Sweets and sugars (12)', '', 'Bánh quy', 'Khác', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW',
             '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', '40', 'Photos (g)', '1', 'NC06-01', '1', 'grams', '2', '', '', '', '', '', '',
             'base_term_food_code', '', '5', 'base_term_food_code', 'no', 'no', 'no', '1200199', '1200199',
             '8007_1',
             '225281cf-ae7e-4d20-9516-0e64c228467e', 'bob', 'bob', '8/17/2019'],
            ['conversion factor', '2', 'using conversion factor from base term food code', 'food_item',
             '075922bb-3837-4b56-88d4-f7f61478e891', '', 'Bánh quy,Khác', 'bánh quy', '09:49', '9 am - 11:59 am',
             '13',
             'Spices and condiments (13', '', 'Bánh quy', 'Khác', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '40', 'Photos (g)', '1', 'NC06-01', '1', 'grams', '2', '', '',
             '',
             '', '', '', 'base_term_food_code', '', '5', 'base_term_food_code', 'no', 'no', 'no', '1200199',
             '1200199',
             '8007_1', '225281cf-ae7e-4d20-9516-0e64c228467e', 'mary', 'mary', '8/17/2019'],
            ['conversion factor', '8', 'no conversion factor available', 'food_item',
             '522d98f5-7d58-49dd-96ec-d0ebf6821c06', '', 'Bánh mỳ,Khác,không ngọt', 'bánh mì sandwich', '02:22',
             '12 am - 2:59 am', '14', 'Beverages (14)', '', 'Bánh mỳ', 'Khác', '', 'không ngọt', '', 'I DONT KNOW',
             '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '40', 'Photos (g)', '5', 'NC08-05', '1', 'grams', '2', '', '',
             '',
             '', '', '', 'base_term_food_code', '', '24', 'none', 'no', 'no', 'no', '101299', '101299', '8007_1',
             '225281cf-ae7e-4d20-9516-0e64c228467e', 'sue', 'sue', '8/17/2019'],
            ['conversion factor', '1', 'conv factor available', 'food_item',
             '522d98f5-7d58-49dd-96ec-d0ebf6821c06', '',
             'Bánh mỳ,Khác,không ngọt', 'bánh mì sandwich', '02:22', '12 am - 2:59 am', '15',
             'Foods for particular nutritional uses (15)', '', 'Bánh mỳ', 'Khác', '', 'không ngọt', '',
             'I DONT KNOW',
             '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '40', 'Photos (g)', '5', 'NC08-05', '1', 'grams', '2', '', '',
             '',
             '', '', '', 'base_term_food_code', '', '24', 'none', 'no', 'no', 'no', '101299', '101299', '8007_1',
             '225281cf-ae7e-4d20-9516-0e64c228467e', 'bob', 'bob', '8/17/2019'],
            ['conversion factor', '1', 'conv factor available', 'food_item',
             '7bc8b6bc-cc6d-46a2-b552-ca068c3a31d3',
             '5001', 'Bưởi', 'bưởi', '02:29', '12 am - 2:59 am', '16', 'Food supplements and similar (16)', '',
             'Bưởi',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '40',
             'Photos (g)', '4', 'NC07-03', '1', 'grams', '3', '', '', '', '', '', '', 'none', '', '', 'food_code',
             'yes', 'yes', 'no', '5001', '5001', '444567_1', 'e22a2245-8370-45b5-aea7-f2b8728dbc5e', 'mary',
             'mary',
             '8/17/2019'],
            ['conversion factor', '1', 'conv factor available', 'food_item', '', '', 'Egg,local hen,raw', '',
             '06:34',
             '6 am - 8:59 am', '18', 'Composite foods (18)', '', 'Trứng', 'gà ta', '', 'sống', '', 'I DONT KNOW',
             '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
             '',
             '', '', 'no', '', '9001008060081', '555_1', 'f3bfc88d-6cb1-4ae8-acdc-9715a9411b13', 'bob', 'bob',
             '8/12/2019'],
            ['conversion factor', '1', 'conv factor available', 'food_item',
             '005b9946-abe4-411d-bb8f-5dbe3217523c',
             '13039', '(i) Gia vị,Ớt (tươi)', '(i) ớt', '21:13', '9 pm - 8:59 pm', '19', 'Savoury snacks (19)', '',
             'Gia vị', 'Ớt (tươi)', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '40',
             'Photos (g)', '1', 'NC06-01', '1', 'grams', '1', '', '', '', '', '', '', 'food_code', '1.9998', '',
             'base_term_food_code', 'no', 'no', 'no', '1300199', '', '1234_1',
             '738d5457-3517-4ef0-b21e-65a7ded2e8d1',
             'mary', 'mary', '8/17/2019'],
            ['conversion factor', '1', 'conv factor available', 'non_std_recipe',
             '01e36d8e-df92-41e3-a882-250af3c096d8', '', 'QUẢ SUNG MUỐI', 'quả sung muối', '06:30',
             '6 am - 8:59 am',
             '1', 'Cereals and their products (1)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
             '',
             '', '', '', '', '', '51', 'Proxy weight (g) - rice', '', '', '32', 'grams', '1', '51',
             'Proxy weight (g) - rice', '', '', '110', '0.2909090909', 'none', '', '', 'none', 'no', 'no', 'no',
             '0',
             '1300199', '8007_1', '225281cf-ae7e-4d20-9516-0e64c228467e', 'sue', 'sue', '8/17/2019'],
            ['conversion factor', '1', 'conv factor available', 'non_std_food_item',
             '04b0d499-cbfb-47a0-bb59-299231d6dbc8', '', '(I) QUẢ SUNY,CẢ VỎ', '(i) quả suny', '06:30',
             '6 am - 8:59 am', '2', 'Roots, tubers, plantains and their products (2)', '', '', '', '', '', '', '',
             '',
             '', '', '', '', '', '', '', '', '', '', '', '', '', '', '51', 'Proxy weight (g) - rice', '', '',
             '113',
             'grams', '1', '', '', '', '', '', '', 'none', '', '', 'none', 'no', 'no', 'no', '0', '0', '8007_1',
             '225281cf-ae7e-4d20-9516-0e64c228467e', 'bob', 'bob', '8/17/2019'],
            ['conversion factor', '1', 'conv factor available', 'non_std_food_item',
             '04b0d499-cbfb-47a0-bb59-299231d6dbc8', '', '(I) QUẢ SUNY,CẢ VỎ', '(i) quả suny', '06:30',
             '6 am - 8:59 am', '3', 'Pulses, seeds and nuts and their products (3) ', '', '', '', '', '', '', '',
             '',
             '', '', '', '', '', '', '', '', '', '', '', '', '', '', '51', 'Proxy weight (g) - rice', '', '',
             '113',
             'grams', '1', '', '', '', '', '', '', 'none', '', '', 'none', 'no', 'no', 'no', '0', '0', '8007_1',
             '225281cf-ae7e-4d20-9516-0e64c228467e', 'mary', 'mary', '8/17/2019'],
            ['conversion factor', '1', 'conv factor available', 'food_item',
             '88fe71d9-fbde-4962-b34c-2ff6918285d3', '',
             '(i) Bột,Khác', '(i) bột canh', '06:30', '6 am - 8:59 am', '4', 'Milk and milk products (4)', '',
             'Bột',
             'Khác', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW',
             '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '10', 'Direct weight (g)',
             '',
             '', '10', 'grams', '1', '', '', '', '', '', '', 'base_term_food_code', '', '1', 'base_term_food_code',
             'no', 'no', 'no', '101799', '0', '8007_1', '225281cf-ae7e-4d20-9516-0e64c228467e', 'sue', 'sue',
             '8/17/2019'],
            ['conversion factor', '1', 'conv factor available', 'food_item',
             '88fe71d9-fbde-4962-b34c-2ff6918285d3', '',
             '(i) Bột,Khác', '(i) bột canh', '06:30', '6 am - 8:59 am', '5', 'Eggs and their products (5)', '',
             'Bột',
             'Khác', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW',
             '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '10', 'Direct weight (g)',
             '',
             '', '10', 'grams', '1', '', '', '', '', '', '', 'base_term_food_code', '', '1', 'base_term_food_code',
             'no', 'no', 'no', '101799', '101799', '8007_1', '225281cf-ae7e-4d20-9516-0e64c228467e', 'bob', 'bob',
             '8/17/2019'],
            ['conversion factor', '1', 'conv factor available', 'non_std_recipe',
             '36ce2096-0bda-4c15-a47f-19dc955e76da', '', 'NƯỚC NGHỆ MẬT ONG', 'nước nghệ mật ong', '09:24',
             '9 am - 11:59 am', '6', 'Fish, shellfish and their products (6)', '', '', '', '', '', '', '', '', '',
             '',
             '', '', '', '', '', '', '', '', '', '', '', '', '50', 'Proxy weight (g) - water', '', '', '190',
             'grams',
             '1', '10', 'Direct weight (g)', '', '', '190', '', 'none', '', '', 'none', 'no', 'no', 'no', '0',
             '101799',
             '555_2', 'f3bfc88d-6cb1-4ae8-acdc-9715a9411b13', 'mary', 'mary', '8/12/2019'],
            ['conversion factor', '1', 'conv factor available', 'non_std_recipe',
             '36ce2096-0bda-4c15-a47f-19dc955e76da', '', 'NƯỚC NGHỆ MẬT ONG', 'nước nghệ mật ong', '09:24',
             '9 am - 11:59 am', '7', 'Meat and meat products (7)', '', '', '', '', '', '', '', '', '', '', '', '',
             '',
             '', '', '', '', '', '', '', '', '', '50', 'Proxy weight (g) - water', '', '', '190', 'grams', '1',
             '10',
             'Direct weight (g)', '', '', '190', '', 'none', '', '', 'none', 'no', 'no', 'no', '0', '0', '555_2',
             'f3bfc88d-6cb1-4ae8-acdc-9715a9411b13', 'sue', 'sue', '8/12/2019'],
            ['conversion factor', '8', 'no conversion factor available', 'non_std_food_item',
             '9c440036-eb8b-461a-94d8-1afdbebe4e9c', '', '(I) BỘT NGHỆ,BỘT NGHỆ XAY', '(i) bột nghệ', '09:24',
             '9 am - 11:59 am', '9', 'Vegetables and their products (9)', '', '', '', '', '', '', '', '', '', '',
             '',
             '', '', '', '', '', '', '', '', '', '', '', '10', 'Direct weight (g)', '', '', '6', 'grams', '1', '',
             '',
             '', '', '', '', 'none', '', '', 'none', 'no', 'no', 'no', '0', '0', '555_2',
             'f3bfc88d-6cb1-4ae8-acdc-9715a9411b13', 'mary', 'mary', '8/12/2019'],
            ['conversion factor', '1', 'conv factor available', 'non_std_food_item',
             '2b4bb306-5fb5-48d8-8c76-8f6be6ae8a9a', '', 'NƯỚC ĐẬU,NƯỚC ĐẬU TƯƠI THÊM ĐƯỜNG VÀ ĐÁ', 'nước đậu',
             '06:17',
             '6 am - 8:59 am', '10', 'Fruits and their products (10)', '', '', '', '', '', '', '', '', '', '', '',
             '',
             '', '', '', '', '', '', '', '', '', '', '50', 'Proxy weight (g) - water', '', '', '172', 'grams', '1',
             '',
             '', '', '', '', '', 'none', '', '', 'none', 'no', 'no', 'no', '0', '0', '12345_1',
             'fbcc5cd9-3d8c-43c8-908d-abb1c0b21089', 'sue', 'sue', '8/17/2019'],
            ['conversion factor', '1', 'conv factor available', 'non_std_food_item',
             '2b4bb306-5fb5-48d8-8c76-8f6be6ae8a9a', '', 'NƯỚC ĐẬU,NƯỚC ĐẬU TƯƠI THÊM ĐƯỜNG VÀ ĐÁ', 'nước đậu',
             '06:17',
             '6 am - 8:59 am', '11', 'Fats and oils (11)', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
             '',
             '', '', '', '', '', '', '', '50', 'Proxy weight (g) - water', '', '', '172', 'grams', '1', '', '', '',
             '',
             '', '', 'none', '', '', 'none', 'no', 'no', 'no', '0', '0', '12345_1',
             'fbcc5cd9-3d8c-43c8-908d-abb1c0b21089', 'bob', 'bob', '8/17/2019'],
            ['fct', '1', 'fct data available', 'food_item', '63069d9d-e46d-4566-b788-b794a2c7f67a', '7170',
             'Nước luộc,rau', 'nước rau cải bắp luộc', '07:46', '6 am - 8:59 am', '1',
             'Cereals and their products (1)',
             '', 'Nước luộc', 'rau', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW',
             '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '50',
             'Proxy weight (g) - water', '', '', '299', 'grams', '1', '', '', '', '', '', '', 'food_code', '1',
             '1.0337', 'base_term_food_code', 'no', 'no', 'no', '712499', '0', '666_1',
             '36271593-cb0d-4a99-ac35-260db7d4b63e', 'mary', 'mary', '8/14/2019'],
            ['fct', '2', 'using fct data from base term food code', 'food_item',
             'ea7ea242-b196-4cfb-8e65-2bfe66b8e199',
             '1004002', 'Cơm,tẻ,nấu', 'cơm', '06:30', '6 am - 8:59 am', '2',
             'Roots, tubers, plantains and their products (2)', '', 'Cơm', 'tẻ', '', 'nấu', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '51', 'Proxy weight (g) - rice', '', '', '172', 'grams', '1',
             '', '',
             '', '', '', '', 'food_code', '0.8588', '0.8588', 'none', 'no', 'no', 'no', '100400299', '', '666_1',
             '36271593-cb0d-4a99-ac35-260db7d4b63e', 'sue', 'sue', '8/14/2019'],
            ['fct', '8', 'no fct data available', 'food_item', '126394a1-a907-45fb-9249-663216062664', '8058',
             'Ruốc,cá', 'ruốc cá', '19:20', '6 pm - 8:59 pm', '3',
             'Pulses, seeds and nuts and their products (3) ', '',
             'Ruốc', 'cá', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '51',
             'Proxy weight (g) - rice', '', '', '52', 'grams', '1', '', '', '', '', '', '', 'base_term_food_code',
             '',
             '1.1765', 'food_code', 'yes', 'yes', 'no', '805999', '', '555_2',
             'f3bfc88d-6cb1-4ae8-acdc-9715a9411b13',
             'bob', 'bob', '8/12/2019'],
            ['fct', '1', 'fct data available', 'food_item', '667c59d9-eebf-4073-be45-9c73950415af', '',
             'Nước luộc,Khác', 'nước rau luộc', '04:05', '3 am - 5:59 am', '4', 'Milk and milk products (4)', '',
             'Nước luộc', 'Khác', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '50',
             'Proxy weight (g) - water', '', '', '200', 'grams', '1', '', '', '', '', '', '',
             'base_term_food_code', '',
             '1.0337', 'base_term_food_code', 'no', 'no', 'no', '712499', '', '666_1',
             '36271593-cb0d-4a99-ac35-260db7d4b63e', 'mary', 'mary', '8/14/2019'],
            ['fct', '2', 'using fct data from base term food code', 'food_item',
             '667c59d9-eebf-4073-be45-9c73950415af',
             '', 'Nước luộc,Khác', 'nước rau luộc', '04:05', '3 am - 5:59 am', '5', 'Eggs and their products (5)',
             '',
             'Nước luộc', 'Khác', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '50',
             'Proxy weight (g) - water', '', '', '200', 'grams', '1', '', '', '', '', '', '',
             'base_term_food_code', '',
             '1.0337', 'base_term_food_code', 'no', 'no', 'no', '712499', '', '666_1',
             '36271593-cb0d-4a99-ac35-260db7d4b63e', 'sue', 'sue', '8/14/2019'],
            ['fct', '8', 'no fct data available', 'food_item', '499f034b-95e3-4d02-909d-af382b1cd46e', '',
             'Bánh mỳ,que,không ngọt', 'bánh mì trắng', '09:42', '9 am - 11:59 am', '6',
             'Fish, shellfish and their products (6)', '', 'Bánh mỳ', 'que', '', 'không ngọt', '', 'I DONT KNOW',
             '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '10', 'Direct weight (g)', '', '', '250', 'grams', '1', '', '',
             '',
             '', '', '', 'base_term_food_code', '', '1', 'none', 'no', 'no', 'no', '101299', '', '888_1',
             'de16bd5b-51bc-4dac-ba81-50e04ac858e5', 'bob', 'bob', '8/14/2019'],
            ['fct', '1', 'fct data available', 'food_item', '499f034b-95e3-4d02-909d-af382b1cd46e', '',
             'Bánh mỳ,que,không ngọt', 'bánh mì trắng', '09:42', '9 am - 11:59 am', '7',
             'Meat and meat products (7)',
             '', 'Bánh mỳ', 'que', '', 'không ngọt', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '10',
             'Direct weight (g)', '', '', '250', 'grams', '1', '', '', '', '', '', '', 'base_term_food_code', '',
             '1',
             'none', 'no', 'no', 'no', '101299', '', '888_1', 'de16bd5b-51bc-4dac-ba81-50e04ac858e5', 'mary',
             'mary',
             '8/14/2019'],
            ['fct', '1', 'fct data available', 'food_item', '1e1d14d3-a801-4249-ab62-c05f2e92e53b', '5017',
             'Đu đủ chín', 'đu đủ', '19:33', '6 pm - 8:59 pm', '8', 'Insects, grubs and their products (8)', '',
             'Đu đủ chín', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW',
             '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             '10',
             'Direct weight (g)', '', '', '154', 'grams', '1', '', '', '', '', '', '', 'none', '', '', 'food_code',
             'yes', 'yes', 'no', '5017', '', '8003_1', '832b98ad-303f-458d-a400-1f8453b358c6', 'sue', 'sue',
             '8/14/2019'],
            ['fct', '2', 'using fct data from base term food code', 'food_item',
             '964416e8-6a98-49d4-86df-cd667bad102a',
             '4116', 'Dưa,cải bẹ', 'dưa muối', '09:19', '9 am - 11:59 am', '9',
             'Vegetables and their products (9)', '',
             'Dưa', 'cải bẹ', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '90',
             'Photo substitutes (g)', '7', 'KC04-07', '1', 'grams', '7', '', '', '', '', '', '', 'food_code',
             '82.08',
             '152', 'base_term_food_code', 'no', 'no', 'no', '411599', '', '12345_1',
             'fbcc5cd9-3d8c-43c8-908d-abb1c0b21089', 'bob', 'bob', '8/17/2019'],
            ['fct', '8', 'no fct data available', 'food_item', 'ac63f5a8-4aec-4551-a843-e7f0b5f10515', '5040',
             'Ổi',
             'ổi', '04:51', '3 am - 5:59 am', '10', 'Fruits and their products (10)', '', 'Ổi', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '40', 'Photos (g)', '4',
             'NC07-03', '1', 'grams', '1', '', '', '', '', '', '', 'food_code', '34.2', '34.2', 'none', 'no', 'no',
             'no', '5040', '', '8007_1', '225281cf-ae7e-4d20-9516-0e64c228467e', 'mary', 'mary', '8/17/2019'],
            ['fct', '1', 'fct data available', 'food_item', '9bfdd247-a9a4-48bd-91a1-3ae83c164a32', '2013002',
             'Khoai sọ,nấu canh', 'khoai sọ', '04:38', '3 am - 5:59 am', '11', 'Fats and oils (11)', '',
             'Khoai sọ',
             'nấu canh', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW',
             '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '40', 'Photos (g)',
             '1',
             'NC06-01', '1', 'grams', '5', '', '', '', '', '', '', 'base_term_food_code', '', '24.6', 'food_code',
             'yes', 'yes', 'no', '201399', '', '8007_1', '225281cf-ae7e-4d20-9516-0e64c228467e', 'sue', 'sue',
             '8/17/2019'],
            ['fct', '2', 'using fct data from base term food code', 'food_item',
             '075922bb-3837-4b56-88d4-f7f61478e891',
             '', 'Bánh quy,Khác', 'bánh quy', '09:49', '9 am - 11:59 am', '12', 'Sweets and sugars (12)', '',
             'Bánh quy', 'Khác', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '40',
             'Photos (g)', '1', 'NC06-01', '1', 'grams', '2', '', '', '', '', '', '', 'base_term_food_code', '',
             '5',
             'base_term_food_code', 'no', 'no', 'no', '1200199', '', '8007_1',
             '225281cf-ae7e-4d20-9516-0e64c228467e',
             'bob', 'bob', '8/17/2019'],
            ['fct', '8', 'no fct data available', 'food_item', '075922bb-3837-4b56-88d4-f7f61478e891', '',
             'Bánh quy,Khác', 'bánh quy', '09:49', '9 am - 11:59 am', '13', 'Spices and condiments (13', '',
             'Bánh quy',
             'Khác', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW',
             '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '40', 'Photos (g)', '1',
             'NC06-01', '1', 'grams', '2', '', '', '', '', '', '', 'base_term_food_code', '', '5',
             'base_term_food_code', 'no', 'no', 'no', '1200199', '', '8007_1',
             '225281cf-ae7e-4d20-9516-0e64c228467e',
             'mary', 'mary', '8/17/2019'],
            ['fct', '1', 'fct data available', 'food_item', '522d98f5-7d58-49dd-96ec-d0ebf6821c06', '',
             'Bánh mỳ,Khác,không ngọt', 'bánh mì sandwich', '02:22', '12 am - 2:59 am', '14', 'Beverages (14)', '',
             'Bánh mỳ', 'Khác', '', 'không ngọt', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '40',
             'Photos (g)', '5', 'NC08-05', '1', 'grams', '2', '', '', '', '', '', '', 'base_term_food_code', '',
             '24',
             'none', 'no', 'no', 'no', '101299', '', '8007_1', '225281cf-ae7e-4d20-9516-0e64c228467e', 'sue',
             'sue',
             '8/17/2019'],
            ['fct', '3', 'using fct data from reference food code', 'food_item',
             '522d98f5-7d58-49dd-96ec-d0ebf6821c06',
             '', 'Bánh mỳ,Khác,không ngọt', 'bánh mì sandwich', '02:22', '12 am - 2:59 am', '15',
             'Foods for particular nutritional uses (15)', '', 'Bánh mỳ', 'Khác', '', 'không ngọt', '',
             'I DONT KNOW',
             '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '40', 'Photos (g)', '5', 'NC08-05', '1', 'grams', '2', '', '',
             '',
             '', '', '', 'base_term_food_code', '', '24', 'none', 'no', 'no', 'no', '101299', '', '8007_1',
             '225281cf-ae7e-4d20-9516-0e64c228467e', 'bob', 'bob', '8/17/2019'],
            ['fct', '1', 'fct data available', 'food_item', '7bc8b6bc-cc6d-46a2-b552-ca068c3a31d3', '5001', 'Bưởi',
             'bưởi', '02:29', '12 am - 2:59 am', '16', 'Food supplements and similar (16)', '', 'Bưởi',
             'I DONT KNOW',
             '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '40', 'Photos (g)', '4',
             'NC07-03', '1', 'grams', '3', '', '', '', '', '', '', 'none', '', '', 'food_code', 'yes', 'yes', 'no',
             '5001', '', '444567_1', 'e22a2245-8370-45b5-aea7-f2b8728dbc5e', 'mary', 'mary', '8/17/2019'],
            ['fct', '7', 'ingredient(s) contain fct data gaps', 'std_recipe',
             '0b77fb58-f265-4897-b817-3a077d81dc3f',
             '9001008060081', 'Trứng gà ta ốp la', 'trứng ốp la', '06:34', '6 am - 8:59 am', '17',
             'Food additives (17)', '', 'I DONT KNOW', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', '10', 'Direct weight (g)', '', '', '68', 'grams', '1', '', '',
             '',
             '', '', '', 'food_code', '1', '1', 'none', 'no', 'no', 'no', '9001008060081', '', '555_1',
             'f3bfc88d-6cb1-4ae8-acdc-9715a9411b13', 'sue', 'sue', '8/12/2019'],
            ['fct', '1', 'fct data available', 'food_item', '', '', 'Egg,local hen,raw', '', '06:34',
             '6 am - 8:59 am',
             '18', 'Composite foods (18)', '', 'Trứng', 'gà ta', '', 'sống', '', 'I DONT KNOW', '', 'I DONT KNOW',
             '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'no',
             '',
             '', '555_1', 'f3bfc88d-6cb1-4ae8-acdc-9715a9411b13', 'bob', 'bob', '8/12/2019'],
            ['fct', '1', 'fct data available', 'food_item', '005b9946-abe4-411d-bb8f-5dbe3217523c', '13039',
             '(i) Gia vị,Ớt (tươi)', '(i) ớt', '21:13', '9 pm - 8:59 pm', '19', 'Savoury snacks (19)', '',
             'Gia vị',
             'Ớt (tươi)', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW',
             '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '40', 'Photos (g)',
             '1',
             'NC06-01', '1', 'grams', '1', '', '', '', '', '', '', 'food_code', '1.9998', '',
             'base_term_food_code',
             'no', 'no', 'no', '1300199', '', '1234_1', '738d5457-3517-4ef0-b21e-65a7ded2e8d1', 'mary', 'mary',
             '8/17/2019'],
            ['fct', '1', 'fct data available', 'non_std_recipe', '01e36d8e-df92-41e3-a882-250af3c096d8', '',
             'QUẢ SUNG MUỐI', 'quả sung muối', '06:30', '6 am - 8:59 am', '1', 'Cereals and their products (1)',
             '', '',
             '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '51',
             'Proxy weight (g) - rice', '', '', '32', 'grams', '1', '51', 'Proxy weight (g) - rice', '', '', '110',
             '0.2909090909', 'none', '', '', 'none', 'no', 'no', 'no', '0', '', '8007_1',
             '225281cf-ae7e-4d20-9516-0e64c228467e', 'sue', 'sue', '8/17/2019'],
            ['fct', '1', 'fct data available', 'non_std_food_item', '04b0d499-cbfb-47a0-bb59-299231d6dbc8', '',
             '(I) QUẢ SUNY,CẢ VỎ', '(i) quả suny', '06:30', '6 am - 8:59 am', '3',
             'Pulses, seeds and nuts and their products (3) ', '', '', '', '', '', '', '', '', '', '', '', '', '',
             '',
             '', '', '', '', '', '', '', '', '51', 'Proxy weight (g) - rice', '', '', '113', 'grams', '1', '', '',
             '',
             '', '', '', 'none', '', '', 'none', 'no', 'no', 'no', '0', '', '8007_1',
             '225281cf-ae7e-4d20-9516-0e64c228467e', 'mary', 'mary', '8/17/2019'],
            ['fct', '8', 'using fct data from base term food code', 'food_item',
             '88fe71d9-fbde-4962-b34c-2ff6918285d3',
             '', '(i) Bột,Khác', '(i) bột canh', '06:30', '6 am - 8:59 am', '4', 'Milk and milk products (4)', '',
             'Bột', 'Khác', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '',
             'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', 'I DONT KNOW', '', '10',
             'Direct weight (g)', '', '', '10', 'grams', '1', '', '', '', '', '', '', 'base_term_food_code', '',
             '1',
             'base_term_food_code', 'no', 'no', 'no', '101799', '', '8007_1',
             '225281cf-ae7e-4d20-9516-0e64c228467e',
             'sue', 'sue', '8/17/2019'],
            ['fct', '2', 'using fct data from base term food code', 'non_std_recipe',
             '36ce2096-0bda-4c15-a47f-19dc955e76da', '', 'NƯỚC NGHỆ MẬT ONG', 'nước nghệ mật ong', '09:24',
             '9 am - 11:59 am', '6', 'Fish, shellfish and their products (6)', '', '', '', '', '', '', '', '', '',
             '',
             '', '', '', '', '', '', '', '', '', '', '', '', '50', 'Proxy weight (g) - water', '', '', '190',
             'grams',
             '1', '10', 'Direct weight (g)', '', '', '190', '', 'none', '', '', 'none', 'no', 'no', 'no', '0', '',
             '555_2', 'f3bfc88d-6cb1-4ae8-acdc-9715a9411b13', 'mary', 'mary', '8/12/2019'],
            ['fct', '1', 'fct data available', 'non_std_recipe', '36ce2096-0bda-4c15-a47f-19dc955e76da', '',
             'NƯỚC NGHỆ MẬT ONG', 'nước nghệ mật ong', '09:24', '9 am - 11:59 am', '7',
             'Meat and meat products (7)',
             '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '50',
             'Proxy weight (g) - water', '', '', '190', 'grams', '1', '10', 'Direct weight (g)', '', '', '190', '',
             'none', '', '', 'none', 'no', 'no', 'no', '0', '', '555_2', 'f3bfc88d-6cb1-4ae8-acdc-9715a9411b13',
             'sue',
             'sue', '8/12/2019'],
            ['fct', '8', 'using fct data from base term food code', 'non_std_food_item',
             '9c440036-eb8b-461a-94d8-1afdbebe4e9c', '', '(I) BỘT NGHỆ,BỘT NGHỆ XAY', '(i) bột nghệ', '09:24',
             '9 am - 11:59 am', '9', 'Vegetables and their products (9)', '', '', '', '', '', '', '', '', '', '',
             '',
             '', '', '', '', '', '', '', '', '', '', '', '10', 'Direct weight (g)', '', '', '6', 'grams', '1', '',
             '',
             '', '', '', '', 'none', '', '', 'none', 'no', 'no', 'no', '0', '', '555_2',
             'f3bfc88d-6cb1-4ae8-acdc-9715a9411b13', 'mary', 'mary', '8/12/2019'],
            ['fct', '1', 'fct data available', 'non_std_food_item', '2b4bb306-5fb5-48d8-8c76-8f6be6ae8a9a', '',
             'NƯỚC ĐẬU,NƯỚC ĐẬU TƯƠI THÊM ĐƯỜNG VÀ ĐÁ', 'nước đậu', '06:17', '6 am - 8:59 am', '10',
             'Fruits and their products (10)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
             '',
             '', '', '', '', '50', 'Proxy weight (g) - water', '', '', '172', 'grams', '1', '', '', '', '', '', '',
             'none', '', '', 'none', 'no', 'no', 'no', '0', '', '12345_1', 'fbcc5cd9-3d8c-43c8-908d-abb1c0b21089',
             'sue', 'sue', '8/17/2019'],
            ['fct', '1', 'fct data available', 'non_std_food_item', '2b4bb306-5fb5-48d8-8c76-8f6be6ae8a9a', '',
             'NƯỚC ĐẬU,NƯỚC ĐẬU TƯƠI THÊM ĐƯỜNG VÀ ĐÁ', 'nước đậu', '06:17', '6 am - 8:59 am', '11',
             'Fats and oils (11)', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
             '',
             '', '50', 'Proxy weight (g) - water', '', '', '172', 'grams', '1', '', '', '', '', '', '', 'none', '',
             '',
             'none', 'no', 'no', 'no', '0', '', '12345_1', 'fbcc5cd9-3d8c-43c8-908d-abb1c0b21089', 'bob', 'bob',
             '8/17/2019'],
        ]
