# Generated by Django 2.2.20 on 2021-05-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhis2', '0010_populate_sqldatasetmap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dhis2Connection',
        ),
    ]
