from corehq.fluff.calculators.xform import FormPropertyFilter
from couchforms.models import XFormInstance
import fluff
from custom.tdh import TDH_DOMAINS, ENROLL_CHILD_XMLNSES, INFANT_CLASSIFICATION_XMLNSES, INFANT_TREATMENT_XMLNSES
from custom.utils.utils import flat_field

class TDHNullEmitter(fluff.Calculator):
    @fluff.null_emitter
    def numerator(self, case):
        yield None

class TDHDateEmiiter(fluff.Calculator):
    @fluff.date_emitter
    def total(self, form):
        yield {
            'date': form.received_on,
            'value': 0
        }

class TDHEnrollChildFluff(fluff.IndicatorDocument):
    document_class = XFormInstance
    document_filter = FormPropertyFilter(xmlns=ENROLL_CHILD_XMLNSES[0])
    domains = TDH_DOMAINS
    save_direct_to_sql = True

    case_id= flat_field(lambda f: f.form['case_rec_child']['case']['@case_id'])
    name = flat_field(lambda f: f.form.get('demographics', {}).get('name', ''))
    sex = flat_field(lambda f: f.form.get('demographics', {}).get('sex', ''))
    mother_name = flat_field(lambda f: f.form.get('demographics', {}).get('mother_name', ''))
    village = flat_field(lambda f: f.form.get('demographics', {}).get('village', ''))
    last_visit_date = flat_field(lambda f: f.form['case_rec_child']['case']['update'].get('last_visit_date', ''))
    dob = flat_field(lambda f: f.form.get('age_questions', {}).get('dob', ''))
    dob_known = flat_field(lambda f: f.form.get('age_questions', {}).get('dob_known', ''))
    age_in_years = flat_field(lambda f: f.form.get('age_in_years', ''))

    numerator = TDHNullEmitter()


class TDHInfantClassificationFluff(fluff.IndicatorDocument):
    document_class = XFormInstance
    document_filter = FormPropertyFilter(xmlns=INFANT_CLASSIFICATION_XMLNSES[0])
    domains = TDH_DOMAINS
    save_direct_to_sql = True

    case_id = flat_field(lambda f: f.form['case']['@case_id'])
    user_id = flat_field(lambda f: f.form['case']['@user_id'])
    username = flat_field(lambda f: f.form['meta']['username'])
    L_hfa = flat_field(lambda f: f.form.get('L_hfa', ''))
    L_wfa = flat_field(lambda f: f.form.get('L_wfa', ''))
    L_wfh = flat_field(lambda f: f.form.get('L_wfh', ''))
    M_hfa = flat_field(lambda f: f.form.get('M_hfa', ''))
    M_wfa = flat_field(lambda f: f.form.get('M_wfa', ''))
    M_wfh = flat_field(lambda f: f.form.get('M_wfh', ''))
    S_hfa = flat_field(lambda f: f.form.get('S_hfa', ''))
    S_wfa = flat_field(lambda f: f.form.get('S_wfa', ''))
    S_wfh = flat_field(lambda f: f.form.get('S_wfh', ''))
    age_in_months = flat_field(lambda f: f.form.get('age_in_months', ''))
    bad_height = flat_field(lambda f: f.form.get('bad_height', ''))
    dob = flat_field(lambda f: f.form.get('dob', ''))
    au_moins_deux_signes_vih = flat_field(lambda f: f.form.get('au_moins_deux_signes_vih', ''))
    incapable_nourir = flat_field(lambda f: f.form.get('incapable_nourir', ''))
    infection_bac_grave = flat_field(lambda f: f.form.get('infection_bac_grave', ''))
    infection_bac_locale = flat_field(lambda f: f.form.get('infection_bac_locale', ''))
    mean_hfa = flat_field(lambda f: f.form.get('mean_hfa', ''))
    mean_wfa = flat_field(lambda f: f.form.get('mean_wfa', ''))
    mean_wfh = flat_field(lambda f: f.form.get('mean_wfh', ''))

    alimentation_low = flat_field(lambda f: f.form.get('alimentation', {}).get('alimentation_low', ''))
    alimentation_medium = flat_field(lambda f: f.form.get('alimentation', {}).get('alimentation_medium', ''))
    alimentation_qa = flat_field(lambda f: f.form.get('alimentation', {}).get('alimentation_qa', ''))
    alimentation_qb = flat_field(lambda f: f.form.get('alimentation', {}).get('alimentation_qb', ''))
    alimentation_qc = flat_field(lambda f: f.form.get('alimentation', {}).get('alimentation_qc', ''))
    alimentation_qd = flat_field(lambda f: f.form.get('alimentation', {}).get('alimentation_qd', ''))
    alimentation_qe = flat_field(lambda f: f.form.get('alimentation', {}).get('alimentation_qe', ''))
    alimentation_qf = flat_field(lambda f: f.form.get('alimentation', {}).get('alimentation_qf', ''))
    alimentation_qg = flat_field(lambda f: f.form.get('alimentation', {}).get('alimentation_qg', ''))
    alimentation_qh = flat_field(lambda f: f.form.get('alimentation', {}).get('alimentation_qh', ''))

    centile_hfa = flat_field(lambda f: f.form.get('centile_hfa', ''))
    centile_wfa = flat_field(lambda f: f.form.get('centile_wfa', ''))
    centile_wfh = flat_field(lambda f: f.form.get('centile_wfh', ''))
    classification_deshydratation = flat_field(lambda f: f.form.get('classification_deshydratation', ''))
    classification_diahree = flat_field(lambda f: f.form.get('classification_diahree', ''))
    classification_infection = flat_field(lambda f: f.form.get('classification_infection', ''))
    classification_malnutrition = flat_field(lambda f: f.form.get('classification_malnutrition', ''))
    classification_vih = flat_field(lambda f: f.form.get('classification_vih', ''))

    diarrhee_non = flat_field(lambda f: f.form.get('diarrhee', {}).get('diarrhee_non', ''))
    diarrhee_qa = flat_field(lambda f: f.form.get('diarrhee', {}).get('diarrhee_qa', ''))

    inf_bac_freq_resp = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_freq_resp', ''))
    inf_bac_grave = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_grave', ''))
    inf_bac_non = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_non', ''))
    inf_bac_qa = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_qa', ''))
    inf_bac_qc = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_qc', ''))
    inf_bac_qd = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_qd', ''))
    inf_bac_qe = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_qe', ''))
    inf_bac_qf = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_qf', ''))
    inf_bac_qg = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_qg', ''))
    inf_bac_qh = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_qh', ''))
    inf_bac_qi = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_qi', ''))
    inf_bac_qj = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_qj', ''))
    inf_bac_qk = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_qk', ''))
    inf_bac_ql = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_ql', ''))
    inf_bac_qm = flat_field(lambda f: f.form.get('inf_bac', {}).get('inf_bac_qm', ''))

    muac_change = flat_field(lambda f: f.form.get('muac_change', ''))
    muac_change_status = flat_field(lambda f: f.form.get('muac_change_status', ''))
    muac_grading = flat_field(lambda f: f.form.get('muac_grading', ''))
    pas_signes_vih = flat_field(lambda f: f.form.get('pas_signes_vih', ''))

    sd2neg_hfa = flat_field(lambda f: f.form.get('sd2neg_hfa', ''))
    sd2neg_wfa = flat_field(lambda f: f.form.get('sd2neg_wfa', ''))
    sd2neg_wfh = flat_field(lambda f: f.form.get('sd2neg_wfh', ''))
    sd2pos_hfa = flat_field(lambda f: f.form.get('sd2pos_hfa', ''))
    sd2pos_wfa = flat_field(lambda f: f.form.get('sd2pos_wfa', ''))
    sd2pos_wfh = flat_field(lambda f: f.form.get('sd2pos_wfh', ''))
    sd3neg_hfa = flat_field(lambda f: f.form.get('sd3neg_hfa', ''))
    sd3neg_wfa = flat_field(lambda f: f.form.get('sd3neg_wfa', ''))
    sd3neg_wfh = flat_field(lambda f: f.form.get('sd3neg_wfh', ''))
    sd3pos_hfa = flat_field(lambda f: f.form.get('sd3pos_hfa', ''))
    sd3pos_wfa = flat_field(lambda f: f.form.get('sd3pos_wfa', ''))
    sd3pos_wfh = flat_field(lambda f: f.form.get('sd3pos_wfh', ''))

    selected_user_id_and_name = flat_field(lambda f: f.form.get('selected_user_id_and_name', ''))

    seriousness_alimentation = flat_field(lambda f: f.form.get('seriousness_alimentation', ''))
    seriousness_diarrhee = flat_field(lambda f: f.form.get('seriousness_diarrhee', ''))
    seriousness_inf_bac = flat_field(lambda f: f.form.get('seriousness_inf_bac', ''))
    seriousness_vih = flat_field(lambda f: f.form.get('seriousness_vih', ''))
    sex = flat_field(lambda f: f.form.get('sex', ''))
    sex_loaded = flat_field(lambda f: f.form.get('sex_loaded', ''))
    signes_deshy_evident = flat_field(lambda f: f.form.get('signes_deshy_evident', ''))
    signes_deshy_severe = flat_field(lambda f: f.form.get('signes_deshy_severe', ''))
    signes_pb_alim = flat_field(lambda f: f.form.get('signes_pb_alim', ''))
    update_vaccines = flat_field(lambda f: f.form.get('update_vaccines', ''))

    bcg = flat_field(lambda f: f.form.get('vaccines', {}).get('bcg', ''))
    vih_non = flat_field(lambda f: f.form.get('vih', {}).get('vih_non', ''))
    vih_qa = flat_field(lambda f: f.form.get('vih', {}).get('vih_qa', ''))
    vih_qb = flat_field(lambda f: f.form.get('vih', {}).get('vih_qb', ''))
    vih_qc = flat_field(lambda f: f.form.get('vih', {}).get('vih_qc', ''))
    vih_qd = flat_field(lambda f: f.form.get('vih', {}).get('vih_qd', ''))
    vih_qe = flat_field(lambda f: f.form.get('vih', {}).get('vih_qe', ''))
    vih_qf = flat_field(lambda f: f.form.get('vih', {}).get('vih_qf', ''))
    vih_qg = flat_field(lambda f: f.form.get('vih', {}).get('vih_qg', ''))
    vih_qh = flat_field(lambda f: f.form.get('vih', {}).get('vih_qh', ''))
    vih_qi = flat_field(lambda f: f.form.get('vih', {}).get('vih_qi', ''))
    vih_qj = flat_field(lambda f: f.form.get('vih', {}).get('vih_qj', ''))
    vih_qk = flat_field(lambda f: f.form.get('vih', {}).get('vih_qk', ''))
    vih_ql = flat_field(lambda f: f.form.get('vih', {}).get('vih_ql', ''))
    vih_symp_possible = flat_field(lambda f: f.form.get('vih', {}).get('vih_symp_possible', ''))

    visit_date = flat_field(lambda f: f.form.get('visit_date', ''))
    visit_type = flat_field(lambda f: f.form.get('visit_type', ''))

    height = flat_field(lambda f: f.form.get('vitals', {}).get('height', ''))
    muac = flat_field(lambda f: f.form.get('vitals', {}).get('muac', ''))
    temp = flat_field(lambda f: f.form.get('vitals', {}).get('temp', ''))
    weight = flat_field(lambda f: f.form.get('vitals', {}).get('weight', ''))

    zscore_grading_hfa = flat_field(lambda f: f.form.get('zscore_grading_hfa', ''))
    zscore_grading_wfa = flat_field(lambda f: f.form.get('zscore_grading_wfa', ''))
    zscore_grading_wfh = flat_field(lambda f: f.form.get('zscore_grading_wfh', ''))
    zscore_hfa = flat_field(lambda f: f.form.get('zscore_hfa', ''))
    zscore_hfa_change = flat_field(lambda f: f.form.get('zscore_hfa_change', ''))
    zscore_hfa_change_status = flat_field(lambda f: f.form.get('zscore_hfa_change_status', ''))
    zscore_wfa = flat_field(lambda f: f.form.get('zscore_wfa', ''))
    zscore_wfa_change = flat_field(lambda f: f.form.get('zscore_wfa_change', ''))
    zscore_wfa_change_status = flat_field(lambda f: f.form.get('zscore_wfa_change_status', ''))
    zscore_wfh = flat_field(lambda f: f.form.get('zscore_wfh', ''))
    zscore_wfh_change = flat_field(lambda f: f.form.get('zscore_wfh_change', ''))
    zscore_wfh_change_status = flat_field(lambda f: f.form.get('zscore_wfh_change_status', ''))

    last_height = flat_field(lambda f: f.form['case']['update'].get('last_height', ''))
    last_weight = flat_field(lambda f: f.form['case']['update'].get('last_weight', ''))

    numerator = TDHDateEmiiter()


class TDHInfantTreatmentFluff(fluff.IndicatorDocument):
    document_class = XFormInstance
    document_filter = FormPropertyFilter(xmlns=INFANT_TREATMENT_XMLNSES[0])
    domains = TDH_DOMAINS
    save_direct_to_sql = True

    case_id = flat_field(lambda f: f.form['child_case_id'])
    antibio_valid_meds = flat_field(lambda f: f.form.get('antibio_valid_meds', ''))
    child_age = flat_field(lambda f: f.form.get('child_age', ''))
    child_age_loaded = flat_field(lambda f: f.form.get('child_age_loaded', ''))
    child_weight = flat_field(lambda f: f.form.get('child_weight', ''))
    child_weight_loaded = flat_field(lambda f: f.form.get('child_weight_loaded', ''))
    classification_deshydratation = flat_field(lambda f: f.form.get('classification_deshydratation', ''))
    classification_deshydratation_loaded = flat_field(lambda f: f.form.get('classification_deshydratation_loaded', ''))
    classification_diahree = flat_field(lambda f: f.form.get('classification_diahree', ''))
    classification_diahree_loaded = flat_field(lambda f: f.form.get('classification_diahree_loaded', ''))
    classification_infection = flat_field(lambda f: f.form.get('classification_infection', ''))
    classification_infection_loaded = flat_field(lambda f: f.form.get('classification_infection_loaded', ''))
    classification_malnutrition = flat_field(lambda f: f.form.get('classification_malnutrition'))
    classification_malnutrition_loaded = flat_field(lambda f: f.form.get('classification_malnutrition_loaded', ''))
    classification_vih = flat_field(lambda f: f.form.get('classification_vih', ''))
    classification_vih_loaded = flat_field(lambda f: f.form.get('classification_vih_loaded', ''))
    other_treatments = flat_field(lambda f: f.form.get('other_treatments', ''))

    antibio = flat_field(lambda f: f.form.get('select_meds', {}).get('antibio', '') if f.form.get('select_meds', {}) else '')
    deshydratation_severe = flat_field(lambda f: f.form.get('select_treatments', {}).get('deshydratation_severe', '') if f.form.get('select_treatments', {}) else '')
    infection_grave = flat_field(lambda f: f.form.get('select_treatments', {}).get('infection_grave', '') if f.form.get('select_treatments', {}) else '')
    signe_deshydratation = flat_field(lambda f: f.form.get('select_treatments', {}).get('signe_deshydratation', '') if f.form.get('select_treatments', {}) else '')

    deshydratation_severe_sans_infection_title = flat_field(lambda f: f.form.get('treatments', {}).get('deshydratation_severe_sans_infection', {})
                                                            .get('deshydratation_severe_sans_infection_title', '') if f.form.get('treatments', {}).get('deshydratation_severe_sans_infection', {}) else '')
    deshydratation_severe_sans_infection_treat_0 = flat_field(lambda f: f.form.get('treatments', {}).get('deshydratation_severe_sans_infection', {})
                                                            .get('deshydratation_severe_sans_infection_treat_0', '') if f.form.get('treatments', {}).get('deshydratation_severe_sans_infection', {}) else '')

    incapable_nourrir_title = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                         .get('incapable_nourrir_title', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_0 = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                           .get('incapable_nourrir_treat_0', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_1 = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                           .get('incapable_nourrir_treat_1', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_2 = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                           .get('incapable_nourrir_treat_2', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_2_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                                  .get('incapable_nourrir_treat_2_help_0', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_2_help_0_prompt = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                                         .get('incapable_nourrir_treat_2_help_0_prompt', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_2_help_1 = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                                  .get('incapable_nourrir_treat_2_help_1', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_2_help_1_prompt = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                                         .get('incapable_nourrir_treat_2_help_1_prompt', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_2_help_2 = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                                  .get('incapable_nourrir_treat_2_help_2', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_2_help_2_prompt = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                                         .get('incapable_nourrir_treat_2_help_2_prompt', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_3 = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                           .get('incapable_nourrir_treat_3', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_3_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                                  .get('incapable_nourrir_treat_3_help_0', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_3_help_0_prompt = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                                         .get('incapable_nourrir_treat_3_help_0_prompt', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')
    incapable_nourrir_treat_4 = flat_field(lambda f: f.form.get('treatments', {}).get('incapable_nourrir', {})
                                           .get('incapable_nourrir_treat_4', '') if f.form.get('treatments', {}).get('incapable_nourrir', {}) else '')

    infection_grave_title = flat_field(lambda f: f.form.get('treatments', {}).get('infection_grave', {})
                                       .get('infection_grave_title', '') if f.form.get('treatments', {}).get('infection_grave', {}) else '')
    infection_grave_treat_0 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_grave', {})
                                         .get('infection_grave_treat_0', '') if f.form.get('treatments', {}).get('infection_grave', {}) else '')
    infection_grave_treat_1 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_grave', {})
                                         .get('infection_grave_treat_1', '') if f.form.get('treatments', {}).get('infection_grave', {}) else '')
    infection_grave_treat_2 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_grave', {})
                                         .get('infection_grave_treat_2', '') if f.form.get('treatments', {}).get('infection_grave', {}) else '')
    infection_grave_treat_3 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_grave', {})
                                         .get('infection_grave_treat_3', '') if f.form.get('treatments', {}).get('infection_grave', {}) else '')
    infection_grave_treat_3_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_grave', {})
                                                .get('infection_grave_treat_3_help_0', '') if f.form.get('treatments', {}).get('infection_grave', {}) else '')
    infection_grave_treat_4 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_grave', {})
                                         .get('infection_grave_treat_4', '') if f.form.get('treatments', {}).get('infection_grave', {}) else '')
    infection_grave_treat_4_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_grave', {})
                                                .get('infection_grave_treat_4_help_0', '') if f.form.get('treatments', {}).get('infection_grave', {}) else '')
    infection_grave_treat_5 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_grave', {})
                                         .get('infection_grave_treat_5', '') if f.form.get('treatments', {}).get('infection_grave', {}) else '')
    infection_grave_treat_5_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_grave', {})
                                                .get('infection_grave_treat_5_help_0', '') if f.form.get('treatments', {}).get('infection_grave', {}) else '')
    infection_grave_treat_6 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_grave', {})
                                         .get('infection_grave_treat_6', '') if f.form.get('treatments', {}).get('infection_grave', {}) else '')
    infection_grave_treat_7 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_grave', {})
                                         .get('infection_grave_treat_7', '') if f.form.get('treatments', {}).get('infection_grave', {}) else '')

    infection_locale_title = flat_field(lambda f: f.form.get('treatments', {}).get('infection_locale', {})
                                        .get('infection_locale_title', '') if f.form.get('treatments', {}).get('infection_locale', {}) else '')
    infection_locale_treat_0 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_locale', {})
                                          .get('infection_locale_treat_0', '') if f.form.get('treatments', {}).get('infection_locale', {}) else '')
    infection_locale_treat_1 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_locale', {})
                                          .get('infection_locale_treat_1', '') if f.form.get('treatments', {}).get('infection_locale', {}) else '')
    infection_locale_treat_2 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_locale', {})
                                          .get('infection_locale_treat_2', '') if f.form.get('treatments', {}).get('infection_locale', {}) else '')
    infection_locale_treat_2_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_locale', {})
                                                 .get('infection_locale_treat_2_help_0', '') if f.form.get('treatments', {}).get('infection_locale', {}) else '')
    infection_locale_treat_2_help_1 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_locale', {})
                                                 .get('infection_locale_treat_2_help_1', '') if f.form.get('treatments', {}).get('infection_locale', {}) else '')
    infection_locale_treat_2_help_2 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_locale', {})
                                                 .get('infection_locale_treat_2_help_2', '') if f.form.get('treatments', {}).get('infection_locale', {}) else '')
    infection_locale_treat_3 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_locale', {})
                                          .get('infection_locale_treat_3', '') if f.form.get('treatments', {}).get('infection_locale', {}) else '')
    infection_locale_treat_4 = flat_field(lambda f: f.form.get('treatments', {}).get('infection_locale', {})
                                          .get('infection_locale_treat_4', '') if f.form.get('treatments', {}).get('infection_locale', {}) else '')

    pas_infection_title = flat_field(lambda f: f.form.get('treatments', {}).get('pas_infection', {})
                                     .get('pas_infection_title', '') if f.form.get('treatments', {}).get('pas_infection', {}) else '')
    pas_infection_treat_0 = flat_field(lambda f: f.form.get('treatments', {}).get('pas_infection', {})
                                       .get('pas_infection_treat_0', '') if f.form.get('treatments', {}).get('pas_infection', {}) else '')
    pas_infection_treat_0_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('pas_infection', {})
                                              .get('pas_infection_treat_0_help_0', '') if f.form.get('treatments', {}).get('pas_infection', {}) else '')
    pas_infection_treat_0_help_0_prompt = flat_field(lambda f: f.form.get('treatments', {}).get('pas_infection', {})
                                                     .get('pas_infection_treat_0_help_0_prompt', '') if f.form.get('treatments', {}).get('pas_infection', {}) else '')
    pas_infection_treat_0_help_1 = flat_field(lambda f: f.form.get('treatments', {}).get('pas_infection', {})
                                              .get('pas_infection_treat_0_help_1', '') if f.form.get('treatments', {}).get('pas_infection', {}) else '')
    pas_infection_treat_0_help_1_prompt = flat_field(lambda f: f.form.get('treatments', {}).get('pas_infection', {})
                                                     .get('pas_infection_treat_0_help_1_prompt', '') if f.form.get('treatments', {}).get('pas_infection', {}) else '')
    pas_infection_treat_0_help_2 = flat_field(lambda f: f.form.get('treatments', {}).get('pas_infection', {})
                                              .get('pas_infection_treat_0_help_2', '') if f.form.get('treatments', {}).get('pas_infection', {}) else '')
    pas_infection_treat_0_help_2_prompt = flat_field(lambda f: f.form.get('treatments', {}).get('pas_infection', {})
                                                     .get('pas_infection_treat_0_help_2_prompt', '') if f.form.get('treatments', {}).get('pas_infection', {}) else '')
    pas_infection_treat_1 = flat_field(lambda f: f.form.get('treatments', {}).get('pas_infection', {})
                                       .get('pas_infection_treat_1', '') if f.form.get('treatments', {}).get('pas_infection', {}) else '')
    pas_infection_treat_1_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('pas_infection', {})
                                              .get('pas_infection_treat_1_help_0', '') if f.form.get('treatments', {}).get('pas_infection', {}) else '')
    pas_infection_treat_1_help_0_prompt = flat_field(lambda f: f.form.get('treatments', {}).get('pas_infection', {})
                                                     .get('pas_infection_treat_1_help_0_prompt', '') if f.form.get('treatments', {}).get('pas_infection', {}) else '')

    probleme_alimentation_title = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                             .get('probleme_alimentation_title', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_0 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                               .get('probleme_alimentation_treat_0', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_0_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                                      .get('probleme_alimentation_treat_0_help_0', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_1 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                               .get('probleme_alimentation_treat_1', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_1_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                                      .get('probleme_alimentation_treat_1_help_0', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_2 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                               .get('probleme_alimentation_treat_2', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_2_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                                      .get('probleme_alimentation_treat_2_help_0', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_3 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                               .get('probleme_alimentation_treat_3', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_4 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                               .get('probleme_alimentation_treat_4', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_4_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                                      .get('probleme_alimentation_treat_4_help_0', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_5 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                               .get('probleme_alimentation_treat_5', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_6 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                               .get('probleme_alimentation_treat_6', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_6_help_0 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                                      .get('probleme_alimentation_treat_6_help_0', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_6_help_1 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                                      .get('probleme_alimentation_treat_6_help_1', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_7 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                               .get('probleme_alimentation_treat_7', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')
    probleme_alimentation_treat_8 = flat_field(lambda f: f.form.get('treatments', {}).get('probleme_alimentation', {})
                                               .get('probleme_alimentation_treat_8', '') if f.form.get('treatments', {}).get('probleme_alimentation', {}) else '')

    signe_deshydratation_infection_title = flat_field(lambda f: f.form.get('treatments', {}).get('signe_deshydratation_infection', {})
                                                      .get('signe_deshydratation_infection_title', '') if f.form.get('treatments', {}).get('signe_deshydratation_infection', {}) else '')
    signe_deshydratation_infection_treat_0 = flat_field(lambda f: f.form.get('treatments', {}).get('signe_deshydratation_infection', {})
                                                        .get('signe_deshydratation_infection_treat_0', '') if f.form.get('treatments', {}).get('signe_deshydratation_infection', {}) else '')
    signe_deshydratation_infection_treat_1 = flat_field(lambda f: f.form.get('treatments', {}).get('signe_deshydratation_infection', {})
                                                        .get('signe_deshydratation_infection_treat_1', '') if f.form.get('treatments', {}).get('signe_deshydratation_infection', {}) else '')
    signe_deshydratation_infection_treat_2 = flat_field(lambda f: f.form.get('treatments', {}).get('signe_deshydratation_infection', {})
                                                        .get('signe_deshydratation_infection_treat_2', '') if f.form.get('treatments', {}).get('signe_deshydratation_infection', {}) else '')

    vih_pas_infection_title = flat_field(lambda f: f.form.get('treatments', {}).get('vih_pas_infection', {})
                                         .get('vih_pas_infection_title', '') if f.form.get('treatments', {}).get('vih_pas_infection', {}) else '')
    vih_pas_infection_treat_0 = flat_field(lambda f: f.form.get('treatments', {}).get('vih_pas_infection', {})
                                           .get('vih_pas_infection_treat_0', '') if f.form.get('treatments', {}).get('vih_pas_infection', {}) else '')
    vih_pas_infection_treat_1 = flat_field(lambda f: f.form.get('treatments', {}).get('vih_pas_infection', {})
                                           .get('vih_pas_infection_treat_1', '') if f.form.get('treatments', {}).get('vih_pas_infection', {}) else '')

    vih_possible_title = flat_field(lambda f: f.form.get('treatments', {}).get('vih_possible', {}).
                                    get('vih_possible_title', '') if f.form.get('treatments', {}).get('vih_possible', {}) else '')
    vih_possible_treat_0 = flat_field(lambda f: f.form.get('treatments', {}).get('vih_possible', {})
                                      .get('vih_possible_treat_0', '') if f.form.get('treatments', {}).get('vih_possible', {}) else '')
    vih_possible_treat_1 = flat_field(lambda f: f.form.get('treatments', {}).get('vih_possible', {})
                                      .get('vih_possible_treat_1', '') if f.form.get('treatments', {}).get('vih_possible', {}) else '')
    vih_possible_treat_2 = flat_field(lambda f: f.form.get('treatments', {}).get('vih_possible', {})
                                      .get('vih_possible_treat_2', '') if f.form.get('treatments', {}).get('vih_possible', {}) else '')
    vih_possible_treat_3 = flat_field(lambda f: f.form.get('treatments', {}).get('vih_possible', {})
                                      .get('vih_possible_treat_3', '') if f.form.get('treatments', {}).get('vih_possible', {}) else '')

    numerator = TDHNullEmitter()


TDHEnrollChildFluffPillow = TDHEnrollChildFluff.pillow()
TDHInfantClassificationFluffPillow = TDHInfantClassificationFluff.pillow()
TDHInfantTreatmentFluffPillow = TDHInfantTreatmentFluff.pillow()
