from django.test import SimpleTestCase

import pytest
from couchdbkit.exceptions import BadValueError

from corehq.apps.app_manager.dbaccessors import wrap_app
from corehq.apps.builds.models import (
    SemanticVersionProperty,
    StrictSemanticVersionProperty,
)


class ValidateTestBase(SimpleTestCase):

    def check_value(self, class_, value, expected):
        with self.subTest(value):
            if type(expected) is type and issubclass(expected, Exception):
                with pytest.raises(expected):
                    class_(required=True).validate(value)
            else:
                assert class_(required=True).validate(value) == expected


class TestSemanticVersionProperty(ValidateTestBase):

    def test_values(self):
        for value, expected in [
            ('1.2.3', '1.2.3'),
            ('1.2.foo', '1.2.foo'),
            ('1.2', BadValueError),
        ]:
            self.check_value(SemanticVersionProperty, value, expected)


class TestStrictSemanticVersionProperty(ValidateTestBase):

    def test_values(self):
        for value, expected in [
            ('1.2.3', '1.2.3'),
            ('1.2.foo', BadValueError),
            ('1.2', BadValueError),
        ]:
            self.check_value(StrictSemanticVersionProperty, value, expected)


def test_commcare_build_version():
    """
    Wrapping Application with "built_with" "version" == "1.2.dev" should
    not raise BadValueError
    """
    wrap_app(app_doc)


app_doc = {
    'modules': [
        {
            'name': {'en': 'Surveys'},
            'forms': [
                {
                    'name': {'en': 'Survey'},
                    'form_type': 'module_form',
                    'requires': 'none',
                    'actions': {
                        'open_case': {
                            'name_update': {
                                'question_path': None,
                                'update_mode': 'always',
                                'doc_type': 'ConditionalCaseUpdate',
                            },
                            'name_update_multi': [],
                            'external_id': None,
                            'DIFF_VALUE_UPDATED': 'updated',
                            'doc_type': 'OpenCaseAction',
                            'condition': {
                                'type': 'never',
                                'question': None,
                                'answer': None,
                                'operator': '=',
                                'doc_type': 'FormActionCondition',
                            },
                        },
                        'update_case': {
                            'update': {},
                            'update_multi': {},
                            'DIFF_ACTION_ADD': 'add',
                            'DIFF_ACTION_DELETE': 'del',
                            'DIFF_ACTION_UPDATE': 'update',
                            'DIFF_VALUE_UPDATED': 'updated',
                            'doc_type': 'UpdateCaseAction',
                            'condition': {
                                'type': 'never',
                                'question': None,
                                'answer': None,
                                'operator': '=',
                                'doc_type': 'FormActionCondition',
                            },
                        },
                        'close_case': {
                            'condition': {
                                'type': 'never',
                                'question': None,
                                'answer': None,
                                'operator': '=',
                                'doc_type': 'FormActionCondition',
                            },
                            'doc_type': 'FormAction',
                        },
                        'open_referral': {
                            'name_path': None,
                            'doc_type': 'OpenReferralAction',
                            'followup_date': None,
                            'condition': {
                                'type': 'never',
                                'question': None,
                                'answer': None,
                                'operator': '=',
                                'doc_type': 'FormActionCondition',
                            },
                        },
                        'update_referral': {
                            'followup_date': None,
                            'doc_type': 'UpdateReferralAction',
                            'condition': {
                                'type': 'never',
                                'question': None,
                                'answer': None,
                                'operator': '=',
                                'doc_type': 'FormActionCondition',
                            },
                        },
                        'close_referral': {
                            'condition': {
                                'type': 'never',
                                'question': None,
                                'answer': None,
                                'operator': '=',
                                'doc_type': 'FormActionCondition',
                            },
                            'doc_type': 'FormAction',
                        },
                        'case_preload': {
                            'preload': {},
                            'doc_type': 'PreloadAction',
                            'condition': {
                                'type': 'never',
                                'question': None,
                                'answer': None,
                                'operator': '=',
                                'doc_type': 'FormActionCondition',
                            },
                        },
                        'referral_preload': {
                            'preload': {},
                            'doc_type': 'PreloadAction',
                            'condition': {
                                'type': 'never',
                                'question': None,
                                'answer': None,
                                'operator': '=',
                                'doc_type': 'FormActionCondition',
                            },
                        },
                        'load_from_form': {
                            'preload': {},
                            'doc_type': 'PreloadAction',
                            'condition': {
                                'type': 'never',
                                'question': None,
                                'answer': None,
                                'operator': '=',
                                'doc_type': 'FormActionCondition',
                            },
                        },
                        'usercase_update': {
                            'update': {},
                            'update_multi': {},
                            'DIFF_ACTION_ADD': 'add',
                            'DIFF_ACTION_DELETE': 'del',
                            'DIFF_ACTION_UPDATE': 'update',
                            'DIFF_VALUE_UPDATED': 'updated',
                            'doc_type': 'UpdateCaseAction',
                            'condition': {
                                'type': 'never',
                                'question': None,
                                'answer': None,
                                'operator': '=',
                                'doc_type': 'FormActionCondition',
                            },
                        },
                        'usercase_preload': {
                            'preload': {},
                            'doc_type': 'PreloadAction',
                            'condition': {
                                'type': 'never',
                                'question': None,
                                'answer': None,
                                'operator': '=',
                                'doc_type': 'FormActionCondition',
                            },
                        },
                        'subcases': [],
                        'doc_type': 'FormActions',
                    },
                    'doc_type': 'Form',
                    'unique_id': '3f2456d63d97493484f9c1a101ea2327',
                    'show_count': False,
                    'xmlns': 'http://openrosa.org/formdesigner/C4053F9F-0BF3-408E-9FC7-2CE42FBAF896',
                    'version': None,
                    'post_form_workflow': 'default',
                    'post_form_workflow_fallback': None,
                    'auto_gps_capture': False,
                    'form_links': [],
                    'custom_assertions': [],
                    'custom_instances': [],
                    'case_references_data': {
                        'load': {},
                        'save': {},
                        'doc_type': 'CaseReferences',
                    },
                    'is_release_notes_form': False,
                    'enable_release_notes': False,
                    'respect_relevancy': True,
                    'function_datum_endpoints': [],
                    'submit_label': {},
                    'submit_notification_label': {},
                    'comment': '',
                    'media_image': {},
                    'media_audio': {},
                    'custom_icons': [],
                    'use_default_image_for_all': False,
                    'use_default_audio_for_all': False,
                }
            ],
            'case_type': '',
            'case_details': {
                'short': {
                    'columns': [
                        {
                            'format': 'plain',
                            'header': {'en': 'Name'},
                            'field': 'name',
                            'model': 'case',
                            'hasAutocomplete': True,
                            'useXpathExpression': False,
                            'grid_x': None,
                            'grid_y': None,
                            'enum': [],
                            'graph_configuration': {
                                'config': {},
                                'locale_specific_config': {},
                                'annotations': [],
                                'series': [],
                                'doc_type': 'GraphConfiguration',
                            },
                            'late_flag': 30,
                            'time_ago_interval': 365.25,
                            'date_format': '%d/%m/%y',
                            'doc_type': 'DetailColumn',
                        }
                    ],
                    'display': 'short',
                    'tabs': [],
                    'sort_elements': [],
                    'instance_name': 'casedb',
                    'persist_case_context': None,
                    'persistent_case_context_xml': 'case_name',
                    'multi_select': False,
                    'auto_select': False,
                    'max_select_value': 100,
                    'persist_tile_on_forms': None,
                    'pull_down_tile': None,
                    'case_tile_group': {
                        'index_identifier': None,
                        'header_rows': 2,
                        'doc_type': 'CaseTileGroupConfig',
                    },
                    'no_items_text': {'en': 'List is empty.'},
                    'select_text': {'en': 'Continue'},
                    'doc_type': 'Detail',
                    'lookup_enabled': False,
                    'lookup_autolaunch': False,
                    'lookup_image': None,
                    'lookup_extras': [],
                    'lookup_responses': [],
                    'lookup_display_results': False,
                    'lookup_field_header': {},
                },
                'long': {
                    'columns': [
                        {
                            'format': 'plain',
                            'header': {'en': 'Name'},
                            'field': 'name',
                            'model': 'case',
                            'hasAutocomplete': True,
                            'useXpathExpression': False,
                            'grid_x': None,
                            'grid_y': None,
                            'enum': [],
                            'graph_configuration': {
                                'config': {},
                                'locale_specific_config': {},
                                'annotations': [],
                                'series': [],
                                'doc_type': 'GraphConfiguration',
                            },
                            'late_flag': 30,
                            'time_ago_interval': 365.25,
                            'date_format': '%d/%m/%y',
                            'doc_type': 'DetailColumn',
                        }
                    ],
                    'display': 'long',
                    'tabs': [],
                    'sort_elements': [],
                    'instance_name': 'casedb',
                    'persist_case_context': None,
                    'persistent_case_context_xml': 'case_name',
                    'multi_select': False,
                    'auto_select': False,
                    'max_select_value': 100,
                    'persist_tile_on_forms': None,
                    'pull_down_tile': None,
                    'case_tile_group': {
                        'index_identifier': None,
                        'header_rows': 2,
                        'doc_type': 'CaseTileGroupConfig',
                    },
                    'no_items_text': {'en': 'List is empty.'},
                    'select_text': {'en': 'Continue'},
                    'doc_type': 'Detail',
                    'lookup_enabled': False,
                    'lookup_autolaunch': False,
                    'lookup_image': None,
                    'lookup_extras': [],
                    'lookup_responses': [],
                    'lookup_display_results': False,
                    'lookup_field_header': {},
                },
                'doc_type': 'DetailPair',
            },
            'module_type': 'basic',
            'ref_details': {
                'short': {
                    'display': 'short',
                    'columns': [],
                    'tabs': [],
                    'sort_elements': [],
                    'instance_name': 'casedb',
                    'persist_case_context': None,
                    'persistent_case_context_xml': 'case_name',
                    'multi_select': False,
                    'auto_select': False,
                    'max_select_value': 100,
                    'persist_tile_on_forms': None,
                    'pull_down_tile': None,
                    'case_tile_group': {
                        'index_identifier': None,
                        'header_rows': 2,
                        'doc_type': 'CaseTileGroupConfig',
                    },
                    'no_items_text': {'en': 'List is empty.'},
                    'select_text': {'en': 'Continue'},
                    'doc_type': 'Detail',
                    'lookup_enabled': False,
                    'lookup_autolaunch': False,
                    'lookup_image': None,
                    'lookup_extras': [],
                    'lookup_responses': [],
                    'lookup_display_results': False,
                    'lookup_field_header': {},
                },
                'long': {
                    'display': 'long',
                    'columns': [],
                    'tabs': [],
                    'sort_elements': [],
                    'instance_name': 'casedb',
                    'persist_case_context': None,
                    'persistent_case_context_xml': 'case_name',
                    'multi_select': False,
                    'auto_select': False,
                    'max_select_value': 100,
                    'persist_tile_on_forms': None,
                    'pull_down_tile': None,
                    'case_tile_group': {
                        'index_identifier': None,
                        'header_rows': 2,
                        'doc_type': 'CaseTileGroupConfig',
                    },
                    'no_items_text': {'en': 'List is empty.'},
                    'select_text': {'en': 'Continue'},
                    'doc_type': 'Detail',
                    'lookup_enabled': False,
                    'lookup_autolaunch': False,
                    'lookup_image': None,
                    'lookup_extras': [],
                    'lookup_responses': [],
                    'lookup_display_results': False,
                    'lookup_field_header': {},
                },
                'doc_type': 'DetailPair',
            },
            'case_list': {
                'label': {},
                'show': False,
                'doc_type': 'CaseList',
                'media_image': {},
                'media_audio': {},
                'custom_icons': [],
                'use_default_image_for_all': False,
                'use_default_audio_for_all': False,
            },
            'referral_list': {
                'label': {},
                'show': False,
                'doc_type': 'CaseList',
                'media_image': {},
                'media_audio': {},
                'custom_icons': [],
                'use_default_image_for_all': False,
                'use_default_audio_for_all': False,
            },
            'task_list': {
                'label': {},
                'show': False,
                'doc_type': 'CaseList',
                'media_image': {},
                'media_audio': {},
                'custom_icons': [],
                'use_default_image_for_all': False,
                'use_default_audio_for_all': False,
            },
            'parent_select': {
                'active': False,
                'relationship': 'parent',
                'module_id': None,
                'doc_type': 'ParentSelect',
            },
            'search_config': {
                'command_label': {'en': 'Search All Cases'},
                'again_label': {'en': 'Search Again'},
                'search_label': {
                    'label': {'en': 'Search All Cases'},
                    'doc_type': 'CaseSearchLabel',
                    'media_image': {},
                    'media_audio': {},
                    'custom_icons': [],
                    'use_default_image_for_all': False,
                    'use_default_audio_for_all': False,
                },
                'search_again_label': {
                    'label': {'en': 'Search Again'},
                    'doc_type': 'CaseSearchAgainLabel',
                    'media_image': {},
                    'media_audio': {},
                    'custom_icons': [],
                    'use_default_image_for_all': False,
                    'use_default_audio_for_all': False,
                },
                'properties': [],
                'auto_launch': False,
                'default_search': False,
                'default_properties': [],
                'custom_sort_properties': [],
                'additional_case_types': [],
                'additional_registry_cases': [],
                'title_label': {},
                'description': {},
                'include_all_related_cases': False,
                'dynamic_search': False,
                'search_on_clear': False,
                'inline_search': False,
                'doc_type': 'CaseSearch',
            },
            'display_style': 'list',
            'lazy_load_case_list_fields': False,
            'show_case_list_optimization_options': False,
            'doc_type': 'Module',
            'unique_id': '4c719c0323a342efbfd91bd738cdad15',
            'case_list_form': {
                'form_id': None,
                'label': {},
                'post_form_workflow': 'default',
                'doc_type': 'CaseListForm',
                'media_image': {},
                'media_audio': {},
                'custom_icons': [],
                'use_default_image_for_all': False,
                'use_default_audio_for_all': False,
            },
            'put_in_root': False,
            'fixture_select': {
                'active': False,
                'localize': False,
                'doc_type': 'FixtureSelect',
            },
            'report_context_tile': False,
            'auto_select_case': False,
            'is_training_module': False,
            'custom_assertions': [],
            'media_image': {},
            'media_audio': {},
            'custom_icons': [],
            'use_default_image_for_all': False,
            'use_default_audio_for_all': False,
            'comment': '',
        }
    ],
    'name': 'Micro Application',
    'langs': ['en'],
    'date_created': '2025-09-01T18:35:21.216494Z',
    'profile': {},
    'use_custom_suite': False,
    'custom_base_url': None,
    'cloudcare_enabled': False,
    'translations': {},
    'translation_strategy': 'select-known',
    'auto_gps_capture': False,
    'created_from_template': None,
    'use_grid_menus': False,
    'grid_form_menus': 'none',
    'add_ons': {
        'advanced_itemsets': False,
        'calc_xpaths': False,
        'case_detail_overwrite': False,
        'case_list_menu_item': False,
        'conditional_enum': False,
        'conditional_form_actions': False,
        'display_conditions': False,
        'enum_image': False,
        'menu_mode': False,
        'register_from_case_list': False,
        'subcases': False,
        'submenus': False,
        'empty_case_lists': False,
    },
    'smart_lang_display': None,
    'custom_assertions': [],
    'family_id': None,
    'doc_type': 'Application',
    'recipients': '',
    'build_spec': {
        'version': '2.0.0',
        'build_number': None,
        'latest': True,
        'doc_type': 'BuildSpec',
    },
    'built_with': {
        'signed': True,
        'datetime': None,
        'doc_type': 'BuildSpec',
        'version': '1.2.dev',
        'build_number': 7106,
        'latest': None,
    },
    'build_signed': True,
    'built_on': None,
    'build_comment': None,
    'comment_from': None,
    'last_released': None,
    'build_broken': False,
    'is_auto_generated': False,
    'build_broken_reason': None,
    'is_released': False,
    'admin_password': None,
    'admin_password_charset': 'n',
    'secure_submissions': True,
    'amplifies_workers': 'not_set',
    'amplifies_project': 'not_set',
    'minimum_use_threshold': '15',
    'experienced_threshold': '3',
    'cached_properties': {},
    'description': None,
    'deployment_date': None,
    'phone_model': None,
    'user_type': None,
    'attribution_notes': None,
    'case_sharing': False,
    'vellum_case_management': True,
    'application_version': '2.0',
    'last_modified': '2025-09-01T18:36:17.322334Z',
    'build_profiles': {},
    'practice_mobile_worker_id': None,
    'target_commcare_flavor': 'none',
    'has_submissions': False,
    'mobile_ucr_restore_version': '2.0',
    'location_fixture_restore': 'project_default',
    'split_screen_dynamic_search': False,
    'persistent_menu': False,
    'show_breadcrumbs': True,
    'copy_history': [],
    'comment': '',
    'multimedia_map': {},
    'logo_refs': {},
    'archived_media': {},
}
