#!/usr/bin/env bash
# usage: scripts/inventory/mosh <environment> <group>[:<n>]

CHOICE=$(SCRIPT=$0 python scripts/inventory/getinventory.py $1 $2 | sed 's/:\([0-9]*\)/ -p \1/')
if [[ -n "$CHOICE" ]]; then
    shift; shift  # drop environment and group
    echo "mosh ${CHOICE} $@"
    mosh ${CHOICE} "$@"
else
    exit 1
fi
