#!/usr/bin/env bash
# usage: scripts/inventory/ssh <environment> <group>[:<n>]

CHOICE=$(SCRIPT=$0 python scripts/inventory/getinventory.py $1 $2)
if [[ -n "$CHOICE" ]]; then
    shift; shift  # drop environment and group
    echo "ssh ${CHOICE} $@"
    ssh ${CHOICE} "$@"
else
    exit 1
fi
