# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0003_emailrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrequest',
            name='email_address',
            field=models.CharField(default='foo@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
