BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBB
   gettext(u'500 Error') 
BBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBXXXX gettext(u'Oh no, something unexpected just happened!') XXXXXBBBBBBBB
BBBBB BBBBBBBBBBBB
  XXXX XXXXXXXXXXXX
  BB BBB BBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Sad Danny is Sad') X XXXXXX
    XXXXXX
  BBBBB
    XXXX XXXXXXXBB BBB BBBBBBBBBBBBBBBXXXXXXXXBBBBXXXXXXXXXBBBBBXX
      XXXX XXXXXXXXXXXXX
        XXXXXX
          XXXXXXXXXX
            XXXXXXXX
               gettext(u'First time here?') 
            XXXXXXXXX
             gettext(u'\n              Try refreshing. Often the problem is temporary and the page will succeed if you try again.<br><br>\n            ') 
              SSS SSSSSSSSSSS SSSSS SSS SSSSSSS SS SSSSSSSSS SSS SSS SSSS SSSS SSSSSSS SS SSS SSS SSSSSSSSSSSSSS
            
            XXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Refresh Page') XXXXXXXXX
          XXXXXXXXXXX
        XXXXXXX
      XXXXXX

      BB BBB BBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX
            XXXXXXXXXX
              XXXXXXXX
                 gettext(u'Check the status of our services.') 
              XXXXXXXXX
               gettext(u"\n                If there is a problem with our systems, we'll post an update to our Status Page.\n              ") 
                SS SSSSS SS S SSSSSSS SSSS SSS SSSSSSSS SSSSS SSSS SS SSSSSS SS SSS SSSSSS SSSSS
              XXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'View Status Page') XXXX
            XXXXXXXXXXX
          XXXXXX
        XXXXXX
      BBBBB

      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
               gettext(u'\n                Been here before? Report an issue to help us get this problem fixed faster.\n              ') 
                SSSS SSSS SSSSSSS SSSSSS SS SSSSS SS SSSS SS SSS SSSS SSSSSSS SSSSS SSSSSSS
              
            XXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBX XXXXXXXXXXXXXX
              BBBBBBBBBB
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX

              
              XXXXXXXXXX
                 gettext(u'We would appreciate any additional information about what happened before you encountered this problem.') XXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Short Description') XXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Full Description') XXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                XXXXXX
              XXXXXXXXXXX

              XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Submit Report') XXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
      BBBBB
      XXX XX
    XXXXXX
  XXXXXX
BBBBBBBB
