BBBBBBB BBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBB gettext(u'Change User Password') BBBBBBBB
BBBBB BBBBBBB
  XXXX
     gettext(u'Change Password for')  
  XXXXX
  XXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXXX
      
    XXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XX
  XXXXXXX
BBBBBBBB
