# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sector_datamigration', '0004_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('accountTypeId', models.CharField(max_length=256, null=True)),
                ('addressLineOne', models.CharField(max_length=256, null=True)),
                ('addressLineTwo', models.CharField(max_length=256, null=True)),
                ('agencyId', models.IntegerField()),
                ('alternateMobileNumber', models.CharField(max_length=256, null=True)),
                ('alternateMobileNumber1', models.CharField(max_length=256, null=True)),
                ('alternateMobileNumber2', models.CharField(max_length=256, null=True)),
                ('bankAccountName', models.CharField(max_length=256, null=True)),
                ('bankAccountNumber', models.CharField(max_length=256, null=True)),
                ('bankBranch', models.CharField(max_length=256, null=True)),
                ('bankIFSCCode', models.CharField(max_length=256, null=True)),
                ('bankName', models.CharField(max_length=256, null=True)),
                ('blockOrHealthPostId', models.CharField(max_length=256, null=True)),
                ('creationDate', models.DateTimeField(null=True)),
                ('creator', models.CharField(max_length=256, null=True)),
                ('districtId', models.CharField(max_length=256, null=True)),
                ('dob', models.DateTimeField(null=True)),
                ('email', models.CharField(max_length=256, null=True)),
                ('firstName', models.CharField(max_length=256, null=True)),
                ('gender', models.CharField(max_length=256, null=True)),
                ('isPasswordResetFlag', models.NullBooleanField()),
                ('isPrimary', models.BooleanField()),
                ('landLineNumber', models.CharField(max_length=256, null=True)),
                ('lastName', models.CharField(max_length=256, null=True)),
                ('latitude', models.CharField(max_length=256, null=True)),
                ('longitude', models.CharField(max_length=256, null=True)),
                ('micrCode', models.IntegerField(null=True)),
                ('middleName', models.CharField(max_length=256, null=True)),
                ('mobileNumber', models.CharField(max_length=256, null=True)),
                ('modificationDate', models.DateTimeField(null=True)),
                ('modifiedBy', models.CharField(max_length=256, null=True)),
                ('motechUserName', models.CharField(max_length=256, null=True)),
                ('organisationId', models.IntegerField()),
                ('owner', models.CharField(max_length=256, null=True)),
                ('passwordResetFlag', models.BooleanField()),
                ('pincode', models.IntegerField()),
                ('stateId', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(max_length=256, null=True)),
                ('subOrganisationId', models.IntegerField()),
                ('tuId', models.CharField(max_length=256, null=True)),
                ('uniqIDNo', models.CharField(max_length=256, null=True)),
                ('uniqIDType', models.CharField(max_length=256, null=True)),
                ('userId', models.IntegerField()),
                ('userName', models.CharField(max_length=256, null=True)),
                ('valid', models.BooleanField()),
                ('villageTownCity', models.CharField(max_length=256, null=True)),
                ('wardId', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
