# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_sector_datamigration', '0012_auto_20170526_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodePrescription',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('adultOrPaediatric', models.CharField(max_length=255, null=True)),
                ('beneficiaryID', models.CharField(max_length=18)),
                ('creationDate', models.DateTimeField(null=True)),
                ('creator', models.CharField(max_length=255, null=True)),
                ('dosageStrength', models.CharField(max_length=255, null=True)),
                ('episodeId', models.CharField(max_length=8, null=True)),
                ('modificationDate', models.DateTimeField(null=True)),
                ('modifiedBy', models.CharField(max_length=255, null=True)),
                ('next_refill_date', models.DateTimeField(null=True)),
                ('numberOfDays', models.IntegerField()),
                ('numberOfDaysPrescribed', models.CharField(max_length=255, null=True)),
                ('numberOfRefill', models.CharField(max_length=255, null=True)),
                ('owner', models.CharField(max_length=255, null=True)),
                ('presUnits', models.CharField(max_length=255, null=True)),
                ('prescStatus', models.CharField(max_length=255, null=True)),
                ('prescriptionID', models.IntegerField()),
                ('pricePerUnit', models.DecimalField(decimal_places=10, max_digits=14)),
                ('pricePerUnits', models.CharField(max_length=255, null=True)),
                ('productID', models.IntegerField()),
                ('productName', models.CharField(max_length=255, null=True)),
                ('refill_Index', models.IntegerField()),
                ('typicalUnits', models.CharField(max_length=255, null=True)),
                ('unitDesc', models.CharField(max_length=255, null=True)),
                ('voucherID', models.IntegerField()),
                ('voucherStatus', models.CharField(max_length=255, null=True)),
                ('motechUserName', models.CharField(max_length=255, null=True)),
                ('physicalVoucherNumber', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
