# Generated by Django 3.2.20 on 2023-09-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatial', '0002_geoconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoconfig',
            name='case_location_property_name',
            field=models.CharField(default='geo_point', max_length=256),
        ),
        migrations.AlterField(
            model_name='geoconfig',
            name='user_location_property_name',
            field=models.CharField(default='geo_point', max_length=256),
        ),
    ]
