BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
 gettext(u'Export Data Source Data') 
BBBBBBBB

BBBBB BBBBBBBBBBBB
  XXX
     gettext(u"\n    Generate a query file for the Data Export Tool from any of the project's data sources.\n    ") 
    SSSSSSSS S SSSSS SSSS SSS SSS SSSS SSSSSS SSSS SSSS SSS SS SSS SSSSSSSSS SSSS SSSSSSSS
    
  XXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
       gettext(u'\n      The project has no data sources configured.\n      ') 
      SSS SSSSSSS SSS SS SSSS SSSSSSS SSSSSSSSSSS
      
    XXXXXX
    BBBBBB BBBB
  XXXXXX
BBBBBBBB
