BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB

BBBBB BBBBBBBBBBB
  XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXX XXXXXXXXX
    X
    XXXXXXXXXXXX X
      XXXXXXXXX XXXXXXXXX
      XXXX XX
      XXXXX XX
      XXXXXX XXXXX
      XXXXXXX XXXXX
      XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX
      XXXXX XXXXXXX XX XXX XX XXXXX XXXX XXXXX XXXXXXXX XXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XX
      XXXXX XXXXXXX XX XXX XX X XX XXXXXXXXXX XX XXXXXX XXXX X XX
      XXXXXXXX XX

    X
    XXXXXXXXXXXX XXXXXX X
      XXXXXXXX XXXXXX
    X
    XXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXX XXXX
      XXXXXXXXXXX XXXX
    X
    XXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXX XXXXX
    X
  XXXXXXXX
BBBBBBBB BBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
  
BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB

  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    BB BBB BBBBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXX
         gettext(u'\n          You are downloading the following exports:\n        ') 
          SSS SSS SSSSSSSSSSS SSS SSSSSSSSS SSSSSSSS
        
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXX
            XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX
          XXXXX
        XXXXX
      XXXXXX
    BBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'No submissions available.') 
        XXXXX
        XXX
           gettext(u"\n            It seems your project doesn't have any submissions\n            from its applications. Please submit data before\n            using the export tool.\n          ") 
            SS SSSSS SSSS SSSSSSS SSSSSSS SSSS SSS SSSSSSSSSSS
            SSSS SSS SSSSSSSSSSSSS SSSSSS SSSSSS SSSS SSSSSS
            SSSSS SSS SSSSSS SSSSS
          
        XXXX
        XXX
           gettext(u'\n            To get started, please\n            <a href="https://confluence.dimagi.com/display/commcarepublic/Deploy+and+Install+an+Application+on+CommCareHQ"\n               target="_blank">deploy</a>\n            your application and submit data from a phone. You may also\n            <a href="https://help.commcarehq.org/display/commcarepublic/Web+Apps"\n               target="_blank">submit data via Web Apps\n            </a>\n            , depending on your project\'s\n            <a href="https://www.commcarehq.org/pricing/" target="_blank">plan level</a>.\n          ') 
            SS SSS SSSSSSSS SSSSSS
            SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
               SSSSSSSSSSSSSSSSSSSSSSSSSS
            SSSS SSSSSSSSSSS SSS SSSSSS SSSS SSSS S SSSSSS SSS SSS SSSS
            SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
               SSSSSSSSSSSSSSSSSSSSSS SSSS SSS SSS SSSS
            SSSS
            S SSSSSSSSS SS SSSS SSSSSSSSS
            SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSS SSSSSSSSSS
          
        XXXX
      XXXXXX
    BBBB
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB
  XXXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBBB BBBBBBBBBBBB
