BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBB
  
BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBB BBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB

  XXXXXXX

  BB BBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XBBBBBBBBBBBBBBB BBBBBBBB B BBBBBBB BBBBBBBBBBBBXXXXXXXXXXXXXX
    XXXXXX
  BBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBB
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXX
         XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXX
         XXXXXXXXXXXXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXFFFFFFFFFFFFFFX XXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XX XXXXXXXXXXXXX
         gettext(u'Now access forms and cases directly from your exports. Check out the new "form_link" and "case_link" fields in your export settings!') 
      XXXX
    XXXXXX
  BBBBB
BBBBBBBB
