BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB

BB BBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXX XXXXXXX XXXXX
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
XXXXXX
BBBBB

XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XX XXXX XXXXXXX
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    BB BBB BBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXX
        XXXXX XXX XX XXXXXX XXXXXXXXXXXXX XX XXXX XXXXXXXX
      XXXXXX
    BBBB
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXX
        XXXX
          XXXXXXXXXXX XXXXXXXXXX
          XXXXXXXXXXX XXXXXXXXXXXX
          XXXXXXXXX XXXXXXXXX
          XXXXXXX XXXXXXXXX
          XXXXXXXXXXXXXX XXXXXXXX XXXXXXX
          XXXXXXXXXXXXX
        XXXXX
        XXXXXXXX
        XXXXXXX
        BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBB
          XXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXXXXX
            XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
        BBBBBB
        XXXXXXXX
      XXXXXXXX
    BBBBB
  XXXXXX
XXXXXX
