BBBB BBBB

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXX
    XXXXXXXX gettext(u'Select Payment Method') XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
         gettext(u'Card') 
      XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX
          XXXXXXX
            XXXXXX XXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXX
             gettext(u'Use a saved card') 
          XXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                           XXXXXXXXXXXX XXXXXXXXXXX
                                           XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXX gettext(u'Actually remove this card?') XXXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXX XXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Yes, Remove') 
          XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXX XXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Cancel') 
          XXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Removing card...') 
        XXXXXX
        XXXX XXXXXXXXXXXXXX
          XXXXXXX
            XXXXXX XXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXX
             gettext(u'Use a different card') 
          XXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX X
                            XXXXX XXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXX
                        XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX X
                            XXXXX XXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXX
                        XXXXXXXXX
  XXXXXXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXX
    XXXXXXXX gettext(u'Card Information') XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX X
                            XXXXX XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
  XXXXXXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXX XXXXXX XX
  XX XXXXXXXXXXXX XXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
     gettext(u'\n      Processing your payment...\n    ') 
      SSSSSSSSSS SSSS SSSSSSSSSS
    
  XXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXX

  XXXXXX XXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXX XXXXXX XX

  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
         gettext(u'Card Number') 
      XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXXXXXX XXXXXXX
               XXXXXXXXX
               XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
         gettext(u'CVC') 
      XXXXXXXX

      XXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXXXXXX XXXX
               XXXXXXXX
               XXXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
         gettext(u'Expiration') 
      XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX
                   XXXXXXXXXXXXXXXXX XXXXXXXXX
                   XXXXXXXX
                   XXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXX XX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX
                   XXXXXXXXXXXXXXXXX XXXXXXXX
                   XXXXXXXX
                   XXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXX XX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
           gettext(u'Save card for later') 
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                                                                         XXXXXXXX XXXXXXXXXXXXXX
           gettext(u'Use this card to autopay') 
        XXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
           gettext(u'\n            We use <a href="http://www.stripe.com/" target="_blank">Stripe</a>\n            to process this transaction.\n          ') 
            SS SSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSS
            SS SSSSSSS SSSS SSSSSSSSSSSS
          
                XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  XX XXXXXXXXXXXX XXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
     gettext(u'\n      Processing your payment...\n    ') 
      SSSSSSSSSS SSSS SSSSSSSSSS
    
  XXXX

  XX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
     gettext(u"Using Stripe's TEST API.") 
  XXXX
XXXXXXXXX
