BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
  XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXX
    XXX XXX XXXXXXXXXXXX
  XXXX
XXXXXX

XXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXX
    XXXX
      XXXX gettext(u'Project Space') XXXXX
      XXXX gettext(u'Software Plan') XXXXX
      XXXX gettext(u'Start Date') XXXXX
      XXXX gettext(u'End Date') XXXXX
      XXXX gettext(u'Currently Active') XXXXX
      XXXX gettext(u'Salesforce Contract ID') XXXXX
      XXXX gettext(u'Last Invoice Due Date') XXXXX
      XXXX gettext(u'Do Not Invoice') XXXXX
      XXXX gettext(u'"Do Not Invoice" Reason') XXXXX
      XXXX gettext(u'Edit') XXXXX
    XXXXX
    XXXXXXXX
    XXXXXXX
    BBB BBBBBBBBBBBBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
      XXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    BBBBBB
    XXXXXXXX
  XXXXXXXX
XXXXXX
