from django.conf.urls.defaults import *

urlpatterns = patterns('',
    url(r'^xforms/?$', 'corehq.apps.xforms.views.dashboard', name='corehq.apps.xforms.views.dashboard'),
    url(r'^xforms/(?P<formdef_id>\d+)/form.xhtml$', 'corehq.apps.xforms.views.get_xform', name='corehq.apps.xforms.views.get_xform'),
    (r'^xforms/reregister/(?P<domain_name>.*)/?$', 'corehq.apps.xforms.views.reregister_xform'),
    (r'^xforms/remove/(?P<form_id>\d+)/?$', 'corehq.apps.xforms.views.remove_xform'),
    (r'^xforms/show/(?P<formdef_id>\d+)/?$', 'corehq.apps.xforms.views.single_xform'),
    (r'^xforms/validator/?$', 'corehq.apps.xforms.views.validator'),
    (r'^xforms/readable_xform/?$', 'corehq.apps.xforms.views.readable_xform'),
    (r'^xforms/form_versions/?$', 'corehq.apps.xforms.views.xmlns_group'),
    (r'^xforms/form_versions/popup/?$', 'corehq.apps.xforms.views.xmlns_group_popup'),
    (r'^xforms/groups/?$', 'corehq.apps.xforms.views.manage_groups'),
    (r'^xforms/groups/new/?$', 'corehq.apps.xforms.views.new_form_data_group'),
    (r'^xforms/groups/from_xmlns/?$', 'corehq.apps.xforms.views.create_form_data_group_from_xmlns'),
    (r'^xforms/groups/(?P<group_id>\d+)/edit/?$', 'corehq.apps.xforms.views.edit_form_data_group'),
    (r'^xforms/groups/(?P<group_id>\d+)/editcolumns/?$', 'corehq.apps.xforms.views.edit_form_data_group_columns'),
    (r'^xforms/groups/(?P<group_id>\d+)/delete/?$', 'corehq.apps.xforms.views.delete_form_data_group'),
    (r'^xforms/groups/(?P<group_id>\d+)/?$', 'corehq.apps.xforms.views.form_data_group'),
    url(r'^xforms/show/(?P<formdef_id>\d+)/(?P<instance_id>\d+)/?$', 'corehq.apps.xforms.views.single_instance', name="single_instance"),
    (r'^xforms/show/(?P<formdef_id>\d+)/(?P<instance_id>\d+)/csv/?$', 'corehq.apps.xforms.views.single_instance_csv'),
    url(r'^xforms/data/(?P<formdef_id>\d+)/delete/?$', 'corehq.apps.xforms.views.delete_data', name="delete_data"),
    (r'^xforms/data/(?P<formdef_id>\d+)/?$', 'corehq.apps.xforms.views.data'),
    (r'^xforms/data/(?P<formdef_id>\d+)/plain/?$', 'corehq.apps.xforms.views.plain_data'),
    (r'^xforms/data/(?P<formdef_id>\d+)/csv/?$', 'corehq.apps.xforms.views.export_csv'),
    (r'^xforms/data/(?P<formdef_id>\d+)/xml/?$', 'corehq.apps.xforms.views.export_xml'),
    (r'^xforms/(?P<formdef_id>\d+)/submit/?$', 'corehq.apps.xforms.views.submit_data'),
    (r'', include('corehq.apps.xforms.api_.urls')),
)
