# Generated by Django 4.2.17 on 2025-01-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_limits', '0003_pillowlaggaugedefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('limit', models.PositiveIntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
