BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
          XXXXXXXX XXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX
          XXXXXXXXXXXX XXXXXXXX
          XXXXX XXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXX
      XXXXXXXXXXX
    XXXXXXX
    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
          XXXXXXXX XXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXX XXXXXXXX
          XXXXX XXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXX
          XXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXX
    XXXXXXX
  XXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXX XXXXXXXX
                         XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                         XXXXXXXXXXXX XXXXXXXX
                         XXXXX X
                           XXXXXXXXX XXXXXXXXXXX
                           XXX XXXXXXX
                         XXXXXXXXXXXX
    XXXXXXX
    XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX
              XXXXXXXXXXXXXXXXXXX XXXXXXXX
                         XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXX XXXXXXXX
                         XXXXX X
                           XXXXXXXXX XXXXXXXXXXX
                           XXX XXXXXXX
                         XX
                         XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXX
  XXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                      XXXXX X
                        XXXXXXXXX XXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXX
                      XXXX
  XXXXXX
  XXXX XX XXX XXXXXXXXXXXXXXXXXX XXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXXXXX
     gettext(u'\n      You cannot re-enable this feature once it is disabled\n      until you upgrade your subscription.\n    ') 
      SSS SSSSSS SSSSSSSSS SSSS SSSSSSS SSSS SS SS SSSSSSSS
      SSSSS SSS SSSSSSS SSSS SSSSSSSSSSSSS
    
  XXXXXX
  XXXX XXX XXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXX
      XXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX
            XXXXX X
                XXXX XXXXXXXXXXX
            X
        XXX
  XXXX
  XX XXXXXXXXXXXXXXXXXXX
     XXXXXXXXXX XXXXXXXXXXXX
     XXXXXXXXXXX
        XXXXX X
            XXXXXXXXXXXXXXXXXXX XXXXX
            XXXXX XXXX
        XX
        XXXXXX XXXXXXXXXXXXXX
        XXXXXX X
            XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        X
    XX
    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
             gettext(u'Replace Logo') 
        XXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
             gettext(u'Upload Logo') 
        XXXXXXX
  XXXX
  XX XXXXXXXXXX XXXXXXXXXXX
     XXXXXXXXXXX
           XXXXXXXX XXXXXX
           XXXXXX XXXXXXXXXX
    XX
    XX XXXXXXXXX XXXXXXXXXXXXXXX
  XXXX
XXXXXXXXX

BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXX
        X XX
    XXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXX
        X XX
    XXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
        XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
    XXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX
    XXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'User Interface Translations') XXXXX
        XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
      XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXX
XXXXXXXXX

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXX
       XXXXXXXXXXXFFFFFFFFFFFFFFX
       XXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XX XXXXXXXXXXXXX gettext(u'New Add-ons tab') XXXX
    XXX
       gettext(u'\n        Intermediate functionality, such as child cases, can now be enabled or disabled using the\n        <strong>Add-Ons</strong> tab below. Several feature previews, such as icons in the case list,\n        are also now accessible in this tab.\n      ') 
        SSSSSSSSSSSS SSSSSSSSSSSSSS SSSS SS SSSSS SSSSSS SSS SSS SS SSSSSSS SS SSSSSSSS SSSSS SSS
        SSSSSSSSSSSSSSSSSSSSSSSS SSS SSSSSS SSSSSSS SSSSSSS SSSSSSSSS SSSS SS SSSSS SS SSS SSSS SSSSS
        SSS SSSS SSS SSSSSSSSSS SS SSSS SSSS
      
    XXXX
  XXXXXX
BBBBB

XXXX XXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
    BB BBBBBBBBBBBBB
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Linked Application') XXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Languages') XXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Multimedia') XXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Actions') XXXXXXXXX
    BBBB
      XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Languages') XXXXXXXXX
      BB BBB BBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Multimedia') XXXXXXXXX
      BBBBB
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Actions') XXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Add-ons') XXXXXXXXX
    BBBBB
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Advanced Settings') XXXXXXXXX
    BB BBB BBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Custom Assertions') XXXXXXXXX
    BBBBB
  XXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXXX
               gettext(u'Update from upstream application') 
            XXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXX
                BB BBBBBBBBBBBB
                   gettext(u"\n                    Your app was last pulled from\n                    <a href='%(upstream_url)s'>%(upstream_name)s</a>,\n                    version %(upstream_version)s.\n                  ") 
                    SSSS SSS SSS SSSS SSSSSS SSSS
                    SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
                    SSSSSSS SSSSSSSSSSSSSSSSSSSSS
                  
                BBBB
                   gettext(u'\n                    Your app was last pulled from %(upstream_name)s, version %(upstream_version)s.\n                  ') 
                    SSSS SSS SSS SSSS SSSSSS SSSS SSSSSSSSSSSSSSSSSS SSSSSSS SSSSSSSSSSSSSSSSSSSSS
                  
                BBBBB
              XXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                      XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                              XXXXXXXXXXXXXXXXXXBBBBBBBBBBBBBBB BBBBBBB BB BBBBBBBB BBB BB BBBBBXX
                        XXXXXXX XXXXXXXXX gettext(u'Select an upstream app to pull') XXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBB
                          
                          XXXXXXX XXXXXXXXXBBB BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BB BBBBBBBB X gettext(u'version %(v)s') SSSSSSS SSSSSXBBBBBBBBBBBXXXXXXXXX
                        BBBBBB
                      XXXXXXXXX
                    XXXXXX
                  XXXXXX
                BBBB
                  XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
                BBBBB
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                         gettext(u'Email when finished (recommended for large applications)') 
                      XXXXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXBBBBBBBBBBBBBBBXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                      XX XXXXXXXXX XXXXXXXXXXXXXXXXX
                       gettext(u'Update') 
                    XXXXXXXXX
                  XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXXX
        XXXXXX
      XXXXXX
    BBBBB
    BB BBB BBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXXXX
          XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Loading ...') 
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXX XXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Try again') XXXXXXXXX
        XXXXXX
      XXXXXX
    BBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      BB BBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBB BBBBBBXX
            BBBBBB BBBBBBBBBBBBB
          XXXXXXX
        XXXXXX
      BBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX gettext(u'Delete Application') XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXX
             gettext(u'Delete this application') 
          XXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX

    BB BBB BBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBX
              XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXX
      XXXXXX
    BBBBB

  XXXXXX
XXXXXX
