BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB

XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX
    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Show') XXXXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX
      XXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX
          XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXX gettext(u'Custom Properties') 
          XXXX
        XXXXX
      BBBBB
    XXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XX XXXXXXXX XXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                 gettext(u"\n                  Oops!\n                  This setting shouldn't be here.\n                  Could you change it to the default\n                  to make it go away?\n                  Sorry about that.\n                ") 
                  SSSSS
                  SSSS SSSSSSS SSSSSSSSS SS SSSSS
                  SSSSS SSS SSSSSS SS SS SSS SSSSSSS
                  SS SSSS SS SS SSSSS
                  SSSSS SSSSS SSSSS
                
              XXXXXXX
            XXXX
            XXXX XX XXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
               gettext(u'\n                This feature is not available on your subscription. Please upgrade to\n                the <!-- ko text: upgrade_plan --><!-- /ko --> plan or higher.\n              ') 
                SSSS SSSSSSS SS SSS SSSSSSSSS SS SSSS SSSSSSSSSSSSS SSSSSS SSSSSSS SS
                SSS SSSS SS SSSSS SSSSSSSSSSSS SSSSSSS SSS SSS SSSS SS SSSSSSS
              
              BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX
            XXXX XXX XXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Preview') XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        XXXX XXX XXX
      XXXXXX
    XXXXXX
  XXXXXX
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Custom Properties') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXX
               gettext(u'Add Custom Property') 
            XXXXXXXXX
          XXXXXX
        XXXXXXXXXXX
      XXXXXX
    XXXXXX
  BBBBB
XXXXXXX
