BBBB BBBBBBBBBBBBBB
BBBB BBBB
BB BBBBBBBBBBBBBBBBBBBBBBBBBB
  BB BBB BBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Multimedia Reference Checker') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBXX
             gettext(u"View, upload, and download your application's multimedia") SSSSS SSSSSSS SSS SSSSSSSS SSSS SSSSSSSSSSSSS SSSSSSSSSS
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX
        XXXX
      XXXXXX
    XXXXXX
  BBBBB

  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Download Multimedia Zip') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXX gettext(u'This .zip file is structured to match the multimedia paths referenced in your CommCare Application.') SSSS SSSS SSSS SS SSSSSSSSSS SS SSSSS SSS SSSSSSSSSS SSSSS SSSSSSSSSS SS SSSS SSSSSSSS SSSSSSSSSSSSXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX

  BB BBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXXXX
           gettext(u'Sync all multimedia with master') 
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
               gettext(u'Email when finished (recommended for applications with large number of multimedia files or heavy files)') 
            XXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
               gettext(u'Force pull all multimedia (this can take a long time and will re-write all the multimedia in your app)') 
            XXXXXXXX
          XXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u'Sync') 
          XXXXXXXXX
        XXXXXX
      XXXXXXX
    XXXXXX
  BBBBB

BBBB
  XXXX XXXXXXXXXXXX XXXXXXXXXXXX gettext(u'This application currently does not contain any multimedia references.') SSSS SSSSSSSSSSS SSSSSSSSS SSSS SSS SSSSSSS SSS SSSSSSSSSS SSSSSSSSSSSXXXXXX
BBBBB
