BBBB BBBB

XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Set Password') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
           gettext(u"The passwords don't match. Please try again.") 
        XXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
           gettext(u'Please enter a password or cancel.') 
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Password') XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Repeat Password') XXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX
          XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Cancel') XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX gettext(u'Save') XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
