BBBB BBBB
XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
  XXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XX
    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXXX
      XXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXX

    XXXXX
    XXX XXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Set as default') XXXX
    XXXXX
    XXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXX
  XXXXX
  XXXXXXXX
XXXXXXXX
XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXX XXXXXXXXXXXXX
   gettext(u'Add Language') 
XXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Please save before adding another language') XXXXXXX
BB BBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
     gettext(u'Smart language display in forms') X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX
  XXXXXX
BBBBB
XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX gettext(u'Deleting Languages:') XXXXX
  XXXXXX XXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX
      XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX  gettext(u"Don't Delete") XXXXXXXXX
    XXXXX
    XXXXXXXX
  XXXXXXXX
XXXXXX
