BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBB
  XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
      XXXXXXXXXXXXX XXXX
      XXXXXX XXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X
      XXXXXX XXXX
    X
  XXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBB BBBBBB
  BBBBBBBBBBBBBBBBB BBBBBB BBBB
  BBBBBBBBBBBBBBBBB BBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBB

  XXXX gettext(u'Manage Web Apps Permissions') XXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
         gettext(u'Allow all mobile workers to see all Web Apps applications.') SSSSS SSS SSSSSS SSSSSSS SS SSS SSS SSS SSSS SSSSSSSSSSSSS
      XXXXXXXX
      XXXXXX XXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
         gettext(u"Customize each mobile worker's access to Web Apps") SSSSSSSSS SSSS SSSSSS SSSSSSSS SSSSSS SS SSS SSSS
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX
            XXXX
              XXX XXXXXXXXXXXXXXXXX gettext(u'Application') XXXXX
              XXX XXXXXXXXXXXXXXXXX gettext(u'Group') XXXXX
            XXXXX
          XXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
          XXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXX
                                    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXXXXXX XXXXXXX
                                    XXXXXXXXXXXXX XXXXXX
                                    XXXXXXXXXXXXXXX XXX XXXX
                                XXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'You have no groups') XXXXXXX
            XXXXX
          XXXXX
          XXXXXXXX
        XXXXXXXX
        XXXX XXXXXXXXXXXXX
          XXXX gettext(u"Here's what this means") XXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX
              XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXX
                                 gettext(u'Mobile workers in group\n                                  <strong data-bind="text: group.name"></strong>\n                                  have access to') SSSSSS SSSSSSS SS SSSSS
                                  SSSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSS
                                  SSSS SSSSSS SS
                            XXXXXXX
              XXXXX XXXXXXXXXXXXXX XXXXXXXX
                                 gettext(u'<strong>No Mobile Workers</strong> have access to') SSSSSSSSSS SSSSSS SSSSSSSSSSSSSSSS SSSS SSSSSS SS
                            XXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX XXXXXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXX
            XXXXX
          XXXXX
          XXX gettext(u'...and all other mobile workers do not have access to any Web Apps applications.') SSSSSS SSS SSSSS SSSSSS SSSSSSS SS SSS SSSS SSSSSS SS SSS SSS SSSS SSSSSSSSSSSSSXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'No Web Apps applications available') 
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX
BBBBBBBB
