BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB

BBBBB BBBBB
   gettext(u'Web Apps') 
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBB
  
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXX
      XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX X
        XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Show Full Menu') XXXXXXXXX
      XXXXX
    XXXXXX
  XXXXXX
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBBBBB
  BBBBBBBB BBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
  BBBBBBBBBBB
  BBBBBBBB BBB
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
  BBBBBBBBBBB
BBBBBBBB

BBBBB BB 
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB

  BBBBBBBBBBBBBBBBB BBBBBB BBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBB BBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBB BBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBB
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBB

  XXXX XXX XXX XX XXXXX XXXXX XXXX XXXXX XXX XXXX XXXXX XXXX XX XXXXXXX XXXX XX  XXX

  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                XXXXXXXXX X
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXX XXXXXXXXXXX
                XXX
      XXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXXXXXXX X
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXX XXXXXXXXXXX
          X
        XXXXXXXXXXXX
    BBBBB
  XXXXXX
  BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBBB
