BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Functionality Disabled') BBBBBBBB

BBBBB BBBBBBBBB gettext(u'This functionality is disabled.') BBBBBBBB
BBBBB BBBBBBBBBBBB
XXXXX gettext(u'Web apps for %(app_or_domain_name)s are currently down for maintainence.') SSS SSSS SSS SSSSSSSSSSSSSSSSSSSSSS SSS SSSSSSSSS SSSS SSS SSSSSSSSSSSSSXXXXXX
BB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXX
XXXXXX gettext(u"The 'disable_web_apps' feature flag is turned on.") SSS SSSSSSSSSSSSSSSSSS SSSSSSS SSSS SS SSSSSS SSSXXXXXXX
BBBBB
BBBBBBBB