BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBB BBBBB

  XX XXXXXXXXXXXXX
     gettext(u"\n      Use this page to test out <a href='%(settings_url)s' target='_blank'>case search configuration</a> and profile case search or\n      case list explorer queries.\n    ") 
      SSS SSSS SSSS SS SSSS SSS SS SSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSS SSSSSS SSSSSSSSSSSSSSSSS SSS SSSSSSS SSSS SSSSSS SS
      SSSS SSSS SSSSSSSS SSSSSSSS
    
  XXXX

  XXXX XXXXXXXXXXXXXXXXX
    XXXX gettext(u'Search Parameters') XXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX gettext(u'Case Metadata') XXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXX
                   gettext(u'Case Type:') 
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
                XXXXXXX
                   gettext(u'Owner ID:') 
                  XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX gettext(u'Case Properties') XXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX X
                  XXXXXXX
                  XXXX gettext(u'Property name') XXXXX
                  XXXX gettext(u'Property value') XXXXX
                  XXXX gettext(u'Clause') XXXXX
                  XXXX gettext(u'Fuzzy') XXXXX
                  XXXX gettext(u'Remove Characters') XXXXX
                  XXXXXXXXX
                  XXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                  XXXX
                    XXXX
                      XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXX XXXXXXXXXXXX XXXXXXXXXXX  XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX
                    XXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXX
                    XXXX
                      XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Delete') 
                      XXXXXXX
                    XXXXX
                  XXXXX
                  XXXXXXXX
                XXXXXXXX
                XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add input') XXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX X XXXXXXXX XX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
            BB BBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXX gettext(u'Custom Query Addition') XXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX
                    BBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
                      XXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBB
                  XXXXXXXXX
                XXXXXX
              XXXXXX
            BBBBB
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
              XX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Search') 
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Profile') 
            XXXXXXXXX
          XXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXX XXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Results') XXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Query') XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Profile') XXXXXXXXX
        XXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXX XX XXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'results') 
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
              XXXXXXX
              XXXX
                XXXX gettext(u'Name') XXXXX
                XXXX gettext(u'Case Type') XXXXX
                XXXX gettext(u'Closed') XXXXX
                XXXX gettext(u'Properties') XXXXX
                XXXX gettext(u'Indices') XXXXX
                XXXX gettext(u'Score') XXXXX
              XXXXX
              XXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXX XXXXXXXX XXX
                XXXX
                  XXXX
                    XX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX
                    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
                    XXXXXX
                  XXXXX
                  XXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXX
                        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
                      XXXXX
                    XXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
              XXXXXXXX
            XXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
               gettext(u"\n                See <a href='https://www.elastic.co/guide/en/elasticsearch/reference/current/search-profile.html' target='_blank'>ElasticSearch docs</a> for help interpreting profile data.\n              ") 
                SSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSS SSS SSSS SSSSSSSSSSSS SSSSSSS SSSSS
              
            XXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
BBBBBBBB
