# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 13:24
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations




class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0006_one_reinstall_measure'),
    ]

    operations = [
        migrations.RunSQL(
            # This migration is not reversible because blobs created
            # since the migration will no longer be accessible after
            # reversing because the old blob db would use the wrong path.
            #
            # '_default' is the bucket name from the old blob db API.
            """
            UPDATE ota_demouserrestore
            SET restore_blob_id = '_default/' || restore_blob_id
            WHERE restore_blob_id NOT LIKE '_default/%'
            """
        ),
    ]
