BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFXX
  BBBBBBBBBB
  BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
      
    XXXXXX
  BBBBBB
  XXXXXXXXXX
    BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXBB BBBBBBBBBBBB XXXXXXXXXBBBBBXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXX
          
          BBB BBBBB BB BBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          BBBBBB
          BB BBBBBBBBBBBBBBBB BB B
            XXXX XXXXXXXXXXXXXXXXXXX
               gettext(u'\n                We will email instructions to you for resetting your password.\n              ') 
                SS SSSS SSSSS SSSSSSSSSSSS SS SSS SSS SSSSSSSSS SSSS SSSSSSSSS
              
            XXXXXX
          BBBBB
        XXXXXX
      XXXXXX
    BBBBBB
  XXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBB BBBBBBB BB BBBBBBBBBBBBBBBBB
    XX XXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFX
       XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
       gettext(u'Back') 
    XXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
       gettext(u'Reset Password') 
    XXXXXXXXX
  XXXXXX
XXXXXXX
