# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 18:56
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nikshay_datamigration', '0008_auto_20170119_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nikshay_datamigration.PatientDetail')),
                ('IntervalId', models.IntegerField()),
                ('TestDate', models.DateField()),
                ('DMC', models.IntegerField()),
                ('LabNo', models.IntegerField()),
                ('SmearResult', models.IntegerField()),
                ('PatientWeight', models.IntegerField(null=True)),
                ('DmcStoCode', models.CharField(max_length=255, null=True)),
                ('DmcDtoCode', models.CharField(max_length=255, null=True)),
                ('DmcTbuCode', models.IntegerField(null=True)),
                ('RegBy', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
