nginx: 
  extends: 
    file: docker-compose-base.yml
    service: nginx
  ports: 
    - "80:80"
  volumes: 
    - "../nginxconf/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "../../staticfiles:/static:ro"
  external_links: 
    - commcarehq_web_1:web
  labels:
    commcare.name: "nginx"
