BBBB BBBBBBBBBBBBBB
BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add Automatic Case Update Rule') 
    XXXXXXXXX
  XXXX

  XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XX XXX XXXXXXXXX XXX
      XXXX XX XXXXXX XXXXXXXXXXXXXXXX XXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Unlock Linked Rules For Me') 
        XXXXXXXXX
      XXXX XXX XXX
      XXXX XX XXX XXXXXXXXXXXXXXXX XXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Lock Linked Rules For Me') 
        XXXXXXXXX
      XXXX XXX XXX
    XXXX XXX XXX
    XXXX XX XXXXXX XXXXXXXXX XXX
      XX XXXXXXXXX XXXXXXXXXXXXX
      XXXXXXXX XXXXXX XXXXX
    XXXX XXX XXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX gettext(u'Linked Configurations') X
        XXXXXXXXXXXXXX
           gettext(u"\n            Linked configurations are controlled from a separate, linked project space.\n              <a href='https://confluence.dimagi.com/display/commcarepublic/Enterprise+Release+Management' target='_blank'>Learn more</a>.\n          ") 
            SSSSSS SSSSSSSSSSSSSS SSS SSSSSSSSSS SSSS S SSSSSSSSS SSSSSS SSSSSSS SSSSSS
              SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSS SSSSSSSSS
          XX
    XXXXXXX
  XXXX

  XXXX XXXXXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXX
          XXXX gettext(u'Name') XXXXX
          XXXX gettext(u'Case Type') XXXXX
          XXXX gettext(u'Status') XXXXX
          XXXX gettext(u'Last Run') XXXXX
          XXXX gettext(u'Action') XXXXX
          XXXX XX XXX XXXXXXXXXXXXXXXXXXXXX XXX
            XXXXXXXXX XXXX XXXXX XXXXXX XXXXXX XXX
          XXXX XXX XXX
        XXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX
            XXXX
              XX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXX
            XXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'deprecated') XXXXXXX
            XXXXX
            XXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Active') XXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Inactive') XXXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Activate') 
              XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Deactivate') 
              XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                      XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX XXXXXXXXXXXXXXX X XXXX XX XXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXX
                 gettext(u'Delete') 
              XXXXXXXXX
              XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXX X XXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXX gettext(u'Delete this rule?') XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXXXXXX
                         gettext(u'\n                          Are you sure you want to <strong>delete</strong> this rule?\n                        ') 
                          SSS SSS SSSS SSS SSSS SS SSSSSSSSSSSSSSSSSSSSSSS SSSS SSSSS
                        
                      XXXX
                      XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Cancel') 
                      XXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                              XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXXXXX
                         gettext(u'Delete Rule') 
                      XXXXXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
              XXXXXX
              XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXX
            XXXXX
            XXXX XX XXX XXXXXXXXXXXXXXXXXXXXX XXX
              XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXX
              XXXXX
            XXXX XXX XXX
          XXXXX
        XXXXXXXX
      XXXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
