BBBB BBBBBBBBBBBBBB
BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXX
       gettext(u'All rules for a specific case type are run together and are referred to as rule runs. This table displays information associated with each rule run.') 
        SSS SSSSS SSS S SSSSSSSS SSSS SSSS SSS SSS SSSSSSSS SSS SSS SSSSSSSS SS SS SSSS SSSSS SSSS SSSSS SSSSSSSS
        SSSSSSSSSSS SSSSSSSSSS SSSS SSSS SSSS SSSS
      
    XXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                  XXXXXXX XXXXXXX
                  XXXXXXXXXX XXXXX
                  XXXXXXXXXXXX XBBBBBBBBBBBBBBB BBBBBBB BBBB BBBB BB BBBB BBBBBBBBXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXX
        XXXX
          XXXX gettext(u'Case Type') XXXXX
          XXXX gettext(u'Status') XXXXX
          XXXX gettext(u'Started On') XXXXX
          XXXX gettext(u'Finished On') XXXXX
          XXXX gettext(u'# of Cases Updated') XXXXX
          XXXX gettext(u'# of Cases Closed') XXXXX
        XXXXX
        XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXX
        XXXXXXXX
      XXXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX XXXXXXXXX
                XXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXX XXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXX
