BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB



XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  BB BBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Error:') XXXXXXXXXXXXXXXX
      BBB BBBBBB BBBBBB BB BBBBBBBBBBBBBBBBB
        BBB BBBBB BB BBBBBB
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBB
      BBBBBB
    XXXXXX
  BBBBB
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Add Action') 
        XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Close the case') XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Update case property') XXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Custom action') XXXXXXXXX
          BBBBB
        XXXXX
      XXXXXX

    XXXXXX
  XXXXXX
XXXXXXXXX



XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXXXXX




XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Close the case') XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'All cases matching the above criteria will be closed') 
        XXXXXXX
  XXXXXX
XXXXXXXXX




XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Set case property') XXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'to the exact value') XXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'to the value from other case property') XXXXXXXXX
      XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXX XXX XXXXXXXX XX
      XXXX XX XXX XXXXXXXXXXXX XXX XX XXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXX
          XXXXXXXXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXX XXX
    XXXXXX
  XXXXXX
XXXXXXXXX




XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Custom action ID') XXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
        BBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
          XXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBB
      XXXXXXXXX
    XXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Requires System Admin') XXXXXXX
    XXXXXXXX
  XXXXXX
XXXXXXXXX
