BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB



BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  BB BBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Error:') XXXXXXXXXXXXXXXX
      BBB BBBBBB BBBBBB BB BBBBBBBBBBBBBBBBB
        BBB BBBBB BB BBBBBB
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBB
      BBBBBB
    XXXXXX
  BBBBB
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBB
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
       gettext(u'Add Filter') 
    XXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXX XX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Select a filter') 
        XXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Case not modified since') XXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Case property') XXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Date case property') XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Date case property (advanced)') XXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Location') XXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Parent case is closed') XXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Custom filter') XXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'UCR Filter') XXXXXXXXX
        BBBBB
        XXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX



XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XX XXX XXXXXXXX X X XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'AND') XXXXXXXX
        XXXX XXX XXX
        XXXX XX XXX XXXXXXXX X X XX XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'OR') XXXXXXXX
        XXXX XXX XXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX




XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Case not modified in') XXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'days') XXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX




XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Case property') XXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'equals') XXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'does not equal') XXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'has a value') XXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'does not have a value') XXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXXX XXXXXXXXX gettext(u'matches the regular expression') XXXXXXXXX
        BBBBB
      XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXX
  XXXXXX
XXXXXXXXX




XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'When the current date is') XXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'greater than') XXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'less than') XXXXXXXXX
      XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'the date in case property') XXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX




XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'When the current date is') XXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'greater than') XXXXXXXXX
        XXXXXXX XXXXXXXXX gettext(u'less than') XXXXXXXXX
      XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'the date in case property') XXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX gettext(u'plus') XXXXXXXXX
        XXXXXXX XXXXXXXXXX gettext(u'minus') XXXXXXXXX
      XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX gettext(u'days') X XX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'days') XXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX




XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'The parent case is closed') XXXXXXXX
  XXXXXX
XXXXXXXXX




XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Custom filter ID') XXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
        BBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
          XXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBB
      XXXXXXXXX
    XXXXXX
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
    XXXXXXXX
  XXXXXX
XXXXXXXXX



XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Case belongs to location') XXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBB
          XXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBB
      XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXX
         gettext(u'Include cases from child locations') 
      XXXXXXXX
      XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXX
  XXXXXX
XXXXXXXXX




XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Filter Definition') XXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX
