BBBBBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Error') BBBBBBBB BBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBB

  XXXXXXX

  BB BBBBBBBBBBBBB
    XXXX gettext(u'Error details') XXXXX
    BBB BBB BB BBBBBBBBBBBBB
      XXXXXXX
    BBBBBB
  BBBBB

  BB BBBB
    XX XXXXXXXX gettext(u'Back') XXXX
  BBBBB

  BB BBBBBBBBBBBBBBBBBB
    XX XXXXXXBBB BBBBBBBXX gettext(u'Log In') XXXX
  BBBBB

BBBBBBBB
