

# XSD Types
XSD_GEOPOINT_TYPE = "geopoint"


# Geopoint DB column suffixes
DBCOLUMN_LATITUDE  = "lat"
DBCOLUMN_LONGITUDE = "lon" 
DBCOLUMN_ALTITUDE  = "alt"
DBCOLUMN_ACCURACY  = "acc"

GEOPOINT_COLUMNS = (DBCOLUMN_LATITUDE, DBCOLUMN_LONGITUDE, 
                    DBCOLUMN_ALTITUDE, DBCOLUMN_ACCURACY)