JSERROR_COUNT = 'commcare.jserror.count'
ERROR_COUNT = 'error.count'
REPEATER_ERROR_COUNT = 'commcare.repeaters.error'
MULTIMEDIA_SUBMISSION_ERROR_COUNT = 'corrupt-multimedia-submission.error.count'
DATE_OPENED_CASEBLOCK_ERROR_COUNT = 'date-opened-caseblock-bug.error.count'
