BBBB BBBB
XX XX XXXXXXXXXXXXXX X XX X XX
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
  XXXX gettext(u'Errors found') XXXXX
  XX XXX XXXX X X XX X X XXXXXXXXXXXXXX XXXX X
  XXX XXXXX X XXXXXXXXXX XX
  XXXXXX XXXXX XXXXXX
  XX X XX
XXXXXX
XX X XX
