BBBB BBBB
XXX
  XX XXXXXXXXX XXX XXX
     XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XX XXX XXXXXX gettext(u'Watch Video') XXXX
XXXX
XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'New Video Uploaded Successfully') XXXXXXX
XXXX
