BBBB BBBB
XXX
  XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XX
  XX XXXXXXXXX XXX XXX
     XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XX XXX XXXXXX gettext(u'View Full Size') XXXX
XXXX
XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'New Image Uploaded Successfully') XXXXXXX
XXXX

