BBBB BBBB
XXX
  XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
     XXXXXXXXX XXX XXX
     XXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXX gettext(u'Opens file in new tab.') XX gettext(u'Open HTML') XXXX
XXXX
XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
  XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'New Template Uploaded Successfully') XXXXXXX
XXXX
