BBBB BBBB
XXXX XXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXX XX XXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXX
    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
       gettext(u'Ready to upload. Click <strong>Begin Upload</strong> below to start.') SSSSS SS SSSSSSS SSSSS SSSSSSSSSSSSS SSSSSSSSSSSSSSS SSSSS SS SSSSSS
    XXXX
    XX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'There were errors') XXXXXXX
    XXXX
    XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Select another file') 
    XXXX
    XX XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Cancel Upload') 
    XXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
