BBBB BBBB
XXX XXXXXXX XXXXXXXXX XXXX
  XXXXXXX XXXXXXXXX XXXXXXX
  XXXXXXX XXXXXXXXX XX XXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    XXXXXX
    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
       gettext(u'Added to queue. Click <strong>Begin Upload</strong> above to start.') SSSSS SS SSSSSS SSSSS SSSSSSSSSSSSS SSSSSSSSSSSSSSS SSSSS SS SSSSSS
    XXXX
    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
       gettext(u'Queued for processing. Please wait.') 
    XXXX
    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Files') 
            XXXXXXX
       gettext(u'Processing upload, please wait.') 
    XXXX
    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Upload Finished') XXXXXXX
    XXXX
    XX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'There were errors') XXXXXXX
    XXXX
    XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Remove from queue') 
    XXXX
    XX XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Cancel Upload') 
    XXXX
  XXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX
