XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXX
        XXXXXXXX
          BB BBBBBBBBBBBBBBBBB
            
          BBBB
            
          BBBBB
        XXXXXXXXX
      XXXX
    XXXXX
    BBB BBBBBB BB BBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXX
          
        XXXX
      XXXXX
    BBBBBB
    XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
      BB BBBBBBBBBBBBBB
        
      BBBB
        
      BBBBB
    XXXXX
  XXXXX
XXXXXX
