BBBB BBBB
BBBB BBBBBBBBBBBBBB
XXXXXXXX
  XXXX XXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
               XXXXXXXXXXXXXX
               XXXXXXXXXXX  XX
        XXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXX
        XXXXXX
         gettext(u'\n          <a href="https://dimagi.com/commcare/">CommCare</a>\n          is copyright &copy;\n        ') 
          SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
          SS SSSSSSSSS SSSSSS
        BBB BBB
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Learn more about CommCare HQ') XXXX

        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Privacy') 
        XXXX
        XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Terms of Service') 
        XXXX
        XXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
           gettext(u'Business Agreement') 
        XXXX
      XXXX
    XXXXXX
  XXXXXX
XXXXXXXXX
