BBBB BBBBBBBBBBBBBB
BBBB BBBB

XXXXX XXXXXXXXXXXXXXX
      XXXXXXXXXX
      XXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXX
  BBBBBBBBBB
  XXXXXXXXXX
    BB BBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
         gettext(u'Form has errors') 
      XXXXXX
    BBBBB
    XXXX XXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX

        XXXXXXX
        XXXX
          BBB BBBBBB BB BBBBBBB
            XXXXXXXXX
          BBBBBB
        XXXXX
        XXXXXXXX

        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXX XXX
          BBB BBBB BB BBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXX X XXXXXXX XXXXXXX XXX
                BB BBBBBBBBB BB BBBBB
                  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                BBBB
                  XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
                  BBB BB B BB BBBBBBBBBBBBBBBBBBBBB
                    XXX
                  BBBBBB
                  XXXXXXXXXXXXXXXXX XXXXXXX
                BBBBB
                XXXXX XXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXX XXXXXXXX
                                             XXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
            XXXXX
          BBBBBB
        XXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXX XX
                                   XXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXXXXXXX

      XXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
           gettext(u'Submit') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXXX
XXXXXXX
