BBBB BBBB

XXXX XXXXXXXXXXXX XXXXX
     XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
          BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
             gettext(u'Request a CommCare Demo') 
          BBBB
             gettext(u'Get a Tour of CommCare') 
          BBBBB
        XXXXX
      XXXXXX

      
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXX
             gettext(u'\n              Thank you! A member of our team will be in touch to schedule a time with you.\n            ') 
              SSSSS SSSS S SSSSSS SS SSS SSSS SSSS SS SS SSSSS SS SSSSSSSS S SSSS SSSS SSSS
            
          XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Done') XXXX
        XXXXXX
      XXXXXX

    XXXXXX
  XXXXXX
XXXXXX
