BBBB BBBB
BBBB BBBBBBBBBBBBBB
XXXX XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXX XXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Give Feedback') 
    XX XXXXXXXXX XXXXXXXXXXXXXXXXXX
  XXXX

  XXXX XXXXXXXXXXXX XXXXX
       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX
               gettext(u'Close') 
            XXXXXXX
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX
             gettext(u'\n              We would love to get your feedback\n            ') 
              SS SSSSS SSSS SS SSS SSSS SSSSSSSS
            
          XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX
               gettext(u'\n                How would you rate this feature?\n              ') 
                SSS SSSSS SSS SSSS SSSS SSSSSSSS
              
            XXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXX XXXXXXXX XXXX X XXXXXXXXX XXXXXXXX XXX X XX
                        XXXXXXXXXX XXXXXXXX XXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXX
                   gettext(u"Don't Like It / Not Useful") 
                XXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXX XXXXXXX XXXX X XXXXXXXXX XXXXXXXX XXX X XX
                        XXXXXXXXXX XXXXXXXX XXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXX
                   gettext(u'Not Sure / Confusing') 
                XXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX X XXXXXXXXX XXXXXXXX XXX X XX
                        XXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXX
                   gettext(u'Love It / Useful') 
                XXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX
               gettext(u'Any other comments?') 
            XXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XX XXXXXXXXXXXXX
             gettext(u'\n              Thank you for your feedback! We appreciate it.\n            ') 
              SSSSS SSS SSS SSSS SSSSSSSSS SS SSSSSSSSSS SSS
            
          XXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Close') XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXX XXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXX XX XXXXXXXXXXXXXXXX
             gettext(u'Submit Feedback') 
          XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX
                  XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
             gettext(u'Submit Feedback') 
          XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX
