XXXXX
  BBB BBBBBBBBBBBBBB BBBB BB BBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
      BBB BBB BB BBBB
        XXX XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBB XXXXXXXXXXXXXXXBBBBBX
          BB BBBBBBXXXXXBBBBBX
          XX XXXXXXX
            XXXXXXXXXXXXXXXBB BBBBBBBBBBBBB BBB BBB BBBBBBBBBBB XXXXXXBBBBBBB BBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXBBBBBBB BBBBBBBBBBBBB BB BBBBBBBBB XXXXXXXXXXBBBBBX
            BB BBBBBBBBBBBBB BBB BBB BBBBBBBBBBB
              XXXXXXXXXXXXXXXXXXX
            BBBBB
            BB BBBBBBBBBBBBBBB
              XXXXXXXXXXXXX
              XXXXXXXXXXXXXXX
            BBBBB
            BB BBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXBBBBBX
            BB BBBBBBBBBBB
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXX 
              XXXXXXX
            BBBBB
            BB BBBBBBBBXX XXXXXXXXXXXXXBBBBB
            
          XXXX
          BB BBBBBBBBBBB BBB BBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXX
          BBBBB
        XXXXX
        BB BBBBBBBBBBB
          XXXX

          XXXXX
        BBBBB
      BBBBBB
    XXXXX
  BBBBBB
XXXXXX
