BBBB BBBB

XXXX XXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXX XXXXXXXXXXX
                XXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XX
      XX XXXXXXXX
         XXXXXXXXXXX
                   XXXXXX XXXXXXXX XXXXXX XXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
               XX gettext(u'Previous') XXXX
    XXXXX
    XXX XXXXXXXXXXX
                XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXX
            XX
      XX XXXXXXXX
         XXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXX
               XXXXXX
    XXXXX
    XXX XXXXXXXXXXX
                XXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XX
      XX XXXXXXXX
         XXXXXXXXXXX
                    XXXXXX XXXXXXXX XXXXXX XXXXXX X
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X
                XX
         gettext(u'Next') 
      XXXX
    XXXXX
  XXXXX
XXXXXX
