# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-15 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linked_domain', '0009_merge_20190408_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedReportIDMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_domain', models.CharField(max_length=126)),
                ('master_domain', models.CharField(max_length=126)),
                ('master_id', models.CharField(max_length=255)),
                ('linked_id', models.CharField(max_length=255)),
                ('model_type', models.PositiveSmallIntegerField(choices=[(1, 'Datasource'), (2, 'Report')])),
            ],
        ),
        migrations.AlterField(
            model_name='domainlink',
            name='remote_base_url',
            field=models.CharField(blank=True, help_text='should be the full link with the trailing /. Example: https://www.commcarehq.org/', max_length=255, null=True),
        ),
    ]
