BBBB BBBB
BBBB BBBBBBBBBBBBBB
XXXXXXXX
  XXXX XXXXXXXXXXXXXX
       XXXXXXXXXXXXXXXXX
       XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
                 XXXXXXXXXXXXXX
                 XXXXXXXXXXX  XX
          XXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX
          XXXXXX
           gettext(u'\n            <a href="https://dimagi.com/commcare/">CommCare</a>\n            is copyright &copy;\n          ') 
            SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
            SS SSSSSSSSS SSSSSS
          BBB BBB
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

          XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XX

          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Learn more about CommCare HQ') XXXX

          XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXX XX

          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u'Privacy') 
          XXXX
          XXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u'Terms of Service') 
          XXXX
          XXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
             gettext(u'Business Agreement') 
          XXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX
