BBBB BBBB
BBBB BBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXX
           XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX
                   XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                               XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                               XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX

          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXX
          XXXXXX
          XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
          XXXXXX
          XXXX XXX XXX
          XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
          XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX
               XXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
          XXXXXX
          XXXX XXX XXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
            XXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXX XXXXX
          XXXXXX
          XXXX XXX XXX
        XXXXXX
      XXXXXX
    XXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
         XXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
        XXX XXX XXXXXX XXXXX XXXXXXX
      XXXX
    XXXXXX
  XXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
             XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXX XXXXXXX X XXXXX
                            XXXXXX XXXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXX XXXXXXXXX XXXXXXXXX XXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
    XXXXX
      XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXX XXXXXXX XX XXXX XXX XXXXXXX XXXXXXXXX XXXXXXXXX XXXXXX XX XXX XX XXXXX XXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX X
      XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
    XXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                           XXXXX X XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
                           XXXXXX X
                                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                           XXX
      XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Replace') XXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Upload') XXXXXXX
    XXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX
                    XXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXX
       gettext(u'Set Path') 
    XXXXXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXX
       XXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                              XXXXXXXXXXXX XXXXXXXXXXXXX XX
      XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXX XXXXXXXXXX XX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXX
           gettext(u'Use Default Path') 
        XXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
