BBBB BBBB
XXXX XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXX
         XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX XXXXXXXX
                             XXXXXXXX XXX XXX XXX XXXXX
                             XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
        XXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX X XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXXXX
        XXXX
          XX XXXXXXXX
             XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
          XXXX
        XXXXX
        XXXX XX XXXXXXXX XXXXXXXXXX XXX
        XXX XXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXX X XXXXXXX XXXXX XX XXXXXXXXXXXXXXXXXXXXX XXX
          XX XXXXXXXX
             XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXX XXXXXXXXXXX
               XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX XXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX
        XXXXX
        XXXX XXX XXX
        XXXX
          XX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXX
          XXXX
        XXXXX
      XXXXX
    XXXXXX
  XXXXXX
XXXXXXXXX
