BBBB BBBB
BBBB BBBBBBBBBBBBBB
XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
     XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'CommCare HQ looks better on desktop!') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'\n            Hi%(" " + full_name)s, it looks like you’re on a mobile device.\n          ') 
            SSSSS S S SSSSSSSSSSSS SS SSSSS SSSS SSSSSS SS S SSSSSS SSSSSSS
          
        XXXX
        XX XXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'\n            CommCare HQ is optimized for desktop or laptop browsers.\n          ') 
            SSSSSSSS SS SS SSSSSSSSS SSS SSSSSSS SS SSSSSS SSSSSSSSS
          
        XXXX
        XXX
           gettext(u'\n            Send yourself an email with a login link to use when you’re back on a full-size browser:\n          ') 
            SSSS SSSSSSSS SS SSSSS SSSS S SSSSS SSSS SS SSS SSSS SSSSSS SSSS SS S SSSSSSSSS SSSSSSSS
          
        XXXX
        XX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Email Link') XXXX
        XXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX gettext(u'CommCare HQ looks better on desktop!') XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'\n            Reminder sent!\n          ') 
            SSSSSSSS SSSSS
          
        XXXX
        XX XXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'\n            Check out this video to get an introduction to CommCare HQ.\n          ') 
            SSSSS SSS SSSS SSSSS SS SSS SS SSSSSSSSSSSS SS SSSSSSSS SSS
          
        XXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
