XXXXX
  BBB BBBBBBBBBBBBBB BBBB BB BBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXX XXXXXXXXXXXXXXXX
      BBB BBB BB BBBB
        XXX
          XXXXXXXBB BBBBBBBBBBBBB BBB BBB BBBBBBBBBBBXXXXXXBBBBBBB BBBBBBBBBBBBBBB XXXXXXXXXXXXXXXBBBBBX
          BB BBBBBBXXXXXBBBBB
        X
          XX XXXXXXX BB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
             XXXXXXXXXXXXXXX BBBBB
             BB BBBBBBBBBBBBB BB BBBBBBBBBXXXXXXXXXXXXXXXXXX XXXXXXXX BBBBBX
            BB BBBBBBBBBBB
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
                            XX XXXXXXXXX XXXXXXXXXXXXXXXX 
                        XXXXXXX
            BBBBB
            BB BBBBBBBBXX XXXXXXXXXXXXXBBBBB
            
          XXXX

          BB BBBBBBBBBBB BBB BBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXX
          BBBBB
        XXXXX
        BB BBBBBBBBBBB
          XXXX

          XXXXX
        BBBBB
      BBBBBB
    XXXXX
  BBBBBB
XXXXXX
