# Generated by Django 3.2.19 on 2023-05-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleanup', '0013_migrate_kafka_checkpoint_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedCouchDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=126)),
                ('doc_type', models.CharField(max_length=126)),
                ('deleted_on', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
