# Generated by Django 1.9.11 on 2016-11-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_dictionary', '0002_auto_20161118_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseproperty',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='caseproperty',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    (b'date', b'Date'),
                    (b'plain', b'Plain'),
                    (b'number', b'Number'),
                    (b'select', b'Select'),
                    (b'integer', b'Integer'),
                    (b'', b'No Type Currently Selected')
                ],
                default=b'',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
