# Generated by Django 2.2.24 on 2021-11-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_dictionary', '0007_property_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseproperty',
            name='data_type',
            field=models.CharField(blank=True, choices=[('date', 'Date'), ('plain', 'Plain'), ('number', 'Number'),
                ('select', 'Multiple Choice'), ('barcode', 'Barcode'), ('gps', 'GPS'),
                ('phone_number', 'Phone Number'), ('password', 'Password'), ('', 'No Type Currently Selected')],
                default='', max_length=20),
        ),
        migrations.CreateModel(
            name='CasePropertyAllowedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_value', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('case_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='allowed_values', related_query_name='allowed_value',
                 to='data_dictionary.CaseProperty')),
            ],
            options={
                'unique_together': {('case_property', 'allowed_value')},
            },
        ),
    ]
