# Generated by Django 3.2.16 on 2023-01-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_dictionary', '0008_casepropertyallowedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseproperty',
            name='label',
            field=models.TextField(blank=True, default=''),
        ),
    ]
