# Generated by Django 2.2.24 on 2021-09-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_dictionary', '0008_casepropertyallowedvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseproperty',
            name='data_type',
            field=models.CharField(blank=True, choices=[('date', 'Date'), ('plain', 'Plain'), ('number', 'Number'), ('select', 'Multiple Choice'), ('barcode', 'Barcode'), ('gps', 'GPS'), ('phone_number', 'Phone Number'), ('password', 'Password'), ('', 'No Type Currently Selected')], default='', max_length=20),
        ),
    ]
