# Generated by Django 3.2.18 on 2023-05-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_dictionary', '0013_casepropertygroup_deprecated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casepropertygroup',
            unique_together={('case_type', 'name')},
        ),
    ]
