# Generated by Django 3.2.20 on 2023-10-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_dictionary', '0016_remove_caseproperty_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseproperty',
            old_name='group_obj',
            new_name='group',
        ),
    ]
