# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-12 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0039_trumpia_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=126, null=True)),
                ('date', models.DateTimeField(db_index=True, null=True)),
                ('couch_recipient_doc_type', models.CharField(db_index=True, max_length=126, null=True)),
                ('couch_recipient', models.CharField(db_index=True, max_length=126, null=True)),
                ('recipient_address', models.CharField(db_index=True, max_length=255, null=True)),
                ('subject', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('messaging_subevent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sms.MessagingSubEvent')),
            ],
        ),
        migrations.CreateModel(
            name='InfobipBackend',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('sms.sqlsmsbackend',),
        ),
        migrations.CreateModel(
            name='PinpointBackend',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('sms.sqlsmsbackend',),
        ),
    ]
