name: Lint

on:
  pull_request:
    branches:
      - master

permissions:
  checks: write
  contents: write

jobs:
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check changed py files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          files: |
            **/*.py

      - name: Run ruff linter
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: astral-sh/ruff-action@v3
        with:
          src: ${{ steps.changed-files.outputs.all_changed_files }}

  # If this is in the same step as python linting the annotations don't show up
  lint-javascript:
    name: Lint Javascript
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - uses: sibiraj-s/action-eslint@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          annotations: true
