name: commcare-hq docs
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: astral-sh/setup-uv@v6
        with:
          version: '0.7.2'
      - name: Install docs requirements
        # HACK install lxml separately to work around no-binary-package in pyproject.toml
        # no-binary-package (lxml) is only needed for xmlsec, which is excluded by --no-group=sso
        run: |
          uv sync --group=docs --no-group=sso --locked --compile-bytecode --no-progress --no-install-package=lxml
          uv pip install --no-config --python=.venv/bin/python \
            $(uv export --format=requirements.txt --no-hashes | grep ^lxml==)
      - name: Test docs build
        run: |
          source .venv/bin/activate
          ./scripts/test-make-docs.sh
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: make-docs-artifacts
          path: artifacts
          if-no-files-found: ignore
          retention-days: 7
