name: commcare-hq docs
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          submodules: recursive
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7.6.0
      - name: Install docs requirements
        run: uv sync --group=docs --no-group=sso --locked --compile-bytecode --no-progress
      - name: Test docs build
        run: |
          source .venv/bin/activate
          ./scripts/test-make-docs.sh
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: make-docs-artifacts
          path: artifacts
          if-no-files-found: ignore
          retention-days: 7
