name: commcare-hq docs
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install docs requirements
        run: pip install -r requirements/docs-requirements.txt
      - name: Test docs build
        run: bash ./scripts/test-make-docs.sh
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: make-docs-artifacts
          path: artifacts
          if-no-files-found: ignore
          retention-days: 7
