name: commcare-hq docs
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: astral-sh/setup-uv@v6
        with:
          version: '0.7.2'
      - name: Install docs requirements
        run: uv sync --group=docs --no-group=sso --locked --compile-bytecode --no-progress
      - name: Test docs build
        run: |
          source .venv/bin/activate
          ./scripts/test-make-docs.sh
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: make-docs-artifacts
          path: artifacts
          if-no-files-found: ignore
          retention-days: 7
