BBBB BBBBBBBBBBBBBB
BBBB BBBB
XXXXXX XXXXXXXX XXXXXXXXXXXXXX
XXXX

  XXXX
    XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXX
    XX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX
  XXXXX

  XXX XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XBBBBBBBBBBBBBBB BBBBBBB BBBBB BBBB BBBBBBXX
        XXXXXX XXXXXXXXXX
    XXXXXXXXXXX
  XXXXX

  XXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXXX

  XXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
           XXXXXXXXXXXXXXXXXX XXX XXXXXXXX XXXXX
           XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX XBBBBBBBBBBBBBBB BBBBBBB BBBBBBBB BBBBBXX
        XXXXXXXXXXXX XXXXXXXX
        XXXXXXXXXXXXX XXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX

    XXXX XXXXXXXXXXX
        XXXX X
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        X
    XX
      XX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXX
        XXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXX gettext(u'This is a deprecated property') XXXX
    XXXXXX
    XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXX
         gettext(u'\n          Did you mean "%(suggestion)s" instead?\n        ') 
          SSS SSS SSSS SSSSSSSSSSSSSSSS SSSSSSSS
        
      XXXX
    XXXXXX
    XXXXXXXXXX
  XXXXX

  XXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXX
    XXXXXX
  XXXXX

  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX
      XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX gettext(u'blank') XXXXXXXXXXXXXXXXXXXXXX
      XXXXX
  XXXXX
  BBBBB

XXXXX
XXXXXXXXXX
