BBBB BBBB
XXXXXX XXX XXXXX XXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX
XXXXX
  XXXXXX XXX XXXXXXXXXXXXXXXXXXXXX
  XXX
     gettext(u'\n      <strong data-bind="text: %(match_count)s"></strong> rows were matched and\n      updated.\n    ') 
      SSSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSS SSSS SSSS SSSSSSS SSS
      SSSSSSSS
    
  XXXX
  XXXXXXXXXX

  XXXXXX XXX XXXXXXXXXXXXXXXXXXXX X XXXX
  XXX
     gettext(u'\n      <strong data-bind="text: %(created_count)s"></strong> rows did\n      not match any existing cases and had new cases created\n      for them. If case_id\'s were used, these were ignored.\n    ') 
      SSSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSS SSS
      SSS SSSSS SSS SSSSSSSS SSSSS SSS SSS SSS SSSSS SSSSSSS
      SSS SSSSS SS SSSSSSSSS SSSS SSSSS SSSSS SSSS SSSSSSSS
    
  XXXX
  XXXXXXXXXX

  XXXXXX XXX XXXXXXXXXXXXXXXXXX XXX X XX XXXXXXXXXXXXXXXXXXXX XXX XXXX
  XXX
     gettext(u'No cases were created or updated during this import.') 
  XXXX
  XXXXXXXXXX
XXXXXX
XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXX XXX XXXXXXX
    XXXX
      XXXXXX XXX XXXXXXXXX
      XXXXXXXXXXX
        XXXX XX XXX XXXXXXXXXXX XX XXXX
         gettext(u'\n          <span data-bind="text: rows.length"></span> row had an invalid\n          "<span data-bind="text: column"></span>" cell and was not saved\n        ') 
          SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSS SSS SSS SS SSSSSSS
          SSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSS SSSS SSS SSS SSS SSSSS
        
        XXXXXXXXXX
        XXXX XX XXX XXXXXXXXXXX X XXXX
         gettext(u'\n          <span data-bind="text: rows.length"></span> rows had invalid\n          "<span data-bind="text: column"></span>" cells and were not saved\n        ') 
          SSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSSSSSS SSSS SSS SSSSSSS
          SSSSSS SSSSSSSSSSSSSSSS SSSSSSSSSSSSSSSS SSSSS SSS SSSS SSS SSSSS
        
        XXXXXXXXXX
      XXXXXXXXXXXXX
      XXXXXXXXXX
      XXXXXX XXX XXXXXXX XXX
      XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXX
      XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXX
      XX XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XXXXXXXX
      XXXX
      XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX gettext(u'Row(s):') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
      XXXX
    XXXXX
    XXXXXXXXXX
    XXXXXXXXXX
  XXXXX
XXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXX XXX XXXXX XX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXX gettext(u'Unable to retrieve details') XXXX
XXXXXX
XXXXXXXXXX
XXXXXX XXX XXXXX XXX XXXXXXXXXXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
    XXXX
      XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXX
    XXXXXXXXXX
  XXXXX
XXXXXX
XXXXXXXXXX
