BBBB BBBB
BBBB BBBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
       gettext(u'Recent Uploads') 
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXXXX
                    XXXXXX XXXXXX
                    XXXXXXX XXXXXXXXXX X XXXXXXXXXXXX XX
                    XXXXXXXXXXXX XBBBBBBBBBBBBBBB BBBBBBB BB BBBBBBBB BB BBBBBBBBX
                  XXXXXXXXXXXXXXX
    XXXXXX
  XXXXX
  XXXXXX XXX XXXXXXX XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Status') XXXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Time') XXXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Case Type') XXXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Details') XXXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'Comment') XXXXX
      XXX XXXXXXXXXXXXXXXXX gettext(u'File') XXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
        XXXX gettext(u'Form IDs') XXXXX
        XXXX gettext(u'Case IDs') XXXXX
      BBBBB

    XXXXX
    XXXXXX XXXXXXXX XXXXXXXXXXXXXXX
    XXXX
      XXX XXXXXXXXXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Success') XXXXXXX
        XXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Success with warnings') XXXXXXX
        XXXXXXXXXX
        XXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Success') XXXXXXX
        XXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Failed') XXXXXXX
        XXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Waiting to start') 
        XXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
               XXXXXXXXXXXXXXXX XXXXXXX XXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
                      XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                         gettext(u'Complete') XXXXXXX
          XXXXXX
        XXXXXX
        XXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXXX
      XXX XXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                  XXXXXX XXXXXXXX
                  XXXX XXXXXXXXXXXXX
                  XXXXX XX
                  XXXXXXXXXXXX X gettext(u'(Click here to add a comment)') XX
                  XXXXXXXXXXXXXX XXXXXXXXXX
                  XXXXXXXXXXXXX X gettext(u'Error updating comment.  Please try again.') X
              XXXXXXXXXXXXXXXX
        XXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXXXXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXX
                      XXXXXXXX X
                          XXXXXX XBBBBBBBBBBBBBBB BBBB BBB BBB BBBBBBBB BBBB BBBB BBBBBBBBBXX
                          XXXXXXXX XBBBBBBBBBBBBBBB BBBBBBB BBB BB BBBBBBBBBBBBB BB BBB BBBB BBB BBBBBBBB BBB BBBB BBB BBBBB BBBBBXX
                          XXXXXXXXXX XXXXX
                      X
                  XXXXXX
        XXXXXXXXXX
        XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
        XXXXXXXXXX
        XXXXXXXXXX
      XXXXX
      BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
        XXXX
          XX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXX
        XXXXX
        XXXX
          XX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXX
        XXXXX
      BBBBB
    XXXXX
    XXXXXXXXXX
  XXXXXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXX XXXXXXXXX
                      XXXXX XXXXXXXXXXXXXX
                      XXXXXXXX XXXXXXXXXXXXX
                      XXXXXXXXXXX XXXXXXXXXXX
                      XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXX
  XXXXXX XXX XXXXXXX XXX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXX
     gettext(u'No recent uploads found.') 
  XXXXXX
  XXXXXXXXXX
  XXXXXX XXX XXXXXXX XXX XXXXXXXXXXXXXX XXX
  XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXXX
  XXXXXX XXX XXXXXXX XXX XXXXXXXXXXXXX XXX
  XX XXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXXXXXXX
XXXXXX
