BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBB
   gettext(u'Releases')  X
  BB BBBBBBBB
    FFFFFFFFF
  BBBB
     gettext(u'Applications') 
  BBBBB
BBBBBBBB

BBBBB BB
  BBBBBBBB BB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBBBBBBBB
BBBBBBBB BB

BBBBB BBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBB BBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBB BBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBB BBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBB
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBB
      BB BBB BBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
      BBBB
        XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX
      BBBBB
           gettext(u'Release Mode') 
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXX XXXXXXXXXXX
            XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX
            XXXXXXXXX
        XXXXXX
    BBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX
BBBBBBBB BBBBBBBBBBBBB
