BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBB
   gettext(u'Settings')  X
  BB BBBBBBBB
    FFFFFFFFF
  BBBB
     gettext(u'Applications') 
  BBBBB
BBBBBBBB

BBBBB BB
  BBBBBBBB BB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXX XXX
  BBBBBBBBBBB
  BBBBBBBB BB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBBBBBBBB
BBBBBBBB BB

BBBBB BBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBB BBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB BBBBBBBBBBBBB
