BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB
BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBB
  BBBBBBBB BBB
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXX
  BBBBBBBBBBB
BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB
  X XXXXX X XX X
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBB BBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'Multimedia Sizes') XXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX
       gettext(u'\n        Multimedia download needed to update from %(from_version)s to %(to_version)s\n      ') 
        SSSSSSSSSS SSSSSSSS SSSSSS SS SSSSSS SSSS SSSSSSSSSSSSSSSS SS SSSSSSSSSSSSSS
      
      XXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBB
  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X
  XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBB
  
BBBBBBBB BBBBBBBBBBB
