BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBB

 #
 #


BBBBB BBBBBBBBBBBBBBBBBBBB
  XXXXXXXXXXXXXXXXXX
BBBBBBBB


BBBBB BBBBBBBBBBBBBBBBBBBB
  XXXXXXXXXXXXXXXXXXXXXXXXXBB BBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBB
BBBBBBBB

BBBBB BBBBB gettext(u'Applications') BBBBBBBB

BBBBB BBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BB
  XXXX
      XXXXXX XX XXXXX XX XX XXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXX
      XXXXXXX XXXXXXX XXXXXXXXX XXX XX XXXX XXXXXXXX XXXXX XXXX XX XXXX XXXX XXX XXX XXX
      XXXXXXXXXXXXXX XXXXXXXXXX XXX XXX XXXXXXX XXXXXXXX XX XXXXXXX XXXXXXX XXXX XXX XXXXXX
      XXXXXXXX XXXX XX XXX XXXXXXX XXX XXXXXXXXX
  XXX
  BBBBBBBB BB
    XXXX XXXX XXXXXXX XXXXXX XX XXXXXX XX XXXX XXXX XXXX XXXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXX XXX XXXXX XXXXXXXXXX XX XXXXXXXX XX XXXX XXXX XXX XXXXXXXX XXX XX XX XXX XXX XX XXXX XX XXXXXXXXXX XX XXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBB BB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBB BBB BBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXX BBBBBX
       XXXXXXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXX
           XXXXXXXXXXXFFFFFFFFFFFFFFX
           XXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XX XXXXXXXXXXXXX gettext(u'New App Builder Officially Released') XXXX
        XXX
           gettext(u'\n            After months of testing and feedback, we are happy to announce the\n            official release of the new CommCare App Builder. The previous App Builder\n            interface is now no longer available.\n          ') 
            SSSSS SSSSSS SS SSSSSSS SSS SSSSSSSSS SS SSS SSSSS SS SSSSSSSS SSS
            SSSSSSSS SSSSSSS SS SSS SSS SSSSSSSS SSS SSSSSSSS SSS SSSSSSSS SSS SSSSSSS
            SSSSSSSSS SS SSS SS SSSSSS SSSSSSSSSS
          
        XXXX
        XXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Learn More') 
          XXXX
        XXXX
      XXXXXX
    BBBBB

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    BBBBB BBBBBBBBBBBBBBBBBBB
  XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBB
  
  BB BBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBB
BBBBBBBB BBBBBB

BBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXBBBBBBBB
