BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  BBBBBBBB BBB
    XXXXX XXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXXXXXXX
          XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
  BBBBBBBBBBB

BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBB BBBB
  BBBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBB BBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBB

  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBB

          XXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX gettext(u'High Level Summary') XXXXXXX
                XXXX
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXBB BBBBBBBBB BB BBBBBBBBBBBBBB XXXXXXBBBBBXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBB BBBBBBX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX gettext(u'Form Summary') XXXXXXX
                XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                   XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBXXXXXXX
                   XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXBB BBBBBBBBB BB BBBBBBBBBBBBBB XXXXXXBBBBBXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBB BBBBBBX
                   XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX gettext(u'Case Summary') XXXXXXX
                XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                   XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBXXXXXXX
                   XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX
              XXXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX X XXXXXXX XXXXXXXXXXXXXXX XXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX
              XXXXXX
            XXXXX
            XXXX XX XXX XXXXXXXXXXX XXX
            XXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX
              XXXXXX
            XXXXX
            XXXX XXX XXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XX XXXXXXXX XXXXX XXX
            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXX XXXXXXXXXX XXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XXXXXXX
                  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XXXX
              XXXXXX
              XXXX XX XXXXXXXX XXXXXXXX XXX
              XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX
                  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX X XXXXXXX XXXXXXXXXX XXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXX XXXXXXX
                      XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXX
                  XXXXXX
                XXXXX
              XXXXX
              XXXX XXX XXX
            XXXXX
            XXXX XXX XXX
          XXXXX

        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          BBBBB BBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX

  
  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX X XXXXXXXXX XXXXXXXXXX XXX
         gettext(u'Labels') 
      XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX X XXXXXXXXX XXXXXXX XXX
         gettext(u'Question IDs') 
      XXXXXXXXX
    XXXXXX
  XXXXXXXXX
BBBBBBBB BBBBBBB
