BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Case Summary')  X  gettext(u'Version')  BBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBB
    BBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBB BBBBB
    XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX
      XXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
         gettext(u'Case Summary')  X  gettext(u'Version')  XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Go') XXXX
      XXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXXXXXXXXX XXXXXX
                              XXXXXXX XXXXXXXX
                              XXXXXXXXXX XXXXX
                              XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXX XXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX X
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX X XXXXXX X XXXXXXXXXXXXXX XXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXX
                XXXXXX gettext(u'Show Conditions') 
              XXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
                      XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX X XXXXXX X XXXXXXXXXXXXXXXX XXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXX gettext(u'Show Calculations') 
              XXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    BB BBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
        BBB BBBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
         gettext(u"\n          Your app's forms contain errors.\n          Please visit the <a href='%(form_summary_url)s'>form summary</a> for more details.\n        ") 
          SSSS SSSSS SSSSS SSSSSSS SSSSSSS
          SSSSSS SSSSS SSS SS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSS SSS SSSS SSSSSSSS
        
      XXXXXX
    BBBBB

    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XX XXXXXXXX XXXXXXXXX XXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XX XXXXX XXXX XXXXXXX XXX XXX
            XXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXXXXXX gettext(u'Relationships:') XXXXXXXXX
                  XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXX
                      XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                      XXXX XX XXXXX XXXXXXXX XXXXXXX XXX XXX
                    XXXXX
                  XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXXXXXX gettext(u'Opened by:') XXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXXXXXX gettext(u'Closed by:') XXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX
                XXXXXX
              XXXXXX
              XXXX XX XXXXXXXXXXXXX XXX
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                   gettext(u'Problems:') 
                  XXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXX
                    XXXX XX XXXXXXXX XXXXXXXXXX XXX
                    XXXX XX XXX XXXXXXXXXX XXX
                    XXXX
                      XX XXXXXXXXXXXXXXXX XXXXXX XXX X XXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX
                    XXXXX
                    XXXX XXX XXX
                    XXXX XXX XXX
                  XXXXX
                XXXXXX
              XXXXXX
              XXXX XXX XXX
            XXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
              XXXXXXX
              XXXX
                XXXX gettext(u'Case Property') XXXXX
                XXXX gettext(u'Form') XXXXX
                XXXX gettext(u'Load questions') XXXXX
                XXXX gettext(u'Save questions') XXXXX
                XXXX gettext(u'Case Lists') XXXXX
                XXXX gettext(u'Case Details') XXXXX
              XXXXX
              XXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
              XXXX XX XXX XXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XXX
              XXXX XX XXXXXXXX XXXXX XXX
              XXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XX XXX XXXXXXXXX XXX
                XXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                  XXXX
                    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                XXXXX
                XXXX XXX XXX
                XXXX
                  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XX XXXXXXXX XXXXXX XXX
                  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                     XXXXXXXXXXXXXXXXXXX X XXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXX XXXXXXX
                  XXXX XXX XXX
                XXXXX
                XXXX
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXX
                XXXX
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXX
                XXXX XX XXX XXXXXXXXX XXX
                XXXX
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXX
                XXXX
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXX
                XXXX XXX XXX
              XXXXX
              XXXX XXX XXX
              XXXX XX XXX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXX
              
              XXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
                XXXX
                  XXXX
                    XXXX
                      XXXX XX XXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX XXX
                      XXXX XX XXXXX XXXX XXXXXXX XXX XXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                  XXXXX
                XXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBB
                XXXXX
                XXXX
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBB
                XXXXX
              XXXXX
              XXXX XXX XXX
              XXXX XXX XXX
              XXXXXXXX
            XXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXX XXX
      XXXXXX
    XXXXXX

    
    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXX
        XXXX
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XX XXX XXXXXXXXXX XXX
          XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
            XXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXX
              XXXX XX XXXXX XXXXXXXX XXXXXXX XXX XXX
              XXXX XX XXXXX XXXXXXXX XXXXXXX XXX XXX
              XXXX XX XXXXX XXXXXX XXXXXXX XXX XXX
            XXXXX
          XXXXX
          XXXX XXX XXX
        XXXXX
      XXXXX
    XXXXXXXXX
  XXXXXX

BBBBBBBB BBBBBBBBBBBBB
