BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB
BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB


BBBBB BBBBBBBBBB
  X XXXXX XBB BBBBBBBBBBBBBBBBBX BBBBB
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXX
      XXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXXXXXX
      XXXXXXX
      BBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
        XXXX
          XXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXFFFFFFF FXXXXX
          XXX XXXXXXXXXXXXXXXXX
            BBB BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              BB BB BB BBBBBBBBBBBBBBBB
                
              BBBBB
            BBBBBB
          XXXXX
          XXX XXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                 gettext(u'Revoke restriction') 
              XXXX
            BBBB
              XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXX
                 gettext(u'Restrict to this version') 
              XXXX
            BBBBB
          XXXXX
        XXXXX
      BBBBBB
      XXXXXXXX
    XXXXXXXX
  BBBBB
BBBBBBBB

BBBBB BBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBB BBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  XXXX gettext(u'Multimedia Sizes') XXXXX
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBB
  XXXXXX
BBBBBBBB
BBBBB BBBBBBBBB
  XXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX
      XXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXX
        XXXX
      XXXXX
    XXXXX
    XXXX
      XXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBXX
          XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
           gettext(u'Bulk application translations') 
        XXXX
      XXXXX
    XXXXX
  XXXXXXXX
BBBBBBBB BBBBBBBBB

BBBBB BBBBBBBBBBBBBBBB
  XX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXX
BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB
  BB BBBBBBBBBBB BBB BBB BBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXX
      XXXX XXXXX XXX XXXX XXXXXX X XXXX XXX XX XXXX XXX XXXXX XXX X XXXXXXXX XXXXXX
      XX XXX XXXX XXXX XXX XXX XXXXXXX XXXXXXXXXXXXX XXXXXXX XX XXXX XXXX
      XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBXXXXXXX XXXXXXXXX
    XXXXXX
  BBBBB
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBB
  
  BBB BBBBBBBBBBBBBB BBBBBBBBBB BBBBBB BB BBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
BBBBBBBB
