BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBBBB
  XXXXXXX
    XXXXXXXX X
      XXXXXXXXXX XXXXXX
    X
  XXXXXXXX
BBBBBBBB

BBBBB BBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BB
  BBBBBBBB BB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBB
  BBBBBBBB BB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBBBBBBBB
  BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
    BBBBBBBB BB
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBBBBBBBB
  BBBB
    BBBBBBBB BB
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBBBBBBBB
  BBBBB
  XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXX XXXXX
    X
    XXXXXXX X
      XXXXXXXXXXXX XXXXX
    X
  XXXXXXXX

  BBBBBBBB BB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBB BB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBBBBBBBB
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBB BB
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBBBBBBBB
  BBBBB
  BB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBB BB
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBBBBBBBB
  BBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Edit Form') 
    XXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBB BBBBBBBBBBBBBBBBBBBBBBBB B BBB BBBBBBBBBB B BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      BB BBBBBBBBBBBBBBBBBBBB BB BBBBBB
        BBBBBBBBBBBBBBBBB BBBBBBBBB BBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBB BBBBBBBBBBBBBBBBBB
        BBBBBBBBBBBBBBBBB BBBBBBBBB BBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBB
        BBBBBBBBBBBBBBBBB BBBBBBBBB BBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBB
        BBBBBBBBBBBBBBBBB BBBBBBBBB BBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBB
    BBBBBBB
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXX
          XXXXX XXXXXXXXXX
          XXXXXXXXXXXXXXXX
          XXXXXX XFFFFFFFFXX
          XXXXXXXXXXXX X gettext(u'Enter form description here') XX
          XXXX XBBB BBBBBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBB BBBBBBBBBXX
          XXXXXXXXXXXXXX XXXXXXXXXX
          XXXXX XXX
          XXXXXXXXXXXXXX FFFFFFFFFFFFFFFFFFX
      XXXXXXXXXXXXXXXX
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
  BB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBB

  
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBB BBBBBB

  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX

      BB BBBBBBBBBBBBBBB
        XXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
             gettext(u'Case Management') 
          XXXX
        XXXXX
      BBBBB

      XXXX
        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Settings') XXXX
      XXXXX

      BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
        XXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
             gettext(u'User Properties') 
          XXXX
        XXXXX
      BBBBBBBBBB

      BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBB
          XXXX
            XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
               gettext(u'Visit Scheduler') 
            XXXX
          XXXXX
        BBBBB
      BBBBB

      BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBB
        XXXX
          XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Actions') XXXX
        XXXXX
      BBBBB
    XXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX

      BB BBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXX
               gettext(u'We were unable to validate your form due an error on the server. Proceed with caution.') 
            XXXX
          BBBBB
          BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBB
            XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
               gettext(u'You are viewing a shadow form, therefore:') 
              XXXX
                XXXX gettext(u'You will be unable to add "Open case" action') XXXXX
                XXXX gettext(u'Load/Update actions will be "merged" with the source form actions') XXXXX
                XXXX gettext(u'Every case tag in the source form load/update action configuration must appear in this configuration') XXXXX
                XXXX gettext(u'You are not allowed to specify load or save case properties') XXXXX
                XXXX gettext(u'The load and save case property behaviors specified in the shadow source form actions will be used for the actions with matching case tags specified here.') XXXXX
                XXXX gettext(u'You are not allowed to specify case closures here') XXXXX
              XXXXX
            XXXXXX
          BBBBB
          BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXX
               gettext(u'There are errors in your form. Fix your form in order to view and edit Case Management.') 
            XXXX
          BBBB BBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
              BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
                BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              BBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              BBBBB
            XXXXXX
          BBBB
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXX
               gettext(u'Add questions to your form to make use of case management.') 
            XXXX
          BBBBB
        XXXXXX
      BBBBB


      BB BBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBB


      BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXX
               gettext(u'There are errors in your form. Fix your form in order to view and edit Case Management.') 
            XXXX
          BBBB BBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB
                BB BBBBBBBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBBB
                  XXXXX
                    XXX gettext(u'\n                      The User Properties feature is no longer available because of the change in your\n                      CommCare subscription. Although currently-deployed applications will still\n                      function properly, it will not be possible to update or redeploy them unless\n                      the User Properties functionality is removed, or you upgrade your CommCare\n                      subscription.\n                    ') 
                      SSS SSSS SSSSSSSSSS SSSSSSS SS SS SSSSSS SSSSSSSSS SSSSSSS SS SSS SSSSSS SS SSSS
                      SSSSSSSS SSSSSSSSSSSSS SSSSSSSS SSSSSSSSSSSSSSSSSS SSSSSSSSSSSS SSSS SSSSS
                      SSSSSSSS SSSSSSSSS SS SSSS SSS SS SSSSSSSS SS SSSSSS SS SSSSSSSS SSSS SSSSSS
                      SSS SSSS SSSSSSSSSS SSSSSSSSSSSSS SS SSSSSSSS SS SSS SSSSSSS SSSS SSSSSSSS
                      SSSSSSSSSSSSS
                    XXXX

                    XX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'\n                      WARNING: By clicking "Remove User Properties" you will lose User Properties\n                      functionality if you redeploy your application. However, you will still be\n                      able to see all previously collected data.\n                    ') 
                      SSSSSSSS SS SSSSSSSS SSSSSSS SSSS SSSSSSSSSSS SSS SSSS SSSS SSSS SSSSSSSSSS
                      SSSSSSSSSSSSS SS SSS SSSSSSSS SSSS SSSSSSSSSSSS SSSSSSSS SSS SSSS SSSSS SS
                      SSSS SS SSS SSS SSSSSSSSSS SSSSSSSSS SSSSS
                    XXXX

                    XXX
                      XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBX XXXXXXXXXX XXXXXXXXXXXXX
                         gettext(u'Change your subscription') 
                      XXXX
                      XX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBB BBBBBBX XXXXXXXXXX XXXXXXXXXXXX
                         gettext(u'Remove User Properties') 
                      XXXX
                    XXXX
                  XXXXXX
                BBBBB
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              BBBBBBBB
            XXXXXX
          BBBB
            XX XXXXXXXXXXXX XXXXXXXXXXXXXXX
               gettext(u'You have not created a form yet. Create a form in order to view and edit User Properties.') 
            XXXX
          BBBBB
        XXXXXX
      BBBBBBBBBB

      BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBB
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBB
      BBBBB
      BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBB
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB BBBBBB
