BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB
   gettext(u'\n    Form Summary - Version %(app_version)s\n  ') 
    SSSS SSSSSSS S SSSSSSS SSSSSSSSSSSSSSS
  
BBBBBBBB

BBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBB BBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBB BBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBB BBBBBB BBBBBB BBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBB
  XXXXXX
BBBBBBBB BBBBBBBBBBBBB
