BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBB
  BB BBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBB
  BB BBB BBBBBBBBBBBB
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  BBBB BBBBBBBBBBBB BB BBBBBBBBB
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
  BBBBB
BBBBBBBB

BBBBB BBBBBBBBBBB
  XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX X
      XXXXXXXXXXXXXXX XX
      XXXXXXXXXXXXXX XX
    X
  XXXXXXXX
BBBBBBBB

BBBBB BB
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  
  XXXXXXXX
    XX
        XXXX XXXX XXXXXXXXX XXX XXXXXXXXX XXXXXX XXX XXXXX XX XXXX XX XXX X XXXX XX XXXXXXXX XXX XXXXXXX
        XXXXX XXXXX XXXXXXX XXX XXXX XX XXXX XXXXXXXXX XXX XXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXX XX XXXXXX
        XX XXXX XXX XX XX X XXXXX XX XXXXXXXXXXXXX XXX XX XXXXXXXX XX XXXXXXXX XXXXXXXXXX XXXXXXX XXXXX
        XXXXXXX XXXXX XXXXXXXXX XXX XXX XXXX XXXXXXXX XXXXX XXX XX XXXX XXXXXXX XXX XXXXXXXXX XXX XXXXXX
        XXXXXX XXXXX XXXXXXXX XXXX XXXXXXX XXXX X XXXXX XXXX XX XXXXXXXXX XX XXXX XXXXXXXXXX XXXX XXXXXXXXX XXX
    XX
    XXXXXX X XXXXXXXXXX
  XXXXXXXXX
  BBBBBBBB BB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBB

BBBBB BBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBBBB BBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBB BBBBBBX
         XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXX
      X
        XX XXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'App Summary') 
      XXXX
      XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBB BBBBBB BBBBBB BBBBBBBBBBBBBBX
         XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXX
      X
        XX XXXXXXXXX XXXXXXXXXXXX  gettext(u'Manage Case') 
      XXXX
    XXXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'This is a <i class="fcc fcc-app-createform"></i> Registration Form.') SSSS SS S SS SSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSSSSSS SSSSSXXXXX
    XXX
       gettext(u'\n        Users will fill it out when they need to <strong>add</strong> a new item to the application.\n      ') 
        SSSSS SSSS SSSS SS SSS SSSS SSSS SSSS SS SSSSSSSSSSSSSSSSSSSS S SSS SSSS SS SSS SSSSSSSSSSSS
      
    XXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'This is a <i class="fcc fcc-app-updateform"></i> Followup Form.') SSSS SS S SS SSSSSSSSSS SSSSSSSSSSSSSSSSSSSSSSSS SSSSSSSS SSSSSXXXXX
    XXX
       gettext(u'\n        Users will fill it out when they need to <strong>update</strong> an item that has already been added to the application.\n      ') 
        SSSSS SSSS SSSS SS SSS SSSS SSSS SSSS SS SSSSSSSSSSSSSSSSSSSSSSS SS SSSS SSSS SSS SSSSSSS SSSS SSSSS SS SSS SSSSSSSSSSSS
      
    XXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX gettext(u'This is a <i class="fa fa-file-o"></i> Survey.') SSSS SS S SS SSSSSSSSS SSSSSSSSSSSSSSS SSSSSSSXXXXX
    XXX
       gettext(u"\n        It's useful for asking questions once, for information that you won't need to follow up on later.\n      ") 
        SSSS SSSSSS SSS SSSSSS SSSSSSSSS SSSSS SSS SSSSSSSSSSS SSSS SSS SSSSS SSSS SS SSSSSS SS SS SSSSSS
      
    XXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXXXX
    XXXX
  XXXXXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBB
  XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Edit Form Details') XXXXX
        XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Form Name') 
                XXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                   gettext(u'Comment') 
                XXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                              XXXXXXXXX XXXXXXXX
                                        XXXXXXXXXXXXXXXXX XXXXXXXX
                                        XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Cancel') XXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Save') XXXXXXXXX
          XXXXXX
        XXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBB
