BBBB BBBBBBBBBBBBBB
BBBB BBBB


XXXX XX XXX XXXXXXXXXXXXX XXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
   gettext(u"\n    Your app's forms contain errors. Case and form information below may be inaccurate until you fix the issues.\n  ") 
    SSSS SSSSS SSSSS SSSSSSS SSSSSSS SSSS SSS SSSS SSSSSSSSSSS SSSSS SSS SS SSSSSSSSSS SSSSS SSS SSS SSS SSSSSSS
  
XXXXXX
XXXX XXX XXX

XXXX XX XXXXXXXX XXXXXX XXX
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Error in form:') 
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
XXXXXX
XXXX XXX XXX

XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XX
    XXXX
      XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX X XXXXX XXX XXX
        XX XXXXXXXXXXXXXXXX X XXXXXXXX XXXX XXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXX
      XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXX X XXXXXXXX XXXX XXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX
    XXXXX
    XXXX XX XXX XXXXXXXXXXXXX XXX
    XXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX
        XX XXXXX X XXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXX
    XXXX XXX XXX
    XXXX XX XXX XXXXXXXXXXXXX XXX
    XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX
        XX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXX
    XXXX XXX XXX
    XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX
        XXXX
          XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX X XXXXX XXX XXX
            XX XXXXXXXXXXXXXXXX X XXXXXXXX XXXX XXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXX
          XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX X XXXXXXXX XXXX XXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXX
        XXXXX
        XXXX XX XXX XXXXXXXXXXXXX XXX
        XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX
            XX XXXXX X XXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
        XXXXX
        XXXX XXX XXX
        XXXX XX XXX XXXXXXXXXXX XXX
        XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXX
        XXXXX
        XXXX XXX XXX
        XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXX XXX
        XXXXX
      XXXXX
    XXXXX
  XXXXX
XXXXX


XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXX XXXX X XXXXXXX XXXXXXXXX XXX
    XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
      XX XXXXXXXXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
      XXXX XX XXXXXX XXXXXXXXXXXXXX XXX
      XX XXXXXXXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXXXXXX XX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXX XXX
      XXXX XX XXX XXXXXXXXXXXXXX XXX
      XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXX XXX
      XXXX XX XXX XXXXXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'required') XXXXXX
      XXXX XXX XXX
    XXXXXXX
    XXXX XX XXX XXXXXXXX XXX
    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
      XXXX XX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX XXX
    XXXXX
    XXXX XXX XXX
    XXXX XX XXX XXXX XX XXXXXXXX XXX
    XXXX XX XXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX gettext(u'Instance') XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX gettext(u'Nodeset') XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX gettext(u'Value') XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXX gettext(u'Label') XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX XXX XXX
    XXXX XXX XXX
    XXXX XX XXX  XXXXXXX XX XXXXXXXXX XX XXXXXXXX XX XXXXXXXXXX XX XXXXXXXX XX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX  XXX
    XXX XXXXXXXXXXXXXX
      XXXX XX XXX XXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXX X XXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXX XXX XXX
      XXXX XX XXX XXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXX X XXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXX XXX XXX
      XXXX XX XXX XXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XX XXXXX X XXXXXX XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXX XXX XXX
      XXXX XX XXX XXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXX X XXXXXX XX XXXXXXXXXX XXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXX XXX XXX
      XXXX XX XXX XXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXX X XXXXXX XX XXXXXXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      XXXXX
      XXXX XXX XXX
      XXXX XX XXXXXXXX XXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXX X XXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
          XXXX XX XXXXX XXXXXXXXXXXXXX XXXXXXX XXX XXX
        XXXXXXX
        XXXXX XXXXXXX gettext(u'Load property') XX
          XX XXXXX X XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXX X XXX XXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXX
      XXXXX
      XXXX XXX XXX
      XXXX XX XXXXXXXX XXXXXXXXXXXXXXX XXX
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXX X XXX XXXXX XXXXXXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXX gettext(u'Save property') XX
          XX XXXXX X XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXX X XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XXXX XX XXXXX XXXXXXXXXXXXXX XXXXXXX XXX XXX
          XXXX XX XXX XXXXXXXXXXXXXXXXX XXX XXXXXX XXX
          XXXX XXXXXXXXXXXXXXXXXXX gettext(u'save only on edit') XXXXXX
          XXXX XXX XXX
        XXXXXXX
      XXXXX
      XXXX XXX XXX
    XXXXX
    XXXX XXX XXX
    XXXX XX XXX XXXXXXXXXXXXXX XXX
    XXX XXXXXXXXXXXXXXXXXXX XXXXXXX XX
      XXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXX
    XXXX XXX XXX
  XXXXX
XXXXXXXXX
