BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB

 #
 #


BBBBB BB
  BBBBBBBB BB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBB
  XXXX gettext(u'Import Application') XXXXX
BBBBBBBB

BBBBB BBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBB BBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXX
    BBBBBBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBB
    XXXXX XXXXXXXXBBB BBBBBBBBBBBB BBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBBBBBBB
      BB BBB
        XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX
      BBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXBBBBBBBBBBBBBBBXX
            XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXBBBBBBBBBBBBBBB XXXXXXXXXXXXXXX gettext(u'Application Source File') XXXXXXXX
          XXXX XXXXXXXBBBBBBBBBBBBBBBXX
            XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXBBBBBBBBBBBBBBBBXX
            XX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XX XXXXXXXXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Yes, import application') XXXXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXXX
  XXXXXX
BBBBBBBB
