BBBB BBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBBBBBBBBBBB BBBBBB BBBB
BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBB BBBBBB
BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBB
BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBB

XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BB BBB BBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXX XXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Language List') 
          XXXX
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
      XXXXXX
    XXXXXX
  BBBBB

  BB BBB BBBBBBBBBBBBB BBB BBB BBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'CommCare Translations') 
          XXXX
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  BBBBB

  BB BBB BBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Bulk CommCare Translations') 
          XXXX
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
        XXXXXX
      XXXXXX
    XXXXXX
  BBBBB

  BB BBB BBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Bulk Application Translations') 
          XXXX
        XXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBB
        XXXXXX
      XXXXXX
    XXXXXX

  BBBBB

XXXXXX
