BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBB
BBBB BBBBBBBBBBBBB

BBBBB BBBBBFFFFFFFFFFFFFFFFFBBBBBBBB

BBBBB BB
  
  BBBBBBBB BB
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXX XXXXXXX XX XXXXXXX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  BBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBB
  BB BBB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX

      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBB BBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

      BB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
        BB BBB BBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBB B B
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBB
        BBBBB

        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      BBBBB
    XXXXXX
  BBBBB
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXX
           XXXXXXXXXXXFFFFFFFFFFFFFFX
           XXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
        XX XXXXXXXXXXXXX gettext(u'New setting to hide translations') XXXX
        XXX
           gettext(u'\n            Working with multiple languages but want to just focus on app building?\n          ') 
            SSSSSSS SSSS SSSSSSSS SSSSSSSSS SSS SSSS SS SSSS SSSSS SS SSS SSSSSSSSS
          
        XXXX
        XXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXX
             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Learn More') 
          XXXX
        XXXX
      XXXXXX
    BBBBB
  BBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB BBBBBBBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBB BBBBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBB BBBBBB
  BBBBBBBBBBB BBBBBBBBBB BBBBBB BBBBBB BBBBB
  BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
  BBBBB BBBBBBBBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Surveys') 
          XXX gettext(u'Collect data once.') SSSSSSS SSSS SSSSSXXXX
        XXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXX  gettext(u'Case List') 
          XXX gettext(u'Track items over time.') SSSSS SSSSS SSSS SSSSSXXXX
        XXXXXXXXX
      XXXXXX
      BB BBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Biometrics') 
            XXX gettext(u'Identify clients by fingerprint.') SSSSSSSS SSSSSSS SS SSSSSSSSSSSSXXXX
          XXXXXXXXX
        XXXXXX
      BBBBB
      BB BBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Advanced Menu') 
            XXX gettext(u'Complex case management.') SSSSSSS SSSS SSSSSSSSSSSXXXX
          XXXXXXXXX
        XXXXXX
      BBBBB
      BB BBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXX  gettext(u'Report Menu') 
            XXX gettext(u'Worker performance.') SSSSSS SSSSSSSSSSSSXXXX
          XXXXXXXXX
        XXXXXX
      BBBBB
      BB BBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Shadow Menu') 
            XXX gettext(u'Mimic another menu.') SSSSS SSSSSSS SSSSSXXXX
          XXXXXXXXX
        XXXXXX
      BBBBB
      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Shadow Menu V1') 
            XXX gettext(u'Old style shadow menu with deprecated child behaviour') SSS SSSSS SSSSSS SSSS SSSS SSSSSSSSSS SSSSS SSSSSSSSSXXXX
          XXXXXXXXX
        XXXXXX
      BBBBB
      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Training') 
            XXX gettext(u'Content for training users.') SSSSSSS SSS SSSSSSSS SSSSSSXXXX
          XXXXXXXXX
        XXXXXX
      BBBBB
    XXXXXX
  XXXXXXXXX

  XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX
      XX XX XXXXXXXXXXXX X XX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Survey') 
        XXXXXXXXX
      XXXXXX
      XX X XX
      XX XX XXXXXXXXXXXXXX X XX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Lesson') 
        XXXXXXXXX
      XXXXXX
      XX X XX
      XX XX XXXXXXXXXXXXXXX X XX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Followup') 
        XXXXXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'Register') 
        XXXXXXXXX
      XXXXXX
      XX X XX
      XX XX XXXXXXXXXXXXXX X XX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Form') 
        XXXXXXXXX
      XXXXXX
      XX X XX
      XX XX XXXXXXXXXXXX X XX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXXX  gettext(u'Shadow Form') 
        XXXXXXXXX
      XXXXXX
      XX X XX
      XXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX
        BBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
      XXXXXXX
    XXXXXX
  XXXXXXXXX
BBBBBBBB

BBBBB BBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB
