BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBB

BBBBB BB
  BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBB BB
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
      XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBBBBBBBB
  BBBBB
BBBBBBBB

BBBBB BBBBBBBBBBB
  BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
         gettext(u'Visit Scheduler') 
      XXXX
    XXXXX
  BBBBB
BBBBBBBB

BBBBB BBBBBBBBBBB
  BB BBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBB
    BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBB BBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
  BBBBB
BBBBBBBB
