BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB
BBBBB BBBBBXXX XX XXXXXX XXXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBBB
  BB BBB
    XXXX
      XX XXXXXXBBB BBBBBBBBBB BBBBBB BBBBBBXX
        XXXXXXFFFFFFFFFXXXXXXX
      XXXX
    XXXXX
  BBBBB
BBBBBBBB
BBBBB BBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXX
BBBBBBBB
BBBBB BBBBBBBBBBB
  XXXXXXXX XXX XX XX XXXXXX XXXXXXXXXXXXXX
  XXXXX XXX XXXXXXX XXXX XX XX XX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX
BBBBBBBB
