BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBBBBBBBBBBBB
BBBB BBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBBBBBBBBB BBBBBB BBBBBBBBBB BBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBB
  BBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBB BBBBB BBBBB
  BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB

  XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXX
    XX XXXXXXBBB BBBBBBBBBB BBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
      XXXXXXX XXX
    XXXX XXX XXX XXXXXX XXXX XX XXXXXXXXX

    BB BBB BBBBBBBBB
      XX XXXXXXX XXXX XXXXXXX XXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB
  XXXX

  BBBBB BBBBBBBBBBBBBBBBBBBB
  BBBBB BBBBBBBBBBBBBBBB
  BBBBB BBBBBBBBBBBBBBBBB

  XXXXXXXXXXXX XXXXXXXXXX

  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    BBB BBBBBBBB BBBBB BB BBBBBBBBBBB
      BB BBBBBBBXXXXXXXXXXXXXXXXXXBBBBB
      BBB BBBB BB BBBBB
        XXXX
          XXX XXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBB
              XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            BBBB
              
            BBBBB
            BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBB BBB BBBBBBBBBBBBBBBBBB
              
            BBBBB
          XXXXX
          XXX XXXXXXXXXXXXXXXXX
            BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
          XXXXX
        XXXXX

        BB BBBBBBBBBBB
          XXX XXXXXXXXXXXXX
            XXX XXXXXXXXXXXX
              BBBBB BBBBBBBBBBBBBBBBBBB
            XXXXX
          XXXXX
        BBBBB
      BBBBBB
    BBBBB
      XXXXXXXXXX XXXXXXXXXXXXXXX
    BBBBBB
  XXXXXXXX
  BBBBB BBBBBBBBBBBBBBBBBB
BBBBBBBB BBBBBBBBBBBB
